[GPU] Create functional tests with batch more than 1
openvinotoolkit/openvino pull request #10076
Opened 2022-02-02 13:23 UTC by amolotko

### Details:
 - *item1*
 - *...*

### Tickets:
 - *ticket-id*

2022-02-22 12:27 UTC, myshevts approved these changes

2022-03-31 18:11 UTC, nsemaev requested changes

2022-03-31 18:11 UTC, nsemaev commented on src/tests/functional/plugin/gpu/shared_tests_instances/single_layer_tests/convolution.cpp
> +                }
```
inputShapes.push_back({i, 15, 30, 30});
inputShapes.push_back({i, 16, 30, 30});
inputShapes.push_back({i, 17, 30, 30});
```
looks more suitable or an array of 2 values

2022-09-27 13:24 UTC, praasz approved these changes

2023-03-02 02:47 UTC, riverlijunjie commented
Close this PR due to it has been move to https://github.com/openvinotoolkit/openvino/pull/13262

2023-03-02 02:47 UTC, closed without merging