[GNA] Added SW_FP32 mode w/o SF for BasicLSTM
openvinotoolkit/openvino pull request #10115
Opened 2022-02-03 15:58 UTC by a-noskov

### Details:
 - Disabled TI3AlignedPropagateForward and TI1AlignedPropagateForward were moved to new infrastructure w/o using old version IR

### Tickets:
 - *31901*

2022-02-08 11:32 UTC, mryzhov commented on src/tests/functional/plugin/gna/shared_tests_instances/subgraph_tests/basic_lstm_sw_fp32.cpp
> +    {"GNA_COMPACT_MODE", "NO"},
We don't need to test it with disabled compact mode, please remove it

2022-02-08 11:33 UTC, mryzhov commented on src/tests/functional/plugin/gna/shared_tests_instances/subgraph_tests/basic_lstm_sw_fp32.cpp
> +    {"GNA_DEVICE_MODE", "GNA_SW_FP32"}
We need to test the both GNA_SW_EXACT and GNA_SW_FP32 modes every time if it is possible

2022-02-08 11:34 UTC, mryzhov requested changes
What is the difference of the test with the existed basic_lstm test?

2022-02-11 09:52 UTC, nkogteva commented on src/tests/functional/plugin/gna/shared_tests_instances/subgraph_tests/basic_lstm_sw_fp32.cpp
> +    std::shared_ptr<ngraph::Function> GetNetwork_sw_fp32(size_t thirdDimOut,
Can we reuse SubgraphTestsDefinitions::Basic_LSTM_S::GetNetwork?

2022-02-16 14:52 UTC, mryzhov requested changes
Please do not merge until we known why SW_FP32 and SW_EXACT work differently for the same network

2022-02-16 14:57 UTC, nkogteva commented on src/tests/functional/shared_test_classes/src/subgraph/basic_lstm.cpp
> +    auto gna_mode = configuration.find("GNA_DEVICE_MODE");
It is common place for all plugins. We should not introduce here GNA specific.

2022-03-01 13:44 UTC, mryzhov requested changes
Please remove gna specific code from the common test and replace hardcoded input range with test parameters as we discussed on previous review

2022-03-04 10:28 UTC, mryzhov commented on src/tests/functional/plugin/gna/shared_tests_instances/subgraph_tests/basic_lstm.cpp
> +float weights_range = 0.02f;
let's use pair instead of maximum value and hardcoded "0"

2022-03-09 16:11 UTC, mryzhov approved these changes

2022-03-11 08:12 UTC, nkogteva approved these changes

2022-03-17 08:32 UTC, merged