Change User Transformations applying order in MO
openvinotoolkit/openvino pull request #10241
Opened 2022-02-09 13:07 UTC by daniil-lyakhov

### Details:
Ngraph pruning transformation expects IR model with all mo optimization passes applied. In case when `--transfrom=Pruning` cli used, pruning transformation is receiving model before mock and fake quantize optimization passes applied, which leads to incorrect pruning transformation work. 

Suggested order of transformations allows to apply pruning transformation correctly

2022-02-09 13:08 UTC, GlebKazantaev approved these changes

2022-02-09 13:59 UTC, alexsu52 approved these changes

2022-02-09 14:20 UTC, GlebKazantaev commented on tools/mo/openvino/tools/mo/back/offline_transformations.py
> +    apply_user_transformations(func, parse_transform(argv.transform))
It won't impact LowLatency as in MOC we apply only fusions that only could help to perform LowLatency, Pruning and other user-defined transformations.

2022-02-10 06:22 UTC, daniil-lyakhov commented
Convert job 1074 reveals some model can't be converted with pruning turned on by default with such order of transformation. Looks like some models can't be pruned before fp16 compression. In latest changes pruning transformation is applying just before serialization, so, now only fully transformed models will be fed to pruning transformation.

2022-02-10 07:03 UTC, rkazants commented
@daniil-lyakhov, @GlebKazantaev, what kind of testing was performed against this change? Not sure that we can rely on the pre-commit. Did you check this change for other user transformations?

2022-02-10 08:33 UTC, GlebKazantaev commented
> @daniil-lyakhov, @GlebKazantaev, what kind of testing was performed against this change? Not sure that we can rely on the pre-commit. Did you check this change for other user transformations?

Pruning transformation was tests by @daniil-lyakhov. LowLatency unfortunately is not tested in our CI by some e2e and covered only with unit tests which enough since LL doesn't depend on graph structure and relies only on inputs and outputs of models that we do not change during MOC. So for LL it doesn't matter when it will be applied.

2022-02-10 09:40 UTC, mvafin commented
@daniil-lyakhov Why are we moving user transformations step after FP16 compression? It wasn't expected. Converts inserted by FP16 compression transformation weren't marked as "disable_constant_folding" since it was last before serialization. If we want to add transformation after it we need to do that marking or otherwise call to ConstantFolding transformation will fold those Converts.

2022-02-10 09:49 UTC, rkazants approved these changes
I am fine with this change if @mvafin and @itikhono are fine as well

2022-02-10 10:25 UTC, itikhono commented
Looks like moc and legacy moc transformations don't affect TensorIterator and tensor names of Parameter/Result nodes, so LowLatency and MakeStateful transformations should not be affected either.
LGTM

2022-02-10 10:25 UTC, itikhono approved these changes

2022-02-10 11:19 UTC, mvafin requested changes
Currently, it is dangerous to move user transformations after FP16 compression. See my comment earlier.

2022-02-10 11:38 UTC, daniil-lyakhov commented
> Currently, it is dangerous to move user transformations after FP16 compression. See my comment earlier.

Looks like problem with pruning transformation isn't related to FP16 compression, it's sporadic issue inside pruning transformation. Have changed that, sorry for inconvenience

2022-02-10 14:04 UTC, mvafin approved these changes

2022-02-10 14:41 UTC, daniil-lyakhov commented
@GlebKazantaev, please merge if there are no comments

2022-02-14 12:06 UTC, merged