Revised Tuning For Performance and Model optimization docs
openvinotoolkit/openvino pull request #10276
Opened 2022-02-10 15:06 UTC by AlexKoff88

### Details:
 - Changes the structure of Tuning For Performance
 - Added Model Optimization doc
 - Added NNCF introduction

2022-02-10 15:09 UTC, AlexKoff88 commented
@vyashina please take a look

2022-02-21 18:03 UTC, vyashina requested changes

2022-02-21 18:03 UTC, vyashina commented on docs/optimization_guide/dldt_optimization_guide.md
> +> **NOTE**: Make sure that your model can be successfully inferred with OpenVINO Inference Engine before diving into optimization topic.
Make sure that your model can be successfully inferred with OpenVINO Inference Engine before referring to the optimization topic.

2022-02-21 18:03 UTC, vyashina commented on docs/optimization_guide/dldt_optimization_guide.md
> +To get performance numbers for OpenVINO, as well as tips how to measure it and compare with native framework, check [Getting performance numbers](../MO_DG/prepare_model/Getting_performance_numbers.md
"go to" instead of "check"

2022-02-21 18:03 UTC, vyashina commented on docs/optimization_guide/dldt_optimization_guide.md
>  Latency measures inference time (ms) required to process a single input. When it comes to batch input need to measure throughput (images per second or frames per second, FPS). To calculate throughput
divide the number of frames

2022-02-28 11:38 UTC, AlexKoff88 commented
@vyashina, I applied all the comments. Please review and merge.

cc'ed @myshevts

2022-03-01 15:04 UTC, vyashina approved these changes

2022-03-03 15:58 UTC, merged

2022-03-11 08:03 UTC, vyashina commented on docs/optimization_guide/nncf_introduction.md
> +### Usage examples
Usage Examples
Please check the upper case in all headings

2022-03-11 08:03 UTC, vyashina commented on docs/optimization_guide/nncf_introduction.md
> +- GPU-accelerated layers for the faster compressed model fine-tuning.
Please fix the bullets issue