[XLink] - run XLink tests in pre-commit
openvinotoolkit/openvino pull request #10302
Opened 2022-02-11 11:02 UTC by DariaMityagina

### Details:
Purpose: run XLink tests to validate the PRs that update the XLink code from the OpenVINO repository.

### Tickets:
-76384

2022-02-21 08:52 UTC, azhogov requested changes

2022-02-21 08:52 UTC, azhogov commented on .ci/azure/linux.yml
> +  - script: . $(SETUPVARS) && $(REPO_DIR)/src/plugins/intel_myriad/third_party/tests/ --gtest_output=xml:TEST-XLinkTests.xml
tests should be installed

2022-02-21 08:52 UTC, azhogov commented on .ci/azure/windows.yml
> +  - script: call $(SETUPVARS) && $(REPO_DIR)/src/plugins/intel_myriad/third_party/tests/ --gtest_output=xml:TEST-XLinkTests.xml
install tests

2022-02-28 13:57 UTC, DariaMityagina commented on .ci/azure/linux.yml
> +  - script: . $(SETUPVARS) && $(REPO_DIR)/src/plugins/intel_myriad/third_party/tests/ --gtest_output=xml:TEST-XLinkTests.xml
done, thank you!

2022-02-28 13:57 UTC, DariaMityagina commented on .ci/azure/windows.yml
> +  - script: call $(SETUPVARS) && $(REPO_DIR)/src/plugins/intel_myriad/third_party/tests/ --gtest_output=xml:TEST-XLinkTests.xml
done, thank you!

2022-03-18 08:56 UTC, DariaMityagina commented
@azhogov , @beleiuandrei , @Maxim-Doronin could you please take a look?

2022-03-21 07:26 UTC, beleiuandrei approved these changes

2022-03-21 10:23 UTC, azhogov approved these changes

2022-03-21 10:28 UTC, merged