Add note to YOLO-v3 conversion instructions
openvinotoolkit/openvino pull request #10428
Opened 2022-02-16 09:07 UTC by yekruglov

Description: The instructions for converting YOLO-v3 from DarkNet to TensorFlow only apply to TensorFlow 1.X. Also, if numpy version is 1.20 or higher, the conversion script will throw an error, which is presented in the ticket. Need to add a note about these restrictions.

Ticket: CVS-79042

2022-02-16 09:13 UTC, vgavrilo approved these changes

2022-02-16 09:21 UTC, achetver commented on docs/MO_DG/prepare_model/convert_model/tf_specific/Convert_YOLO_From_Tensorflow.md
> +> **NOTE:** This converter works with TensorFlow 1 and numpy 1.19 or lower.
Maybe `TensorFlow 1.x`?

2022-02-16 11:41 UTC, achetver approved these changes

2022-02-17 13:56 UTC, andrew-zaytsev approved these changes

2022-02-17 13:56 UTC, andrew-zaytsev requested changes

2022-02-17 13:56 UTC, andrew-zaytsev commented on docs/MO_DG/prepare_model/convert_model/tf_specific/Convert_YOLO_From_Tensorflow.md
> +> **NOTE:** This converter works with TensorFlow 1.x and numpy 1.19 or lower.
```suggestion
> **NOTE**: This converter works with TensorFlow 1.x and numpy 1.19 or lower.
```

2022-02-17 14:01 UTC, andrew-zaytsev approved these changes

2022-02-17 15:00 UTC, merged