Fixed default inference precision in benchmark app
openvinotoolkit/openvino pull request #10443
Opened 2022-02-16 13:08 UTC by apankratovantonp

### Details:
 - *item1*
 - *...*

### Tickets:
 - *ticket-id*

2022-02-16 13:49 UTC, ilya-lavrenov approved these changes

2022-02-16 13:50 UTC, nkogteva approved these changes

2022-02-16 16:39 UTC, fzhar approved these changes

2022-02-16 16:41 UTC, fzhar requested changes
Please add information to help message that default value is f32

2022-02-16 16:49 UTC, apankratovantonp commented
The default value is plugin-dependent.

2022-02-17 10:01 UTC, fzhar approved these changes
ok, approved

2022-02-17 10:53 UTC, merged