[GNA] Moved single Lstm-cell test from deprecated tests
openvinotoolkit/openvino pull request #10472
Opened 2022-02-17 09:51 UTC by a-noskov

### Details:
 - lstm_cell_test moved from deprecated tests, now without using old IR

### Tickets:
 - 74184

2022-02-18 08:46 UTC, dmitriikhurtin approved these changes

2022-02-18 09:13 UTC, mryzhov requested changes
Please fix comments

2022-02-18 11:43 UTC, mryzhov commented on src/tests/functional/plugin/gna/shared_tests_instances/single_layer_tests/lstm_cell_basic.cpp
> +            {"GNA_COMPACT_MODE", "NO"}
```suggestion
            {"GNA_DEVICE_MODE", "GNA_SW_FP32"}
```

2022-02-18 11:44 UTC, mryzhov commented on src/tests/functional/plugin/gna/shared_tests_instances/single_layer_tests/lstm_cell_basic.cpp
> +            {"GNA_COMPACT_MODE", "NO"},
```suggestion
            {"GNA_DEVICE_MODE", "GNA_SW_EXACT"}
```

2022-02-18 13:10 UTC, mryzhov approved these changes

2022-03-11 08:15 UTC, nkogteva approved these changes

2022-03-11 12:03 UTC, merged