creating remote ocl buffer/tensor per request, to avoid simulteneous locking of the same ocl buffer when auto-batching is used
openvinotoolkit/openvino pull request #10607
Opened 2022-02-22 16:48 UTC by myshevts

when using auto-batching (e.g. take some simple classification network that is batched to the large batch size, like lenet or age-gender etc) the "--use-device-mem" crashes sporadically.

My impression is that the primary reason is that same (or limited set of the) OCL buffer(s) is set to the inference requests, eventually the may be locked (to [copy the input data to the input of the batched network's request](https://github.com/openvinotoolkit/openvino/blob/master/src/plugins/auto_batch/auto_batch.cpp#L539) ) **simultaneously** which leads to a crash due to [failure to lock](https://github.com/openvinotoolkit/openvino/blob/master/src/plugins/intel_gpu/src/plugin/remote_context.cpp#L192).

A simple solution is always creating an OCL buffer/OV tensor per request's input.
BTW this gives more fair benchmarking.

still I'm a bit puzzled on the other possible reasons, since at the time when the auto-batching was merged, [the code logic seems to be pretty much the same](https://github.com/openvinotoolkit/openvino/blob/49b5e5728ba62a3e93ce63557accc85664abfc04/samples/cpp/benchmark_app/remote_blobs_filling.cpp#L91)  so potentially something has been changed on the GPU plugin side
so, CC-ing @vladimir-paramuzov

2022-02-22 19:51 UTC, fzhar commented
Won't it lead to memory overconsumption ? Particularly in case of dynamic shapes tests ? Maybe it's better to wait for buffer to be unlocked (this may affect performance though) ?

2022-02-24 14:25 UTC, myshevts commented
> Won't it lead to memory overconsumption ? Particularly in case of dynamic shapes tests ? Maybe it's better to wait for buffer to be unlocked (this may affect performance though) ?

I fully agree, again, the current failure should be investigated in depth, as it is seemingly not the OCL lock failures (and the gpu buffer class in clDNN does has a mutex lock), So this is rather workaround

2022-02-25 11:23 UTC, myshevts commented
@sshlyapn , @vladimir-paramuzov pls see the CVS-80418

2022-02-28 11:15 UTC, tgubanova-lohika requested changes
[Stop russian aggression in Ukraine!](https://github.com/openvinotoolkit/openvino/pull/10646)

2022-02-28 12:04 UTC, vladimir-paramuzov approved these changes

2022-02-28 12:04 UTC, merged