Transformation guide
openvinotoolkit/openvino pull request #10628
Opened 2022-02-24 04:54 UTC by ilyachur

### Details:
 - *item1*
 - *...*

### Tickets:
 - *ticket-id*

2022-02-24 08:10 UTC, ilya-lavrenov commented
could you please provide description what is changed here? it's hard to detect why files are split..

2022-02-24 09:14 UTC, ilyachur commented
> could you please provide description what is changed here? it's hard to detect why files are split..

done

2022-02-24 10:08 UTC, ilya-lavrenov commented on docs/OV_Runtime_UG/ov_transformations.md
>  Using `ov::pass::ModelPass`, you need to override the `run_on_model` method where you will write the transformation code.
`Template for FunctionPass` => `Template for ov::pass::ModelPass`

2022-02-24 10:57 UTC, ilya-lavrenov commented on docs/OV_Runtime_UG/ov_transformations.md
>  Using `ov::pass::ModelPass`, you need to override the `run_on_model` method where you will write the transformation code.
remove ngraph everywhere in this file including code snippets, function to model

2022-02-24 10:57 UTC, ilya-lavrenov commented on docs/OV_Runtime_UG/ov_transformations.md
>  Return value is `true` if the original function has changed during transformation (new operation was added, or operations replacement was made, or node attributes were changed); otherwise, it is `fal
function has changed => model has changed

2022-02-28 11:11 UTC, tgubanova-lohika requested changes
Original comment was removed because it violates [A Code of Conduct for Open Source Communities](https://www.contributor-covenant.org/version/2/1/code_of_conduct/)

2022-02-28 15:10 UTC, ilya-lavrenov approved these changes

2022-02-28 15:10 UTC, ilya-lavrenov commented on docs/Extensibility_UG/ov_transformations.md
> +## Transformation conditional compilation
is it needed for end users?

2022-02-28 15:10 UTC, ilya-lavrenov commented on docs/Extensibility_UG/ov_transformations.md
> +```
can we move to snippets?

2022-02-28 15:10 UTC, ilya-lavrenov commented on docs/Extensibility_UG/ov_transformations.md
> +> **Note**: Make sure that you have dot installed on your machine; otherwise, it will silently save only dot file without svg file.
it's not rendered as true `note`

2022-02-28 15:10 UTC, ilya-lavrenov commented on docs/Extensibility_UG/ov_transformations.md
> +## Transformation conditional compilation
it's also demonstrated in snippets..

2022-02-28 15:10 UTC, ilya-lavrenov commented on docs/Extensibility_UG/graph_rewrite_pass.md
> +![graph_rewrite_execution]
it's not here.

2022-02-28 15:10 UTC, ilya-lavrenov commented on docs/Extensibility_UG/graph_rewrite_pass.md
> +![graph_rewrite_efficient_search]
it's not rendered

2022-03-01 06:03 UTC, merged