[CPU] Change Set/Get blob error message for dynamic model
openvinotoolkit/openvino pull request #10643
Opened 2022-02-24 12:46 UTC by mandrono

### Details:
 - *item1*
 - *...*

### Tickets:
 - *ticket-id*

2022-02-24 15:44 UTC, maxnick commented on src/plugins/intel_cpu/src/infer_request.cpp
> +            IE_THROW() << "Can't set input blob for dynamic model via legacy API!";
```suggestion
            IE_THROW(Unexpected) << "Can't set input blob for a model with dynamic shapes via legacy API!";
```

2022-02-24 15:44 UTC, maxnick commented on src/plugins/intel_cpu/src/infer_request.cpp
> +            IE_THROW() << "Can't set output blob for dynamic model via legacy API!";
```suggestion
            IE_THROW(Unexpected) << "Can't set output blob for a model with dynamic shapes via legacy API!";
```

2022-02-24 15:44 UTC, maxnick commented on src/plugins/intel_cpu/src/infer_request.cpp
> +            IE_THROW() << "Can't get input blob for dynamic model via legacy API!";
```suggestion
            IE_THROW(Unexpected) << "Can't get input blob for a model with dynamic shapes via legacy API!";
```

2022-02-24 15:44 UTC, maxnick commented on src/plugins/intel_cpu/src/infer_request.cpp
> +            IE_THROW() << "Can't get output blob for dynamic model via legacy API!";
```suggestion
            IE_THROW(Unexpected) << "Can't get output blob for a model with dynamic shapes via legacy API!";
```

2022-02-24 15:44 UTC, maxnick commented on src/plugins/intel_cpu/src/plugin.cpp
> +    // checking that all inputs have static shapes perform in common part
```suggestion
    // checking that all inputs have static shapes is performed in the common part
```

2022-02-24 15:44 UTC, maxnick commented on src/plugins/intel_cpu/src/plugin.cpp
> +                IE_THROW() << "CPU plug-in can't load model with dynamic output shapes via legacy API.";
```suggestion
                IE_THROW() << "CPU plug-in can't load a model with dynamic output shapes via legacy API.";
```

2022-02-25 13:04 UTC, maxnick approved these changes

2022-02-28 11:06 UTC, tgubanova-lohika requested changes
Stop russian aggression in Ukraine!

2022-02-28 14:01 UTC, merged