Fix `-layout` option
openvinotoolkit/openvino pull request #10648
Opened 2022-02-24 15:26 UTC by dpigasin

Fixed: parsing was performed incorrectly if a layout is specified for one input

2022-02-25 08:26 UTC, vladimir-dudnik approved these changes

2022-02-28 11:05 UTC, tgubanova-lohika requested changes
Original comment was removed because it violates [A Code of Conduct for Open Source Communities](https://www.contributor-covenant.org/version/2/1/code_of_conduct/)

2022-03-02 12:42 UTC, nkogteva approved these changes

2022-03-03 08:22 UTC, mryzhov approved these changes

2022-03-03 09:12 UTC, merged