Add changes to contribution guide
openvinotoolkit/openvino pull request #10675
Opened 2022-02-25 18:14 UTC by AnastasiaKazantaeva

Provided changes to Contribution guide: better wording, tone of voice, shorten rules.

2022-02-28 10:54 UTC, tgubanova-lohika requested changes
Original comment was removed because it violates [A Code of Conduct for Open Source Communities](https://www.contributor-covenant.org/version/2/1/code_of_conduct/)

2022-03-17 05:13 UTC, ilyachur approved these changes

2022-03-17 05:14 UTC, ilyachur commented
@andrew-zaytsev Please take a look

2022-03-17 14:28 UTC, ilya-lavrenov approved these changes

2022-03-22 08:51 UTC, merged