[Python API] Update doc style
openvinotoolkit/openvino pull request #10708
Opened 2022-03-01 10:41 UTC by akuporos

### Details:
 - *item1*
 - *...*

### Tickets:
 - *ticket-id*

2022-03-01 21:01 UTC, jiwaszki requested changes
Overall most of the changes are requested to keep consistency. In some places there are functions without docstrings at all -- is there a plan to document them as well? (Example `convert_color` in PreProcessSteps)

2022-03-01 21:01 UTC, jiwaszki commented on src/bindings/python/src/pyopenvino/core/variable_state.cpp
> +        :rtype: None
```suggestion
```
None is just a void -- no need to mark it.

2022-03-09 12:26 UTC, ilya-lavrenov commented
is it a target for 2022.1?

2022-03-09 13:04 UTC, akuporos commented on src/bindings/python/src/pyopenvino/frontend/frontend.cpp
> +                :param model: Partially converted nGraph function.
done

2022-03-09 13:43 UTC, akuporos commented on src/bindings/python/src/pyopenvino/frontend/frontend.cpp
> +                :return: Current frontend name. Empty string if not implemented.
done

2022-03-09 13:43 UTC, akuporos commented on src/bindings/python/src/pyopenvino/frontend/input_model.cpp
> +                :param place: Model place
done

2022-03-09 13:43 UTC, akuporos commented on src/bindings/python/src/pyopenvino/frontend/input_model.cpp
> +                :param place: Model place
done

2022-03-09 13:43 UTC, akuporos commented on src/bindings/python/src/pyopenvino/graph/preprocess/pre_post_process.cpp
> +            :param value: Value to divide.
done

2022-03-09 13:43 UTC, akuporos commented on src/bindings/python/src/pyopenvino/graph/preprocess/pre_post_process.cpp
> +            :param values: Value to divide.
done

2022-03-09 13:43 UTC, akuporos commented on src/bindings/python/src/pyopenvino/graph/preprocess/pre_post_process.cpp
> +            :rtype: PostProcessSteps
done

2022-03-09 13:44 UTC, akuporos commented on src/bindings/python/src/pyopenvino/graph/preprocess/pre_post_process.cpp
> +            :rtype: openvino.runtime.preprocess.PreProcessSteps
done

2022-03-09 13:44 UTC, akuporos commented on src/bindings/python/src/pyopenvino/graph/preprocess/pre_post_process.cpp
> +            :return: Reference to itself to allow chaining of calls in client's code in a builder-like manner.
done

2022-03-09 13:45 UTC, akuporos commented on src/bindings/python/src/pyopenvino/graph/passes/manager.cpp
> +        :param version: sets the version of the IR which will be generated.
done

2022-03-09 13:45 UTC, akuporos commented on src/bindings/python/src/pyopenvino/graph/preprocess/pre_post_process.cpp
> +            :param values: Value to subtract.
done

2022-03-09 13:51 UTC, akuporos commented on src/bindings/python/src/pyopenvino/graph/passes/manager.cpp
>                              - "IR_V11" : v11 IR
done

2022-03-09 13:51 UTC, akuporos commented on src/bindings/python/src/pyopenvino/graph/passes/manager.cpp
> +        :param pass_name : string to set the type of a pass
done

2022-03-09 13:59 UTC, akuporos commented on src/bindings/python/src/pyopenvino/frontend/place.cpp
>                      Can be empty if there are no names associated with this place or name cannot be attached.
done

2022-03-09 13:59 UTC, akuporos commented on src/bindings/python/src/pyopenvino/frontend/manager.cpp
> +                :return: Frontend interface for further loading of models. 'None' if no suitable frontend is found
done

2022-03-09 14:00 UTC, akuporos commented on src/bindings/python/src/pyopenvino/frontend/manager.cpp
> +                :param model_path: Path to model file/directory.
done

2022-03-09 14:00 UTC, akuporos commented on src/bindings/python/src/pyopenvino/frontend/input_model.cpp
> +            :type value: ndarray
done

2022-03-09 14:00 UTC, akuporos commented on src/bindings/python/src/pyopenvino/frontend/input_model.cpp
> +                :return: A list of output places
done

2022-03-09 14:01 UTC, akuporos commented on src/bindings/python/src/pyopenvino/frontend/input_model.cpp
> +                :return: A list of input places
done

2022-03-11 16:18 UTC, merged