Docs ovtf altered
openvinotoolkit/openvino pull request #10965
Opened 2022-03-15 11:36 UTC by kblaszczak-intel

the one-page version of OVTF documentation for OV 2022.1

2022-03-15 12:36 UTC, andrew-zaytsev requested changes

2022-03-15 12:36 UTC, andrew-zaytsev commented on docs/resources/OVTF_overview.md
> +(https://github.com/openvinotoolkit/openvino_tensorflow/tree/master/docs)
```suggestion
```

2022-03-15 12:36 UTC, andrew-zaytsev commented on docs/resources/OVTF_overview.md
> +To find out more about the product itself, as well as learn how to use it in your project, check its dedicated GitHub repository:
```suggestion
To find out more about the product itself, as well as learn how to use it in your project, check its dedicated [GitHub repository]((https://github.com/openvinotoolkit/openvino_tensorflow/tree/master/docs). 
```

2022-03-15 12:36 UTC, andrew-zaytsev commented on docs/resources/OVTF_overview.md
> +**OpenVINO™ integration with TensorFlow** is licensed under [Apache License Version 2.0](LICENSE).
Shoukd it be a  link to LICENSE?

2022-06-08 06:54 UTC, kblaszczak-intel commented
Changes moved to a new PR together with structure changes enabling this implementation.

2022-06-08 06:54 UTC, closed without merging