add ov namespace api
openvinotoolkit/openvino pull request #11030
Opened 2022-03-17 23:41 UTC by ntyukaev

2022-03-18 04:03 UTC, ilyachur requested changes

2022-03-18 04:03 UTC, ilyachur commented on src/inference/include/ie/ie_api.h
> + *  @defgroup ie_cpp_api OpenVINO C++ API
It is not OpenVINO API.
It is old headers and it is still IE API.

2022-03-18 08:14 UTC, ilya-lavrenov commented on src/inference/include/openvino/runtime/core.hpp
> + * @ingroup ie_cpp_api
we must use different groups for IE and OpenVINO APIs: 
- ie_cpp_api for IE API, such API must not be visible in documentation.
- ov_cpp_api for OpenVINO Runtime C++ API, which must be visible in documentation.

2022-03-20 16:14 UTC, ilya-lavrenov commented
Replaced by https://github.com/openvinotoolkit/openvino/pull/11063

2022-03-20 16:14 UTC, closed without merging