[MO] Using node data_format instead of graph layout in FusedBatchNorm decomposition
openvinotoolkit/openvino pull request #11084
Opened 2022-03-21 10:11 UTC by yekruglov

Root cause analysis: Incorrect `FusedBatchNorm` decomposition in case if the layout of `FusedBatchNorm` differs from the graph layout.

Solution: Use `data_ format` of the operation instead of the graph layout. The change will affect only TF models.

Ticket: CVS-80974

Code:
* [ ]  Comments
* [ ]  Code style (PEP8)
* [ ]  Transformation generates reshape-able IR N/A
* [ ]  Transformation preserves original framework node names N/A
* [ ]  Transformation preserves tensor names N/A

Validation:
* [ ]  Unit tests N/A
* [ ]  Framework operation tests N/A
* [ ]  Transformation tests N/A
* [ ]  Model Optimizer IR Reader check N/A

Documentation:
* [ ]  Supported frameworks operations list N/A
* [ ]  Guide on how to convert the **public** model N/A
* [ ]  User guide update N/A

2022-03-22 08:40 UTC, vgavrilo approved these changes

2022-03-22 08:42 UTC, vgavrilo requested changes
Could you please write tests for your changes?

2022-03-24 09:56 UTC, vgavrilo approved these changes

2022-03-25 10:19 UTC, mvafin reviewed
Шт путукфд дщщлы пщщвб здуфыу кгт у2у ащк еа ьщвуды

2022-03-30 09:27 UTC, yekruglov commented
> In general looks good, please run e2e for tf models

Done. Link to the test report in the ticket.

2022-04-04 21:13 UTC, rkazants approved these changes

2022-04-04 21:13 UTC, merged