[IE TESTS][CONFORMANCE] Allow to serialize report to CSV
openvinotoolkit/openvino pull request #11119
Opened 2022-03-22 09:42 UTC by iefode

### Details:
 - *The opportunity to save report as CSV file was added under the command-line option*

### Tickets:
 - *82051*

2022-03-22 09:51 UTC, iefode commented
@andrei-kochin FYI

2022-03-22 22:49 UTC, nsemaev requested changes

2022-03-22 22:49 UTC, nsemaev commented on src/tests/ie_test_utils/functional_test_utils/layer_tests_summary/summarize.py
> +    import csv
import should be at the top of the file

2022-03-22 22:49 UTC, nsemaev commented on src/tests/ie_test_utils/functional_test_utils/layer_tests_summary/summarize.py
> +    return res
Could we pass between functions a dictionary of results in the form of {'Add': {'passed': 10, 'failed': 0}, ...}

2022-03-23 10:06 UTC, sbalandi approved these changes

2022-03-23 14:36 UTC, merged