[tools][benchmark_app] --extensions parameter
openvinotoolkit/openvino pull request #11289
Opened 2022-03-29 06:03 UTC by AlexeyLebedev1

### Tickets:
 - *80901*

2022-03-30 06:19 UTC, nkogteva requested changes

2022-03-30 06:19 UTC, nkogteva commented on tools/benchmark_tool/README.md
> -  -c PATH_TO_CLDNN_CONFIG, --path_to_cldnn_config PATH_TO_CLDNN_CONFIG
-с should not be removed

2022-04-01 08:19 UTC, AlexeyLebedev1 commented on tools/benchmark_tool/README.md
> -  -c PATH_TO_CLDNN_CONFIG, --path_to_cldnn_config PATH_TO_CLDNN_CONFIG
Reverted.

2022-10-04 08:04 UTC, nkogteva approved these changes

2022-10-26 21:26 UTC, merged