Merged-PR proofreading
openvinotoolkit/openvino pull request #11345
Opened 2022-03-30 13:46 UTC by sgolebiewski-intel

2022-03-31 02:31 UTC, xu-yuan1 requested changes
For installing-openvino-docker-windows.md and installing-openvino-pip.md and other installation topics, please do NOT change the structure as it's agreed by developers. You can directly copy the file from releases/22/1.

2022-03-31 02:52 UTC, xu-yuan1 commented on docs/install_guides/installing-openvino-pip.md
>  For system requirements and troubleshooting, see <https://pypi.org/project/openvino/>.
You can revise this sentence if you want to add System Requirements above.

2022-03-31 02:53 UTC, xu-yuan1 commented on docs/install_guides/installing-openvino-pip.md
> +@sphinxdirective
The following steps are repeating the 5 steps above.

2022-03-31 02:57 UTC, xu-yuan1 commented on docs/install_guides/installing-openvino-docker-windows.md
>  ## Installation Flow
Changes starting from here need be reverted. We agreed on having a simple overview of the flow first and then the detailed steps.

2022-04-14 07:07 UTC, xu-yuan1 approved these changes

2022-05-27 11:06 UTC, sgolebiewski-intel commented
Moved to #11750

2022-05-27 11:06 UTC, closed without merging