[GNA] Support of sub requests
openvinotoolkit/openvino pull request #11470
Opened 2022-04-05 15:23 UTC by mryzhov

### Details:
 - Excluded unused tuples
 - Added sub requests processing

### Tickets:
 - N/A

2022-04-05 15:44 UTC, nkogteva commented on src/plugins/intel_gna/gna_data_types.hpp
> +    uint32_t id = 0;
why not `FAKE_REQUEST_CONFIG_ID` is used as default?

2022-04-05 15:47 UTC, nkogteva approved these changes

2022-09-15 10:22 UTC, kbruniec requested changes
It looks like this PR is adding dead code (unused structure) only.

2022-09-15 10:33 UTC, mryzhov commented
> It looks like this PR is adding dead code (unused structure) only.
Yes, I'm rebasing the old PRs, and looks like those code has been submitted already

2022-09-15 10:33 UTC, closed without merging

2022-09-15 10:34 UTC, mryzhov commented
no need anymore because those changes were submitted as part of other PRs