[MO] update ROIAlign op to opset9
openvinotoolkit/openvino pull request #11623
Opened 2022-05-04 14:33 UTC by bszmelcz

### Details:
 - [x] add `aligned_mode` attribute
 - [x] update ROIAligned MO implementation
 - [x] add MO unit tests for ROIAlign-9

### Tickets:
 - 83653

2022-05-20 12:11 UTC, mitruska requested changes

2022-05-20 12:11 UTC, mitruska commented on tools/mo/unit_tests/mo/ops/roialign_test.py
> +class TestROIAlignOps(unittest.TestCase):
There are additional tests for MO ONNX ROIAlign:
https://github.com/openvinotoolkit/openvino/blob/252c72146b8c7ec054bc27f001bbdef52c783f51/tests/layer_tests/onnx_tests/test_roi_align.py#L107-L109
Could you enable it (`@pytest.mark.precommit`) at least for one CI cycle?
Also you can update these tests if needed, and please ensure they won't go by default MO path, so with ONNX FE (onnx importer).

2022-06-09 08:37 UTC, tomdol approved these changes

2022-06-09 09:39 UTC, mitruska requested changes

2022-06-09 09:39 UTC, mitruska commented on tools/mo/openvino/tools/mo/front/onnx/roialign_ext.py
> +            aligned_mode = onnx_attr(node, 'coordinate_transformation_mode', 's', default=b'half_pixel').decode()
It won't work for onnx ROIAlign-16 `coordinate_transformation_mode` set to "output_half_pixel".
We need to map it to one of the openvino ROIAlign-9 `aligned_mode` options.

Please take a look at support for ONNX ROIAlign-16 from new ONNX FE (onnx importer):
https://github.com/openvinotoolkit/openvino/blob/5fa669785c555838df8b3cdc3fe24a644c91d59c/src/frontends/onnx/frontend/src/op/roi_align.cpp#L64-L66

2022-06-09 09:39 UTC, mitruska commented on tests/layer_tests/onnx_tests/test_roi_align.py
> +        operatorsetid.version = 10
What about tests for ONNX ROIAlign-16?

2022-06-09 09:39 UTC, mitruska commented on tests/layer_tests/common/layer_test_class.py
> +            mo_params["use_legacy_frontend"] = True
I suggested this line to enable triggering tests for legacy frontend, but it also has impact on default frontend for layer tests. I think we should set `use_new_frontend` default `True`, to keep testing new frontend as default. 
https://github.com/openvinotoolkit/openvino/blob/9a2f2e446189d396fd27dbc6b7d67520ae00b47b/tests/layer_tests/common/layer_test_class.py#L33

2022-06-09 12:18 UTC, bszmelcz commented on tests/layer_tests/onnx_tests/test_roi_align.py
> +        operatorsetid.version = 10
I will add them

2022-06-09 12:34 UTC, bszmelcz commented on tools/mo/openvino/tools/mo/ops/roialign.py
> +                '"aligned_mode" attribute range of values is ["asymmetric", "half_pixel_for_nn", "half_pixel"]'
Yeah, got it.

2022-06-21 09:30 UTC, mitruska approved these changes

2022-06-22 07:07 UTC, jiwaszki approved these changes

2022-06-22 08:58 UTC, merged