Fixed ConvertColorI420LayerTest::SetUp() method
openvinotoolkit/openvino pull request #11757
Opened 2022-05-27 17:59 UTC by lohika-denis-kotov

### Details:
Bugfix for ConvertColorI420LayerTest::SetUp() method. There for single plane was used wrong `ngraph` class

2022-05-30 14:10 UTC, dkalinowski approved these changes

2022-05-30 14:25 UTC, atobiszei commented on src/tests/functional/shared_test_classes/src/single_layer/convert_color_i420.cpp
> +            convert_color = std::make_shared<ov::op::v8::I420toRGB>(param);
```suggestion
            convert_color = std::make_shared<ov::op::v8::I420toBGR>(param);
```

2022-05-30 14:26 UTC, dkalinowski requested changes
There is typo in the change @lohika-denis-kotov

2022-05-30 14:26 UTC, atobiszei requested changes
There seems to be mistake with BGR->RGB

2022-05-30 14:26 UTC, lohika-denis-kotov commented on src/tests/functional/shared_test_classes/src/single_layer/convert_color_i420.cpp
> +            convert_color = std::make_shared<ov::op::v8::I420toRGB>(param);
Yeah, copy-paste :)

2022-05-30 14:27 UTC, dkalinowski approved these changes

2022-05-31 07:10 UTC, atobiszei approved these changes

2022-06-02 12:36 UTC, lohika-denis-kotov commented
@atobiszei @dkalinowski Could you ping somebody to start jenkins job to finish this PR ?

2023-05-24 00:19 UTC, akladiev commented
This PR was closed because it has been stalled for 2 week with no activity.

2023-05-24 00:19 UTC, closed without merging