[ONNX] Extend ONNX FE with SoftSign-9 operation
openvinotoolkit/openvino pull request #11766
Opened 2022-05-30 15:31 UTC by jiwaszki

### Tickets:
 - *79215*

2022-05-31 08:11 UTC, t-jankowski approved these changes

2022-05-31 08:52 UTC, mitruska requested changes

2022-05-31 09:51 UTC, jiwaszki commented on src/frontends/onnx/frontend/src/default_opset.hpp
> +namespace default_opset = ngraph::opset9;
Reverted.

2022-05-31 09:54 UTC, mitruska approved these changes

2022-06-01 11:37 UTC, tomdol approved these changes

2022-06-01 11:37 UTC, merged