Optimize FullyConnected FakeQuantize post-ops
openvinotoolkit/openvino pull request #11819
Opened 2022-06-07 14:43 UTC by mangguo321

### Details:
 - *Optimize FullyConnected FakeQuantize post-ops with a inner product output scaling*
 - *Optimize FullConnected "eltwise+ FakeQuantize" post-ops with a eltwise scaling*

### Tickets:
 - *CVS-86027*
 - *CVS-85020*

2022-06-09 06:52 UTC, zhangYiIntel commented
Hi Mang,
also need this to avoid bias fused with FQ
https://github.com/mangguo321/openvino/pull/8

2022-06-16 07:45 UTC, mangguo321 commented on src/plugins/intel_cpu/src/nodes/fullyconnected.cpp
> +                            ops.get()->entry_[len - 1].eltwise.scale = isc[0];
Done.

2022-06-16 07:45 UTC, mangguo321 commented on src/plugins/intel_cpu/src/nodes/fullyconnected.cpp
> +                            if (std::abs(cl[0] * isc[0] + 128.f) > 0.0001f) {
Done.

2022-06-21 06:37 UTC, mangguo321 commented on src/plugins/intel_cpu/src/docs/fake_quantize.md
> +$$
Done.

2022-07-01 03:15 UTC, xuchen-intel requested changes

2022-07-01 03:15 UTC, xuchen-intel commented on src/plugins/intel_cpu/src/docs/fake_quantize.md
> +$$
```suggestion
$$
\begin{align}
   q = round(\frac{x - il}{ih - il} * (levels-1)) \\
   output = q * \frac{oh - ol}{levels-1}  + ol
\end{align}
$$
```

2022-07-01 03:15 UTC, xuchen-intel commented on src/plugins/intel_cpu/src/docs/fake_quantize.md
> +$$
```suggestion

$$
```

2022-07-01 03:15 UTC, xuchen-intel commented on src/plugins/intel_cpu/src/docs/fake_quantize.md
> + - equation (5) is traditional quantization x into q only if Zi is integer:
Please mark the corresponding equation (5) and (7).

2022-07-01 03:15 UTC, xuchen-intel commented on src/plugins/intel_cpu/src/docs/fake_quantize.md
> +$$
```suggestion
$$
\begin{align}
   (levels-1)/Z_i = -(ih - il)/il = 1 - ih/il \\
   2(1-1/levels) = 1 - ih/il \\
   il = -ih/(1 - 2/levels)
\end{align}
$$
```

2022-07-04 11:11 UTC, usstq approved these changes

2022-07-05 01:39 UTC, xuchen-intel approved these changes

2022-07-05 01:39 UTC, merged