[Feature request][MO] add ONNX operator com.microsoft.gelu support into frontend/onnx
openvinotoolkit/openvino pull request #11971
Opened 2022-06-27 05:25 UTC by MyGInt

### Details:

- Add onnx op com.microsoft.gelu support in frontend/onnx
- Add gelu test in layer_tests

### Tickets:
 #11881

2022-06-27 09:06 UTC, t-jankowski requested changes

2022-06-27 09:06 UTC, t-jankowski commented on src/core/tests/models/onnx/com.microsoft/gelu.prototxt
> +ir_version: 3
Why the oldest `ir_version`? Let's use the newest supported by OV. Same about `opset_import.version`.

2022-06-27 10:20 UTC, tomdol requested changes

2022-06-27 10:20 UTC, tomdol commented on src/frontends/onnx/frontend/src/op/com.microsoft/gelu.cpp
> +#include "op/com.microsoft/bias_gelu.hpp"
```suggestion
```

2022-07-07 07:48 UTC, t-jankowski approved these changes

2022-07-07 08:00 UTC, t-jankowski commented
@MyGInt Code Style check fails - `make clang_format_fix_all` should help.

2022-07-25 09:07 UTC, tomdol approved these changes

2022-07-25 09:15 UTC, artkuli approved these changes

2022-07-26 08:28 UTC, MyGInt commented
> The code in `ops_bridge.cpp` is not correctly formatted. Please run `make clang_format_fix_all` locally in your build directory and commit the resulting changes.

 It works,  thanks a lot!

2022-07-27 13:51 UTC, tomdol commented
There's a problem with one of the commits, GH is not going to accept it. Could you perhaps squash all of the commits in this PR under your username and force-push? This should resolve the issue.

2022-08-10 05:29 UTC, closed without merging