Update module version to remove vulnerability
openvinotoolkit/openvino pull request #12054
Opened 2022-07-06 05:54 UTC by byungilm

Signed-off-by: Min, Byungil <byungil.min@intel.com>

### Details:
 - update module lxml, nltk and pylint
 -
 -

### Tickets:
 - 85245

2022-07-06 09:43 UTC, jiwaszki requested changes

2022-07-06 09:43 UTC, jiwaszki commented on tools/mo/requirements_dev.txt
> +pylint==2.7.0
You need to loosen requirements. Please only restrict them "from the bottom" like:
```
astroid>=2.5.0
pylint>=2.7.0
```
Note: Look at astroid packaged being bumped as well, this also fix linux error with deps

2022-07-06 09:43 UTC, jiwaszki commented on docs/requirements.txt
> +lxml==4.6.5
```suggestion
lxml>=4.6.5
```

2022-07-06 11:49 UTC, jiwaszki approved these changes

2022-07-08 06:28 UTC, tomdol approved these changes

2022-07-08 06:28 UTC, merged