[TF FE] Add Transpose Sinking for additional unary-wise Operations
openvinotoolkit/openvino pull request #12691
Opened 2022-08-22 14:49 UTC by rkazants

**Details:** It helps to fix performance degradation for MobileNet models

**Tickets:** 89908

Signed-off-by: Kazantsev, Roman <roman.kazantsev@intel.com>

2022-08-22 18:03 UTC, mvafin approved these changes

2022-08-24 14:03 UTC, itikhono approved these changes

2022-08-24 14:33 UTC, mvafin approved these changes

2022-08-24 15:34 UTC, cavusmustafa requested changes

2022-08-24 15:45 UTC, rkazants commented on src/frontends/tensorflow/src/pass/transpose_sinking.cpp
> +                       as_type_ptr<Elu>(n) || as_type_ptr<SoftPlus>(n) || as_type_ptr<LogicalNot>(n)) {
is it not quite unary operation since it has two inputs. It requires a bit different fix. I will return to this tomorrow in the scope of separate PR.

2022-08-24 16:59 UTC, ilya-lavrenov approved these changes

2022-08-24 18:10 UTC, merged