[ONNX] propagate model directory path to Graph, Attribute and Tensor …
openvinotoolkit/openvino pull request #13010
Opened 2022-09-12 11:13 UTC by mateusztabaka

…class

Required by external data mechanism in ONNX standard, where Tensor object has to be able to find external data file based on the location field and model directory path. Previously, it was done by a transformation, but it handled initializers only, but in order to handle Constant nodes we need one more loop, but over all of the model's nodes. Propagating model directory path to Tensor allows us to reduce that overhead.

Ticket: 91271

2022-09-13 11:21 UTC, t-jankowski requested changes

2022-09-13 11:21 UTC, t-jankowski commented on src/frontends/onnx/frontend/src/core/attribute.hpp
> +        std::vector<Tensor> ret;
Vector size is known up front - consider `reserve()`.

2022-09-13 11:21 UTC, t-jankowski commented on src/frontends/onnx/frontend/src/utils/tensor_external_data.cpp
> +        }
Consider `switch` statement.

2022-09-13 11:24 UTC, mateusztabaka commented on src/frontends/onnx/frontend/src/utils/tensor_external_data.cpp
> +        }
you can't use switch with string in c++

2022-09-13 11:46 UTC, t-jankowski commented on src/frontends/onnx/frontend/src/utils/tensor_external_data.cpp
> +        }
Right .. may I delete my comment? ;)

2022-09-13 11:47 UTC, mateusztabaka commented on src/frontends/onnx/frontend/src/utils/tensor_external_data.cpp
> +        }
sure

2022-09-14 06:59 UTC, mbencer commented on src/frontends/onnx/frontend/src/core/tensor.cpp
> +        return detail::__get_data<int16_t>(m_tensor_proto->int32_data());
shouldn't be `m_tensor_proto->int16_data`?

2022-09-14 07:03 UTC, mbencer approved these changes
LGTM

2022-09-15 08:14 UTC, mateusztabaka commented on src/frontends/onnx/tests/onnx_import_external_data.in.cpp
> +NGRAPH_TEST(${BACKEND_NAME}, onnx_external_data_in_constant_node) {
this test does inference so it requires backend to do so.

2022-09-15 09:54 UTC, t-jankowski commented on src/frontends/onnx/tests/onnx_import_external_data.in.cpp
> +NGRAPH_TEST(${BACKEND_NAME}, onnx_external_data_in_constant_node) {
I meant that it need not be run on various backends, one (doesn't matter which) should be enough as the purpose of the test is to check proper model external data location propagation. And that is not dependent to a backend.

2022-09-15 09:58 UTC, t-jankowski approved these changes

2022-09-15 10:09 UTC, t-jankowski commented on src/frontends/onnx/tests/onnx_import_external_data.in.cpp
> +NGRAPH_TEST(${BACKEND_NAME}, onnx_external_data_in_constant_node) {
Let's leave it for now - other tests in the file needs to reviewed for the same reason.

2022-09-16 04:48 UTC, merged