[AUTO plugin] Enable benchmark setting performance hint with none value to hardware device through AUTO/MULTI plugin
openvinotoolkit/openvino pull request #13063
Opened 2022-09-15 09:40 UTC by yangwang201911

### Details:
 - Enable benchmark app passing hint with none value to plugin.
 - Enable AUTO/MULTI plugin to support passing hint with none value to hardware device from user app.

### Tickets:
 - 90196

2022-09-16 02:21 UTC, peterchen-intel requested changes
Keep current 2.0/IE API mapping UNDEFINDED (2.0) <---> "" (IE API), check inside the AUTO Plugin

2022-09-26 09:55 UTC, nkogteva commented on samples/cpp/benchmark_app/main.cpp
> +            device_config.emplace(ov::hint::performance_mode(ov_perf_hint));
Please do the same for python app

2022-09-29 03:00 UTC, yangwang201911 commented on samples/cpp/benchmark_app/main.cpp
> +            device_config.emplace(ov::hint::performance_mode(ov_perf_hint));
Done.

2022-09-30 01:48 UTC, peterchen-intel approved these changes

2022-10-10 13:23 UTC, nkogteva approved these changes

2022-10-12 02:03 UTC, wangleis approved these changes

2022-10-12 02:03 UTC, merged