[PyOV] Fix iteration over AsyncInferQueue
openvinotoolkit/openvino pull request #13496
Opened 2022-10-14 13:57 UTC by akuporos

### Details:
 - Previously iterator yielded binded InferRequest objects. We need that it should go via python InferRequest wrapper.

### Tickets:
 - 94246

2022-10-14 14:26 UTC, Wovchena approved these changes

2022-10-17 10:02 UTC, jiwaszki requested changes

2022-10-17 10:02 UTC, jiwaszki commented on src/bindings/python/tests/test_runtime/test_infer_request.py
> +def test_infer_queue_iteration(device):
Also the test for `iter(asyncinferqueue_obj)` would be great. It might be added in this one as an assert.

2022-10-18 12:59 UTC, akuporos commented on src/bindings/python/tests/test_runtime/test_infer_request.py
> +        infer_req.start_async()
done

2022-10-18 12:59 UTC, akuporos commented on src/bindings/python/src/openvino/runtime/ie_api.py
> +    def __iter__(self) -> map:
done

2022-10-18 14:42 UTC, akuporos commented on src/bindings/python/src/openvino/runtime/ie_api.py
> +    def __iter__(self) -> map:
Looks like we don't need  `__next__` implementation as AsyncInferQueue isn't `Iterator` by itself. Please, look at the test that `next` will work as `iter` is a map object.

2022-10-19 15:45 UTC, merged