Transpose sinking on passes for Concat, Split and binary eltwise operations
openvinotoolkit/openvino pull request #13545
Opened 2022-10-19 08:01 UTC by evkotov

### Details:
 - transpose sinking group of transformations
 - binary eltwise operations
 - concat
 - split
 - use ngraph MatcherPass
 - forward and backward propagation
 - unit tests

### Tickets:
 - 92221
 - 94139

2022-10-21 13:19 UTC, evkotov commented on src/common/transformations/src/transformations/common_optimizations/transpose_sinking_binary.cpp
> +        auto transpose = GetFirstTransposeInput(binary.get());
No it doesn't work. If there are two transpose inputs it founds not the first transpose input.

2022-10-22 19:25 UTC, evkotov commented on src/common/transformations/src/transformations/common_optimizations/transpose_sinking_binary.cpp
> +        return {};
No. This function is also used in IfNodeHasTransposeInputs to check if Concat has any input with transposes. If no we just check that return is empty shared_ptr<Node>. Throwing exception and than catching it later is not the best idea.

2022-10-22 19:26 UTC, evkotov commented on src/common/transformations/src/transformations/common_optimizations/transpose_sinking_binary.cpp
> +        return dynamic_cast<const ov::opset9::Transpose*>(node) != nullptr;
I wanted to separate traversing inputs and predicate that input is transpose.

2022-10-22 19:28 UTC, evkotov commented on src/common/transformations/src/transformations/common_optimizations/transpose_sinking_binary.cpp
> +ov::AxisVector ReverseTransposeOrder(const ov::AxisVector & axis_order)
I will check it. But on the first glance std::reverse is just reversing vector elements in backward order. But here we need to reverse a transpose permutation. I think it is not the same

2022-10-24 06:44 UTC, nkogteva reviewed
In general, LGTM

2022-10-24 06:44 UTC, nkogteva commented on src/common/transformations/src/transformations/common_optimizations/transpose_sinking_binary.cpp
> +struct TrasposeInputInfo {
```suggestion
struct TransposeInputInfo {
```

2022-10-24 06:44 UTC, nkogteva commented on src/common/transformations/src/transformations/common_optimizations/transpose_sinking_binary.cpp
> +    for (int input_idx = 0; input_idx < node->get_input_size(); ++input_idx) {
```suggestion
    for (size_t input_idx = 0; input_idx < node->get_input_size(); ++input_idx) {
```

2022-10-24 06:44 UTC, nkogteva commented on src/common/transformations/src/transformations/common_optimizations/transpose_sinking_binary.cpp
> +    throw std::runtime_error("no transpose input found");
Do we need it?

2022-10-24 06:44 UTC, nkogteva commented on src/common/transformations/src/transformations/common_optimizations/transpose_sinking_binary.cpp
> +    for (int input_idx = 0; input_idx < output.get_node()->get_input_size(); ++input_idx) {
```suggestion
    for (size_t input_idx = 0; input_idx < output.get_node()->get_input_size(); ++input_idx) {
```

2022-10-24 06:44 UTC, nkogteva commented on src/common/transformations/src/transformations/common_optimizations/transpose_sinking_binary.cpp
> +{
style {

2022-10-24 06:44 UTC, nkogteva commented on src/common/transformations/src/transformations/common_optimizations/transpose_sinking_binary.cpp
> +void SwapOutputNames(ov::Output<ov::Node> output1, ov::Output<ov::Node> output2) {
```suggestion
void SwapOutputNames(ov::Output<ov::Node>& output1, ov::Output<ov::Node>& output2) {
```

2022-10-24 06:44 UTC, nkogteva commented on src/common/transformations/src/transformations/common_optimizations/transpose_sinking_binary.cpp
> +    int input_idx;
```suggestion
    size_t input_idx;
```

2022-10-24 06:44 UTC, nkogteva commented on src/common/transformations/src/transformations/common_optimizations/transpose_sinking_binary.cpp
> +    int output_idx;
```suggestion
    size_t output_idx;
```

2022-10-24 06:44 UTC, nkogteva commented on src/common/transformations/src/transformations/common_optimizations/transpose_sinking_binary.cpp
> +            else {
style 
```
} else {
```

2022-10-24 06:44 UTC, nkogteva commented on src/common/transformations/src/transformations/common_optimizations/transpose_sinking_binary.cpp
> +        const auto & pattern_to_output = m.get_pattern_value_map();
Let's use the same & aligment in code

2022-10-24 06:44 UTC, nkogteva commented on src/common/transformations/src/transformations/common_optimizations/transpose_sinking_binary.cpp
> +            for (auto consumer: split_consumers) {
```suggestion
            for (auto& consumer: split_consumers) {
```

2022-10-24 06:44 UTC, nkogteva commented on src/common/transformations/src/transformations/common_optimizations/transpose_sinking_binary.cpp
> +                    for (auto consumer: transpose_consumers) {
```suggestion
                    for (auto& consumer: transpose_consumers) {
```

2022-10-24 06:44 UTC, nkogteva commented on src/common/transformations/src/transformations/common_optimizations/transpose_sinking_binary.cpp
> +        for (auto consumer: binary_consumers) {
```suggestion
        for (auto& consumer: binary_consumers) {
```

2022-10-24 06:44 UTC, nkogteva commented on src/common/transformations/src/transformations/common_optimizations/transpose_sinking_binary.cpp
> +        for (auto consumer: transpose_consumers) {
```suggestion
        for (auto& consumer: transpose_consumers) {
```

2022-10-24 06:44 UTC, nkogteva commented on src/common/transformations/src/transformations/common_optimizations/transpose_sinking_binary.cpp
> +        for (auto consumer: binary_consumers) {
```suggestion
        for (auto& consumer: binary_consumers) {
```

2022-10-24 06:44 UTC, nkogteva commented on src/common/transformations/src/transformations/common_optimizations/transpose_sinking_binary.cpp
> +        for (auto consumer: transpose_consumers) {
```suggestion
        for (auto& consumer: transpose_consumers) {
```

2022-10-24 06:44 UTC, nkogteva commented on src/common/transformations/src/transformations/common_optimizations/transpose_sinking_binary.cpp
> +    for (int output_idx = 0; output_idx < node->get_output_size(); ++output_idx) {
```suggestion
    for (size_t output_idx = 0; output_idx < node->get_output_size(); ++output_idx) {
```

2022-10-24 06:44 UTC, nkogteva commented on src/common/transformations/src/transformations/common_optimizations/transpose_sinking_binary.cpp
> +        for (auto input : node->get_output_target_inputs(output_idx)) {
```suggestion
        for (auto& input : node->get_output_target_inputs(output_idx)) {
```

2022-10-24 06:44 UTC, nkogteva commented on src/common/transformations/src/transformations/common_optimizations/transpose_sinking_binary.cpp
> +    for (int output_idx = 0; output_idx < node->get_output_size(); ++output_idx) {
```suggestion
    for (size_t output_idx = 0; output_idx < node->get_output_size(); ++output_idx) {
```

2022-10-24 06:44 UTC, nkogteva commented on src/common/transformations/src/transformations/common_optimizations/transpose_sinking_binary.cpp
> +        for (int output_idx = 0; output_idx < split->get_output_size(); ++output_idx) {
```suggestion
        for (size_t output_idx = 0; output_idx < split->get_output_size(); ++output_idx) {
```

2022-10-24 06:44 UTC, nkogteva commented on src/common/transformations/src/transformations/common_optimizations/transpose_sinking_binary.cpp
> +            for (auto input : split->get_output_target_inputs(output_idx)) {
```suggestion
            for (auto& input : split->get_output_target_inputs(output_idx)) {
```

2022-10-27 18:04 UTC, itikhono requested changes

2022-10-27 18:04 UTC, itikhono commented on src/common/transformations/include/transformations/common_optimizations/transpose_sinking_binary.hpp
> +class ngraph::pass::TransposeSinkingSplitForward : public ov::pass::MatcherPass {
Can we combine TransposeSinkingSplit and TransposeSInkingBinary?
Does Split has a specific except number of outputs?

2022-10-31 08:25 UTC, closed without merging

2022-10-31 08:25 UTC, itikhono commented
PR has been re-opened https://github.com/openvinotoolkit/openvino/pull/13718