Transpose sinking general
openvinotoolkit/openvino pull request #13943
Opened 2022-11-10 12:22 UTC by evkotov

### Details:
- unite all transformations into general
- fix TransposeFuse transformation setting up Transpose Constant element type
- add code that prevents moving backward Transposes
- includes PR https://github.com/openvinotoolkit/openvino/pull/13718

### Tickets:
 - 92896

2022-11-30 06:55 UTC, nkogteva requested changes
Something is wrong with onednn sunmodules, please rebase carrefully

2022-11-30 06:55 UTC, nkogteva commented on src/common/transformations/src/transformations/common_optimizations/transpose_sinking.cpp
> +        auto transpose_oder_type = transpose1_order->get_element_type();
```suggestion
        auto transpose_order_type = transpose1_order->get_element_type();
```

2022-11-30 06:55 UTC, nkogteva commented on src/common/transformations/src/transformations/common_optimizations/transpose_sinking_utils.cpp
> +#define NO_TRANSPOSE_SINKING_KEY "no_transpose_sinking"
Does it make sense to create attribute based on `ov::RuntimeAttribute` ?

2022-11-30 06:55 UTC, nkogteva commented on src/common/transformations/src/transformations/common_optimizations/transpose_sinking_general.cpp
> +bool ov::pass::TransposeSinkingGeneral::run_on_model(const std::shared_ptr<ov::Model>& f) {
```suggestion
bool ov::pass::TransposeSinkingGeneral::run_on_model(const std::shared_ptr<ov::Model>& f) {
    RUN_ON_FUNCTION_SCOPE(TransposeSinkingGeneral);
```

2022-11-30 06:55 UTC, nkogteva commented on src/common/transformations/include/transformations/common_optimizations/transpose_sinking_utils.hpp
> +bool IsSinkingEnable(std::shared_ptr<ov::Node>);
```suggestion
bool IsSinkingEnabled(std::shared_ptr<ov::Node>);
```

2022-11-30 06:55 UTC, nkogteva commented on src/common/transformations/include/transformations/common_optimizations/transpose_sinking_utils.hpp
> +bool IsSinkingEnable(ov::Node*);
```suggestion
bool IsSinkingEnabled(ov::Node*);
```

2022-12-01 15:31 UTC, evkotov commented on src/common/transformations/src/transformations/common_optimizations/transpose_sinking_general.cpp
> +bool ov::pass::TransposeSinkingGeneral::run_on_model(const std::shared_ptr<ov::Model>& f) {
I don't see the difference )

2022-12-09 08:47 UTC, nkogteva approved these changes

2022-12-13 04:16 UTC, itikhono approved these changes

2022-12-13 16:08 UTC, merged