reintroduce benchmarks for ovms
openvinotoolkit/openvino pull request #14271
Opened 2022-11-28 10:26 UTC by kblaszczak-intel

2022-11-30 19:15 UTC, mfhansen requested changes
The Resnet-18 images (PNGs) for FP32 and INT8 are missing from the OVMS page. Changes required in docs/benchmarks/performance_benchmarks_ovms.md

-Michael

2022-12-01 09:39 UTC, kblaszczak-intel commented
two remaining files included

2022-12-01 18:46 UTC, mfhansen approved these changes

2022-12-02 07:34 UTC, sgolebiewski-intel approved these changes

2022-12-02 07:34 UTC, tsavina approved these changes

2022-12-02 07:36 UTC, merged