[AUTO][Benchmark APP] sync config parsing logic of benchmark python version with benchmark c++ version
openvinotoolkit/openvino pull request #14328
Opened 2022-11-30 05:41 UTC by yangwang201911

### Details:
 - sync config parsing logic of benchmark python version with benchmark C++ version

### Tickets:
 - CVS-94329

2022-11-30 06:41 UTC, nkogteva approved these changes

2022-12-05 13:08 UTC, Wovchena requested changes

2022-12-05 13:08 UTC, Wovchena commented on tools/benchmark_tool/openvino/tools/benchmark/utils/utils.py
> +                    properties[device]['DEVICE_PROPERTIES'][property_name] = {}
```suggestion
                properties[device].setdefault('DEVICE_PROPERTIES', {})
                properties[device]['DEVICE_PROPERTIES'].setdefault(property_name, {})
```

2022-12-06 01:20 UTC, yangwang201911 commented on tools/benchmark_tool/openvino/tools/benchmark/parameters.py
> +    parser = argparse.ArgumentParser(add_help=False, formatter_class=HelpFormatterWithLines)
This change replacing `HelpFormatterWithLines` with `RawTextHelpFormatter`, will affect the display format of other help msg. The display length of help msg using `RawTextHelpFormatter` is too long and not aligned, while `HelpFormatterWithLines` only changes the help msg display format of `load_config`. Need your confirm.

2022-12-06 01:54 UTC, wangleis approved these changes

2022-12-06 03:47 UTC, yangwang201911 commented on tools/benchmark_tool/openvino/tools/benchmark/parameters.py
> +                           "             	\"AUTO\": {\n"
Done

2022-12-06 03:48 UTC, yangwang201911 commented on tools/benchmark_tool/openvino/tools/benchmark/utils/utils.py
> +    original_config = {}
Done

2022-12-06 03:48 UTC, yangwang201911 commented on tools/benchmark_tool/openvino/tools/benchmark/utils/utils.py
> +        if device not in [AUTO_DEVICE_NAME, MULTI_DEVICE_NAME]:
Done

2022-12-06 03:48 UTC, yangwang201911 commented on tools/benchmark_tool/openvino/tools/benchmark/utils/utils.py
> +                    properties[device]['DEVICE_PROPERTIES'][property_name] = {}
Done

2022-12-06 09:23 UTC, Wovchena commented on tools/benchmark_tool/openvino/tools/benchmark/parameters.py
> +    parser = argparse.ArgumentParser(add_help=False, formatter_class=HelpFormatterWithLines)
Well, that would align C++ and Python implementations even more. C++ also doesn't limit message length. But I will approve, not to block you

2022-12-06 09:28 UTC, merged