upgrade gflags version for rhel8
openvinotoolkit/openvino pull request #14664
Opened 2022-12-15 12:33 UTC by dtrawins

fix seg fault in cpp sample apps on rhel8

2022-12-15 14:51 UTC, p-durandin requested changes
Should we use platform spec or "$arch@ here

2022-12-20 05:47 UTC, ilyachur reviewed
In general LGTM

2022-12-20 05:47 UTC, ilyachur commented on scripts/install_dependencies/install_openvino_dependencies.sh
> +	    http://mirror.centos.org/centos/8-stream/PowerTools/$arch/os/Packages/gflags-2.2.2-1.el8.$arch.rpm
Please fix the indentation.
```suggestion
            http://mirror.centos.org/centos/8-stream/PowerTools/$arch/os/Packages/gflags-2.2.2-1.el8.$arch.rpm
```

2023-01-06 14:17 UTC, ilya-lavrenov commented
Solution is here https://github.com/openvinotoolkit/openvino/pull/14724

2023-01-06 14:17 UTC, closed without merging