[GPU] bugfix: block copy accessed out of valid position.
openvinotoolkit/openvino pull request #14845
Opened 2022-12-29 02:17 UTC by sungeunk

### Tickets:
 - 97947

2022-12-30 01:40 UTC, sungeunk commented
No perf drop.

2023-01-02 02:26 UTC, isanghao requested changes

2023-01-02 02:26 UTC, isanghao commented on src/plugins/intel_gpu/src/kernel_selector/cl_kernels/resample_opt.cl
>          WRITE_FUNC(output, OUTPUT_GET_INDEX(b, feature_block, z, y, (x + out_x)), out);
Please handle 5d case, too

2023-01-02 02:26 UTC, isanghao commented on src/plugins/intel_gpu/src/kernel_selector/cl_kernels/resample_opt.cl
> +            output[OUTPUT_GET_INDEX(b, feature_num, y, (x + out_x))] = out;
Please add unittest for this

2023-01-02 02:26 UTC, isanghao commented on src/plugins/intel_gpu/src/kernel_selector/cl_kernels/resample_opt.cl
> +            output[OUTPUT_GET_INDEX(b, feature_num, y, (x + out_x))] = out;
Let's check performance impact from unittest.

2023-01-17 07:04 UTC, isanghao approved these changes

2023-01-17 07:05 UTC, merged