Keras to tflite version of tests
openvinotoolkit/openvino pull request #15042
Opened 2023-01-11 09:29 UTC by rnugmanx

### Tickets:
 - CVS-99807

2023-01-11 10:11 UTC, jane-intel commented on tests/layer_tests/common/tf2_layer_test_class.py
> +            interpreter.set_tensor(input_details[tensor_id]['index'], data)
```suggestion
            interpreter.set_tensor(input_details[tensor_id]['index'], data.astype(tensor['dtype']))
```

2023-01-11 11:52 UTC, rkazants requested changes

2023-01-11 11:52 UTC, rkazants commented on tests/layer_tests/common/utils/tf_utils.py
> +        return data
This routines not necessarily use for TFLite only. It makes sense to put them to the common utils then.

2023-01-11 11:52 UTC, rkazants commented on tests/layer_tests/common/utils/tf_utils.py
> +    return os.path.join(path_to_saved_tf_model, 'model.pb')
absolutely this is not TFLite specific.

2023-01-11 11:58 UTC, rkazants commented on tests/layer_tests/common/utils/tf_utils.py
> +    return tf_lite_result
propose to put all TF Lite specific routines into `tf_lite_layer_test_class.py`

2023-01-11 12:02 UTC, rkazants commented on tests/layer_tests/common/tf2_layer_test_class.py
> +
please move this into TF Lite specific file.

2023-01-11 14:48 UTC, rkazants submitted a review, later dismissed
PR breaks layer tests for TF FE.
Please fix it.

2023-01-12 11:31 UTC, jane-intel approved these changes

2023-01-12 11:45 UTC, rkazants approved these changes

2023-01-13 10:29 UTC, merged