Add aten narrow
openvinotoolkit/openvino pull request #15493
Opened 2023-02-03 13:23 UTC by bszmelcz

### Details:
- [x] add support for `aten::narrow`
- [x] add test coverage
- [x] update `op_table.cpp`
### Tickets:
 - 101085

2023-02-07 07:04 UTC, sikorsl1 commented on tests/layer_tests/pytorch_tests/test_narrow.py
> +    ])
PyTorch documentation allows `start` to be `int` or `Tensor`: https://pytorch.org/docs/stable/generated/torch.narrow.html#torch.narrow:~:text=start%20(Tensor%20or%20int)%20%E2%80%93%20the%20starting%20dimension. Why don't you test it for `Tensor`?

2023-02-07 07:05 UTC, sikorsl1 commented on tests/layer_tests/pytorch_tests/test_narrow.py
> +                self.length = length
I think that you should consider test case, where these values are not constant.

2023-02-07 09:28 UTC, mvafin requested changes

2023-02-07 09:28 UTC, mvafin commented on src/frontends/pytorch/src/op/narrow.cpp
> +#include <climits>
Do you need this include?

2023-02-07 09:28 UTC, mvafin commented on src/frontends/pytorch/src/op/narrow.cpp
> +#include "utils.hpp"
Don't think you need this include

2023-02-07 09:28 UTC, mvafin commented on src/frontends/pytorch/src/op/narrow.cpp
> +#include "openvino/opsets/opset10.hpp"
It would be better to use individual op includes for such small files, but opset is also fine

2023-02-14 12:19 UTC, mvafin commented on src/frontends/pytorch/src/op/narrow.cpp
> +    auto input_tensor = context.get_input(0);
Please check number of inputs using `num_inputs_check` helper function

2023-02-17 11:42 UTC, sikorsl1 commented
This PR should be closed without merging because I can't push to @bszmelcz fork. Continuation of this task can be found in the following PR: https://github.com/openvinotoolkit/openvino/pull/15788

2023-02-20 14:49 UTC, closed without merging