[PT FE] Add aten::empty perator with layer test
openvinotoolkit/openvino pull request #15490
Opened 2023-02-03 11:30 UTC by sikorsl1

### Details:
 - `aten::norm` operator has been added
 - layer test for this operator has been added

### Tickets:
 - 101075

### Comments:

- Generally in PyTorch `aten::empty` operator returns a tensor with uninitialized data, but we don't support such case in OV, so I decided to return a tensor filled with zeros. My solution is based on: https://github.com/pytorch/pytorch/blob/b41e2779f2e24364515d3980e660a6bb23ef5926/torch/onnx/symbolic_opset9.py#L3554

2023-02-07 10:02 UTC, mmikolajcz approved these changes

2023-02-07 11:14 UTC, mvafin requested changes

2023-02-07 11:14 UTC, mvafin commented on tests/layer_tests/pytorch_tests/test_empty.py
> +    def test_empty(self, ie_device, precision, ir_version, ):
```suggestion
    def test_empty_bool(self, ie_device, precision, ir_version, ):
```

2023-02-08 15:59 UTC, mvafin approved these changes

2023-02-09 07:24 UTC, tomdol approved these changes

2023-02-09 07:24 UTC, merged