[PT FE]: support aten:Bool, add tests for aten::add_
openvinotoolkit/openvino pull request #15590
Opened 2023-02-09 05:51 UTC by eaidova

### Details:
 - *support aten::Bool operator*
 - *Added test cases for aten::add_*

### Tickets:
 - *10110*
 - *101100*

2023-02-09 05:52 UTC, eaidova commented on src/frontends/pytorch/src/op/bool.cpp
> +}  // namespace ov
```suggestion
}  // namespace ov

```

2023-02-09 05:52 UTC, eaidova commented on tests/layer_tests/pytorch_tests/test_bool.py
> +        self._test(*self.create_model(input_type), ie_device, precision, ir_version)
```suggestion
        self._test(*self.create_model(input_type), ie_device, precision, ir_version)

```

2023-02-10 13:22 UTC, mvafin approved these changes

2023-02-13 09:52 UTC, mvafin requested changes

2023-02-13 09:52 UTC, mvafin commented on src/frontends/pytorch/src/op/bool.cpp
> +    return {context.mark_node(std::make_shared<ov::op::v0::Convert>(context.get_input(0), element::boolean))};
Please check number of inputs

2023-02-13 13:39 UTC, eaidova commented on src/frontends/pytorch/src/op/bool.cpp
> +    return {context.mark_node(std::make_shared<ov::op::v0::Convert>(context.get_input(0), element::boolean))};
added

2023-02-13 13:44 UTC, mvafin approved these changes

2023-02-13 22:29 UTC, merged