Update timetest tool to support ip and op params config
openvinotoolkit/openvino pull request #15916
Opened 2023-02-23 13:22 UTC by pereanub

### Details:
 - *User can set input and output precision for the timetest tool*

### Tickets:
 - *[CVS-104240](https://jira.devtools.intel.com/browse/CVS-104240)*

2023-02-24 06:27 UTC, ilya-lavrenov commented
why do we need to test such scenarios? Users may also want to add a lot of things to the model, but it does not mean we need it in this tool.

2023-02-24 07:54 UTC, pereanub commented
> why do we need to test such scenarios? Users may also want to add a lot of things to the model, but it does not mean we need it in this tool.

Because we found a specific case with IRv10 where OpenVino is changing precision from FP16 to FP32 even if that network has input and output set to FP16 and that creates some issues when running it on VPU. The problem is described in [CVS-104240](https://jira.devtools.intel.com/browse/CVS-104240).

If you have other suggestions on how it can be fixed, please let us know.

2023-03-02 09:50 UTC, ilya-lavrenov commented
> if that network has input and output set to FP16

how is it set? Could you please provide more details in which flow OpenVINO changes precisions? 
Is the model originally in fp16? converted via MO? etc

2023-03-02 10:04 UTC, pereanub commented
> > if that network has input and output set to FP16
> 
> how is it set? Could you please provide more details in which flow OpenVINO changes precisions? Is the model originally in fp16? converted via MO? etc

Originally the model is FP16, and OpenVino change it to FP32 when read_model is called. Please check the ticket for more details.

2023-03-29 07:42 UTC, vurusovs requested changes

2023-03-29 09:24 UTC, ilya-lavrenov approved these changes

2023-03-29 11:51 UTC, vurusovs approved these changes

2023-03-30 06:40 UTC, ilya-lavrenov commented on tests/lib/src/common_utils.cpp
> +    };
created ticket CVS-107170

2023-03-30 07:27 UTC, merged