[CPU]JIRA 93714 fix CPU plugin warning after remove wd4309 wd4018
openvinotoolkit/openvino pull request #15961
Opened 2023-02-27 01:47 UTC by xipingyan

### Details:
 - *Remove intel_cpu/CMakeLists.txt **ie_add_compiler_flags(/wd4018)** and **ie_add_compiler_flags(/wd4309)***
 - *Fix all the corresponding warning of Windows.*
 - *I also fix some Linux sign-compare issues, but I find there are too many linux issues, new PR will be used to processing left Linux sign-compare issues.*

### Tickets:
 - *104792*

2023-03-02 05:57 UTC, zhangYiIntel requested changes

2023-03-02 06:09 UTC, xipingyan commented on src/plugins/intel_cpu/src/ngraph_transformations/align_matmul_input_ranks.cpp
> +            for (int64_t j = 0; j < static_cast<int64_t>(rankTo - rankFrom); ++j)
Actually, unsqueeze_axes is vector of int64_t, so the next push_back will not need to data type convertion.

2023-03-02 06:12 UTC, xipingyan commented on src/plugins/intel_cpu/src/nodes/interaction.cpp
> +    for (int64_t start = 0; start < static_cast<int64_t>(batchSize); start++) {
@zhangYiIntel , The next function "cat" need to input int64_t param.

2023-03-02 06:20 UTC, xipingyan commented on src/plugins/intel_cpu/src/nodes/roi_align.cpp
> +            for (auto binSampleInd = 0; binSampleInd < numSamplesROI; binSampleInd++) {
Yes, size_t is more reasonable in physical. But binSampleInd is not used in the following code, and binSampleInd is started from 0, and if I change it to auto(expanding to  int), we will not need to convert numSamplesROI.

2023-03-02 06:23 UTC, xipingyan commented on src/plugins/intel_cpu/src/nodes/unique.cpp
> +                for (int64_t i = 0; i < static_cast<int64_t>(uniqueLen); i++) {
@zhangYiIntel , The following code need to use i to initialize struct "OrdEl", and it will receive int64_t type.

2023-03-02 06:59 UTC, zhangYiIntel approved these changes
LGTM Thx!

2023-03-02 07:56 UTC, dmitry-gorokhov approved these changes
CPU part LGTM

2023-03-08 00:55 UTC, xipingyan commented
Hi @ilya-lavrenov , Do you have some comments about this PR? If not, coudl you help merge it, or forward to others, because Linux sign-compare issue needs this PR as base.

2023-03-08 06:40 UTC, ilya-lavrenov approved these changes

2023-03-08 06:41 UTC, merged