【PaddlePaddle Hackathon 4 】add silu for paddle
openvinotoolkit/openvino pull request #16007
Opened 2023-02-28 17:11 UTC by taixiurong

### Details:
add silu for paddle

###Reference:
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/nn/Silu_cn.html#silu

###Test
<img width="1037" alt="35cff261e003becbda310c850402ce05" src="https://user-images.githubusercontent.com/6076976/221926600-be267bfe-680b-4627-90e3-fd5f188071a7.png">

2023-03-02 08:32 UTC, taixiurong commented
@ceciliapeng2011  please review this silu

2023-03-04 12:07 UTC, mvafin requested changes

2023-03-04 12:07 UTC, mvafin commented on src/frontends/paddle/src/op/silu.cpp
> +    return node.default_single_output_mapping({std::make_shared<default_opset::Divide>(x, denominator)}, {"Out"});
Please use [Swish](https://docs.openvino.ai/latest/openvino_docs_ops_activation_Swish_4.html) operation from openvino opset.

2023-05-26 00:17 UTC, akladiev commented
This PR will be closed in a week because of 2 weeks of no activity.

2023-06-02 00:19 UTC, akladiev commented
This PR was closed because it has been stalled for 2 week with no activity.

2023-06-02 00:19 UTC, closed without merging