[cpu] optimize shape infer of Reshape
openvinotoolkit/openvino pull request #16537
Opened 2023-03-24 12:16 UTC by tiger100256-hu

### Details:
 - *optimize the shape infer of Reshape, squeeze, unsqueeze*

### Tickets:
 - *100509*

2023-03-24 17:01 UTC, maxnick requested changes

2023-03-24 17:01 UTC, maxnick commented on src/plugins/intel_cpu/tests/functional/single_layer_tests/shape_ops.cpp
> +                    RESHAPE_TEST_CASE(i8)
`i8` doesn't make sense here. The second input is a parameter of the operation that is not quantized. Testing `i8` on the second input may only increase the amount of test cases without a practical value.

2023-03-27 10:41 UTC, maxnick approved these changes

2023-03-27 10:43 UTC, maxnick commented
@tiger100256-hu , please make CI green.

2023-03-29 02:02 UTC, tiger100256-hu commented
@maxnick  I make the CI green, I updated below 3 points
1.  fix a pytorch layer test failed issue
      inputShape(1,0) outpattern(-1) is a valid input in the test
2. fix compile issue on windows
     compare between int and uint cause compile issue
3. rebase to master to fix CI issue
    https://github.com/openvinotoolkit/openvino/pull/16573 is merged into master and  fix this issue

2023-03-29 08:36 UTC, yuxu42 commented
@maxnick @dmitry-gorokhov Whether can it be merged? Thanks!

2023-03-29 09:26 UTC, merged