[GPU] update are_data_types_suitable_for_onednn for deconv
openvinotoolkit/openvino pull request #17108
Opened 2023-04-21 08:58 UTC by sungeunk

-deconv and conv used same logic to check data_types
 At document, they are not same.

### Tickets:
 - 108266

2023-04-24 11:56 UTC, hyunback approved these changes

2023-04-25 07:59 UTC, isanghao requested changes
please do not change conv case

2023-04-26 03:45 UTC, isanghao approved these changes

2023-04-26 03:46 UTC, isanghao commented
Performance is good: --this ../log/pr/2023-04-26--09-11.report --ref ../log/2023-04-25--22-30.report

2023-04-26 04:20 UTC, merged