[GPU] Fuse eltwise into MVN
openvinotoolkit/openvino pull request #17473
Opened 2023-05-11 08:31 UTC by jade-cho

### Tickets:
 - *101692*

2023-05-12 09:30 UTC, isanghao requested changes

2023-05-12 09:30 UTC, isanghao commented on src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_primitive_fusing.cpp
> +            return for_quantize ? data_type_traits::is_i8_u8(in_layout.data_type) : true;
what about: `data_type_traits::is_i8_u8(in_layout.data_type) || for_eltwise_fusion`

2023-05-16 01:33 UTC, hyunback approved these changes

2023-05-16 11:47 UTC, jade-cho commented on src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_primitive_fusing.cpp
> +            return for_quantize ? data_type_traits::is_i8_u8(in_layout.data_type) : true;
fixed

2023-05-16 11:47 UTC, jade-cho commented on src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_primitive_fusing.cpp
Included

2023-05-16 11:48 UTC, jade-cho commented on src/plugins/intel_gpu/src/graph/graph_optimizer/prepare_primitive_fusing.cpp
>          };
Tested.

2023-05-17 05:25 UTC, isanghao commented
no perf regression: --this ~/log/pr/2023-05-16--21-20.report --ref ~/log/2023-05-16--17-00.report

2023-05-17 05:27 UTC, isanghao approved these changes

2023-05-17 05:27 UTC, isanghao approved these changes

2023-05-17 05:27 UTC, merged