Update md files. Add cpp in docs/examples
openvinotoolkit/openvino pull request #1769
Opened 2020-08-13 15:08 UTC by pmishanina

2020-08-15 23:09 UTC, alalek commented on docs/examples/Bfloat16Inference0.cpp
> +auto cpuOptimizationCapabilities = core.GetMetric("CPU", METRIC_KEY(OPTIMIZATION_CAPABILITIES)).as<std::vector<std::string>>();
You may want to run `dos2unix` tool over these files to normalize line endings (I assume that `.gitattributes` is valid)

2020-08-27 12:04 UTC, ntyukaev approved these changes

2020-08-28 12:56 UTC, evgenytalanin-intel requested changes
Need to fix some snippets according to internal CI status

2020-09-17 10:12 UTC, evgenytalanin-intel approved these changes

2020-09-22 11:59 UTC, andrew-zaytsev approved these changes

2020-09-22 15:01 UTC, merged