Align sync mode fps measurement in py benchmark_app with cpp benchmark_app
openvinotoolkit/openvino pull request #17773
Opened 2023-05-29 07:50 UTC by ivikhrev

### Details: 
 -  In PR https://github.com/openvinotoolkit/openvino/pull/13743 fps measurement for sync mode in cpp benchmark_app was removed and now it has only one way to measure fps. Need to align it in py version of benchmark_app.

2023-05-29 07:50 UTC, ivikhrev commented
CC @Wovchena

2023-05-29 11:05 UTC, Wovchena requested changes
`py ~/r/openvino/tools/benchmark_tool/benchmark_app.py -m ~/.cache/omz/intel/age-gender-recognition-retail-0013/FP16/age-gender-recognition-retail-0013.xml -d CPU -niter 1 -api sync` fails with
```
[ ERROR ] local variable 'fps' referenced before assignment
Traceback (most recent call last):
  File "/home/wov/r/openvino/tools/benchmark_tool/openvino/tools/benchmark/main.py", line 570, in main
    fps, median_latency_ms, avg_latency_ms, min_latency_ms, max_latency_ms, total_duration_sec, iteration = benchmark.main_loop(requests, data_queue, batch_size, args.latency_percentile, pcseq)
  File "/home/wov/r/openvino/tools/benchmark_tool/openvino/tools/benchmark/benchmark.py", line 185, in main_loop
    return fps, median_latency_ms, avg_latency_ms, min_latency_ms, max_latency_ms, total_duration_sec, iteration
UnboundLocalError: local variable 'fps' referenced before assignment
```
Fix it please

2023-05-29 12:07 UTC, Wovchena approved these changes

2023-05-29 12:15 UTC, nkogteva approved these changes

2023-05-31 07:24 UTC, Wovchena commented
build_jenkins

2023-05-31 09:04 UTC, merged