Add Mish with SoftPlus transformation
openvinotoolkit/openvino pull request #1815
Opened 2020-08-17 13:33 UTC by iimironov

2020-08-18 09:28 UTC, GlebKazantaev commented on inference-engine/src/transformations/src/transformations/softplus_to_mish_fusion.cpp
> +    ngraph::graph_rewrite_callback matcher_pass_callback = [=](ngraph::pattern::Matcher& m) {
```suggestion
    ngraph::matcher_pass_callback callback = [=](ngraph::pattern::Matcher& m) {
```

2020-08-18 09:33 UTC, GlebKazantaev commented on inference-engine/src/transformations/src/transformations/softplus_to_mish_fusion.cpp
> +ngraph::pass::SoftPlusToMishFusion::SoftPlusToMishFusion() {
Let's create GraphRewrite that will register all types of Mish fusions.

2020-08-18 09:33 UTC, GlebKazantaev commented on inference-engine/src/transformations/include/transformations/softplus_to_mish_fusion.hpp
> + * @brief MishFusion transformation replaces group of
```suggestion
 * @brief SoftPlusToMishFusion transformation replaces group of
```

2020-09-01 09:31 UTC, GlebKazantaev commented on inference-engine/src/transformations/src/transformations/softplus_to_mish_fusion.cpp
> +ngraph::pass::SoftPlusToMishFusion::SoftPlusToMishFusion() {
We can do it later.

2020-09-01 09:31 UTC, GlebKazantaev commented
@iimironov why this transformation is not registered in CommonOptimizations?

2020-09-01 09:44 UTC, iimironov commented
> @iimironov why this transformation is not registered in CommonOptimizations?
Fixed

2020-09-03 08:58 UTC, GlebKazantaev requested changes

2020-09-03 08:58 UTC, GlebKazantaev commented on inference-engine/src/transformations/src/transformations/softplus_to_mish_fusion.cpp
> +    auto softplus = std::make_shared<ngraph::opset4::SoftPlus>(input);
Softplus and Tanh could have more than one consumer and this replacement can break something. So I suggest to use wrap_type and use predicate that checks consumers count

2020-09-03 10:49 UTC, GlebKazantaev approved these changes

2020-09-04 08:07 UTC, lazarevevgeny approved these changes

2020-09-04 08:07 UTC, merged