[GNA] Set GNA 3.5 as default target and add 3.5 to properties
openvinotoolkit/openvino pull request #18182
Opened 2023-06-22 07:00 UTC by marcinkusm

### Details:
 - set 3.5 as default version of GNA target
 - added 3.5 version of GNA to properties

### Tickets:
 - *106266*
 - *108844*

2023-06-22 08:07 UTC, sirzabek requested changes

2023-06-22 08:07 UTC, sirzabek commented on src/inference/include/ie/gna/gna_config.hpp
> + * For the OV GNA Plugin 2023.2, the latest supported GNA HW generation corresponds to GNA_TARGET_3_5.
```suggestion
 * For the OV GNA Plugin 2023.1, the latest supported GNA HW generation corresponds to GNA_TARGET_3_5.
```

2023-06-23 05:09 UTC, sirzabek approved these changes

2023-06-26 06:52 UTC, rjeziers approved these changes

2023-08-05 00:18 UTC, closed without merging