[CPU] I64 native support.
openvinotoolkit/openvino pull request #18236
Opened 2023-06-26 11:53 UTC by nshchego

### Details:
 - *INT64 support in CPU plugin*

### Tickets:
 - *100339*

2023-06-27 20:56 UTC, ilya-lavrenov requested changes

2023-06-27 20:56 UTC, ilya-lavrenov commented on src/inference/dev_api/cpp_interfaces/interface/ie_internal_plugin_config.hpp
> +DECLARE_CONFIG_KEY(CPU_NATIVE_I64);
should be discussed before merging

2023-07-03 09:24 UTC, maxnick commented
@antonvor , could you please review?

2023-07-13 06:20 UTC, a-sidorova commented on src/plugins/intel_cpu/src/emitters/x64/jit_eltwise_emitters.cpp
> -        uni_vadd(vmm_dst, vmm_dst, vmm_src1);
Unfortunately, `sse` uses two-operand SIMD instructions so you should move registers to have this semantic before.
oneDNN usually provides common interface for different ISA with prefix `uni_`. Thus, the transformation from three-operand to two-operand SIMD for `sse` is [hidden](https://github.com/openvinotoolkit/oneDNN/blob/33bb2b261d3829162395aaa9bbe8c1c5b139e855/src/cpu/x64/jit_generator.hpp#L730) in this unified functions 🙂

2023-07-13 07:27 UTC, v-Golubev commented on src/plugins/intel_cpu/src/emitters/x64/jit_eltwise_emitters.cpp
> -        uni_vadd(vmm_dst, vmm_dst, vmm_src1);
Thanks for the explanation!

2023-07-14 09:57 UTC, v-Golubev reviewed
2nd part of review comments. Emitters part left unreviewed

2023-07-14 09:57 UTC, v-Golubev commented on src/plugins/intel_cpu/tests/functional/shared_tests_instances/skip_tests_config.cpp
> +        R"(.*smoke.*Split.*(4D|5D).*netPRC=i8.*)",
Are Split instances skipped due to some issue? Do we have a ticket for that?

2023-07-14 09:57 UTC, v-Golubev commented on src/plugins/intel_cpu/tests/functional/single_layer_tests/classes/reduce.cpp
Just an idea: maybe we can add new helper to [CommonTestUtils](https://github.com/openvinotoolkit/openvino/blob/master/src/tests/test_utils/common_test_utils/include/common_test_utils/common_utils.hpp) and resuse it anywhere?

2023-07-14 09:57 UTC, v-Golubev commented on src/plugins/intel_cpu/tests/functional/single_layer_tests/classes/reduce.cpp
> +            //     }
Should we uncomment this?

2023-07-14 09:57 UTC, v-Golubev commented on src/plugins/intel_cpu/tests/functional/single_layer_tests/concat.cpp
> +        }
This logic occurs several times. Maybe we can create some helper that we can reuse in such places?

2023-07-14 09:57 UTC, v-Golubev commented on src/plugins/intel_cpu/tests/functional/single_layer_tests/concat.cpp
> +const ov::AnyMap emptyConfig = {};
We have `CPUTestUtils::cpuEmptyPluginConfig`. Can we use it instead of creation empty config in each test file?

2023-07-14 09:57 UTC, v-Golubev commented on src/plugins/intel_cpu/tests/functional/single_layer_tests/conversion.cpp
> +const ov::AnyMap i64Config = {{PluginConfigInternalParams::KEY_CPU_NATIVE_I64, PluginConfigParams::YES}};
Can we add i64 native config (and probably not native, with KEY_CPU_NATIVE_I64=NO) to CPUTestUtils?

2023-07-14 09:57 UTC, v-Golubev commented on src/plugins/intel_cpu/tests/functional/single_layer_tests/non_max_suppression.cpp
> +            }
Can we just use `maxBoxPrec` as a parameter?
```suggestion
            params.push_back(std::make_shared<ov::opset1::Parameter>(maxBoxPrec, inputDynamicShapes.back()));
```

2023-07-14 09:57 UTC, v-Golubev commented on src/plugins/intel_cpu/tests/functional/single_layer_tests/non_max_suppression.cpp
> +            }
`maxOutBoxesPerClass` has `int32_t` type. Do we really need to cast it to `int64_t`?

2023-07-14 09:57 UTC, v-Golubev commented on src/plugins/template/backend/ops/reduce.cpp
> +std::cout << "evaluate ReduceL1" << std::endl;
Please remove `std::cout` in this file

2023-07-14 13:48 UTC, v-Golubev reviewed
Also, I would like to clarify one point about validation. Should we run accuracy validation (at least on the subsets on the local machine using validation scripts) to check that I64 related changes don't introduce any regressions?

2023-07-14 13:48 UTC, v-Golubev commented on src/plugins/intel_cpu/src/emitters/x64/jit_eltwise_emitters.cpp
> +                    Vmm vmm_aux0 = Vmm(aux_vec_idxs[0]);
We use aux register here. Does it mean that we need to return `1` from `aux_vecs_count()` if `exec_prc_ == I32`?

2023-07-14 13:48 UTC, v-Golubev commented on src/plugins/intel_cpu/src/emitters/x64/jit_eltwise_emitters.cpp
> +            Vmm vmm_aux1 = Vmm(aux_vec_idxs[1]);
In case of I64 precision and `isa == x64::avx512_core` we need 2 aux registers. Should we account for this in `aux_vecs_count`?

2023-07-14 13:48 UTC, v-Golubev commented on src/plugins/intel_cpu/src/nodes/kernels/x64/reduce.cpp
> +                    // TODO Convert pd tp qq (v_src, v_src);
Should we solve it within this PR?

2023-07-14 13:48 UTC, v-Golubev commented on src/plugins/intel_cpu/src/nodes/kernels/x64/reduce.cpp
> +//                 }
Why is this code commented? Should we remove or uncomment it?

2023-07-14 13:48 UTC, v-Golubev commented on src/plugins/intel_cpu/src/nodes/kernels/x64/reduce.cpp
> +                    // vblendmps(vmm_src | k_mask, v_zero, v_ones);
Commented code

2023-07-14 13:48 UTC, v-Golubev commented on src/plugins/intel_cpu/src/nodes/kernels/x64/reduce.cpp
> +    // reg_post_ops_data = getReg64();
Commented code

2023-07-14 13:48 UTC, v-Golubev commented on src/plugins/intel_cpu/src/nodes/kernels/x64/reduce.cpp
> +    if (isa == x64::avx512_core) { // Only if bf16?
What does the comment mean? Should we check smth before the merge?

2023-07-14 13:48 UTC, v-Golubev commented on src/plugins/intel_cpu/src/nodes/kernels/x64/reduce.cpp
> +                // TODO
Please take a look at the TODO sections

2023-07-17 06:23 UTC, nshchego commented on src/plugins/intel_cpu/src/nodes/split.cpp
> +        axis = axisOp->cast_vector<int64_t>()[0];
The first one is cheaper than the fn 'cast_vector'.

2023-07-17 06:26 UTC, nshchego commented on src/plugins/intel_cpu/src/nodes/subgraph.cpp
> +        x64::avx512_core : x64::avx2;
Done

2023-07-17 07:09 UTC, nshchego commented on src/plugins/intel_cpu/src/nodes/cum_sum.cpp
> +        const auto cumsum = std::dynamic_pointer_cast<const op::v0::CumSum>(op);
Modified

2023-07-18 12:38 UTC, nshchego commented on src/common/transformations/src/transformations/convert_precision.cpp
> +    if (val >= static_cast<uint64_t>(std::numeric_limits<int64_t>::max())) {
Fixed in PR#18594

2023-07-18 12:39 UTC, nshchego commented on src/plugins/intel_cpu/src/nodes/transpose.cpp
> +        }
Fixed in PR #18613

2023-08-09 00:19 UTC, closed without merging