Add reshaping of dynamic network in python tests
openvinotoolkit/openvino pull request #1850
Opened 2020-08-19 08:37 UTC by tsocha

2020-08-19 08:48 UTC, mbencer approved these changes

2020-08-19 14:16 UTC, postrational requested changes
Overall looks good.

2020-08-19 14:16 UTC, postrational commented on ngraph/python/src/ngraph/utils/types.py
> +    """Wrap data into a numpy ndarray."""
Seems like this is not the right docstring.

2020-08-19 14:16 UTC, postrational commented on inference-engine/src/inference_engine/cnn_network_ngraph_impl.cpp
> +            THROW_IE_EXCEPTION << outName << " has zero dimension that is not allowed";
```suggestion
            THROW_IE_EXCEPTION << outName << " has zero dimension which is not allowed";
```

2020-08-20 08:42 UTC, postrational approved these changes

2020-08-24 11:58 UTC, merged