Improved MaxPool convert by PyTorch FE
openvinotoolkit/openvino pull request #18965
Opened 2023-08-03 10:34 UTC by praasz

### Details:
 - Improved conversion of `MaxPool` operator by `PyTorch` frontend, when sliding windows go off bound.

### Tickets:
 - #18731

2023-08-03 11:00 UTC, mmikolajcz approved these changes

2023-08-04 08:40 UTC, mvafin requested changes

2023-08-04 08:40 UTC, mvafin commented on src/frontends/pytorch/src/op/max_poolnd.cpp
> +                : context.get_input(3).get_node_shared_ptr();
```suggestion
        const auto padding =
            context.input_is_none(3)
                ? context.mark_node(std::make_shared<v0::Constant>(element::i32, Shape{pads.size()}, 0))->output(0)
                : context.get_input(3);
```
It is not good to retrieve node from input. That node can have multiple outputs, but you will use only first output next, that may create incorrect graph.

2023-08-04 08:40 UTC, mvafin commented on src/frontends/pytorch/src/op/max_poolnd.cpp
> +            use_kernel ? context.get_input(1).get_node_shared_ptr() : context.get_input(2).get_node_shared_ptr();
```suggestion
        const auto stride_node = use_kernel ? context.get_input(1) : context.get_input(2);
```

2023-08-04 12:50 UTC, mvafin approved these changes

2023-08-04 15:07 UTC, merged