[DOCS] Change troubleshooting guide
openvinotoolkit/openvino pull request #18968
Opened 2023-08-03 13:24 UTC by tsavina

### Details:
 - *item1*
 - *...*

### Tickets:
 - *ticket-id*

2023-08-04 11:18 UTC, kblaszczak-intel approved these changes

2023-08-04 11:29 UTC, as-suvorov requested changes
We need to update Selector Tool source code and update builds

2023-08-07 11:27 UTC, kblaszczak-intel commented on docs/_static/selector-tool/assets/selector-4429452f.js
> +${pe("versions.titles.hddlSupport")}`,pipVersion:"2022.3.1",githubVersion:"2022.3.1",giteeVersion:"2022.3.1",aptYear:2022,aptVersion:"2022.3.1",yumYear:2022,yumVersion:"2022.3.1"};class gr extends oe
```suggestion
${pe("versions.titles.hddlSupport")}`,pipVersion:"2022.3.1",githubVersion:"2022.3.1",giteeVersion:"2022.3.1",aptYear:2022,aptVersion:"2022.3.1",yumYear:2022,yumVersion:"2022.3.1"};class gr extends oe{constructor(t){super({level:I.VERSION,key:Cn.v_2022_3_1,metadata:Kv,childrenSelector:Ha},t)}}const Wv={title:"2021.4.2",subtitle:pe("versions.titles.previousLTS"),pipVersion:"2021.4.2",githubVersion:"2021.4.2",giteeVersion:"2021.4.2"};class vr extends oe{constructor(t){super({level:I.VERSION,key:Cn.v_2021_4_2,metadata:Wv,childrenSelector:Ha},t)}}const Fo={os:[z.UBUNTU_18,z.UBUNTU_20,z.RED_HAT_8,z.CENT_OS_7],pythonVersions:[N.V_3_6,N.V_3_7,N.V_3_8]},Rr=[...T.DEV_TOOLS,Le.OPEN_CV_PYTHON],Yv=new vr([new mr({linksSet:{installation:"https://docs.openvino.ai/2021.4/openvino_docs_install_guides_installing_openvino_linux.html",getStarted:"https://docs.openvino.ai/2021.4/openvino_docs_get_started_get_started_demos.html",notebooks:"https://github.com/openvinotoolkit/openvino_notebooks",troubleshooting:null},downloadLink:"https://registrationcenter-download.intel.com/akdlm/irc_nas/18319/l_openvino_toolkit_p_2021.4.752.tgz",systemRequirements:Fo,modules:Rr}).default(),new ue({linksSet:{installation:"https://docs.openvino.ai/2021.4/openvino_docs_install_guides_installing_openvino_pip.html",getStarted:"https://docs.openvino.ai/2021.4/get_started.html",notebooks:"https://github.com/openvinotoolkit/openvino_notebooks",troubleshooting:null},systemRequirements:Fo,modules:Rr,frameworks:[]},{hasFrameworks:!0}),new he({systemRequirements:Fo,modules:Rr}),new me({systemRequirements:Fo,modules:Rr}),new $t({linksSet:{installation:"https://docs.openvino.ai/2021.4/openvino_docs_install_guides_installing_openvino_docker_linux.html",getStarted:"https://docs.openvino.ai/2021.4/openvino_docs_get_started_get_started_demos.html",notebooks:"https://github.com/openvinotoolkit/openvino_notebooks",troubleshooting:"https://docs.openvino.ai/2021.4/openvino_docs_install_guides_installing_openvino_docker_linux.html#troubleshooting"},modules:Rr,downloadLink:"https://docs.openvino.ai/2021.4/openvino_docs_install_guides_installing_openvino_docker_linux.html"})]),Is={os:[z.UBUNTU_18,z.UBUNTU_20,z.RED_HAT_8],pythonVersions:[N.V_3_7,N.V_3_8,N.V_3_9,N.V_3_10]},qv=new gr([new ue({linksSet:{installation:"https://docs.openvino.ai/2022.3/openvino_docs_install_guides_install_dev_tools.html",getStarted:"https://docs.openvino.ai/2022.3/get_started.html",notebooks:"https://github.com/openvinotoolkit/openvino_notebooks",troubleshooting:"https://docs.openvino.ai/2022.3/openvino_docs_get_started_guide_troubleshooting_steps.html"},systemRequirements:Is,modules:T.DEV_TOOLS,frameworks:[]},{hasFrameworks:!0}).default(),new he({systemRequirements:Is,modules:T.DEV_TOOLS}),new me({systemRequirements:Is,modules:T.DEV_TOOLS}),new $t({linksSet:{installation:"https://docs.openvino.ai/2022.3/openvino_docs_install_guides_installing_openvino_docker_linux.html",getStarted:"https://docs.openvino.ai/2022.3/openvino_docs_get_started_get_started_demos.html",notebooks:"https://github.com/openvinotoolkit/openvino_notebooks",troubleshooting:"https://docs.openvino.ai/2022.3/openvino_docs_get_started_guide_troubleshooting_steps.html"},modules:T.DEV_TOOLS,downloadLink:"https://docs.openvino.ai/2022.3/openvino_docs_install_guides_installing_openvino_docker_linux.html"})]),bs={os:[z.UBUNTU_18,z.UBUNTU_20,z.UBUNTU_22,z.RED_HAT_8],pythonVersions:[N.V_3_7,N.V_3_8,N.V_3_9,N.V_3_10,N.V_3_11]},Gv=new hr([new ue({linksSet:{installation:"https://docs.openvino.ai/2023.0/openvino_docs_install_guides_install_dev_tools.html",getStarted:"https://docs.openvino.ai/2023.0/get_started.html",notebooks:"https://github.com/openvinotoolkit/openvino_notebooks",troubleshooting:"https://docs.openvino.ai/2023.0/openvino_docs_get_started_guide_troubleshooting_steps.html"},systemRequirements:bs,modules:T.DEV_TOOLS,frameworks:[]},{hasFrameworks:!0}).default(),new he({systemRequirements:bs,modules:T.DEV_TOOLS}),new me({systemRequirements:bs,modules:T.DEV_TOOLS}),new $t({linksSet:{installation:"https://docs.openvino.ai/2023.0/openvino_docs_install_guides_installing_openvino_docker_linux.html",getStarted:"https://docs.openvino.ai/2023.0/get_started.html",notebooks:"https://github.com/openvinotoolkit/openvino_notebooks",troubleshooting:"https://docs.openvino.ai/2023.0/openvino_docs_get_started_guide_troubleshooting_steps.html"},modules:T.DEV_TOOLS,downloadLink:"https://docs.openvino.ai/2023.0/openvino_docs_install_guides_installing_openvino_docker_linux.html"})]),Qv=new oe({level:I.OP_SYSTEM,key:ft.LINUX,metadata:rf},[Gv.default(),qv,Yv]),Uo={os:[Ue.V_10_15_X],pythonVersions:[N.V_3_6,N.V_3_7,N.V_3_8]},jo=[...T.DEV_TOOLS,Le.OPEN_CV_PYTHON],Xv=new vr([new mr({linksSet:{installation:"https://docs.openvino.ai/2021.4/openvino_docs_install_guides_installing_openvino_macos.html",getStarted:"https://docs.openvino.ai/2021.4/openvino_docs_get_started_get_started_demos.html",notebooks:"https://github.com/openvinotoolkit/openvino_notebooks",troubleshooting:null},systemRequirements:Uo,modules:jo,downloadLink:"https://registrationcenter-download.intel.com/akdlm/irc_nas/18317/m_openvino_toolkit_p_2021.4.752.dmg"}).default(),new ue({linksSet:{installation:"https://docs.openvino.ai/2021.4/openvino_docs_install_guides_installing_openvino_pip.html",getStarted:"https://docs.openvino.ai/2021.4/get_started.html",notebooks:"https://github.com/openvinotoolkit/openvino_notebooks",troubleshooting:null},systemRequirements:Uo,modules:jo,frameworks:[]},{hasFrameworks:!0}),new he({systemRequirements:Uo,modules:jo}),new me({systemRequirements:Uo,modules:jo})]),Vs={os:[Ue.V_10_15_X,Ue.V_11,Ue.V_12],pythonVersions:[N.V_3_7,N.V_3_8,N.V_3_9,N.V_3_10],note:of},Jv=new gr([new ue({linksSet:{installation:"https://docs.openvino.ai/2022.3/openvino_docs_install_guides_install_dev_tools.html",getStarted:"https://docs.openvino.ai/2022.3/get_started.html",notebooks:"https://github.com/openvinotoolkit/openvino_notebooks",troubleshooting:"https://docs.openvino.ai/2022.3/openvino_docs_get_started_guide_troubleshooting_steps.html"},systemRequirements:Vs,modules:T.DEV_TOOLS,frameworks:[]},{hasFrameworks:!0}).addFootnote(I.OP_SYSTEM).default(),new he({systemRequirements:Vs,modules:T.DEV_TOOLS}).addFootnote(I.OP_SYSTEM),new me({systemRequirements:Vs,modules:T.DEV_TOOLS}).addFootnote(I.OP_SYSTEM)]),Ds={os:[Ue.V_10_15_X,Ue.V_11,Ue.V_12],pythonVersions:[N.V_3_7,N.V_3_8,N.V_3_9,N.V_3_10,N.V_3_11]},Zv=new hr([new ue({linksSet:{installation:"https://docs.openvino.ai/2023.0/openvino_docs_install_guides_install_dev_tools.html",getStarted:"https://docs.openvino.ai/2023.0/get_started.html",notebooks:"https://github.com/openvinotoolkit/openvino_notebooks",troubleshooting:"https://docs.openvino.ai/2023.0/openvino_docs_get_started_guide_troubleshooting_steps.html"},systemRequirements:Ds,modules:T.DEV_TOOLS,frameworks:[]},{hasFrameworks:!0}).default(),new he({systemRequirements:Ds,modules:T.DEV_TOOLS}),new me({systemRequirements:Ds,modules:T.DEV_TOOLS})]),ey=new oe({level:I.OP_SYSTEM,key:ft.MACOS,metadata:nf},[Zv.default(),Jv,Xv]),Mo={os:[Pt.V_10],pythonVersions:[N.V_3_6,N.V_3_7,N.V_3_8]},Ao=[...T.DEV_TOOLS,Le.OPEN_CV_PYTHON],ty=new vr([new mr({linksSet:{installation:"https://docs.openvino.ai/2021.4/openvino_docs_install_guides_installing_openvino_windows.html",getStarted:"https://docs.openvino.ai/2021.4/openvino_docs_get_started_get_started_demos.html",notebooks:"https://github.com/openvinotoolkit/openvino_notebooks",troubleshooting:null},systemRequirements:Mo,modules:Ao,downloadLink:"https://registrationcenter-download.intel.com/akdlm/irc_nas/18320/w_openvino_toolkit_p_2021.4.752.exe"}).default(),new ue({linksSet:{installation:"https://docs.openvino.ai/2021.4/openvino_docs_install_guides_installing_openvino_pip.html",getStarted:"https://docs.openvino.ai/2021.4/get_started.html",notebooks:"https://github.com/openvinotoolkit/openvino_notebooks",troubleshooting:null},systemRequirements:Mo,modules:Ao,frameworks:[]},{hasF [...]

2023-08-08 09:44 UTC, closed without merging

2023-08-08 09:46 UTC, kblaszczak-intel commented
Changes to the Selector Tool .js dropped, changes to the troubleshooting guide moved to a different PR:
https://github.com/openvinotoolkit/openvino/pull/19044