[ MO ][ RESHAPE ] Fixes in RNNSequenceNormalize transformation
openvinotoolkit/openvino pull request #1909
Opened 2020-08-24 08:56 UTC by yekruglov

Description: Fixes in implementation make this transformation reshape-able

JIRA: 34207

Code:
* [ ]  Comments
* [ ]  Code style (PEP8)
* [ ]  Transformation generates reshape-able IR
* [ ]  Transformation preserves original framework node names

Validation:
* [ ]  Unit tests
* [ ]  Framework operation tests N/A: no new operations were enabled
* [ ]  Transformation tests
* [ ]  e2e model test with an update of ./tests/e2e_oss/utils/reshape_utils.py N/A: no new models were enabled
* [ ]  Model Optimizer IR Reader check

Documentation:
* [ ]  Supported frameworks operations list N/A: no new operations were enabled
* [ ]  Supported **public** models list N/A: no new models were enabled
* [ ]  New operations specification N/A: no new operations were enabled
* [ ]  Guide on how to convert the **public** model N/A: no new models were enabled
* [ ]  User guide update N/A

2020-08-24 09:49 UTC, jane-intel approved these changes

2020-08-24 10:21 UTC, lazarevevgeny requested changes
Can you provide a results of e2e run where the modified transformation was called?
How about transformation test?

2020-08-24 10:21 UTC, lazarevevgeny commented on model-optimizer/extensions/middle/RNNSequenceNormalizeToIE.py
> +            reshape_dim_data = Const(graph, {'name': rnn_layer.name + '/UnsqueezeNumDirections/{}/Dim'.format(i),
`reshape_dim_data` -> `unsqueeze_dim_data`?

2020-08-24 10:21 UTC, lazarevevgeny commented on model-optimizer/extensions/middle/RNNSequenceNormalizeToIE.py
> -            reshape_dim_data = Const(graph, {'name': rnn_layer.name + '/SqueezeNumDirections/{}/Dim'.format(i),
use `rnn_layer.soft_get('name', rnn_layer.id)` instead of `rnn_layer.name`.

2020-08-24 10:42 UTC, jane-intel commented
>> Can you provide a results of e2e run where the modified transformation was called?
@lazarevevgeny, there is MXNET_RNN_Bidirectional_transducer_encoder and it fails here.

@yekruglov, please debug it

2020-08-24 11:50 UTC, lazarevevgeny commented on model-optimizer/extensions/middle/RNNSequenceNormalizeToIE.py
> +                                             'value': [direction_dim[i]]}).create_node_with_data()
It is not clear for me how the latest commit fixes the conversion issue of the MxNet model. Could you commen?

2020-08-27 07:19 UTC, lazarevevgeny commented
@yekruglov , please, fix code style in nGraph. You can download the artefact with the patch and apply it.

2020-08-27 08:18 UTC, jane-intel commented
> @yekruglov , please, fix code style in nGraph. You can download the artefact with the patch and apply it.
or run make style-apply

2020-08-27 10:00 UTC, itikhono approved these changes

2020-08-27 10:12 UTC, itikhono commented
in general, LGTM, `prevalidate_and_infer `functions of Cells ops will be deleted in my next PR

2020-08-27 10:46 UTC, jane-intel approved these changes

2020-08-27 13:43 UTC, lazarevevgeny commented
pre-commit failed once again. Please, retry one more time

2020-08-27 13:44 UTC, lazarevevgeny approved these changes

2020-08-27 14:34 UTC, jane-intel commented
I restarted failed job

2020-08-29 22:19 UTC, merged