Remove makeDynamicParams
openvinotoolkit/openvino pull request #19226
Opened 2023-08-16 13:08 UTC by olpipi

### Details:
 - *item1*
 - *...*

### Tickets:
 - *ticket-id*

2023-08-17 13:36 UTC, vurusovs requested changes

2023-08-17 13:36 UTC, vurusovs commented on src/plugins/intel_cpu/tests/functional/single_layer_tests/ctc_greedy_decoder_seq_len.cpp
> +        for (size_t i = 0; i < inType.size(); i++) {
check `inType.size() == inputDynamicShapes.size()` is required, otherwise it will lead to segfault

2023-08-17 13:36 UTC, vurusovs commented on src/plugins/intel_cpu/tests/functional/single_layer_tests/roialign.cpp
> +        auto int_params = std::make_shared<ov::op::v0::Parameter>(ngraph::element::i32, inputDynamicShapes[2]);
```suggestion
        auto int_param = std::make_shared<ov::op::v0::Parameter>(ngraph::element::i32, inputDynamicShapes[2]);
```

2023-08-23 13:02 UTC, olpipi commented
@vurusovs could you please re-review?

2023-08-23 13:51 UTC, vurusovs approved these changes

2023-08-23 16:57 UTC, merged