Handle unspecified type in wrap_tensor function
openvinotoolkit/openvino pull request #19220
Opened 2023-08-16 11:41 UTC by itikhono

### Details:
 - The original model contains Parameter node with "unspecified" type. ConstantFolding tries to create ViewTensor via wrap_tensor function with "unspecified" type. ViewTensor ctor contains an assert for this case. So "unspecified" type was handled in wrap_tensor function.

### Tickets:
 - *CVS-111263*

2023-08-16 13:24 UTC, rkazants approved these changes

2023-08-16 15:57 UTC, andrei-kochin requested changes
Please wait for release branch

2023-08-17 12:18 UTC, jane-intel approved these changes

2023-08-18 06:25 UTC, andrei-kochin approved these changes

2023-08-18 06:25 UTC, merged