[DOCS] installation guide restructuring 23.1
openvinotoolkit/openvino pull request #19241
Opened 2023-08-17 05:34 UTC by kblaszczak-intel

2023-08-21 14:55 UTC, artanokhov requested changes

2023-08-21 14:55 UTC, artanokhov commented on docs/install_guides/installing-openvino-vcpkg.md
> +# Install OpenVINO™ Runtime via Homebrew {#openvino_docs_install_guides_installing_openvino_vcpkg}
Need to updated with 'Install OpenVINO™ Runtime via VCPKG'

2023-08-21 14:55 UTC, artanokhov commented on docs/install_guides/installing-openvino-overview.md
> +   .. dropdown:: Distribution Comparison
Do we want to mention that this table applicable for 2023.1?

2023-09-04 13:31 UTC, kblaszczak-intel commented on docs/install_guides/installing-openvino-windows-header.md
> +   Use Docker <openvino_docs_install_guides_installing_openvino_docker_linux>
```suggestion
   Use Docker <openvino_docs_install_guides_installing_openvino_docker>
```

2023-09-05 05:01 UTC, sgolebiewski-intel approved these changes

2023-09-06 08:56 UTC, artanokhov commented on docs/install_guides/installing-openvino-apt.md
> +      ===================  =====  =====  =====  =====  ========  =============  ========  ========
For APT we activating only RPMs/DEBs from following OSes:
Ubuntu18, Ubuntu20, Ubuntu22, RHEL8

2023-09-06 08:59 UTC, artanokhov commented on docs/install_guides/installing-openvino-conda.md
> +      ===================  =====  =====  =====  =====  ========  =============  ========  ========
NPU not presented for Conda-Forge at all, as well as GNA

2023-09-06 09:02 UTC, artanokhov commented on docs/install_guides/installing-openvino-pip.md
> +      The PyPi distribution for macOS currently supports the arm64 architecture only.
We activate x86_64 as well - as for example
https://files.pythonhosted.org/packages/4d/70/ac75b270b7e33a28aab12b9dec2a47e63202457285bc35c1b3454cb43229/openvino-2023.0.2-11065-cp311-cp311-macosx_10_12_x86_64.whl

2023-09-06 09:03 UTC, artanokhov commented on docs/install_guides/installing-openvino-pip.md
> +      ===================  =====  =====  =====  =====  ========  =============  ========  ========
NPU and GNA are not presented for PyPI distr. channel.

2023-09-06 15:46 UTC, merged