[GNA] Fix memory leak in insert_copy_layer.cpp
openvinotoolkit/openvino pull request #19266
Opened 2023-08-18 12:10 UTC by marcinkusm

### Details:
 - Added cleanup transformation for inert copy layer transformations

### Tickets:
 - *116912*

2023-08-21 06:13 UTC, sirzabek requested changes
Looks more like workaround than a fix.

2023-08-21 06:13 UTC, sirzabek commented on src/plugins/intel_gna/src/transformations/insert_copy_layer.cpp
> +static const std::string kResultProprty("result_vector");
```suggestion
static const std::string kResultProperty("result_vector");
```

2023-08-21 10:50 UTC, sirzabek approved these changes

2023-08-23 11:07 UTC, mblaszk approved these changes

2023-08-23 12:11 UTC, merged

2023-08-23 12:13 UTC, mryzhov commented on src/plugins/intel_gna/src/gna_transformations_pipeline.cpp
> +    manager.register_pass<ov::intel_gna::pass::HandleNonFunctionalSubgraphsCleanup>();
it is better to hide cleanup transformations from the plugin transformations pipeline. Why it can not be added to transformation pipeline?