Override Slice::constant_folding to allow to extract static dimensions from ShapeOf subgraphs
openvinotoolkit/openvino pull request #19492
Opened 2023-08-30 07:48 UTC by mateusztabaka

Ticket: CVS-118902

2023-09-05 10:08 UTC, itikhono approved these changes

2023-09-05 14:36 UTC, jane-intel commented
We already have this functionality. Why do we invent the wheel?

2023-09-05 14:36 UTC, jane-intel commented
We already have this functionality. Why do we reinvent the wheel?

2023-09-05 14:49 UTC, itikhono commented
> 

Wheel was invented for strided slice already
![image](https://github.com/openvinotoolkit/openvino/assets/21181928/4a1563ed-e8a7-49ef-b4d2-3b8bfdd2f923)
We just re-used that

2023-09-05 15:19 UTC, jane-intel requested changes
I suggest taking different approach.
This sub-graph comes to some operation which should trigger partial value propagation.
Since it didn't fold -- it means some part of the graph couldn't propagate through. So I propose to search for the faulty op(s) instead of doing this temporary fix.

2023-09-06 07:16 UTC, praasz commented
> > 
> 
> The wheel was invented for strided slice already ![image](https://user-images.githubusercontent.com/21181928/265737749-4a1563ed-e8a7-49ef-b4d2-3b8bfdd2f923.png) We just re-used that @praasz do you remember any details?

Just short description for strided slice. The custom const fold check inputs 1, 2 (start, end) if used values have const value (no interval) and then these inputs are replaced by constants. 
Then strided slice sub-graph is check if its output can replaced by constant (abort if any node in this sub-graph has const folding disabled).

I think test case ` slice_shape_of_with_dynamic_shape_on_static_dimension`  shows the issue. 
There are input data for slice but it has got some interval values, so without proposed modification the slice cannot be folded even if selected values for slice are not interval values `2, 3`. If in this test `param` will be replaced to have only only static shape then slice will fold.

I think similar case can be reproduced for strided slice as well, as the input 0 is not checked in this way.

@jane-intel 
Maybe the slice and strided slice should have same feature to check data input. 
If sliced values has no interval values (no const fold disabled) then it should be possible to fold this operator.

2023-09-06 07:38 UTC, praasz commented
> > > 
> > 
> > 
> > The wheel was invented for strided slice already ![image](https://user-images.githubusercontent.com/21181928/265737749-4a1563ed-e8a7-49ef-b4d2-3b8bfdd2f923.png) We just re-used that @praasz do you remember any details?
> 
> Just short description for strided slice. The custom const fold check inputs 1, 2 (start, end) if used values have const value (no interval) and then these inputs are replaced by constants. Then strided slice sub-graph is check if its output can replaced by constant (abort if any node in this sub-graph has const folding disabled).
> 
> I think test case ` slice_shape_of_with_dynamic_shape_on_static_dimension` shows the issue. There are input data for slice but it has got some interval values, so without proposed modification the slice cannot be folded even if selected values for slice are not interval values `2, 3`. If in this test `param` will be replaced to have only only static shape then slice will fold.
> 
> I think similar case can be reproduced for strided slice as well, as the input 0 is not checked in this way.
> 
> @jane-intel Maybe the slice and strided slice should have same feature to check data input. If sliced values has no interval values (no const fold disabled) then it should be possible to fold this operator.

I've just checked the strided slice with similar case as `slice_shape_of_with_dynamic_shape_on_static_dimension`, it looks like it works correctly and no modification is required.

2023-09-07 07:43 UTC, mateusztabaka commented
> I suggest taking different approach. This sub-graph comes to some operation which should trigger partial value propagation. Since it didn't fold -- it means some part of the graph couldn't propagate through. So I propose to search for the faulty op(s) instead of doing this temporary fix.

So the scenario (in pseudocode) looks like follows:

```
param = Parameter(shape={-1, 2, 3, -1})
shapeof = ShapeOf(param)
slice = Slice(shapeof, start=[1], stop=[3], stride=[1], axis=[0])
model = Model(slice, [param])
manager.register_pass<ConstantFolding>()
manager.run_passes(model)
```

The Slice was not constantfolded because ShapeOf was not constantfolded and this is due its input shape being dynamic.
But the Slice can be constantfolded because it slices the part of the shape that is static.
Also if you use StridedSlice instead of Slice, this subgraph can be constfolded since [StridedSlice has custom constant_fold function](https://github.com/openvinotoolkit/openvino/blob/master/src/core/src/op/strided_slice.cpp#L302).

2023-09-08 10:06 UTC, mateusztabaka commented
I think I should expand on the actual scenario. In the model I'm working on, some ShapeOf subgraphs are not used for shape inference - they're the inputs to some compute layers in the model. So lower and upper bound is never set for such ShapeOfs. Therefore those subgraphs cannot be folded by ConstantFolding.

2023-09-08 10:20 UTC, praasz approved these changes

2023-09-08 11:10 UTC, jane-intel commented
Since Slice has axis attribute -- I agree to introduce constant_fold for it. However, I would rather have better evaluate_lower / upper for it, so that output of this Slice would have upper==lower and ConstantFolding pass would fold it without Slice::constant_fold change

2023-09-11 21:15 UTC, closed without merging