Move Inference Functional Caching Tests to new API
openvinotoolkit/openvino pull request #19513
Opened 2023-08-31 07:00 UTC by ilyachur

### Details:
 - Depends on: https://github.com/openvinotoolkit/openvino/pull/19452

### Tickets:
 - *ticket-id*

2023-08-31 08:11 UTC, p-durandin approved these changes

2023-08-31 19:55 UTC, ilya-lavrenov requested changes

2023-08-31 19:55 UTC, ilya-lavrenov commented on src/inference/tests/functional/caching_test.cpp
> +// // In case of sporadic failures - increase 'TEST_DURATION_MS' 100x times for better reproducibility
let's enable commented tests

2023-09-01 06:10 UTC, ilyachur commented on src/inference/tests/functional/caching_test.cpp
> +// // In case of sporadic failures - increase 'TEST_DURATION_MS' 100x times for better reproducibility
Of course

2023-09-04 08:44 UTC, ilya-lavrenov approved these changes

2023-09-04 20:42 UTC, merged