Add a error message when creating an empty Constant
openvinotoolkit/openvino pull request #19674
Opened 2023-09-07 12:15 UTC by siddhant-0707

### Details:
 - Added an error message when creating an empty constant to the constant wrapper

### Tickets:
 - #19617

2023-09-07 12:19 UTC, p-wysocki approved these changes
Thank you for your contribution! LGTM. @siddhant-0707 have you tested it locally to see if the ValueError is raised?

There are currently some issues with CI, please do not worry that some jobs are failing.

2023-09-07 12:37 UTC, siddhant-0707 commented
@p-wysocki Yes, ValueError raised correctly. I tested it on Python 3.10.12

2023-09-07 19:50 UTC, akuporos commented
Can you please also extend the test [here](https://github.com/openvinotoolkit/openvino/blob/master/src/bindings/python/tests/test_graph/test_ops.py#L122), that error raised?

2023-09-07 19:51 UTC, akuporos reviewed
Can you please also extend the test [here](https://github.com/openvinotoolkit/openvino/blob/master/src/bindings/python/tests/test_graph/test_ops.py#L122), that error raised?

2023-09-08 14:18 UTC, akuporos commented on src/bindings/python/tests/test_graph/test_ops.py
> +            ov.constant(None)
```suggestion
    ov.constant(np.arange(9).reshape(3, 3), np.float32)
])
def test_constant(node):
    with pytest.raises(ValueError) as e:
        ov.constant(None)
    assert 'Cannot create an empty Constant. Please provide valid data.' in str(e.value)
```

2023-09-08 14:33 UTC, akuporos commented on src/bindings/python/tests/test_graph/test_ops.py
> +    None
I suggest to rewrite a little bit this test using [this feature](https://docs.pytest.org/en/7.1.x/example/parametrize.html#parametrizing-conditional-raising).

```suggestion
    ov.constant(None)
```

2023-09-08 22:25 UTC, akuporos commented on src/bindings/python/tests/test_graph/test_ops.py
>      ov.constant(np.arange(9).reshape(3, 3), Type.f32),
```suggestion
@pytest.mark.parametrize(("const", "args", "expectation"), [
    (Constant, (Type.f32, Shape([3, 3]), list(range(9))), does_not_raise()),
    (ov.constant, (np.arange(9).reshape(3, 3), Type.f32), does_not_raise()),
```

2023-09-08 22:25 UTC, akuporos commented on src/bindings/python/tests/test_graph/test_ops.py
>      assert list(node.get_output_shape(0)) == [3, 3]
```suggestion
    (ov.constant, (np.arange(9).reshape(3, 3), np.float32), does_not_raise()),
    (ov.constant, [None], pytest.raises(ValueError)),
])
def test_constant(const, args, expectation):
    with expectation:
        node = const(*args)
        assert node.get_type_name() == "Constant"
        assert node.get_output_size() == 1
        assert list(node.get_output_shape(0)) == [3, 3]
```

2023-09-08 22:29 UTC, akuporos requested changes

2023-09-08 22:29 UTC, akuporos commented on src/bindings/python/tests/test_graph/test_ops.py
>      assert list(node.get_output_shape(0)) == [3, 3]
please, also add indentation to the line with `assert node.get_output_element_type(0) == Type.f32`, this assert need to be under `with expectation`.

and please, add `from contextlib import nullcontext as does_not_raise` in the begging of this file

2023-09-12 07:34 UTC, akuporos approved these changes

2023-09-12 11:55 UTC, jiwaszki approved these changes

2023-09-13 14:26 UTC, siddhant-0707 commented
Hey, was wondering if I need to do something else also to merge this PR?

2023-09-13 14:43 UTC, akuporos commented
> Hey, was wondering if I need to do something else also to merge this PR?

Actually no, just wait for the last job will pass

2023-09-13 19:22 UTC, akuporos commented
build_jenkins

2023-09-13 22:11 UTC, merged