[VPU][OpenCL] Update custom kernels
openvinotoolkit/openvino pull request #1982
Opened 2020-08-28 11:17 UTC by maxim-kurin

Updated kernels for custom layer.
Added elf metadata parser.
Testing with runtime that supports hoisted kernels.

2020-08-28 12:06 UTC, geexie requested changes

2020-08-28 12:06 UTC, geexie commented on inference-engine/src/vpu/custom_kernels/correlate.cl
>  #if defined(USE_MANUAL_DMA)
could you please use the only one macro instead of two `USE_MANUAL_DMA` and `USE_DMA`

2020-09-04 04:27 UTC, maxim-kurin commented
tests
https://gitlab-icv.inn.intel.com/inference-engine/product-configs/merge_requests/868/

2020-09-04 12:14 UTC, geexie approved these changes

2020-09-08 14:09 UTC, elatkin commented
Will replace this PR with another one soon

The other PR will:
- Resolve conflict about clTools version
- Update VPU firmware to no. 1370 (just built from MDK R13 release branch)
- Re-enable the tests for ExpProposalsGenerator

2020-09-08 14:09 UTC, closed without merging