[DOC] Reshape feature
openvinotoolkit/openvino pull request #2023
Opened 2020-08-31 20:26 UTC by jane-intel

2020-09-01 09:02 UTC, lazarevevgeny requested changes

2020-09-01 11:24 UTC, jane-intel commented on docs/IE_DG/ShapeInference.md
> +It should have static (fixed) input shapes to be successfully loaded to the Inference Engine plugins.
I got rid of words `static` and `dynamic` in favor to `(not) fully defined` as we use it starting from Model Optimizer error messages. Regarding the reference to a document -- I failed to find one in our documentation. Probably it is placed in some nGraph specific place. But I believe our users are already familiar with this terms. What do you think?

2020-09-01 19:02 UTC, lazarevevgeny approved these changes

2020-09-02 18:24 UTC, andrew-zaytsev submitted a review, later dismissed

2020-09-03 14:42 UTC, aalborov requested changes

2020-09-03 14:42 UTC, aalborov commented on docs/IE_DG/ShapeInference.md
> +   > - It is required to reshape the network before loading to the plugin for ONNX models with not fully defined input shape that were imported with the ONNX importer.
Sounds a bit confusing. I tried rephrasing, is this what is meant?

```
If an ONNX model does not have a fully defined input shape and the model was imported with the ONNX importer, reshape the model before loading it to the plugin.
```

2020-09-03 14:42 UTC, aalborov commented on docs/IE_DG/ShapeInference.md
> +   > - Older versions of IRs are not guaranteed to reshape successfully. Please re-generate them with the Model Optimizer of the latest version of OpenVINO™.<br>
`regenerate`

2020-09-03 14:42 UTC, aalborov commented on docs/IE_DG/ShapeInference.md
> +   The meaning of a model batch may vary depending on choices you made during the model designing.
--> ```The meaning of a model batch may vary depending on the model design. ```

2020-09-03 14:42 UTC, aalborov commented on docs/IE_DG/ShapeInference.md
> +   Batch-setting algorithm does not involve shape inference mechanism.
The algorithm, the mechanism

2020-09-03 14:42 UTC, aalborov commented on docs/IE_DG/ShapeInference.md
> +   If there is a need to set new batch size for the model, please use `CNNNetwork::reshape` method instead.
--> ```If you need to set a new batch size for the model, use the `CNNNetwork::reshape` method instead.```

2020-09-03 14:42 UTC, aalborov commented on docs/IE_DG/ShapeInference.md
> +Please do not use runtime reshaping methods together, especially do not call `CNNNetwork::reshape` method after `InferenceEngine::CNNNetwork::setBatchSize` usage.
--> 
```Do not use runtime reshaping methods simultaneously, especially do not call the `CNNNetwork::reshape` method after  you use `InferenceEngine::CNNNetwork::setBatchSize`.```

2020-09-03 14:42 UTC, aalborov commented on docs/IE_DG/ShapeInference.md
> +`InferenceEngine::CNNNetwork::setBatchSize` method causes irreversible conversion of internal model representation to the legacy model representation.
--> 
```
The `InferenceEngine::CNNNetwork::setBatchSize` method causes irreversible conversion of the internal model representation into the legacy model representation.
```

2020-09-03 14:42 UTC, aalborov commented on docs/IE_DG/ShapeInference.md
> +It does not use `nGraph` for shape inference which lead to reduced reshape opportunities and may affect performance of the model.
The method does not use `nGraph` for shape inference which leads to reduced reshape opportunities and may affect the performance of the model.

2020-09-06 15:35 UTC, jane-intel commented on docs/MO_DG/prepare_model/convert_model/tf_specific/Convert_Object_Detection_API_Models.md
>  > * Starting with the 2018 R4 release, the Model Optimizer supports the `--input_shape` command line parameter for the TensorFlow\* Object Detection API topologies. Refer to the [Custom Input Shape](
@lazarevevgeny, do we?

2020-09-07 07:29 UTC, lazarevevgeny commented on docs/MO_DG/prepare_model/convert_model/tf_specific/Convert_Object_Detection_API_Models.md
>  > * Starting with the 2018 R4 release, the Model Optimizer supports the `--input_shape` command line parameter for the TensorFlow\* Object Detection API topologies. Refer to the [Custom Input Shape](
Let's remove them.

2020-09-09 06:34 UTC, aalborov approved these changes
LGTM

2020-09-11 18:41 UTC, merged