[PT FE] Add aten::__xor__
openvinotoolkit/openvino pull request #20662
Opened 2023-10-23 19:10 UTC by karanjakhar

### Details:
 - *Add aten::\_\_xor__*

### Tickets:
 - *Closes #20584*

2023-10-24 09:37 UTC, mvafin requested changes
We actually have bitwise_xor op implemented in this draft PR #20339, but it is not ready yet, because bitwise ops are not yet implemented on CPU. So please add more tests and we will accept your change

2023-10-24 09:37 UTC, mvafin commented on tests/layer_tests/pytorch_tests/test_xor.py
Could you add more tests for more types where this operator is used as bitwise operator? Those tests will fail now, so you will have to mark them as `xfail`, but we will have bitwise operations soon in openvino, so we could just enable tests when that happens.

2023-10-24 10:37 UTC, karanjakhar commented on tests/layer_tests/pytorch_tests/test_xor.py
ok @mvafin

2023-10-24 11:28 UTC, mvafin requested changes

2023-10-24 11:28 UTC, mvafin commented on src/frontends/pytorch/src/op_table.cpp
> +OP_CONVERTER(translate_xor);
```suggestion
OP_CONVERTER(translate_bitwise_xor);
```

2023-10-24 11:28 UTC, mvafin commented on src/frontends/pytorch/src/op_table.cpp
> +        {"aten::__xor__", op::translate_xor},
```suggestion
        {"aten::__xor__", op::translate_bitwise_xor},
```

2023-10-24 19:57 UTC, mvafin commented
Please fix code style

2023-10-25 07:24 UTC, rkazants commented
build_jenkins

2023-10-25 07:29 UTC, a-sidorova commented on src/plugins/intel_cpu/thirdparty/mlas
Seems like it's accident change after rebasing since it's not relevant to the PR.
@karanjakhar could you please remove this change from the PR?

2023-10-25 09:42 UTC, karanjakhar commented on src/plugins/intel_cpu/thirdparty/mlas
done

2023-10-25 09:43 UTC, rkazants commented
build_jenkins

2023-10-25 09:44 UTC, a-sidorova approved these changes

2023-10-25 09:47 UTC, mvafin approved these changes

2023-10-26 08:31 UTC, karanjakhar commented
Hi @mvafin @a-sidorova ,    
I am not able to see why some checks failed. When I click on ci/jenkins "Details" it says the site can't be reached. Please guide. 
![Screenshot from 2023-10-26 14-00-20](https://github.com/openvinotoolkit/openvino/assets/29913676/ae6b6a35-f924-4c2d-9a1c-d5ee1f525fa2)

2023-10-26 14:28 UTC, merged

2023-10-29 16:35 UTC, karanjakhar commented
@ilya-lavrenov there is an error in the dtype of the test case. I just observed. it's np.int (which doesn't exist), it should be np.int64. Should I create a new PR or make changes to this one?

2023-10-29 17:32 UTC, ilya-lavrenov commented
Hi @karanjakhar 
Please, create a new one, because this PR is merged and cannot be changed