[GHA] Enable full conformance for template
openvinotoolkit/openvino pull request #20712
Opened 2023-10-26 12:58 UTC by iefode

### Details:
 - *item1*
 - *...*

### Tickets:
 - *ticket-id*

2023-10-26 13:11 UTC, mryzhov commented on .github/workflows/windows.yml
> +          call "${{ env.INSTALL_DIR }}\\setupvars.bat" && ${{ env.INSTALL_TEST_DIR }}/subgraphsDumperTests --gtest_print_time=1  --gtest_print_time=1 --gtest_output=xml:${{ env.INSTALL_TEST_DIR }}/TE
```suggestion
          call "${{ env.INSTALL_DIR }}\\setupvars.bat" && ${{ env.INSTALL_TEST_DIR }}/subgraphsDumperTests --gtest_print_time=1  --gtest_output=xml:${{ env.INSTALL_TEST_DIR }}/TEST-SubgraphsDumperTests.xml
```

2023-10-26 13:24 UTC, ilya-lavrenov commented
Invalid configuration and CI is not run https://github.com/openvinotoolkit/openvino/actions/runs/6654482062

2023-10-26 13:25 UTC, mryzhov commented on .github/workflows/linux.yml
> +        - TEST_TYPE: ['OP', 'API']
```suggestion
        TEST_TYPE: [OP, API]
```

2023-10-26 13:25 UTC, mryzhov commented on .github/workflows/linux.yml
> +        - TEST_DEVICE: ['CPU', 'TEMPLATE']
```suggestion
        TEST_DEVICE: [CPU, TEMPLATE]
```

2023-11-08 11:11 UTC, ilya-lavrenov requested changes
Agree to have it in precommit only iff it does not consume a lot of time.
Template plugin is not a first class citizen to waste precommit time

2023-11-08 11:20 UTC, iefode commented
@akashchi Please take a look

2023-11-08 17:33 UTC, akashchi approved these changes

2023-11-10 08:39 UTC, merged