Extend throughput benchmark with device CLI parameter
openvinotoolkit/openvino pull request #20816
Opened 2023-11-01 11:51 UTC by TolyaTalamanov

Added device name as the second CLI parameter with default CPU value for throughput benchmark sample

2023-11-01 11:59 UTC, vurusovs approved these changes

2023-11-01 12:12 UTC, Wovchena requested changes

2023-11-01 12:12 UTC, Wovchena commented on samples/cpp/benchmark/throughput_benchmark/main.cpp
> +            device_name = TSTRING2STRING(argv[2]);
```suggestion
            device_name = argv[2];
```
This main doesn't take tchars

2023-11-01 12:12 UTC, Wovchena commented on samples/cpp/benchmark/throughput_benchmark/main.cpp
Please update README. It was moved recently. As far as I understand the new location is docs\articles_en\learn_openvino\openvino_samples\cpp_sample_throughput_benchmark.md

2023-11-01 12:15 UTC, Wovchena commented on samples/cpp/benchmark/throughput_benchmark/main.cpp
I guess you are not interested in python equivalent sample, but to keep them aligned, please apply the same change for Python as well

2023-11-01 12:56 UTC, dmatveev commented on samples/cpp/benchmark/throughput_benchmark/main.cpp
Well we're actually interested in Python equivalents - so thanks for heads-up!

2023-11-01 13:06 UTC, TolyaTalamanov commented on samples/cpp/benchmark/throughput_benchmark/main.cpp
Done

2023-11-01 13:52 UTC, Wovchena commented on samples/python/benchmark/throughput_benchmark/throughput_benchmark.py
> -    # Pick a device by replacing CPU, for example MULTI:CPU(4),GPU(8).
Comments also should be aligned

2023-11-01 14:54 UTC, TolyaTalamanov commented on samples/cpp/benchmark/throughput_benchmark/main.cpp
Good catches! Thanks, done

2023-11-01 14:54 UTC, TolyaTalamanov commented on samples/python/benchmark/throughput_benchmark/throughput_benchmark.py
> -    # Pick a device by replacing CPU, for example MULTI:CPU(4),GPU(8).
Done

2023-11-02 08:05 UTC, TolyaTalamanov commented on samples/python/benchmark/throughput_benchmark/throughput_benchmark.py
> -    # Pick a device by replacing CPU, for example MULTI:CPU(4),GPU(8).
Aligned

2023-11-02 10:39 UTC, Wovchena approved these changes

2023-11-03 08:57 UTC, merged