fix #38545 remove CPU network layer check for py samples
openvinotoolkit/openvino pull request #2145
Opened 2020-09-09 11:47 UTC by generalova-kate

2020-09-09 11:54 UTC, ilyachur approved these changes

2020-09-09 11:55 UTC, ilya-lavrenov approved these changes

2020-09-09 12:02 UTC, akuporos requested changes
Please, also remove ```import ngraph as ng``` from samples except object_detection_sample_ssd.py.

2020-09-10 09:38 UTC, akuporos approved these changes
ok, let's merge this PR and remove import in another PR

2020-09-10 09:39 UTC, antonrom23 approved these changes

2020-09-10 09:44 UTC, merged