[CPU] Upgrade CPU func tests to 2.0
openvinotoolkit/openvino pull request #21468
Opened 2023-12-05 08:27 UTC by yangwang201911

### Details:
 - update test case "CompareWithRefs" to API 2.0
 - *...*

### Tickets:
 - 125924

2023-12-06 06:54 UTC, zhaixuejun1993 commented on src/plugins/intel_cpu/tests/functional/single_layer_tests/convert_to_plugin_specific_node.cpp
> +        const auto ngPrc = prc;
can use "prc" directly, remove "ngPrc"

2023-12-11 08:04 UTC, riverlijunjie commented on src/plugins/intel_cpu/tests/functional/single_layer_tests/psroi_pooling.cpp
>          const ngraph::ResultVector results{std::make_shared<ngraph::opset3::Result>(psroi)};
```suggestion
        const ov::ResultVector results{std::make_shared<ov::op::v0::Result>(psroi)};
```

2023-12-11 08:52 UTC, yangwang201911 commented on src/plugins/intel_cpu/tests/functional/single_layer_tests/psroi_pooling.cpp
>          const ngraph::ResultVector results{std::make_shared<ngraph::opset3::Result>(psroi)};
updated

2023-12-11 08:52 UTC, yangwang201911 commented on src/plugins/intel_cpu/tests/functional/single_layer_tests/convert_to_plugin_specific_node.cpp
> +using namespace ov::test::utils;
Updated.

2023-12-13 02:11 UTC, zhaixuejun1993 approved these changes

2023-12-13 03:12 UTC, riverlijunjie commented on src/plugins/intel_cpu/tests/functional/single_layer_tests/psroi_pooling.cpp
>          auto coords = ngraph::builder::makeConstant<float>(ngraph::element::f32, proposalShape, proposal);
```suggestion
        auto coords = ngraph::builder::makeConstant<float>(ov::element::f32, proposalShape, proposal);
```

2023-12-14 09:53 UTC, vurusovs requested changes

2023-12-14 09:53 UTC, vurusovs commented on src/plugins/intel_cpu/tests/functional/single_layer_tests/psroi_pooling.cpp
> +    std::string mode;
Let's make it local for `SetUp()`

2023-12-15 07:39 UTC, yangwang201911 commented on src/plugins/intel_cpu/tests/functional/single_layer_tests/psroi_pooling.cpp
> +    std::string mode;
sure. Updated.

2023-12-15 07:48 UTC, vurusovs approved these changes

2023-12-18 02:02 UTC, riverlijunjie approved these changes

2023-12-26 13:16 UTC, zhaixuejun1993 commented
replaced by https://github.com/openvinotoolkit/openvino/pull/21866
close

2023-12-26 13:16 UTC, closed without merging