support pytorch efrc op
openvinotoolkit/openvino pull request #21567
Opened 2023-12-11 05:22 UTC by ahmadchalhoub

### Details:
Support aten::erfc op (https://pytorch.org/docs/stable/special.html#torch.special.erfc) for Pytorch in OpenVino.

### Tickets:
#20577

2023-12-11 08:26 UTC, mvafin requested changes
Please also fix code style

2023-12-11 08:26 UTC, mvafin commented on src/frontends/pytorch/src/op/erfc.cpp
> +    ones = context.mark_node(make_shared<v1::ConvertLike>(ones, y));
```suggestion
    auto ones = context.mark_node(make_shared<v0::Constant>(element::f32, Shape{}, 1.0f))->output(0);
    align_eltwise_input_types(context, x, ones);
    
    // apply Erf to the input tensor 'x'
    auto y = context.mark_node(std::make_shared<v0::Erf>(x));
```
Your approach will not work for dynamic case. `align_eltwise_input_types` will align type of FP32 `ones` input and `x` the result will be equal type, which will work for FP64, INT and dynamic case.

2023-12-11 13:44 UTC, mvafin approved these changes

2023-12-11 16:20 UTC, ahmadchalhoub commented
@mvafin hmm looks like code format is still giving errors, even though I checked with clang-format. Any idea why it might be failing?

2023-12-11 16:26 UTC, mvafin commented
> @mvafin hmm looks like code format is still giving errors, even though I checked with clang-format. Any idea why it might be failing?

Yes, it is because our codestyle requires 4 spaces instead of 2 spaces. You can run `make clang_format_fix_all` if you had the correct version of clang format installed.

2023-12-12 16:03 UTC, mvafin commented
build_jenkins

2023-12-12 20:54 UTC, merged