[PT FE] Add aten::gcd
openvinotoolkit/openvino pull request #21740
Opened 2023-12-18 19:28 UTC by karanjakhar

### Details:
 - *Add aten::gcd*

### Tickets:
 - *Closes #20580*

2023-12-28 11:07 UTC, mvafin requested changes

2023-12-28 11:07 UTC, mvafin commented on src/frontends/pytorch/src/op/gcd.cpp
> +    auto zero = context.mark_node(v0::Constant::create(element::i32, Shape{}, {0}));
`x` and/or `y` can have `int64` type. Please use `ConvertLike` operation for `zero` and `align_eltwise_input_types` helper function for `x` and `y` to support such case. Also please add a test with mixed `int32` and `int64` types.

2023-12-28 11:07 UTC, mvafin commented on src/frontends/pytorch/src/op/gcd.cpp
> +#include <openvino/openvino.hpp>
```suggestion
#include "openvino/openvino.hpp"
```

2024-01-01 10:06 UTC, karanjakhar commented
Hi @mvafin 
I have updated the code. But I am stuck with an error. Please help me. 
```openvino._pyopenvino.OpConversionFailure: Check 'is_conversion_successful' failed at src/frontends/pytorch/src/frontend.cpp:141:
E       FrontEnd API failed with OpConversionFailure:
E       Model wasn't fully converted. Failed operations detailed log:
E       -- aten::gcd with a message:
E       Exception happened during conversion of operation aten::gcd with schema aten::gcd(Tensor self, Tensor other) -> Tensor
E       Check 'unregistered_parameters.str().empty()' failed at src/core/src/model.cpp:57:
E       Model references undeclared parameters: opset1::Parameter tensor_a () -> (dynamic[...])
E       opset1::Parameter tensor_b () -> (dynamic[...])
```

Thanks

2024-01-02 12:34 UTC, mvafin commented
@karanjakhar This problem is caused by the fact that now `zero` depends from nodes that are outside the `Loop` body. So you have 2 options: either use `align_eltwise_input_types` on `x_input` and 'y_input` rather then on `x` and `y` or create an additional input to `Loop` body that will be `zero` input.

2024-01-02 14:20 UTC, mvafin commented on src/frontends/pytorch/src/op/gcd.cpp
Please also add copyright on top of the file

2024-01-07 09:52 UTC, karanjakhar commented on src/frontends/pytorch/src/op/gcd.cpp
@mvafin x_input and y_input are `Parameter`. How to use `align_eltwise_input_types` on `x_input` and `y_input`.

2024-01-08 10:22 UTC, mvafin commented on src/frontends/pytorch/src/op/gcd.cpp
Parameter is also a Node, so maybe you need to cast.

2024-01-09 21:26 UTC, karanjakhar commented on src/frontends/pytorch/src/op/gcd.cpp
Hi @mvafin 
Can you show me further how it is done?
Thanks

2024-01-10 06:23 UTC, karanjakhar commented on src/frontends/pytorch/src/op/gcd.cpp
Hi @mvafin 
I have managed to get it working. Just one test case is failing. I understand it is because the output type from the torch and our GCD differ. But I am not sure why that is happening. Please can you have a look?
Thanks 
![Screenshot from 2024-01-10 11-47-10](https://github.com/openvinotoolkit/openvino/assets/29913676/ef3eab5e-d9b3-41b0-bd12-1d27f865104a)
![Screenshot from 2024-01-10 11-46-20](https://github.com/openvinotoolkit/openvino/assets/29913676/d5f41568-5de2-49b1-9f71-6966113732b0)

2024-01-10 11:14 UTC, mvafin commented on thirdparty/ade
Please revert this change

2024-01-10 15:32 UTC, mvafin commented on thirdparty/ade
You didn't revert changes in this submodule, but you reverted last commit with changes.

2024-01-12 10:00 UTC, karanjakhar commented on src/frontends/pytorch/src/op/gcd.cpp
Hi @mvafin  
Please guide me on this.
Thanks

2024-01-17 15:24 UTC, mvafin requested changes
The problem that you have is caused by a different way python int is interpreted in openvino and numpy. That is not a problem of your implementation, so I recommend you to return tensor from the test.

2024-01-17 15:24 UTC, mvafin commented on tests/layer_tests/pytorch_tests/test_gcd.py
> +                return torch.gcd(int_a, int_b)
```suggestion
                return torch.tensor(torch.gcd(int_a, int_b))
```

2024-01-17 16:43 UTC, mvafin approved these changes

2024-01-18 09:33 UTC, mvafin commented
build-jenkins

2024-01-18 18:55 UTC, merged