Ops for 2023.3 release
openvinotoolkit/openvino pull request #21753
Opened 2023-12-19 09:17 UTC by suryasidd

### Details:
 - Added operators for 2023.3 release
 - Includes ops required for enabling customer model lightglue. 
 - Also added ops for Lora fine tuning

### Tickets:
 - https://jira.devtools.intel.com/browse/CVS-116701

2023-12-19 11:06 UTC, eaidova commented on src/bindings/python/src/openvino/frontend/pytorch/torchdynamo/backend.py
> +        #input, weight.transpose(0,1), stride=stride, padding=padding, dilation=dilation, groups=groups
looks like some debug comment, please remove?

2023-12-19 11:26 UTC, eaidova commented on src/bindings/python/src/openvino/frontend/pytorch/torchdynamo/backend_utils.py
>          cfg = options["config"]
should here be also check that config is not None?

2023-12-19 11:26 UTC, eaidova commented on src/bindings/python/src/openvino/frontend/pytorch/torchdynamo/backend_utils.py
> -        return options["config"]
please add return value for case if config is not in options

2023-12-19 11:26 UTC, eaidova commented on src/frontends/pytorch/src/op/min_max.cpp
> +OutputVector translate_max_dim_fx(const NodeContext& context) {
I do not see the difference except packing output between 2 translators, can it reuse one inside another?

2023-12-19 11:26 UTC, eaidova commented on src/frontends/pytorch/src/op/var_mean.cpp
> +#include "openvino/op/unsqueeze.hpp"
I do not see unsqueeze usage in this file? Does these headers added accidentally?

2023-12-19 11:26 UTC, eaidova commented on src/frontends/pytorch/src/op/var_mean.cpp
> +    axes = context.get_input(1);
the check of number of inputs does not look correct. Above you check that at least 1 input provided, but here you use the second input without any checks that context contains it

2023-12-19 11:26 UTC, eaidova commented on src/frontends/pytorch/src/op/var_mean.cpp
> +    auto sub_v = context.mark_node(std::make_shared<v1::Subtract>(data, t_mean));
is it possible to reuse some code between translators? Looks very similar to ts translator, except output replacing and first input check

2023-12-19 11:26 UTC, eaidova commented on src/frontends/pytorch/src/op_table.cpp
> +        {"aten::_log_softmax.default", op::translate_log_softmax},
Probably you mean:
```suggestion
        {"aten._log_softmax.default", op::translate_log_softmax},
```

2023-12-20 06:50 UTC, p-durandin commented
Pls fix windows build

2023-12-20 12:29 UTC, suryasidd commented
We don't need to merge this PR for 2023.3. Removing the labels

2024-02-07 15:53 UTC, PiotrKrzem requested changes

2024-02-07 15:53 UTC, PiotrKrzem commented on src/frontends/pytorch/src/op/log.cpp
> +    auto sigmoid = context.mark_node(std::make_shared<v0::Sigmoid>(x));
Should the f32 conversion happen after Sigmoid? Is this the expected behavior for int-type values?

2024-02-07 15:53 UTC, PiotrKrzem commented on src/frontends/pytorch/src/op/min_max.cpp
> +    auto indicies = context.mark_node(std::make_shared<v0::Convert>(topk->output(1), element::i64));
Minor grammar change
```suggestion
    auto indices = context.mark_node(std::make_shared<v0::Convert>(topk->output(1), element::i64));
```

2024-02-07 15:53 UTC, PiotrKrzem commented on src/frontends/pytorch/src/op/min_max.cpp
> +        indicies = std::make_shared<v0::Squeeze>(indicies, axes_node);
```suggestion
        indices = std::make_shared<v0::Squeeze>(indices, axes_node);
```

2024-02-07 15:53 UTC, PiotrKrzem commented on src/frontends/pytorch/src/op/min_max.cpp
> +    return {values, indicies};
```suggestion
    return {values, indices};
```

2024-02-07 15:53 UTC, PiotrKrzem commented on src/frontends/pytorch/src/op/split.cpp
> +    auto shape = context.get_input(0).get_shape();
```suggestion
    auto shape = input.get_shape();
```

2024-02-07 15:53 UTC, PiotrKrzem commented on src/frontends/pytorch/src/op/split.cpp
> +    auto chunk = context.mark_node(std::make_shared<v1::Split>(context.get_input(0), dim, num_splits));
```suggestion
    auto chunk = context.mark_node(std::make_shared<v1::Split>(input), dim, num_splits));
```

2024-02-09 06:49 UTC, suryasidd commented
Closing this, opened a new one. https://github.com/openvinotoolkit/openvino/pull/22745

2024-02-09 06:49 UTC, closed without merging