[apiConformance] Move from Relu to double Concat function in import_export tests
openvinotoolkit/openvino pull request #21788
Opened 2023-12-20 13:27 UTC by sbalandi

### Details:
 - *item1*
 - *...*

### Tickets:
 - *ticket-id*

2023-12-21 09:28 UTC, iefode requested changes

2023-12-21 14:39 UTC, sbalandi commented on src/tests/functional/plugin/shared/include/behavior/compiled_model/import_export.hpp
> -    std::shared_ptr<ov::Core> core = ov::test::utils::PluginCache::get().core();
duplicate of test importExportedParameterResultOnly

2023-12-21 14:39 UTC, sbalandi commented on src/tests/functional/plugin/shared/include/behavior/compiled_model/import_export.hpp
>      std::shared_ptr<InferenceEngine::Core> ie = ::PluginCache::get().ie();
moved to 2.0 api

2024-01-09 08:35 UTC, iefode approved these changes

2024-01-09 08:35 UTC, merged