[ONNX] Extend ONNX Frontend with Function `Celu-12`
openvinotoolkit/openvino pull request #22002
Opened 2024-01-06 12:42 UTC by siddhant-0707

### Details:
 - created implementation for `Celu-12` operator
 - creating tests

### Tickets:
 - #20543

2024-01-18 08:49 UTC, siddhant-0707 commented
@gkrivor

2024-01-18 10:28 UTC, gkrivor commented
@siddhant-0707 you should remove it from the list, otherwise it tries to expand it using an existing simple operators, if possible.

2024-01-23 11:39 UTC, andrei-kochin commented
build_jenkins

2024-01-23 15:32 UTC, gkrivor commented
build_jenkins

2024-01-26 06:51 UTC, siddhant-0707 commented
It appears `Celu` only takes in float type input, so the `int` test I created previously is irrelevant. Also added check to confirm type.

2024-02-15 20:09 UTC, mitruska requested changes
Proposed subgraph looks mathematically correct, but is bigger and not aligned with ONNX Function Celu decomposition.

As currently ONNX Celu op is expanded via ONNX standard mechanism to `Div->Elu->Mul`, 
changes in the subgraph produced by OV can affect performance and backward compatibility. 

I suggest to align the subgraph with the ONNX standard decomposition.

2024-02-15 20:09 UTC, mitruska commented on src/frontends/onnx/frontend/src/op/celu.cpp
> +    CHECK_VALID_NODE(node, input.get_element_type() == element::f32, "Only float32 input type is supported")
Please remove this check, supported types are validated in the constructors of ov operators, also such restriction can be not backward compatible.

2024-02-22 17:13 UTC, mitruska reviewed
Thank you @siddhant-0707 for applying the requested changes. 
Just few additional suggestions for the updated code.

2024-03-01 07:56 UTC, siddhant-0707 commented on src/frontends/onnx/frontend/src/op/celu.cpp
> +    auto divide_node = std::make_shared<v1::Divide>(x_celu, alpha_node);
Hey, @mitruska the type alignment logic you suggested needs to be in a separate PR right? Removing the Convert statement for now. BTW, thank you so much for the detailed review!

2024-03-01 10:43 UTC, mitruska commented
build_jenkins

2024-03-01 11:47 UTC, gkrivor approved these changes

2024-03-01 15:47 UTC, mitruska commented
build_jenkins

2024-03-04 08:53 UTC, gkrivor commented
build_jenkins

2024-03-05 05:06 UTC, merged