[ONNX] Extend ONNX Frontend with `com.microsoft.Pad`
openvinotoolkit/openvino pull request #22000
Opened 2024-01-06 11:08 UTC by siddhant-0707

### Details:
 - created implementation for `com.microsoft.Pad`
 - creating test

### Tickets:
 - #17576

2024-02-16 15:55 UTC, mitruska requested changes
Hello @siddhant-0707, thank you for your contribution!

[MS ONNX Pad](https://onnx.ai/onnx/operators/onnx__Pad.html#pad-11) and [ONNX standard Pad-11](https://onnx.ai/onnx/operators/onnx__Pad.html#pad-11) seem to be compatible. The only difference I can see is that MS Pad allows pads input to be `2D`, then the first dim is required to be `1`, so it could be simply resolved by Squeeze. My suggestion is to reuse `set_11::pad` code within a common function to avoid duplication of the main logic. Squeeze can be applied to the MS pads input if needed, before the common part.

Also this PR doesn't have any tests for the provided changes, please add them including the mentioned 2D pads scenario.
Registration of the correct pad function should be ensured.

2024-02-16 15:55 UTC, mitruska commented on src/frontends/onnx/frontend/src/op/com.microsoft/pad.cpp
> +    auto pads_shape = pads.get_shape();
The `.get_shape()` will throw for dynamic shape, it should be used only if static shape is ensured, 
`.get_partial_shape()` can be used instead. 
For partial shape `.is_static()` or `.is_dynamic()` can be used and `.size()` is safe only for shapes with static rank. 
To check whether the rank is static: `partial_shape.rank().is_static()`.

2024-03-19 08:37 UTC, mlukasze commented
hey @siddhant-0707 :)
will you continue a work on this PR? Or should we move a task back to the open pool?

2024-03-29 13:43 UTC, siddhant-0707 commented
Apologies for the delay @mlukasze, I was a little occupied with other tasks. Please reopen the PR.
@mitruska I have made changes as per your requirements and also added a test for `pads` with 2d shape. However, I'm still stuck as the `.prototxt` model doesn't get converted to `.onnx` when compiling and hence test fails.

2024-03-29 17:10 UTC, siddhant-0707 commented
Apologies for the delay @mlukasze, I was a little occupied with other tasks. Please reopen the PR.
@mitruska I have reused the implementation of `set_11::pad` (with modification in beginning to handle case with 2d `pads` input). I've done this because we have to assign the squeezed value back to `node.get_ng_inputs()[1]` (which we can't do) Is there a way to create a new node and set its inputs and pass it to `set_11::pad`?.
Another way this problem can be solved is creating an overload in `onnx::pad` that takes in `pads` separately and then passes it to `set_11::pad`. Something like `ov::OutputVector pad(const Node& node, const ov::Output<ov::Node>& pads) {}`. However, this would misalign code with docs I think.

2024-03-29 17:11 UTC, siddhant-0707 commented
Also added 2d and 1d tests

2024-03-29 22:32 UTC, mitruska commented
Hello @siddhant-0707, great to see some updates! Reopened the PR as you asked.
To continue review, please push commits with the changes you have mentioned and sync branch with the latest master.

2024-04-03 11:09 UTC, gkrivor approved these changes

2024-04-03 11:09 UTC, gkrivor commented
build_jenkins

2024-04-03 12:36 UTC, mitruska reviewed
My previous concern (https://github.com/openvinotoolkit/openvino/pull/22000#discussion_r1492629220) about `get_shape()` call has been not applied.
Please add suggested change to avoid further issues.

About creating the common pad function, it could be a helper taking `ov::OutputVector` as argument, and called from the onnx standard pad and custom pad (after get_ov_inputs()). 
But such code unification can be considered as follow up improvement within a separate PR. 

Let's focus on the last necessary change:)

2024-04-03 12:36 UTC, mitruska commented on src/frontends/onnx/frontend/src/op/com.microsoft/pad.cpp
> +    }
As I mentioned, `get_shape()` called on the node with dynamic shape will cause an issue, so it should be ensured that the shape is static before the rank size check.

```suggestion
    const auto& pads_pshape = pads.get_partial_shape();
    if (pads_pshape.rank().is_static() && pads_pshape.size() == 2) {
        pads = std::make_shared<v0::Squeeze>(pads);
    }
```

2024-04-03 13:34 UTC, mitruska approved these changes

2024-04-03 13:34 UTC, mitruska commented
build_jenkins

2024-04-04 13:05 UTC, mitruska commented
build_jenkins

2024-04-05 10:19 UTC, merged