benchmark_app Python -load_config "PERFORMANCE_HINT":"LATENCY" doesn't take into effect
openvinotoolkit/openvino pull request #22031
Opened 2024-01-09 03:57 UTC by panhaiqi

### Details:
 - *benchmark_app Python -load_config "PERFORMANCE_HINT":"LATENCY" doesn't take into effect*

### Tickets:
 - *[ticket-id](https://jira.devtools.intel.com/browse/CVS-126988)*

2024-01-09 04:53 UTC, zhaixuejun1993 commented on samples/cpp/benchmark_app/main.cpp
> +                ov_perf_hint = config[ov::hint::performance_mode.name()];
ov::Any can not directly convert to "ov::hint::PerformanceMode"

2024-01-09 10:36 UTC, Wovchena requested changes

2024-01-09 10:36 UTC, Wovchena commented on samples/cpp/benchmark_app/main.cpp
I haven't reviewed the logic yet, but I think you should update Python version the same way

2024-01-09 10:36 UTC, Wovchena commented on samples/cpp/benchmark_app/main.cpp
Please add a test: https://github.com/openvinotoolkit/openvino/blob/c6258294fea969d2908efe841df068bdb98d2b88/tests/samples_tests/smoke_tests/test_benchmark_app.py. It can be something like:
1. Create temp config file
2. Return `stdout` from `_check_output()`
3. Verify `stdout` contains the values used in temp config file

I just noticed that both existing tests were suppressed 10 months ago even though the ticket is resolved. So there's a big risk that tests don't pass. Let me know if you encounter issues with that.

2024-03-06 04:02 UTC, wangleis commented on samples/cpp/benchmark_app/main.cpp
> +            if (config.find(ov::hint::performance_mode.name()) != config.end()) {
"sync" inference should only work with latency mode.

2024-06-04 09:11 UTC, akuporos commented on tests/samples_tests/smoke_tests/test_benchmark_app.py
> +test_priority_cpp = get_tests \
I believe these two tests may be united.

2024-06-27 00:19 UTC, closed without merging