Align behavior of ONNX Frontend operator AveragePool-7, 10, 11, 19 with original framework #20553
openvinotoolkit/openvino pull request #22075
Opened 2024-01-10 15:21 UTC by Sukhvansh2004

### Details:
Have created instances of op-7, op-10, op-11 and op-19. 
fixes: https://github.com/openvinotoolkit/openvino/issues/20553#issuecomment-1889780590

2024-01-17 18:31 UTC, Sukhvansh2004 commented
![image](https://github.com/openvinotoolkit/openvino/assets/120120146/30be8279-9376-4634-8122-f0f4bb9f763c)

@gkrivor @p-wysocki  I am getting the following output on running python -m pytest in onnx folder of the repo. Since no test case of average pool is failing I suppose the code is working right?

2024-01-18 10:04 UTC, p-wysocki commented
Hi @Sukhvansh2004, the tests are currently passing on master, so your implementation may have somehow broke them, or your ONNX version is not compliant with our requirements.
1. Please make sure that your Python environment has onnx==1.15.0 and run the tests again.
2. If they are still failing, please paste the test errors, we'll take a look.

2024-01-18 15:41 UTC, mitruska requested changes
Hello @Sukhvansh2004, thank you for your effort and willingness to make a contribution to the OpenVINO project. 

In general the proposed changes are mixing the OpenVINO Opsets versioning with ONNX Opsets. Looks like OpenVINO `v1::AvgPool` is able to support most of the ONNX AveragePool (7, 10, 11, 19) features that's why the common PoolingFactory is used. 

Definition of the gaps in the existing implementation, can be explored by adding [corresponding tests](https://github.com/openvinotoolkit/openvino/blob/1a8f72f3426e02a2cdd3929b608659cd6003feca/src/frontends/onnx/tests/onnx_import_convpool.in.cpp#L281-L331) for ONNX AvgPool from different ONNX opsets.

Here you can find the disabled tests from the ONNX compliance:
https://github.com/openvinotoolkit/openvino/blob/1a8f72f3426e02a2cdd3929b608659cd6003feca/src/frontends/onnx/tests/tests_python/test_backend.py#L689-L690 https://github.com/openvinotoolkit/openvino/blob/1a8f72f3426e02a2cdd3929b608659cd6003feca/src/frontends/onnx/tests/tests_python/test_backend.py#L742-L747

Most of them are related to the "dilations" attribute, and in fact to cover it, new version of the ov AvgPool is needed (as it was done for ov MaxPool op). But to enable new ov Op not only new class of AvgPool is needed, but also the plugin implementation. 
We will cover such request internally or by a separate, precisely described task for contributors. 

For now I would recommend to add more [tests](https://github.com/openvinotoolkit/openvino/blob/1a8f72f3426e02a2cdd3929b608659cd6003feca/src/frontends/onnx/tests/onnx_import_convpool.in.cpp#L281-L331) and describe, what a single new version of the ov AvgPool should cover. Also feel free to switch to another GFI task.

2024-01-18 17:45 UTC, Sukhvansh2004 commented
> Hello @Sukhvansh2004, thank you for your effort and willingness to make a contribution to the OpenVINO project.
> 
> In general the proposed changes are mixing the OpenVINO Opsets versioning with ONNX Opsets. Looks like OpenVINO `v1::AvgPool` is able to support most of the ONNX AveragePool (7, 10, 11, 19) features that's why the common PoolingFactory is used.
> 
> Definition of the gaps in the existing implementation, can be explored by adding [corresponding tests](https://github.com/openvinotoolkit/openvino/blob/1a8f72f3426e02a2cdd3929b608659cd6003feca/src/frontends/onnx/tests/onnx_import_convpool.in.cpp#L281-L331) for ONNX AvgPool from different ONNX opsets.
> 
> Here you can find the disabled tests from the ONNX compliance:
> 
> https://github.com/openvinotoolkit/openvino/blob/1a8f72f3426e02a2cdd3929b608659cd6003feca/src/frontends/onnx/tests/tests_python/test_backend.py#L689-L690
> 
> https://github.com/openvinotoolkit/openvino/blob/1a8f72f3426e02a2cdd3929b608659cd6003feca/src/frontends/onnx/tests/tests_python/test_backend.py#L742-L747
> 
> Most of them are related to the "dilations" attribute, and in fact to cover it, new version of the ov AvgPool is needed (as it was done for ov MaxPool op). But to enable new ov Op not only new class of AvgPool is needed, but also the plugin implementation. We will cover such request internally or by a separate, precisely described task for contributors.
> 
> For now I would recommend to add more [tests](https://github.com/openvinotoolkit/openvino/blob/1a8f72f3426e02a2cdd3929b608659cd6003feca/src/frontends/onnx/tests/onnx_import_convpool.in.cpp#L281-L331) and describe, what a single new version of the ov AvgPool should cover. Also feel free to switch to another GFI task.


Hi @mitruska , Thank you so much for your review, since you mentioned that op-7, 10 and 11 are having the saming functionality as op-1  (only a additional attribute of ceil mode and documentation changes were there till op-11 while ceil mode was covered via the m_rounding_type variable) so should I revert the changes of op-7,10 and 11. Also for op-19 as you said dilations would require an addtional plugin so what should I do regarding that.

2024-01-19 16:27 UTC, Sukhvansh2004 commented on src/core/include/openvino/op/avg_pool.hpp
> +}  // namespace v11
Ok sir, will try to make the suggested changes in a day or 2.

2024-02-05 06:15 UTC, mlukasze commented
hey @Sukhvansh2004 

Are you willing to finish this PR? :)

2024-02-06 08:29 UTC, Sukhvansh2004 commented
Sorry I wont be able to finish the PR as I have got some other commitments now, however I'll try to find time if I could. Till then you can assign it to anyone else

2024-02-22 10:58 UTC, closed without merging