[GHA] enabled sccache error logging
openvinotoolkit/openvino pull request #22428
Opened 2024-01-25 14:14 UTC by mryzhov

### Details:
 - enabled sccache error logging
 - upload cpu functional tests logs every time 

### Tickets:
 - *ticket-id*

2024-01-25 19:16 UTC, akladiev commented
Over 100 MB per one sccache log... I wonder if we'll hit some storage limits or something someday

2024-01-26 10:48 UTC, mryzhov commented
> Over 100 MB per one sccache log... I wonder if we'll hit some storage limits or something someday Maybe it makes sense to compress it first?

they should be already compressed, but I think debug level is redundant

2024-01-26 13:25 UTC, akladiev approved these changes

2024-01-26 13:29 UTC, akladiev requested changes
Trying to remove approval back to check queue behavior :D

2024-01-26 14:59 UTC, merged