[Core] remove ie_paramater
openvinotoolkit/openvino pull request #22443
Opened 2024-01-26 05:33 UTC by riverlijunjie

### Details:
 - remove ie_paramater

### Tickets:
 - CVS-130761

2024-01-26 06:49 UTC, vurusovs requested changes

2024-01-26 06:49 UTC, vurusovs commented on src/plugins/auto_batch/tests/functional/behavior/ov_plugin/auto_batching_tests.cpp
> +                                                                               ov::Any{"1000"}})),
let's use `ov::auto_batch_timeout(1000)` - it will allow remove `DefaultParameter`

2024-01-26 18:43 UTC, ilya-lavrenov commented on src/plugins/auto_batch/tests/functional/behavior/ov_plugin/auto_batching_tests.cpp
> -    DefaultConfigurationTest::getTestCaseName);
why are these tests removed?

2024-01-29 16:32 UTC, ilya-lavrenov approved these changes

2024-01-30 08:00 UTC, merged