[CPU] Fixed descriptor creation bug for 3D quantized deconvolution
openvinotoolkit/openvino pull request #22731
Opened 2024-02-08 12:33 UTC by v-Golubev

### Details:
 - *Added supported ranks in `canBeExecutedInInt8`*
 - *`getSupportedDescriptors`: added 3D case handling*
 - *Added 3D ConvolutionBackpropData test cases to LPT plugin tests*

### Tickets:
 - *CVS-132070*

2024-02-08 13:27 UTC, eshoguli approved these changes
LGTM

2024-02-12 16:12 UTC, maxnick requested changes

2024-02-12 17:23 UTC, maxnick approved these changes

2024-02-12 21:48 UTC, v-Golubev commented on src/plugins/intel_cpu/src/nodes/deconv.cpp
> +                                  : dnnl::memory::format_tag::ntc;
Format tag corrected, thanks for the suggestion

2024-02-13 09:35 UTC, merged