[CPU] [AARCH64] jit exp
openvinotoolkit/openvino pull request #22937
Opened 2024-02-19 23:11 UTC by eshoguli

### Details:
 - *[CPU] [AARCH64] jit sigmoid*

### Tickets:
 - *CVS-132534*

2024-03-08 11:36 UTC, dmitry-gorokhov commented
@xuchen-intel Please review the PR

2024-03-16 09:11 UTC, xuchen-intel requested changes

2024-03-19 14:11 UTC, eshoguli commented on src/plugins/intel_cpu/src/emitters/plugin/aarch64/jit_eltwise_emitters.cpp
> +        OPENVINO_THROW("Can't create jit eltwise kernel");
done, thanks

2024-03-19 14:11 UTC, eshoguli commented on src/plugins/intel_cpu/src/emitters/plugin/aarch64/jit_eltwise_emitters.cpp
> +    }
done thanks

2024-03-21 11:39 UTC, eshoguli commented on src/plugins/intel_cpu/src/emitters/plugin/aarch64/jit_emitter.cpp
> +    const size_t aux_vec_idxs_size = aux_vec_idxs.size();
removed, fix will be in separated PR: https://github.com/openvinotoolkit/openvino/pull/23387 (wip)

2024-03-22 09:19 UTC, dmitry-gorokhov commented
@xuchen-intel Any remaining comments?

2024-03-23 20:47 UTC, xuchen-intel approved these changes

2024-03-23 21:11 UTC, xuchen-intel commented
> @xuchen-intel Any remaining comments?

The other parts LGTM. Thanks Dmitry for the reminder!

2024-03-25 05:11 UTC, dmitry-gorokhov approved these changes

2024-03-25 05:11 UTC, dmitry-gorokhov commented
@eshoguli Please rebase the PR

2024-03-26 17:35 UTC, merged