[Add] Guide to Python wheels #22688
openvinotoolkit/openvino pull request #23203
Opened 2024-03-01 19:21 UTC by tonguegrease

Fixing https://github.com/openvinotoolkit/openvino/issues/22017 by adding a guide to Python wheels. Hopefully I did everything correctly. This is one of my first contributions so I apologize in advance for any mistakes I may have made. Thank you for allowing me the opportunity to work on this!

Details:
Made a guide to Python wheels by adding:
An introduction
Elaborating the description
Building section
Locating section
Setup section
Workflow section

Tickets:
ticket-id

2024-03-11 18:24 UTC, jiwaszki requested changes
@tonguegrease thanks for this PR! Here is my feedback on it.

CC @kblaszczak-intel please take a look here from documentation point of view, thanks!

2024-03-11 18:24 UTC, jiwaszki commented on src/bindings/python/wheel/guide-to-wheels.rst
> +After building the project, you can find the generated Python wheels under the **openvino_install_dir/tools** directory.
```suggestion
After building the project, you can find the generated Python wheels under the **openvino/build/wheels/** directory.
```
I think this is the easiest way to locate them after building the project and this way should be advised.

2024-03-11 18:24 UTC, jiwaszki commented on src/bindings/python/wheel/guide-to-wheels.rst
> +This ensures that the build process includes the Python components and generates the necessary wheel files.
I would also add info about additional effects of this building pratice:
* That wheels regeneration might need require to delete `wheels` folder before running `make` command again.
* After getting new wheels it is required to reinstall them, i.e. running `pip uninstall openvino` and `pip install wheels/openvino[...]` as effects won't be visible instantly.

2024-03-11 18:24 UTC, jiwaszki commented on src/bindings/python/wheel/guide-to-wheels.rst
> +Workflow Differences
I would also include the case when both pip and PYTHONPATH is set together. This results in conflicts which can be describe in this guide.

2024-03-26 06:08 UTC, mlukasze commented
hey @tonguegrease :)
Will you have a time to finish a PR?

2024-03-30 23:12 UTC, tonguegrease commented
Hey there! Apologies for the late reply. Unfortunately, I have too many things going on in my life at the moment and won't have time to finish this.On Mar 26, 2024, at 2:08 AM, Michal Lukaszewski ***@***.***> wrote:﻿
hey @tonguegrease :)
Will you have a time to finish a PR?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-04-02 05:35 UTC, closed without merging

2024-04-02 05:35 UTC, mlukasze commented
thank you for your time any way!