[IE Tests] Added NormalizeL2 tests
openvinotoolkit/openvino pull request #2327
Opened 2020-09-18 08:52 UTC by l-bat

2020-09-28 05:57 UTC, iefode requested changes

2020-09-28 05:57 UTC, iefode commented on inference-engine/tests/functional/plugin/shared/include/single_layer_tests/normalize_l2.hpp
> +        std::vector<int64_t>,               // axes
Please, align with [specification](https://github.com/openvinotoolkit/openvino/blob/master/docs/ops/normalization/LRN_1.md)

2020-09-28 05:57 UTC, iefode commented on inference-engine/tests/functional/plugin/shared/src/single_layer_tests/normalize_l2.cpp
> +    auto norm = std::make_shared<ngraph::opset4::NormalizeL2>(paramOuts[0], normAxes, eps, epsMode);
Looks like, we can create Normalize builder. Please move constant and norm node creation there

2020-09-28 05:57 UTC, iefode commented on ngraph/core/reference/include/ngraph/runtime/reference/normalize_l2.hpp
> +                AxisSet axes = reduction_axes;
@ilyachur @GlebKazantaev Could you please review NormalizeL2 reference implementation?

2020-09-30 14:35 UTC, iefode approved these changes
Test part LGTM

2020-10-01 20:51 UTC, iefode commented on ngraph/core/reference/include/ngraph/runtime/reference/normalize_l2.hpp
> +                AxisSet axes = reduction_axes;
@ilyachur @GlebKazantaev ping

2020-10-08 04:23 UTC, ilyachur approved these changes

2020-10-08 04:23 UTC, merged