[core] Low precision element iterator
openvinotoolkit/openvino pull request #23279
Opened 2024-03-05 13:48 UTC by praasz

### Details:
 - Introduce new low precision types `u2`, `u3`, `u6`.
 - Introduce `ov::element::Iterator` for low precision types like `u1, u2, u3, u4, i4, u6`:
   - Gives pointer like access to low precision values in Tensor, containers etc.
   - Can be used by STL algorithms to access data in unified algorithms for data manipulation.
   - Can be used in Constant, Convert operators to replace duplicate implementations for accessing low precision data (bin-size reduction).
   - Can be used for operator reference implementation or plugin if there is no hardware specific solution.
   
   
     

### Tickets:
 - [CVS-126998](https://jira.devtools.intel.com/browse/CVS-126998)

2024-03-05 15:16 UTC, ilya-lavrenov commented on src/core/dev_api/openvino/core/type/element_iterator.hpp
why is it required? 
I see it as debug capabilities when you want to iterate over such low-precision array and print its values, but who will do it on inference path where performance is critical? And LP types unpack operation should be performed in plugin in optimal ways

2024-03-06 12:37 UTC, praasz commented on src/core/dev_api/openvino/core/type/element_iterator.hpp
It can help implement new types for `Constant` and `Convert` operators where similar pack/unpack functions are implemented, e.g In `Constant` functions, `write_buffer`, `cast_vector`; In `Convert` reference implementation there are like `set_u4`, `get_u4`. The duplicate implementation can be avoided.

For new `u2, u3, u6`, if supported by Constant (it looks like all types are supported) then pack/unpack has to be implemented and probably `Convert` should support them also. 

The iterator can help avoid code duplication and then reduce binary size. I've made quick test and apply it in `Constant::get_value_strings()` and reduction was about 20k. 
If applied in more places in these two operators the benefit can be bigger (during testing, I've got results around 60k-150k).

It purpose is to use where the standard approach to pack/unpack is used already and to expand it for new types.
For data inference, I agree it should not be used as plugin should provide optimized way.

2024-03-08 07:54 UTC, mitruska reviewed
I was trying to deduce the rules of those new types encoding, but would be great to have some references or docs to verify correctness of the approach in the pack/unpack functions for those new types.

2024-03-08 11:56 UTC, praasz commented on src/core/dev_api/openvino/core/type/element_iterator.hpp
> +}
Cannot be re-used, because they are not compile time available. But this can be used in "element_type.cpp" to remove duplicates.

2024-03-08 13:23 UTC, praasz commented
> I was trying to deduce the rules of those new types encoding, but would be great to have some references or docs to verify correctness of the approach in the pack/unpack functions for those new types.

Added additional ticket link

2024-03-08 17:33 UTC, praasz commented on src/core/tests/element_iterator_test.cpp
> +    auto input = std::array<int8_t, 3>{0x32, static_cast<int8_t>(0xa3), 0x55};
Is required to avoid compilation error of loss data the MSB is set and value is interpreted differently then others where MSB is `0`.

2024-03-12 09:43 UTC, jiwaszki commented
> > Introduce new low precision types u2, u3, u6.
> 
> is it supposed to be used in OpenVINO ? I have not heard that someone compress weights / quantized the model to u3

@ilya-lavrenov It will also help Python API ref: https://github.com/openvinotoolkit/openvino/pull/23263

As `cast_data(dtype)` will be able to reuse the implementation of iterating over low precision without need of duplicating the code. The unpacking will be defined by OV Core instead of relying on custom helpers logic.

2024-03-12 11:08 UTC, t-jankowski requested changes

2024-03-13 11:55 UTC, t-jankowski commented on src/core/tests/element_iterator_test.cpp
> +TEST(ElementIteratorTest, read_u1_from_tensor) {
These test names seem to be switched.

2024-03-13 12:21 UTC, t-jankowski approved these changes

2024-03-18 08:46 UTC, merged