[CPU] Add PagedAttention support
openvinotoolkit/openvino pull request #23524
Opened 2024-03-19 01:12 UTC by luo-cheng2021

### Details:
 - *Support PagedAttention support*
    - depends on https://github.com/openvinotoolkit/openvino_contrib/pull/867

### Tickets:
 - *[134329](https://jira.devtools.intel.com/browse/CVS-134329)*
 - *[134327](https://jira.devtools.intel.com/browse/CVS-134327)*

2024-03-19 07:39 UTC, usstq reviewed
Can we split page attention code into a separate CPU node? although `PageAttention`  share some underlying kernels with `ScaledDotProductAttention` , but the definition of the Node deserve a separate Node type, just for more maintainability.

2024-03-20 08:32 UTC, usstq approved these changes
approve and looking forward to refactor later, great works!

2024-03-20 08:38 UTC, luo-cheng2021 commented on src/plugins/intel_cpu/src/cpu_types.cpp
> +        {"PagedAttentionExtension", Type::ScaledDotProductAttention},
Will do the refactor in the next PR, ticket: [136170](https://jira.devtools.intel.com/browse/CVS-136170)

2024-03-20 08:38 UTC, luo-cheng2021 commented on src/plugins/intel_cpu/src/graph.cpp
> +                    (inPort == 3 || inPort == 4))
Will do the refactor in the next PR, ticket: [136170](https://jira.devtools.intel.com/browse/CVS-136170)

2024-03-20 08:52 UTC, luo-cheng2021 commented on src/plugins/intel_cpu/src/graph.cpp
> +                    (inPort == 3 || inPort == 4))
> another tricky thing is, there seems to be another ways to keep original precision, which is to reject/ignore `getOriginalInputPrecision()` inside `initSupportedPrimitiveDescriptors()`, just report `fp32` in PortConfigurator description

In [line](https://github.com/openvinotoolkit/openvino/blob/67803b691cbabf00488faa4ebe50ceb745356779/src/plugins/intel_cpu/src/graph.cpp#L1720) the original precision will be changed, so `getOriginalInputPrecision()` will not work.

2024-03-20 13:11 UTC, ilya-lavrenov requested changes
Double checked - cache_dtype=float16 does not work and generates invalid output

2024-03-21 02:55 UTC, luo-cheng2021 commented
> Double checked - cache_dtype=float16 does not work and generates invalid output

Could you please try again using the latest version?

2024-03-21 07:26 UTC, ilya-lavrenov approved these changes
Passed with fp16 KV cache

2024-03-21 07:27 UTC, dmitry-gorokhov approved these changes

2024-03-21 07:33 UTC, merged