[TF FE] Support TensorFlow 2.16
openvinotoolkit/openvino pull request #23562
Opened 2024-03-20 08:13 UTC by rkazants

**Details:** Support TensorFlow 2.16

**Ticket:** TBD

2024-03-20 08:21 UTC, p-wysocki approved these changes

2024-03-20 09:03 UTC, gkrivor approved these changes

2024-03-20 09:04 UTC, jiwaszki requested changes
I am only "blocking" this with regards to CVS-134093

@rafalstaroszczyk1 @RaguzovaTatyana would the issue be reproducible again with this change?

2024-03-20 09:27 UTC, jiwaszki approved these changes

2024-03-20 10:05 UTC, rkazants commented
Due to this limitation, we have failures for Notebook tests: https://github.com/tensorflow/hub/issues/903

2024-03-20 12:47 UTC, akuporos approved these changes

2024-03-21 12:58 UTC, rkazants commented
> Due to this limitation, we have failures for Notebook tests: [tensorflow/hub#903](https://github.com/tensorflow/hub/issues/903)

Possible temporal WA, just don't loose a link: https://github.com/tensorflow/tensorflow/issues/63849

2024-03-21 21:46 UTC, merged