New files for checking GFI#20927
openvinotoolkit/openvino pull request #23586
Opened 2024-03-20 16:51 UTC by krish1209

I have added a sample new file for the AveragePooling.cpp and MaxPooling.cpp
Created a pull request to know if the code is correct or not (i tried :) )

The files are named as: Avgpool_check.cpp and maxpool_check.cpp 
Path: src/frontends/pytorch/src/op/Avgpool_check.cpp
         src/frontends/pytorch/src/op/maxpool_check.cpp

2024-03-20 17:24 UTC, mvafin requested changes
Please do not create new files for these operations, rather update old files

2024-03-20 17:24 UTC, mvafin commented on src/frontends/pytorch/src/op/Avgpool_check.cpp
> +    auto res = context.mark_node(std::make_shared<v8::AvgPool>(input, // Changed to AvgPool
I don't see how you reshape `input` to support `CHW` and `NCHW` cases.

2024-03-20 17:27 UTC, krish1209 commented
Okay I'll update the old files and update the PR. Sorry for the inconvenience.

2024-03-21 10:47 UTC, mvafin commented
please also add tests for this functionality and verify that your code works

2024-03-21 17:04 UTC, krish1209 commented
I am currently facing an "IncludePath" error even after adding the location of the header files so it is taking a little time to debug the same. onnx_pb.h is a file my system is unable to find. I'll get back as soon as possible after solving the error.

Also is it possible for you to guide me a little bit on how i can make a custom test case in the code base for these operations? It would be really helpful.

2024-03-29 16:11 UTC, krish1209 commented
Hello Sir, I apologize for the absence. I got my head into a Research Paper based project for publishing, so couldn't find the time.
Is it possible for you to mention what all needs to be done in the markdown comment in order to merge this pull request in the main branch. Thank you. I will get at it as soon as possible :)

2024-04-07 15:52 UTC, krish1209 commented
Can anyone provide an update so that I could be clarified the work I have to do. Thank you :)

2024-04-08 09:51 UTC, mvafin commented
> Hello Sir, I apologize for the absence. I got my head into a Research Paper based project for publishing, so couldn't find the time. Is it possible for you to mention what all needs to be done in the markdown comment in order to merge this pull request in the main branch. Thank you. I will get at it as soon as possible :)

- Write tests for pooling with no batch
- Run your code and identify if all cases work
- Fix issues and make sure that tests pass

2024-04-15 07:39 UTC, krish1209 commented
Okay. Thank you for replying :). I will get on it as soon as possible.

2024-05-07 10:48 UTC, closed without merging