[ONNX] WA for I64 images
openvinotoolkit/openvino pull request #2411
Opened 2020-09-24 13:23 UTC by jiwaszki

Workaround to use CPU backend which currently does not support I64 images.

2020-09-25 11:36 UTC, slyalin commented on ngraph/python/tests/runtime.py
> +                    dataptr.precision = "I32"
Why do we need this part with all layers?

2020-09-28 11:19 UTC, postrational requested changes

2020-09-28 11:19 UTC, postrational commented on ngraph/python/tests/runtime.py
> +        for cnn_input in cnn_network.input_info:
Please move this code to a helper function.

2020-10-07 10:13 UTC, postrational approved these changes

2020-10-22 08:52 UTC, tsocha approved these changes

2020-10-22 12:06 UTC, merged