[TFL FE]: gelu: fix issue when approximate is not specified
openvinotoolkit/openvino pull request #24356
Opened 2024-05-03 01:27 UTC by keyonjie

Sometimes the approximate attribute is not specified in the .tflite file, we need to check its availability before retriving it, otherwise we might hit the 'Check 'opts != nullptr' failed' failure with calling get_attribute() directly.

2024-05-03 06:41 UTC, rkazants reviewed
please share a model to check on our side.

2024-05-03 06:42 UTC, rkazants requested changes
need validation on our side because the preliminary PR was buggy

2024-05-03 18:40 UTC, keyonjie commented
> Why is this issue not caught initially? please share a model to check on our side.

Hi @rkazants , the issue was not caught, as no matter with tf.keras.activations.gelu or tf.keras.ops.gelu or tf.nn.gelu, there is always this 'approximate' attribute in the generated .tflite file. In case the attribute is listed in the .tflite model file, I had verified frontend works in both 'true' and 'false' cases.
![image](https://github.com/openvinotoolkit/openvino/assets/10458135/d463e610-843b-4091-af66-8c9c8ef70492)


But during recent debugging with a customer model, I found that the 'approximate' attribute of the 'gelu' layer is not listed at all, and when using our FE to convert it, we are hitting issue 'Check 'opts != nullptr' failed' failure with calling get_attribute() directly, as mentioned in the commit message.

I am querying the customer about how they generated the gelu layer and the model file there, and then I can try to generate one similar model and share it here, but basically if you open it with netron.app and the gelu ops info looks like this:
![image](https://github.com/openvinotoolkit/openvino/assets/10458135/fc06af84-5fd5-4f8b-8e9c-121cee050db8)

2024-05-20 21:59 UTC, keyonjie commented
Hi @rkazants I have rebased/reimplemented the fix to the latest base and verified it works for all 3 use cases: attribute 'approximate' = true, 'approximate' = false, and no 'approximate' attribute in the .tflite files.

Please help review it, thanks.

2024-05-21 02:14 UTC, rkazants approved these changes

2024-05-21 02:14 UTC, rkazants commented
build_jenkins

2024-05-21 11:11 UTC, merged