[VPU][IE] Disable ConvertMinimum transformation for Myriad Plugin
openvinotoolkit/openvino pull request #2437
Opened 2020-09-28 09:37 UTC by AndrewBakalinIntel

Ticket - #-38650

2020-10-01 07:18 UTC, AndrewBakalinIntel commented
@elatkin @andrejsokolov could you please take a look?
@ilyachur could  you please take a look at the common part? I don't think it's  actually needed to prohibit the creation of Eltwise Minimum because some of the plugins may really want to receive the Minimum layer instead of its decomposition.

2020-10-01 09:41 UTC, elatkin requested changes
@AndrewBakalinIntel 
Could you please rebase your branch on fresh OpenVINO/master?
IE-MDK crashes on LSTMCell, maybe needs #2423 merged recently

2020-10-01 13:04 UTC, AndrewBakalinIntel commented
> @AndrewBakalinIntel
> Could you please rebase your branch on fresh OpenVINO/master?
> IE-MDK crashes on LSTMCell, maybe needs #2423 merged recently

Thanks! Done.

2020-10-02 10:11 UTC, elatkin approved these changes

2020-10-05 08:21 UTC, AndrewBakalinIntel commented
@andrejsokolov @ilyachur ping

2020-10-05 10:05 UTC, ilyachur approved these changes
LGTM

2020-10-05 11:18 UTC, merged