[NPU]Change Npu-plugin log for the behavior of NPU dry on execution path
openvinotoolkit/openvino pull request #24731
Opened 2024-05-28 07:33 UTC by DAN2Liu

### Details:
 - *To update the confusing log in NPU dry on execution path*
 - *...*

### Tickets:
 - *E-83001*

2024-05-29 12:57 UTC, alpkn requested changes
The goal of the ticket [EISW-83001](https://jira.devtools.intel.com/browse/EISW-83001) is to find out a way to alter the execution in such a way that the plugin does not try to initialize backends in case if it does not need to.

For the compilation plugin does not need to initialize level zero backend.
No warning or error messages should appear on the screen therefore if only compilation (and no interaction with NPU device) is requested.
It is stated in the ticket description as well.

2024-06-06 06:10 UTC, DAN2Liu commented
> compilation plugin does not need to initialize level zero backend.

From the log of compile_tool, it seems that compilation does not require initializing zero backend and it can still work.
However, from the perspective of the complete compilation process of the code, **_the constructor of the NPU `Plugin` needs to initialize the backend , and use the backend to handle properties of plugin and device. If the backend is not initialized in the NPU `Plugin`, an error will be reported before the `Plugin.compile_model()` ( the part of the plugin that actually completes the compilation) is [called](https://github.com/openvinotoolkit/openvino/blob/master/src/inference/src/dev/core_impl.cpp#L745), and the compilation will be return failure._** So the initialization of the backend cannot be removed.

Currently, the backend need to be initialized at compilation time, but the executor in the CompiledModel it is not mandatory, and the[ initialize of executor](https://github.com/openvinotoolkit/openvino/blob/master/src/plugins/intel_npu/src/plugin/src/compiled_model.cpp#L344) can be skipped by passing configuration.

Therefore, there is nothing can be removed components and in the backend constructor, when the Zerobackend initialization fails, the old log is unreasonable, so the log is adjusted.
Could you please review it again?

2024-06-07 02:04 UTC, XinWangIntel commented
build_jenkins

2024-06-14 05:12 UTC, DanLiu2Intel commented
Test results has attached to [here](https://jira.devtools.intel.com/browse/EISW-83001)

2024-07-24 00:20 UTC, closed without merging