[GSOC][CPU][ARM] Activate SDPA Fusion on ARM
openvinotoolkit/openvino pull request #24919
Opened 2024-06-10 06:55 UTC by mory91

### Details:
 - This PR enables the SDPA Fusion on ARM devices

2024-06-20 09:18 UTC, maxnick approved these changes

2024-06-20 09:31 UTC, maxnick requested changes
We need to enable dedicated subgraph tests on ARM platform.

2024-06-24 05:27 UTC, dmitry-gorokhov commented
build_jenkins

2024-06-24 08:06 UTC, maxnick approved these changes

2024-06-24 10:24 UTC, merged