[OV JS] Parameters validation, templates approach
openvinotoolkit/openvino pull request #24921
Opened 2024-06-10 08:25 UTC by vishniakov-nikolai

### Details:
 - Validate input parameters of JS binding methods using template approach

### Tickets:
 - 137672

Based on: https://github.com/almilosz/openvino/tree/almilosz/arg_val

2024-06-13 11:18 UTC, t-jankowski requested changes

2024-06-13 11:18 UTC, t-jankowski commented on src/bindings/js/node/include/type_validation.hpp
> +};
```suggestion
template <typename Arg, typename... Args>
std::vector<std::string> get_signature() {
    auto attributes = get_signature<Arg>();
    // pseudo code
    attributes.append(get_signature<Args...>());
    return attributes;
};
```

2024-06-13 14:47 UTC, vishniakov-nikolai commented on src/bindings/js/node/include/type_validation.hpp
> +    throw std::runtime_error("get_attr_type 123 is not implemented for passed type!");
It leads to error:
![image](https://github.com/openvinotoolkit/openvino/assets/72441332/2d854664-7c3b-4495-a620-07be6fd770f3)

2024-06-14 13:36 UTC, vishniakov-nikolai commented on src/bindings/js/node/include/type_validation.hpp
> +    throw std::runtime_error("get_attr_type 123 is not implemented for passed type!");
Fixed

2024-06-14 13:36 UTC, vishniakov-nikolai commented on src/bindings/js/node/include/type_validation.hpp
> +namespace NapiTypename {
Fixed

2024-06-17 08:23 UTC, t-jankowski requested changes

2024-06-17 08:23 UTC, t-jankowski commented on src/bindings/js/node/include/type_validation.hpp
> +static const char BUFFER[] = "Buffer";
Move the definition to cpp file. I think these are not needed in hpp.

2024-06-17 08:23 UTC, t-jankowski commented on src/bindings/js/node/include/type_validation.hpp
> +    throw std::runtime_error("Validation for this type is not implemented!");
It looks `static_assert` doesn't work everywhere, then let's keep the runtime solution.

2024-06-17 08:23 UTC, t-jankowski commented on src/bindings/js/node/include/type_validation.hpp
> +    throw std::runtime_error("get_attr_type 123 is not implemented for passed type!");
So let's keep the runtime solution.

2024-06-18 08:07 UTC, t-jankowski approved these changes

2024-06-18 10:27 UTC, praasz approved these changes

2024-06-18 10:27 UTC, praasz commented on src/bindings/js/node/include/type_validation.hpp
> +bool validate(const Napi::CallbackInfo& info, std::vector<std::string>& checked_signatures) {
```suggestion
bool validate(const Napi::CallbackInfo& info, std::vector<std::string>& allowed_signatures) {
```

2024-06-18 10:27 UTC, praasz commented on src/bindings/js/node/src/core_wrap.cpp
> +            std::string error_message = ov::js::get_parameters_error_msg(info, checked_signatures);
```suggestion
            const auto error_message = ov::js::get_parameters_error_msg(info, checked_signatures);
```

2024-06-18 10:27 UTC, praasz commented on src/bindings/js/node/include/type_validation.hpp
> +    throw std::runtime_error("Validation for this type is not implemented!");
Use OPENVINO_THROW ?

2024-06-18 10:27 UTC, praasz commented on src/bindings/js/node/include/type_validation.hpp
> +    throw std::runtime_error("get_attr_type is not implemented for passed type!");
```suggestion
    OPENVINO_THROW("get_attr_type is not implemented for passed type!");
```
?

2024-06-18 14:18 UTC, vishniakov-nikolai commented
@praasz thank you for detailed review, I implemented the most suggestions that we've discussed

2024-06-19 06:53 UTC, praasz commented on src/bindings/js/node/include/type_validation.hpp
> +    allowed_signatures.push_back(signature_attributes);
```suggestion
    allowed_signatures.push_back(get_signature<Ts...>());
```
or 
```suggestion
    auto signature_attributes = get_signature<Ts...>();
    allowed_signatures.push_back(std::move(signature_attributes));
```

2024-06-19 14:38 UTC, merged