[core] Constant strides can be get from bounds tensor
openvinotoolkit/openvino pull request #24992
Opened 2024-06-13 04:26 UTC by praasz

### Details:
 - The strides of Constant  data can be get as strides of lower or upper bound tensor from output tensor descriptor:
   `Constant::get_output_tensor(0).get_lower_value().get_strides()`
   The upper and lower bound of Constant are set on creation as tensor view on existing data.
 - Get strides will throw exception when Constant has got  low precision data like: `u1, u2, u3, ...` etc.,  tensor not support strides for these types.
 - Update evaluate bounds  utils functions to skip Constant as bounds are set. There is no need to do Constant data copy to temporary bounds tensors.

### Tickets:
 - [CVS-143575](https://jira.devtools.intel.com/browse/CVS-143575)

2024-06-13 07:18 UTC, ilya-lavrenov approved these changes

2024-06-19 10:22 UTC, jane-intel reviewed
Can we provide `Constant::get_tensor` or `Constant::get_stride` to solve the issue?
Why did we choose to incorporate it in partial value propagation?

2024-06-19 13:24 UTC, slyalin requested changes
I find it strange to workaround missing methods in Constant class with re-use of the value bound functionality. Why not to add the required methods in Constant itself? You still need to verify that you are working with Constant node first before getting strides (otherwise they are useless, because bound tensor values are not connected to a specific constant). So the natural approach is to extend Constant node.

2024-06-20 14:38 UTC, praasz commented
> I find it strange to workaround missing methods in Constant class with re-use of the value bound functionality. Why not to add the required methods in Constant itself? You still need to verify that you are working with Constant node first before getting strides (otherwise they are useless, because bound tensor values are not connected to a specific constant). So the natural approach is to extend Constant node.

I've added dedicated members to Constant.

@jane-intel 
Changes related partial value evaluation will move to other PR to not mix it with get strides, it can be useful as will remove not necessary data copy and evaluation should be faster.

2024-06-21 06:05 UTC, jane-intel approved these changes
Thank you, this looks good!

2024-06-21 06:17 UTC, jane-intel commented on src/core/src/op/constant.cpp
> +    }
```suggestion
```

2024-06-21 06:20 UTC, jane-intel commented on src/core/tests/constant.cpp
> +              Strides({element::f8e4m3.size()}));
```suggestion
```

2024-06-21 06:20 UTC, jane-intel commented on src/core/tests/constant.cpp
> +              Strides({element::f8e5m2.size()}));
```suggestion
```

2024-06-21 13:59 UTC, merged