[properties] Extending PCIInfo struct with product ID field
openvinotoolkit/openvino pull request #25147
Opened 2024-06-20 11:24 UTC by csoka

### Details:
- PCIInfo structure's device ID field was previously falsely believed to refer to product ID (for identification of device model), but it actually stores pci endpoint ID of the device in the system, therefore the implemented feature does not address the feature-request (PCIInfo to contain product id) PR #24111 
- This PR extends PCIInfo structure with additional field to include product ID as well

### Tickets:
 - [*CVS-138767*](https://jira.devtools.intel.com/browse/CVS-138767)

2024-06-20 11:36 UTC, p-wysocki commented on src/bindings/python/src/pyopenvino/core/properties/properties.cpp
> +    cls_pciinfo.def(py::init<const uint32_t&, const uint32_t&, const uint32_t&, const uint32_t&, const uint32_t&>());
Won't adding a new `init` argument with no default value break existing scripts? PyAPI needs to follow strict backwards compatibility rules. Is it possible to have a placeholder value here?

2024-06-20 11:43 UTC, t-jankowski requested changes

2024-06-20 11:43 UTC, t-jankowski commented on src/bindings/python/src/pyopenvino/core/properties/properties.cpp
> +    cls_pciinfo.def_readonly("function", &ov::device::PCIInfo::product);
```suggestion
    cls_pciinfo.def_readonly("product", &ov::device::PCIInfo::product);
```

2024-06-20 14:50 UTC, p-wysocki commented on src/bindings/python/src/pyopenvino/core/properties/properties.cpp
> +    cls_pciinfo.def(py::init<const uint32_t&, const uint32_t&, const uint32_t&, const uint32_t&, const uint32_t&>());
True, I just wanted to make sure we're aware about this. :)

2024-07-29 11:11 UTC, ilya-lavrenov commented on src/inference/include/openvino/runtime/properties.hpp
> +    uint32_t product;
@vladimir-paramuzov is this field applicable for GPU?

2024-08-25 00:22 UTC, closed without merging