[MO][Kaldi] Add Statistics Extracting and Pooling components
openvinotoolkit/openvino pull request #2517
Opened 2020-10-02 12:48 UTC by pavel-esir

Added support of Kaldi statistics extracting and pooling components

ticket #22512

2020-10-09 09:13 UTC, lazarevevgeny requested changes

2020-10-09 09:13 UTC, lazarevevgeny commented on model-optimizer/extensions/ops/statistics.py
> +
enabled = False

2020-10-09 09:13 UTC, lazarevevgeny commented on model-optimizer/extensions/ops/statistics.py
> +
enabled = False

2020-10-09 09:13 UTC, lazarevevgeny commented on model-optimizer/extensions/ops/statistics.py
> +    op = 'statisticsextractioncomponent'
Please, add some comments about this operation and what MO does with it. 

The same comment for the operation below.

2020-10-09 09:13 UTC, lazarevevgeny commented on model-optimizer/extensions/front/kaldi/replace_stats_extract_pool.py
> +    enabled = True
Provide explanation of the transformation.

2020-10-09 09:13 UTC, lazarevevgeny commented on model-optimizer/extensions/front/kaldi/replace_stats_extract_pool.py
> +
remove redundant empty line

2021-05-18 08:05 UTC, pavel-esir commented
Closing, @sadolini is finishing these changes on her fork

2021-05-18 08:05 UTC, closed without merging