Add hsigmoid op
openvinotoolkit/openvino pull request #2531
Opened 2020-10-05 09:06 UTC by iimironov

2020-10-05 11:16 UTC, ilyachur reviewed
Could you add a tests for this operation?

@iimironov Please the measure impact from evaluate method on nGraph binary size.

2020-10-06 20:05 UTC, lazarevevgeny requested changes
Please, fix the code style.

2020-10-06 20:05 UTC, lazarevevgeny commented on ngraph/core/include/ngraph/opsets/opset5_tbl.hpp
> +NGRAPH_OP(HSigmoid, ngraph::op::v5)
Please, insert the op in the sorted name order to the section with opset5 ops.

2020-10-06 20:07 UTC, lazarevevgeny commented
We also need fusing transformations and tests for them.

2020-10-09 09:21 UTC, lazarevevgeny commented
@iimironov , have you measured the impact on binary size requested by @ilyachur ?

2020-10-09 14:25 UTC, iimironov commented
> Could you add a tests for this operation?
> 
> @iimironov Please the measure impact from evaluate method on nGraph binary size.


With hsigmid
-rwxr-xr-x 1 imironov inn_avc_ocl_qa  19078424 Oct  9 16:24 libngraph_backend.so
-rw-r--r-- 1 imironov inn_avc_ocl_qa  15492478 Oct  9 16:21 libngraph_builders.a
-rw-r--r-- 1 imironov inn_avc_ocl_qa 109895866 Oct  9 16:28 libngraphFunctions.a
-rw-r--r-- 1 imironov inn_avc_ocl_qa   2947466 Oct  7 12:26 libngraph_reference.a
-rwxr-xr-x 1 imironov inn_avc_ocl_qa  98444624 Oct  9 16:23 libngraph.so
-rw-r--r-- 1 imironov inn_avc_ocl_qa  10800876 Oct  9 16:25 libngraph_test_util.a

Without hsigmoid
-rwxr-xr-x 1 imironov inn_avc_ocl_qa  19078424 Oct  9 16:57 libngraph_backend.so
-rw-r--r-- 1 imironov inn_avc_ocl_qa  15492478 Oct  9 16:54 libngraph_builders.a
-rw-r--r-- 1 imironov inn_avc_ocl_qa 109893690 Oct  9 16:59 libngraphFunctions.a
-rw-r--r-- 1 imironov inn_avc_ocl_qa   2947466 Oct  7 12:26 libngraph_reference.a
-rwxr-xr-x 1 imironov inn_avc_ocl_qa  98212584 Oct  9 16:56 libngraph.so
-rw-r--r-- 1 imironov inn_avc_ocl_qa  10800876 Oct  9 16:58 libngraph_test_util.a

2020-10-09 14:41 UTC, lazarevevgeny commented
> > Could you add a tests for this operation?
> > @iimironov Please the measure impact from evaluate method on nGraph binary size.
> 
> With hsigmid
> -rwxr-xr-x 1 imironov inn_avc_ocl_qa 19078424 Oct 9 16:24 libngraph_backend.so
> -rw-r--r-- 1 imironov inn_avc_ocl_qa 15492478 Oct 9 16:21 libngraph_builders.a
> -rw-r--r-- 1 imironov inn_avc_ocl_qa 109895866 Oct 9 16:28 libngraphFunctions.a
> -rw-r--r-- 1 imironov inn_avc_ocl_qa 2947466 Oct 7 12:26 libngraph_reference.a
> -rwxr-xr-x 1 imironov inn_avc_ocl_qa 98444624 Oct 9 16:23 libngraph.so
> -rw-r--r-- 1 imironov inn_avc_ocl_qa 10800876 Oct 9 16:25 libngraph_test_util.a
> 
> Without hsigmoid
> -rwxr-xr-x 1 imironov inn_avc_ocl_qa 19078424 Oct 9 16:57 libngraph_backend.so
> -rw-r--r-- 1 imironov inn_avc_ocl_qa 15492478 Oct 9 16:54 libngraph_builders.a
> -rw-r--r-- 1 imironov inn_avc_ocl_qa 109893690 Oct 9 16:59 libngraphFunctions.a
> -rw-r--r-- 1 imironov inn_avc_ocl_qa 2947466 Oct 7 12:26 libngraph_reference.a
> -rwxr-xr-x 1 imironov inn_avc_ocl_qa 98212584 Oct 9 16:56 libngraph.so
> -rw-r--r-- 1 imironov inn_avc_ocl_qa 10800876 Oct 9 16:58 libngraph_test_util.a

I have a doubt that a simple reference implementation function resulted in 200K+ file size change. Did you remove just the evaluate method and everything related to it?

2020-10-09 18:34 UTC, iimironov commented
> evaluate

with  evaluate
98444624 libngraph.so

without  evaluate
98423864 libngraph.so

diff 20 760

2020-10-12 11:12 UTC, lazarevevgeny commented
@iimironov, the OpenVINO-ONNX fails because of the following error: "src/ngraph/opset5/ops.py:68:77: W292 no newline at end of file"

Please, fix.

2020-10-12 11:33 UTC, iimironov commented
> @iimironov, the OpenVINO-ONNX fails because of the following error: "src/ngraph/opset5/ops.py:68:77: W292 no newline at end of file"
> 
> Please, fix.

Fixed

2020-10-12 15:08 UTC, lazarevevgeny commented
@iimironov , please, merge changes from master branch. Otherwise you will not be able to pass the pre-commit.

2020-10-12 15:10 UTC, lazarevevgeny commented on inference-engine/src/transformations/src/transformations/hsigmoid_fusion.cpp
> +// Copyright (C) 2018-2020 Intel Corporation
We need also a decomposition transformation for HSigmoid for the plugins which do not support HSigmoid directly. For now it must be enabled for all plugins.

2020-10-15 11:45 UTC, lazarevevgeny commented on ngraph/core/include/ngraph/opsets/opset5_tbl.hpp
> +NGRAPH_OP(NonMaxSuppression, ngraph::op::v5)
Please, revert this change.

2020-10-16 04:10 UTC, ilyachur reviewed
Looks like the description of this PR isn't consistent with content. Am I not right?

2020-10-16 07:44 UTC, iimironov commented
> Looks like the description of this PR isn't consistent with content. Am I not right?

We separated this PR on two. One content only ngraph op and other content transformations and python api.
This PR contain  transformations and python api.

2020-10-21 10:56 UTC, ilyachur commented on inference-engine/src/transformations/include/transformations/common_optimizations/hsigmoid_fusion.hpp
> +class TRANSFORMATIONS_API HSigmoidFusionWithReluDiv;
Why do we need to export all matchers if we use only `HSigmoidFusion` class in other libraries?

I propose to export only `HSigmoidFusion`.

2020-10-21 10:56 UTC, ilyachur commented on inference-engine/src/transformations/include/transformations/common_optimizations/hsigmoid_fusion.hpp
> +class ngraph::pass::HSigmoidFusionWithReluDiv: public ngraph::pass::MatcherPass {
Also if you move constructor of  `HSigmoidFusion` class to cpp we can hide (move to cpp) all matcher passes.

2020-10-21 14:06 UTC, GlebKazantaev requested changes

2020-10-21 14:06 UTC, GlebKazantaev commented on inference-engine/src/transformations/src/transformations/common_optimizations/hsigmoid_fusion.cpp
> +ngraph::pass::HSigmoidFusion::HSigmoidFusion() {
Please move it to hpp file as we do in other transformations

2020-10-21 14:06 UTC, GlebKazantaev commented on inference-engine/src/transformations/src/transformations/op_conversions/hsigmoid_decomposition.cpp
> +        if (m_transformation_callback(hsigmoid_node)) {
Do we have plugins that disable this pass by condition?

2020-10-21 14:06 UTC, GlebKazantaev commented on inference-engine/src/transformations/src/transformations/op_conversions/hsigmoid_decomposition.cpp
> +        auto hsigmoid_node = pattern_to_output.at(hsigmoid).get_node_shared_ptr();
Just use `m.get_match_root()` here

2020-10-21 14:06 UTC, GlebKazantaev commented on inference-engine/src/transformations/src/transformations/op_conversions/hsigmoid_decomposition.cpp
> +        mul->set_friendly_name(m.get_match_root()->get_friendly_name());
```suggestion
        mul->set_friendly_name(hsigmoid->get_friendly_name());
```

2020-10-21 14:06 UTC, GlebKazantaev commented on inference-engine/src/transformations/src/transformations/op_conversions/hsigmoid_decomposition.cpp
> +        ngraph::replace_node(m.get_match_root(), mul);
```suggestion
        ngraph::replace_node(hsigmoid, mul);
```

2020-10-21 14:06 UTC, GlebKazantaev commented on inference-engine/tests/functional/inference_engine/transformations/hsigmoid_decomposition_test.cpp
> +        auto input = std::make_shared<ngraph::opset5::Parameter>(ngraph::element::f16, ngraph::PartialShape::dynamic(1));
Why you have f16 type for reference net?

2020-10-23 07:23 UTC, ilyachur approved these changes

2020-10-23 08:10 UTC, GlebKazantaev approved these changes

2020-10-23 09:35 UTC, lazarevevgeny approved these changes

2020-10-23 09:35 UTC, merged