Symbol: operator+; operator-;
openvinotoolkit/openvino pull request #25360
Opened 2024-07-03 12:46 UTC by jane-intel

### Details:
 - *Introduces operator+ and operator- for ov::Symbol*
 - *Uses introduced operators in `Add::evaluate_symbol`, `Subtract::evaluate_symbol` and shape_infer of Range operation*

Significantly reduces the number of unique symbols in models, allowing better optimization of ShapeOf subgraphs in dynamic models.

### Tickets:
 - *CVS-112292*

2024-07-03 13:01 UTC, akuporos commented on src/bindings/python/src/pyopenvino/graph/symbol.cpp
> +
Please also add/extend tests [here](https://github.com/openvinotoolkit/openvino/blob/master/src/bindings/python/tests/test_runtime/test_dimension.py#L96-L97)

2024-07-09 09:02 UTC, jane-intel commented on src/core/include/openvino/core/symbol.hpp
> +}  // namespace std
to be removed from std namespace

2024-07-09 09:29 UTC, akuporos approved these changes

2024-07-09 09:56 UTC, praasz approved these changes

2024-07-09 09:56 UTC, praasz commented on src/core/tests/symbol.cpp
> +using namespace ov;
```suggestion
namespace ov {
namespace test {
```
Consider wrap test in this namespace, then using `ov::` would not be required and I think `using std` is also not required.

2024-07-09 09:56 UTC, praasz commented on src/core/src/op/subtract.cpp
> +               rhs_pshape = input(1).get_tensor().get_partial_shape();
```suggestion
               &rhs_pshape = input(1).get_tensor().get_partial_shape();
```
?
currently the `rhs_pshape` is not a reference.

2024-08-07 14:01 UTC, rkazants requested changes
TF layer test fails. Need to check

2024-08-07 14:21 UTC, rkazants commented
Re-run does not help. The same test is failing:
FAILED install\tests\layer_tests\tensorflow_tests\test_tf_HSVToRGB.py::TestHSVToRGB::test_hsv_to_rgb_basic[ ie_device:CPU - precision:FP16 - params:{'input_shape': [7, 7, 3], 'input_type': <class 'numpy.float32'>, 'special_case': 'Black Image'} ]
FAILED install\tests\layer_tests\tensorflow_tests\test_tf_HSVToRGB.py::TestHSVToRGB::test_hsv_to_rgb_basic[ ie_device:CPU - precision:FP16 - params:{'input_shape': [7, 7, 3], 'input_type': <class 'numpy.float32'>, 'special_case': 'Grayscale Image'} ]
FAILED install\tests\layer_tests\tensorflow_tests\test_tf_HSVToRGB.py::TestHSVToRGB::test_hsv_to_rgb_basic[ ie_device:CPU - precision:FP16 - params:{'input_shape': [3, 4, 13, 15, 3], 'input_type': <class 'numpy.float64'>} ]
FAILED install\tests\layer_tests\tensorflow_tests\test_tf_HSVToRGB.py::TestHSVToRGB::test_hsv_to_rgb_basic[ ie_device:CPU - precision:FP16 - params:{'input_shape': [5, 23, 27, 3], 'input_type': <class 'numpy.float64'>} ]
FAILED install\tests\layer_tests\tensorflow_tests\test_tf_HSVToRGB.py::TestHSVToRGB::test_hsv_to_rgb_basic[ ie_device:CPU - precision:FP16 - params:{'input_shape': [5, 5, 3], 'input_type': <class 'numpy.float32'>} ]
= 5 failed, 2454 passed, 35 skipped, 19 xfailed, 1 xpassed, 40 warnings in 464.21s (0:07:44) =

Also, PR can be guilty because decomposition for HSVToRGB uses Add, Subtract operations.

2024-08-13 14:40 UTC, itikhono commented
the issues with ONNX models are sporadic, passed after several re-runs and rebase.
the issues with TF models (test_tf_HSVToRGB) are not reproduced on ubuntu,  I'm trying to reproduce them on Windows

2024-08-13 14:53 UTC, rkazants commented
> the issues with ONNX models are sporadic, the tests passed after several re-runs and rebase. the issues with TF models (test_tf_HSVToRGB) are not reproduced on ubuntu, I'm trying to reproduce them on Windows

@itikhono, @mlukasze 
Please don't re-run. It does not help. Failure on Windows is permanently reproduced. It needs to be fixed in this PR.

2024-08-13 20:02 UTC, mlukasze commented
roger, roger

2024-08-14 12:06 UTC, itikhono commented
the issue was reproduced on Windows, it looks like it's related to the hash calculation, investigating.

2024-08-15 10:24 UTC, itikhono commented on src/core/src/symbol.cpp
> +using MathMap = std::unordered_map<WeakSymbolVector, WeakSymbol, WeakSymbolVectorHash>;
```suggestion
using MathMap = std::map<WeakSymbolVector, WeakSymbol>;
```

2024-08-15 10:24 UTC, itikhono commented on src/core/src/symbol.cpp
> +#include <queue>
```suggestion
#include <queue>
#include <map>
```

2024-08-15 10:34 UTC, itikhono commented on src/core/src/symbol.cpp
> +#include <map>
```suggestion
#include <map>
#include <queue>
```

2024-08-15 12:45 UTC, itikhono commented
the issue is caused by the hash calculation algo:
![image](https://github.com/user-attachments/assets/9e5ba6b0-b223-4034-9046-a42c04522b97)
this calculations might give us different results depends on the weak_ptrs are alive or not. 
If we try to use unordered_map with a key which might have different hash, it might cause seg fault.
So I replaced unordered_map with map. It doesn't rely on the hash function, and uses the overload < operator. 
We will be able to merge this PR after that.
 
But why weak_ptrs are expired is an another question. 
Most probably this is something similar to the issue fixed in this commit https://github.com/openvinotoolkit/openvino/pull/25360/commits/ef94d8cd6cb10ff8a4c9ecaf4d8c3ad686a9f556

2024-08-15 15:04 UTC, rkazants approved these changes

2024-08-15 17:59 UTC, merged