[CPU] Avoid rounding to zero if there is post ops fusing
openvinotoolkit/openvino pull request #25483
Opened 2024-07-10 09:17 UTC by xuchen-intel

### Details:
 - *vdivps instruction rounds to the nearest value by default. https://github.com/openvinotoolkit/openvino/pull/25217 applied rounding towards zero, to align behavior with other Plugins/Frameworks. However such behavior should be avoided if there is post ops fusing. Because for such cases, the results vdivps provide are only intermediate results.*
 - *Test cases will be added in separate PR.*

### Tickets:
 - *[CVS-146321](https://jira.devtools.intel.com/browse/CVS-146321)*

2024-07-10 09:17 UTC, xuchen-intel commented
@dmitry-gorokhov Hi Dmitry, could you please take a look? Thanks!

2024-07-10 11:24 UTC, dmitry-gorokhov requested changes
@xuchen-intel Maybe I missed smt but vdivps is floating point division instruction which shouldn't do any rounding.  I believe real rounding should happen during fp32 to int8 conversion right before result storage to dst. Is it correct? 
So I would expect we should do rounding right before this conversion and we should do w.o dependecy on fused post-ops. 

BTW why it is expected to have rounding towards zero in integer ReduceMean op?  Is it specified somewhere?

2024-07-10 14:14 UTC, dmitry-gorokhov commented
@xuchen-intel Original commit is reverted: https://github.com/openvinotoolkit/openvino/pull/25487. Lets push fixed solution in bounds of this PR + tests

2024-07-11 08:02 UTC, xuchen-intel commented
> @xuchen-intel Maybe I missed smt but vdivps is floating point division instruction which shouldn't do any rounding. I believe real rounding should happen during fp32 to int8 conversion right before result storage to dst. Is it correct? So I would expect we should do rounding right before this conversion and we should do w.o dependecy on fused post-ops.
> 
> BTW why it is expected to have rounding towards zero in integer ReduceMean op? Is it specified somewhere?

Good point! 
Following the IEEE 754 standard for floating-point arithmetic, instructions that operate on floating-point numbers (e.g., vdivps and cvtps2dq) rounds to the nearest value by default. On the other hand, C++ standard requires the result of division round toward zero if both operands are integers. To comply with both standards, Reduce node will round the floating point result toward zero before storing, only when both input and output precisions are integers.
Please feel free to have further discussion if you have concerns. Thanks a lot!

2024-07-11 08:03 UTC, xuchen-intel commented
> @xuchen-intel Original commit is reverted: #25487. Lets push fixed solution in bounds of this PR + tests

@dmitry-gorokhov PR updated. Thanks Dmitry!

2024-07-17 13:09 UTC, merged