Add watchdog of OpenVino ONNX CI
openvinotoolkit/openvino pull request #2550
Opened 2020-10-06 06:43 UTC by rblaczkowski

2020-10-06 10:58 UTC, azhogov approved these changes

2020-10-08 11:24 UTC, postrational requested changes
May be good to move `*.py` files to a subdirectory such as `.ci/openvino-onnx/watchdog/src`
Please also use Python file naming convention: `snake_case.py` instead of `CamelCase.py`

2020-10-08 12:50 UTC, rblaczkowski commented
I changed this change to draft - because I need debug more options

2020-10-13 08:34 UTC, azhogov commented
Added PR for enabling nGraph ONNX CI in Azure: https://github.com/openvinotoolkit/openvino/pull/2631

2020-10-20 11:19 UTC, postrational approved these changes

2020-10-23 12:16 UTC, merged