Implemented getOutputElementType
openvinotoolkit/openvino pull request #25760
Opened 2024-07-27 15:51 UTC by Pey-crypto

Implemented Method on c++ side.
Updated typescript definitions.
Created unit tests.
For Issue [https://github.com/openvinotoolkit/openvino/issues/25406](https://github.com/openvinotoolkit/openvino/issues/25406)

Resolved merge errors

2024-07-27 19:16 UTC, rkazants commented on thirdparty/open_model_zoo
please revert this change, it is not needed

2024-07-27 19:17 UTC, rkazants commented on package-lock.json
not sure that any packaging file is needed for this feature. please check

2024-07-29 06:03 UTC, Pey-crypto commented
can i add `if (info.Length() == 1) { error } ` into the getOutputElementType method or is there an alternative way to check? Adding this would solve the errors reported by the second subtests. @almilosz

2024-07-29 11:02 UTC, almilosz requested changes
Hi Pey-crypto!
Answering your question, you cannot add `if (info.Length() == 1) { error } ` check. This is done by `ov::js::validate()` for each correct signature so adding this check would be redundant. 
The second subtest returns errors because you provided incorrect error messages. I suggest making it shorter (see code suggestion). 

You still need to apply my suggestion from the last review I made about method description and remove extra changes from:
 - __.gitignore_
 - _package.json_
 - _thirdparty/open_model_zoo__

If you need more help or detailed guidance you can find me on Discord: `_almilosz`

2024-07-29 11:02 UTC, almilosz commented on src/bindings/js/node/src/model_wrap.cpp
>  #include "node/include/model_wrap.hpp"
```suggestion
#include "node/include/model_wrap.hpp"

```

2024-07-29 11:12 UTC, ilya-lavrenov commented on package.json
do we need it?

2024-07-30 08:07 UTC, almilosz commented on package.json
We don't

2024-07-30 11:41 UTC, Pey-crypto commented on package.json
It was a mistake from my end, i was trying to setup the unit tests and executed npm cmd in the main directory. The file has been removed in the new commit.

2024-07-30 13:48 UTC, almilosz commented on package.json
I think you didn't push the new commit that removes _package.json_

You also need to revert changes from __.gitignore_ and _thirdparty/open_model_zoo__
If you need any help with that, you can find me on Discord _almilosz

2024-08-01 07:05 UTC, p-wysocki reviewed
Hello @Pey-crypto! It seems that there are 2 issues left:

- Changes to `.gitignore` file
Let's keep the PR limited to the JS API component. When you go to "Files Changes" in the PR view you can see that something has been changed in `.gitignore`. Let's revert that change and align the file with OpenVINO master. You can do it with `git checkout upstream/master -- .gitignore`, assuming the main OpenVINO repository remote is called `upstream`, which you can check using `git remote -v`.

- Changes to `open_model_zoo` submodule
`open_model_zoo` is a git submodule, which means that it's a GitHub repository "embedded" into OpenVINO repository as a dependency. For some reason your PR shows that changes have been made to it, most likely due to a gone wrong merge. In order to undo that, you need to:

1. go to `openvino_repo/thirdparty/open_model_zoo`
2. run `git fetch --all` to get all the data on exisintg `open_model_zoo` branches and commits
3. check which `open_model_zoo` commit sha is currently on OpenVINO master by going to `https://github.com/openvinotoolkit/openvino/tree/master/thirdparty`, clicking on `open_model_zoo` and copying the commit hash from URL
4. run `git checkout <commit_sha_you_just_copied>`


Once you do both these things you can just commit them and push. Once it's done the PR will be fixed. :)

2024-08-01 07:17 UTC, p-wysocki commented on src/bindings/js/node/include/model_wrap.hpp
> +     */
The method description should be placed only once, above the declaration. This one can be deleted.
```suggestion
```

2024-08-02 12:00 UTC, almilosz approved these changes

2024-08-02 12:02 UTC, almilosz commented on src/bindings/js/node/lib/addon.ts
> +   * if a model has more than one input, this method throws an exception.
```suggestion
   * If a model has more than one input, this method throws an exception.
```

2024-08-02 12:04 UTC, almilosz commented
build_jenkins

2024-08-03 01:09 UTC, merged