Fixed ngrapth sample logical errors
openvinotoolkit/openvino pull request #2600
Opened 2020-10-09 10:04 UTC by mryzhov

- added batch size, because the sample accepts several images
- set label file as  optional

2020-10-09 11:21 UTC, akuporos requested changes
We still try to find some label file near .bin file [here](https://github.com/openvinotoolkit/openvino/pull/2600/files#diff-fa358112d0e5791dfc6aa345950b254eL374). Let's do it as in python sample.

2020-10-09 11:49 UTC, akuporos reviewed
The general commentt: as python3.6 is minimum required version, instead of format f-strings can be used.

2020-10-09 11:49 UTC, akuporos commented on inference-engine/ie_bridges/python/sample/ngraph_function_creation_sample/ngraph_function_creation_sample.py
> +        print("\n")
I suppose this "\n" is redundant because just print() do the same.

2020-10-09 11:49 UTC, akuporos commented on inference-engine/ie_bridges/python/sample/ngraph_function_creation_sample/ngraph_function_creation_sample.py
> +        print("Image {}\n".format(input_images[i]))
"\n" is also looks redundant

2020-10-12 09:35 UTC, mryzhov commented
> The general commentt: as python3.6 is minimum required version, instead of format f-strings can be used.
excluded python sources from this commit. They were added by mistake

2020-10-12 09:36 UTC, mryzhov commented
> We still try to find some label file near .bin file [here](https://github.com/openvinotoolkit/openvino/blob/master/inference-engine/samples/ngraph_function_creation_sample/main.cpp#L374). Let's do it as in python sample.

agree, but this should be a part of another fix- aligning cmd options for C/C++Python samples (we have a ticket for that)

2020-10-12 09:56 UTC, akuporos approved these changes

2020-10-26 11:16 UTC, ilyachur commented on inference-engine/samples/ngraph_function_creation_sample/main.cpp
> +        network.setBatchSize(imagesData.size());
I propose to don't use `setBatchSize()` method in samples.
Could you use reshape method instead?

2020-10-26 12:36 UTC, merged