[Core] Deprecate get_shape method
openvinotoolkit/openvino pull request #26238
Opened 2024-08-26 15:59 UTC by andrei-cv

### Details:
 - *Deprecate get_shape method*

### Tickets:
 - *CVS-148104*

2024-08-27 16:56 UTC, dmatveev approved these changes
Approved the NPUW change

2024-08-29 08:54 UTC, olpipi requested changes

2024-08-29 08:54 UTC, olpipi commented on src/core/include/openvino/core/model.hpp
> +    Shape get_output_shape(size_t i) const;
We should not change return value of these methods. Just deprecate them.
Please add deprecated annotation to all these methods like here:
https://github.com/openvinotoolkit/openvino/blob/2c9953320a575f24856cb5273d6d23c7600c880b/src/core/include/openvino/op/concat.hpp#L40
Release to remove, I suppose, is 2026.0
+
Add OPENVINO_SUPPRESS_DEPRECATED_START/OPENVINO_SUPPRESS_DEPRECATED_END in every place, where these methods are used.

2024-09-10 07:09 UTC, praasz commented on src/core/include/openvino/core/node_output.hpp
> +    OV_NO_DANGLING Shape get_shape() const;
```suggestion
    Shape get_shape() const;
```
Is `OV_NO_DANGLING ` required when return shape by value (copy)?

2024-09-10 07:10 UTC, praasz commented on src/core/include/openvino/core/node_input.hpp
> +    OV_NO_DANGLING Shape get_shape() const;
```suggestion
    Shape get_shape() const;
```
Is `OV_NO_DANGLING ` required when return shape by value (copy)?

2024-10-22 05:00 UTC, closed without merging