[CPU] Enable inplace StridedSlice on constant path
openvinotoolkit/openvino pull request #26593
Opened 2024-09-13 13:47 UTC by EgorDuplensky

### Details:
 - Very limited amount of use cases is enabled
 - Can be relaxed in the future

### Tickets:
 - 149924

2024-10-07 11:11 UTC, maxnick requested changes

2024-10-07 11:11 UTC, maxnick commented on src/plugins/intel_cpu/src/nodes/strided_slice.cpp
> +        auto memBlock = std::make_shared<PartitionedMemoryBlock>(baseMemBlock);
This variable is not used.

2024-10-07 11:11 UTC, maxnick commented on src/plugins/intel_cpu/src/nodes/strided_slice.cpp
> +            auto memBlock = std::make_shared<PartitionedMemoryBlock>(baseMemBlock, baseMemorySize, offset, partitionSize);
This memory block can be created only once outside the for loop and just shared across all the peer edges.

2024-10-07 11:11 UTC, maxnick commented on src/plugins/intel_cpu/src/nodes/strided_slice.h
>      }
Doesn't look like it's being used. Should be removed.

2024-10-07 11:11 UTC, maxnick commented on src/plugins/intel_cpu/tests/functional/custom/single_layer_tests/split.cpp
> +            // auto fakeEltwise = std::make_shared<ov::op::v0::Relu>(split->output(outIndices[i]));
Please delete commented code.

2024-10-07 11:11 UTC, maxnick commented on src/plugins/intel_cpu/src/nodes/strided_slice.cpp
> +    config.outConfs[0].inPlace(isOptimizedOut ? 0 : -1);
Also it makes sense to assign "unknown" implementation type to raise the priority and distinguish the implementation from the default one.

2025-04-09 07:31 UTC, wenjiew commented
@EgorDuplensky I assume this PR is still needed. Please confirm. Thanks!

2026-04-21 00:46 UTC, closed without merging