[MO] Remove Apache MxNet models support in openvino-dev
openvinotoolkit/openvino pull request #26800
Opened 2024-09-26 09:55 UTC by rkazants

**Details:** Due to drop of Python 3.8 support MxNet support is removed. MxNet is archived project and distributed only up to Python 3.8

**Ticket:** 153365

2024-09-26 11:58 UTC, popovaan approved these changes

2024-09-26 15:17 UTC, mryzhov approved these changes

2024-09-27 11:04 UTC, andrei-kochin requested changes
Waiting for the PxT approval

2024-09-30 07:37 UTC, rkazants commented
> Waiting for the PxT approval

@andrei-kochin, @moslex, please discuss approval for this PR merge today.

Thanks,
Roman

2024-09-30 13:53 UTC, andrei-kochin approved these changes
Approved

2024-09-30 15:32 UTC, merged