Details:
openvinotoolkit/openvino pull request #27008
Opened 2024-10-11 10:44 UTC by pravin25

### Details:
GPU tensorflow_tests/test_tf_Unique.py test was failing, Added in slice_ref_kernel following output datatype which was missing. k. EnableOutputDataType(Datatype::UINT8);
And updated  tensorflow_tests/test_tf_Unique.py, removed skip for GPU.

### Tickets:
 - https://jira.devtools.intel.com/browse/CVS-105900?focusedId=25293445#comment-25293445

2024-10-11 12:04 UTC, vladimir-paramuzov commented on src/plugins/intel_gpu/src/kernel_selector/kernels/slice/slice_kernel_ref.cpp
> +    k.EnableOutputDataType(Datatype::UINT8);
Probably `INT8` should also be added

2024-10-13 16:05 UTC, rkazants commented on tests/layer_tests/tensorflow_tests/test_tf_Unique.py
> -            pytest.skip("GPU error: Could not find a suitable kernel for slice")
why is this regression here for Unique?

2024-10-13 16:05 UTC, rkazants commented on tests/layer_tests/tensorflow_tests/test_tf_Unique.py
> -            pytest.skip("GPU error: Could not find a suitable kernel for slice")
why is this regression here for Unique?

2024-10-13 16:06 UTC, rkazants requested changes
Looks regression for TF models that it skips TF FE layer tests

2024-10-13 16:08 UTC, rkazants approved these changes
From TF FE perspective LGTM

2024-10-13 16:09 UTC, rkazants commented
build_jenkins

2024-10-17 09:44 UTC, rkazants commented
@vladimir-paramuzov, can we merge it?

2024-10-17 12:11 UTC, merged