[GPU] Weightless caching - propagate weights_path from IR FE to the plugin
openvinotoolkit/openvino pull request #27162
Opened 2024-10-21 14:01 UTC by tkrupa-intel

This PR is an implementation of an idea requested in this discussion: https://github.com/openvinotoolkit/openvino/pull/25731#discussion_r1802669119.

2024-10-22 08:12 UTC, praasz approved these changes

2024-10-22 09:23 UTC, t-jankowski requested changes

2024-10-22 09:23 UTC, t-jankowski commented on src/plugins/intel_gpu/src/plugin/plugin.cpp
> +    auto weights_path = rt_info.find("weights_path");
```suggestion
    auto weights_path = rt_info.find("__model_bin_file_path");
```

2024-10-22 09:23 UTC, t-jankowski commented on src/frontends/ir/src/input_model.cpp
> +        model->get_rt_info()["weights_path"] = m_weights_path;
```suggestion
        model->get_rt_info()["__model_bin_file_path"] = m_weights_path;
```

2024-10-22 09:23 UTC, t-jankowski commented on src/frontends/ir/src/frontend.cpp
> +            return std::make_shared<InputModel>(model_buf, weights, create_extensions_map(), weights_path);
Regarding `weights_path` use `std::move` or pass by `const &`.

2024-10-22 09:23 UTC, t-jankowski commented on src/plugins/intel_gpu/src/plugin/plugin.cpp
> +    // using that mechanism.
I think it should be 'WEIGHTS_PATH', not 'GPU_WEIGHTS_PATH'.
I'd also consider to rename property 'WEIGHTS_PATH' to 'MODEL_BIN_FILE_PATH'.

2024-10-22 12:19 UTC, tkrupa-intel commented on src/core/src/pass/serialize.cpp
> +        if (it.first == "version" || it.first == "weights_path")
Added underscores in the rt_info key but didn't change the name (as agreed in the PM) due to the name already being in use elsewhere.

2024-10-23 09:16 UTC, t-jankowski approved these changes

2024-10-24 10:06 UTC, p-durandin commented
build_jenkins

2024-10-24 12:31 UTC, e-ddykim approved these changes
Looks good to me

2024-10-24 15:10 UTC, p-durandin approved these changes

2024-10-25 07:18 UTC, merged