[Python] Don't need to assign object to tensor for empty string
openvinotoolkit/openvino pull request #27269
Opened 2024-10-28 09:06 UTC by davidsnam-intel

### Details:
 - Since tensor data is already created as a string type, if the input is an empty string, even if the data is not assigned to the tensor, the CPU/GPU will be able to handle it as an empty string type.

### Tickets:
 - 148921

2024-10-28 10:29 UTC, p-wysocki reviewed
All plugins handle empty strings without throwing but GPU, and this PR adds an additional if check for every string on all plugins. It's a high level fix for a low level issue.

Still, it's a fix for an existing issue, so I approve under the condition that is an additional story or discussion on what the desired plugin behavior for empty string is and adjust GPU if necessary.

2024-10-28 11:25 UTC, akuporos requested changes
I'd also expect to see the fix in GPU plugin directly, not in Python API.
As it was described in the ticket by @p-wysocki, the problem is GPU-specific, CPU works well.

2024-10-29 08:22 UTC, wilson-seok commented on src/plugins/intel_gpu/src/plugin/sync_infer_request.cpp
> +    if (element_type == ov::element::string) {
Please add comment for initialization

2024-10-29 08:53 UTC, davidsnam-intel commented on src/plugins/intel_gpu/src/plugin/sync_infer_request.cpp
> +    if (element_type == ov::element::string) {
added.

2024-10-29 09:29 UTC, p-wysocki approved these changes

2024-10-30 11:59 UTC, merged