[TF FE] Provide better validation for TopKV2 and stabilize test
openvinotoolkit/openvino pull request #27374
Opened 2024-11-02 17:12 UTC by rkazants

**Details:** Provide better validation for TopKV2 and stabilize test

**Ticket:** TBD

2024-11-04 08:43 UTC, gkrivor approved these changes

2024-11-04 15:42 UTC, andrei-kochin requested changes
Waiting for the master to be unblocked

2024-11-05 08:08 UTC, rkazants commented
> Waiting for the master to be unblocked

Sent a request to committee for approval.

2024-11-05 09:21 UTC, andrei-kochin approved these changes

2024-11-05 10:26 UTC, merged