Add hsigmoid fusing for MO
openvinotoolkit/openvino pull request #2750
Opened 2020-10-21 10:44 UTC by iimironov

2020-10-21 15:36 UTC, rkazants requested changes

2020-10-21 15:36 UTC, rkazants commented on model-optimizer/extensions/front/HSigmoid_fusion.py
> +    #mul = match['mul']
Please remove commented out code.

2020-10-21 15:36 UTC, rkazants commented on model-optimizer/extensions/front/HSigmoid_fusion.py
> +    #mul_input_port_idx = int(mul.in_port(0).get_connection().get_source().node.soft_get('op') in ['Clamp', 'Minimum'])
Please remove commented out code

2020-10-21 15:36 UTC, rkazants commented on model-optimizer/extensions/front/HSigmoid_fusion.py
> +    #    return
please remove commented out code

2020-10-21 15:38 UTC, rkazants commented
@iimironov, why do we need fusing transformations in the MO tool? You can implement it in nGraph and it should be sufficient.

2020-10-21 15:45 UTC, lazarevevgeny commented
> @iimironov, why do we need fusing transformations in the MO tool? You can implement it in nGraph and it should be sufficient.

We need these transformation in the MO so POT can correctly quantize the model.

2020-10-21 19:40 UTC, rkazants commented on model-optimizer/extensions/front/HSigmoid_fusion.py
> +    HSigmoid(x) = Relu6(x + 3) / 6.0.
3.0?

2020-10-21 19:40 UTC, rkazants commented on model-optimizer/extensions/front/HSigmoid_fusion.py
> +                ('const_1_6', dict(op='Const', value=lambda v: v is not None and np.allclose(v, 1 / 6.0, atol=1e-6))),
1.0 / 6.0

2020-10-21 19:43 UTC, rkazants commented on model-optimizer/extensions/front/HSigmoid_fusion.py
> +    HSigmoid(x) = Min(Max(x + 3, 0), 6) / 6.0.
Please normalize al to floats: 3.0, 0.0 and 6.0. Or how you identify what are integers or floats here?

2020-10-21 19:44 UTC, rkazants commented on model-optimizer/extensions/front/HSigmoid_fusion.py
> +                ('mul_2', dict(op='Mul')),
Why did you use `Mul` here if in the specification it is called as `Multiply`?

2020-10-21 19:46 UTC, rkazants commented on model-optimizer/extensions/front/HSigmoid_fusion.py
> +
Why don't you add other fusion transformation where `Divide` is used instead of `Multiply` in case division by 6.0

2020-10-21 19:49 UTC, rkazants commented on model-optimizer/extensions/front/HSigmoid_fusion_test.py
> +                        graph.get_op_nodes(name='final_mul')[0].op == 'HSigmoid')
Please also check that a name of output node is preserved. And the same comment for tests below.

2020-10-21 19:51 UTC, rkazants commented on model-optimizer/extensions/ops/activation_ops.py
> +    operation = staticmethod(lambda x: np.minimum(np.maximum(x + 3.0, 0.0), 6.0) / 6.0)
What if we have integer input type? Due to the specification any input type is supported.

2020-10-21 19:53 UTC, rkazants commented on model-optimizer/extensions/front/HSigmoid_fusion.py
> +                ('const_6', dict(op='Const', value=lambda v: v is not None and np.allclose(v, 6.0, atol=1e-6))),
Here and below you do not specify type of constants. Will it work for cases with integer input type or fp16?

2020-10-22 20:04 UTC, rkazants approved these changes

2020-10-23 10:59 UTC, lazarevevgeny requested changes

2020-10-24 09:51 UTC, lazarevevgeny approved these changes

2020-10-24 09:51 UTC, merged