[ONNX] Added FusedMatMul from com.microsoft domain
openvinotoolkit/openvino pull request #27556
Opened 2024-11-14 10:16 UTC by vatsalashanubhag

Details:
Microsoft Contrib Operator "FusedMatMul" for ONNX RT

Tickets:
N/A

2024-11-15 10:05 UTC, gkrivor requested changes

2024-11-15 10:05 UTC, gkrivor commented on src/frontends/onnx/frontend/src/op/com.microsoft/fusedmatmul.cpp
> +        std::swap(axes[rank - 1], axes[rank - 2]);
please, check size of axes before. it isn't an expected way, but better to prevent out-of-bounds.

2024-11-15 10:05 UTC, gkrivor commented on src/frontends/onnx/frontend/src/op/com.microsoft/fusedmatmul.cpp
> +#include "cmath"
Add copyrights, please

2024-11-15 10:08 UTC, gkrivor commented
build_jenkins

2024-11-19 08:03 UTC, vatsalashanubhag commented on src/frontends/onnx/frontend/src/op/com.microsoft/fusedmatmul.cpp
> +#include "cmath"
Done

2024-11-19 08:30 UTC, vatsalashanubhag commented on src/frontends/onnx/frontend/src/op/com.microsoft/fusedmatmul.cpp
> +    if (transA) {
Yes transA/B is already handled in MatMul.
If the order of handling attributes is not important then MaMul can be used.
Done.

2024-11-20 11:11 UTC, gkrivor commented
build_jenkins

2024-11-21 07:12 UTC, gkrivor approved these changes

2024-11-26 18:13 UTC, merged