Aalborov/see also
openvinotoolkit/openvino pull request #2770
Opened 2020-10-22 11:16 UTC by aalborov

2020-10-22 11:28 UTC, aalborov commented
@lazarevevgeny take a look please if the links make sense

2020-10-22 13:46 UTC, lazarevevgeny requested changes

2020-10-22 13:46 UTC, lazarevevgeny commented on docs/MO_DG/prepare_model/Config_Model_Optimizer.md
> +
Remove empty lines

2020-10-22 13:46 UTC, lazarevevgeny commented on docs/MO_DG/prepare_model/convert_model/Convert_Model_From_Caffe.md
> +* [Converting YOLO* Models to the Intermediate Representation (IR)](../tf_specific/Convert_YOLO_From_Tensorflow.md)
remove this one

2020-10-22 13:46 UTC, lazarevevgeny commented on docs/MO_DG/prepare_model/convert_model/Convert_Model_From_Kaldi.md
> +* [Convert ONNX* Mask R-CNN Model to the Intermediate Representation](../onnx_specific/Convert_Mask_RCNN.md)
remove this one

2020-10-22 13:46 UTC, lazarevevgeny commented on docs/MO_DG/prepare_model/convert_model/Convert_Model_From_Kaldi.md
> +* [Post-Training Optimization Toolkit API](@ref pot_compression_api_README)
remove this one

2020-10-22 13:46 UTC, lazarevevgeny commented on docs/MO_DG/prepare_model/convert_model/Convert_Model_From_Kaldi.md
> +* [Converting YOLO* Models to the Intermediate Representation (IR)](../tf_specific/Convert_YOLO_From_Tensorflow.md)
remove this one

2020-10-22 13:46 UTC, lazarevevgeny commented on docs/MO_DG/prepare_model/convert_model/Convert_Model_From_Kaldi.md
> +* [Custom Layers Guide](../HOWTO/Custom_Layers_Guide.md)
remove this one

2020-10-22 13:46 UTC, lazarevevgeny commented on docs/MO_DG/prepare_model/convert_model/Convert_Model_From_Caffe.md
> +* [Converting a MXNet* Model](Convert_Model_From_MxNet.md)
In general all Convert_Model_From_<FW_1>.md may point to Convert_Model_From_<FW_2>.md

2020-10-22 13:46 UTC, lazarevevgeny commented on docs/MO_DG/prepare_model/convert_model/Convert_Model_From_MxNet.md
> +* [Converting YOLO* Models to the Intermediate Representation (IR)](../tf_specific/Convert_YOLO_From_Tensorflow.md)
remove this one

2020-10-22 13:46 UTC, lazarevevgeny commented on docs/MO_DG/prepare_model/convert_model/Convert_Model_From_ONNX.md
> +* [Super Resolution C++ Demo](@ref omz_demos_super_resolution_demo_README)
Remove references to all demos

2020-10-22 13:46 UTC, lazarevevgeny commented on docs/MO_DG/prepare_model/convert_model/Convert_Model_From_TensorFlow.md
> +* [Converting YOLO* Models to the Intermediate Representation (IR)](../tf_specific/Convert_YOLO_From_Tensorflow.md)
remove

2020-10-22 13:46 UTC, lazarevevgeny commented on docs/MO_DG/prepare_model/convert_model/Convert_Model_From_TensorFlow.md
> +* [Object Detection Faster R-CNN C++ Demo](@ref omz_demos_object_detection_demo_faster_rcnn_README)
remove

2020-10-22 13:46 UTC, lazarevevgeny commented on docs/MO_DG/prepare_model/convert_model/Converting_Model_General.md
> +* [Converting a Model to Intermediate Representation (IR)](Convert_Model_From_Caffe.md)
wrong title?

2020-10-22 13:46 UTC, lazarevevgeny commented on docs/MO_DG/prepare_model/convert_model/Converting_Model_General.md
> +* [Convert TensorFlow* DeepSpeech Model to the Intermediate Representation ](../tf_specific/Convert_DeepSpeech_From_Tensorflow.md)
remove

2020-10-22 13:46 UTC, lazarevevgeny commented on docs/MO_DG/prepare_model/convert_model/Converting_Model_General.md
> +* [Converting YOLO* Models to the Intermediate Representation (IR)](../tf_specific/Convert_YOLO_From_Tensorflow.md)
remove

2020-10-22 13:46 UTC, lazarevevgeny commented on docs/MO_DG/prepare_model/convert_model/Cutting_Model.md
> +* [Converting TensorFlow* Object Detection API Models](../tf_specific/Convert_Object_Detection_API_Models.md)
remove this one

2020-10-22 13:46 UTC, lazarevevgeny commented on docs/MO_DG/prepare_model/convert_model/IR_suitable_for_INT8_inference.md
> +* [Convert GNMT* Model to the Intermediate Representation (IR)](../tf_specific/Convert_GNMT_From_Tensorflow.md)
Remove this one

2020-10-22 13:46 UTC, lazarevevgeny commented on docs/MO_DG/prepare_model/convert_model/kaldi_specific/Aspire_Tdnn_Model.md
> +* [Converting a Style Transfer Model from MXNet*](../mxnet_specific/Convert_Style_Transfer_From_MXNet.md)
Remove all references. May be add a reference to Convert models from Kaldi only.

2020-10-23 12:29 UTC, lazarevevgeny approved these changes

2020-11-06 13:53 UTC, andrew-zaytsev approved these changes

2020-11-06 14:23 UTC, azhogov commented
Doc is changed only

2020-11-06 14:24 UTC, merged