[NPU][IE-MDK] Unskip migration tests
openvinotoolkit/openvino pull request #27801
Opened 2024-11-28 15:31 UTC by sbutnari

### Details:
 - Tests were disabled during NPU Plugin migration into OV repo

### Tickets:
 - EISW-125086

2024-11-29 13:16 UTC, sbutnari commented
build_jenkins

2024-12-03 11:55 UTC, StefaniaHergane commented
Please see: https://github.com/openvinotoolkit/openvino/blob/master/docs/dev/ci/commit_signoff_policy.md
I believe you need to sign-off your commit.

2024-12-03 13:09 UTC, pereanub requested changes

2024-12-03 13:09 UTC, pereanub commented on src/plugins/intel_npu/tests/functional/shared_tests_instances/skip_tests_config.cpp
> -                ".*OVCompiledModelPropertiesDefaultSupportedTests.CanCompileWithDefaultValueFromPlugin.*"
It looks like CanCompileWithDefaultValueFromPlugin fails. Please fix it before merging it.

2025-01-20 00:23 UTC, closed without merging