Tests failed without reshape paramter due to uninitilized value
openvinotoolkit/openvino pull request #27814
Opened 2024-11-29 07:24 UTC by SeptimiuIoachimNeagaIntel

### Details:
Fixed problem in protopipe 
 - if the "reshape" parameter was not set and not needed application would fail with bad variant access

2024-11-29 14:05 UTC, smirnov-alexey commented on src/plugins/intel_npu/tools/protopipe/src/simulation/simulation.cpp
> +    if (std::holds_alternative<AttrMap<std::vector<size_t>>>(params.reshape)) {
Please replicate changes from https://github.com/openvinotoolkit/openvino/pull/27775

2024-11-29 14:05 UTC, smirnov-alexey requested changes
Please replicate https://github.com/openvinotoolkit/openvino/pull/27775

2024-12-04 02:04 UTC, AsyaPronina commented on src/plugins/intel_npu/tools/protopipe/src/simulation/simulation.cpp
> +    } else {
Please remove this else when you will be comfortable with removing of debug logs

2024-12-04 12:40 UTC, smirnov-alexey approved these changes

2024-12-04 13:15 UTC, AsyaPronina approved these changes

2024-12-12 13:25 UTC, AsyaPronina commented
build_jenkins

2024-12-12 17:11 UTC, merged