[core] Result node uses inputs names on creation
openvinotoolkit/openvino pull request #28168
Opened 2024-12-20 12:41 UTC by praasz

### Details:
 - The Result node us inputs names when created. Creation such Result assume as previous layer is model output.
 - The model can be created from OutputVector and if output is not from Result the Result is created and this layer tensor names will be used as model output names.
 - The Result can disable use inputs names as it owns. They still be visible as output names if Result has no dedicated names.

### Tickets:
 - CVS-159672

2024-12-23 16:38 UTC, StefaniaHergane commented
Tests look good in NPU CI

2024-12-23 16:39 UTC, StefaniaHergane approved these changes

2024-12-24 11:18 UTC, razvanapetroaie approved these changes

2024-12-24 21:07 UTC, ilya-lavrenov commented on src/core/src/node_vector.cpp
> +                                                               : std::make_shared<ov::op::v0::Result>(value, true));
should you also fix `ov::Model::add_output` ?

2025-01-02 08:18 UTC, dtrawins commented on src/core/include/openvino/op/result.hpp
> +    Result(const Output<Node>& arg, bool use_input_names = false);
This change is not compatible with https://github.com/openvinotoolkit/model_api/blob/master/model_api/cpp/utils/src/image_utils.cpp#L176
 error: undefined reference to 'ov::op::v0::Result::Result(ov::Output<ov::Node> const&)'
Perhaps an additional constructor would be safer to avoid a breaking change.
I wonder if the default use_input_names = false is the right choice. That would make the empty outputs when postprocessing is added.

2025-01-02 12:25 UTC, praasz commented on src/core/src/node_vector.cpp
> +                                                               : std::make_shared<ov::op::v0::Result>(value, true));
The `add_output` updated when Result node is created.

2025-01-02 12:48 UTC, praasz commented on src/core/include/openvino/op/result.hpp
> +    Result(const Output<Node>& arg, bool use_input_names = false);
Added additional constructor with 2nd parameter.

By default the `use_input_tensor` should be false as tensor names should not be moved.
User can explicit set the Result names using input node names or keep them on that node and add dedicated tensor names to Result. The Result's dedicated names will stay on Result node even prepostproecessig applied

In case of `ov::Model` creation from `OutputVector` the Result nodes can be created and for these Results is better to set names based on input node tensor, is expected all outputs are model outputs.

2025-01-03 10:09 UTC, dtrawins requested changes
the following models still fail to report the output names:
- tokenizer generated with a command: `convert_tokenizer -o bge-m3 BAAI/bge-m3`
- dummy model created using ov operations https://github.com/openvinotoolkit/model_server/blob/5b9a3df739789eb71471643a23d2ed1dac4a0ac1/tests/models/no_name_output.py
- yolo11 : 
```from ultralytics import YOLO
import openvino as ov
det_model = YOLO(f"yolo11n.pt")
ir_model_dir = det_model.export(format="openvino", dynamic=True, half=True)```

The errors from `std::string name = output.get_any_name();` is:
```
OpenVINO with error:Check '!get_names().empty()' failed at src/core/src/descriptor/tensor.cpp:102:
Attempt to get a name for a Tensor without names. 
```

2025-01-07 06:22 UTC, praasz commented
> the following models still fail to report the output names:
> 
> * tokenizer generated with a command: `convert_tokenizer -o bge-m3 BAAI/bge-m3`
> * dummy model created using ov operations https://github.com/openvinotoolkit/model_server/blob/5b9a3df739789eb71471643a23d2ed1dac4a0ac1/tests/models/no_name_output.py
> * yolo11 :
> 
> ```
> import openvino as ov
> det_model = YOLO(f"yolo11n.pt")
> ir_model_dir = det_model.export(format="openvino", dynamic=True, half=True)```
> 
> The errors from `std::string name = output.get_any_name();` is:
> ```
> 
> OpenVINO with error:Check '!get_names().empty()' failed at src/core/src/descriptor/tensor.cpp:102: Attempt to get a name for a Tensor without names.

I can't reproduce issues for:  `convert_tokenizer -o bge-m3 BAAI/bge-m3` and ` yolo11`.
But can easily reproduce for `convert_tokenizer -o bge-m3 BAAI/bge-m3` that without these changes there is no tensor names on model outputs generated by `convert_tokenizer`

In `dummy model` example there is no tensor names on model's outputs because names are not set the example has to be modified e.g.:

```python
op0 = ov.opset1.multiply(in1, in0, name="MULTIPLY")
op1 = ov.opset1.add(in1, in0, name="ADD")
op0.output(0).set_names({"mul"})
op1.output(0).set_names({"add"})
```
or 
```python
model = ov.Model([op0, op1], [in0, in1], model_name)
model.output(0).set_names({"mul"})
model.output(1).set_names({"add"})
```
There is no general feature to auto name tensors in OV, but there are some exception like python API `ov.Model` where Model creation use Parameters friendly names as tensor names.

2025-01-07 08:25 UTC, dtrawins approved these changes

2025-01-07 11:41 UTC, praasz commented
@ilya-lavrenov Could you review PR again?

2025-01-08 12:34 UTC, merged