Add Group Query Attention support with OV base OPs
openvinotoolkit/openvino pull request #28163
Opened 2024-12-20 06:18 UTC by sgbihu

### Details:
 - Try to enable LLM based on onnxruntime. (Phi3, Llama3 is working on CPU, Phi3 can work with iGPU)
 
### Test scripts
```
import onnxruntime as rt
import os
import numpy as np
import time

import onnxruntime.tools.add_openvino_win_libs as utils
utils.add_openvino_libs_to_path()
from transformers import PreTrainedTokenizerFast

test_lama3 = False
test_phi3 = True
if test_phi3:
    modelPath = os.path.join('D:\\', 'models', 'llm', 'Phi-3-mini-4k-instruct-onnx', 'model.onnx')
    tokenizerPath = os.path.join('D:\\', 'models', 'llm', 'Phi-3-mini-4k-instruct-onnx', 'tokenizer.json')

if test_lama3:
    modelPath = os.path.join('D:\\', 'models', 'llm', 'llama3.1-8B-instruct-onnx', 'model.onnx')

so = rt.SessionOptions()
# so.log_severity_level = 3

# sess = rt.InferenceSession(modelPath, so, providers=['CPUExecutionProvider'])
sess = rt.InferenceSession(modelPath, so, providers=['OpenVINOExecutionProvider'], provider_options=[{'device_type' : "CPU", 'cache_dir': "cache"}])
# sess = rt.InferenceSession(modelPath, so, providers=['OpenVINOExecutionProvider'], provider_options=[{'device_type' : "CPU"}])
# sess = rt.InferenceSession(modelPath, so, providers=['OpenVINOExecutionProvider'], provider_options=[{'device_type' : "NPU"}])
tokenizer = PreTrainedTokenizerFast(tokenizer_file=tokenizerPath)

# print(sess.get_device())
# for name in sess.get_inputs():
#     print(f"Name: {name.name}, Shape: {name.shape}, Type: {name.type}")
outputs = sess.get_outputs()
output_names = list(map(lambda output: output.name, outputs))

# Assuming the model has 32 layers and each layer has a key and value state
# Phi3
def get_phi3_param():
    num_layers = 32
    batch_size = 1
    num_heads = 32
    sequence_length = 2048
    hidden_size = 96
    return num_layers, batch_size, num_heads, sequence_length, hidden_size

# lama
def get_llama3_param():
    num_layers = 32
    batch_size = 1
    num_heads = 8
    sequence_length = 2048
    hidden_size = 128
    return num_layers, batch_size, num_heads, sequence_length, hidden_size

if test_phi3:
    num_layers, batch_size, num_heads, sequence_length, hidden_size = get_phi3_param()

if test_lama3:
    num_layers, batch_size, num_heads, sequence_length, hidden_size = get_llama3_param()

# Initialize past_key_values with zeros
cpu_array = np.zeros((batch_size, num_heads, sequence_length, hidden_size), dtype=np.float32)

# print("Output names: ", outputs[0].type.data)

def create_present_state_binding(binding, outputs):
    outputMap={}
    for output in outputs:
        shapes = []
        for item in output.shape:
            if isinstance(item, str):
                if 'batch_size' in item:
                    shapes.append(batch_size)
                elif 'sequence_length' in item:
                    if output.name == 'logits':
                        shapes.append(len(inputToken))
                    else:
                        shapes.append(sequence_length)
                elif 'hidden_size' in item:
                    shapes.append(hidden_size)
                elif 'num_heads' in item:
                    shapes.append(num_heads)
                else:
                    raise ValueError(f"Unknown dimension: {item}")
            else:
                shapes.append(item)
            
        present_state = rt.OrtValue.ortvalue_from_shape_and_type(shapes, np.float32)
        binding.bind_ortvalue_output(output.name, present_state)
        outputMap[output.name] = present_state
    return outputMap

def rebind_inputs(lastOutput, binding):
    for index in range(num_layers):
        binding.bind_ortvalue_input(f'past_key_values.{index}.key', lastOutput[f'present.{index}.key'])
        binding.bind_ortvalue_input(f'past_key_values.{index}.value', lastOutput[f'present.{index}.value'])
    return binding

def init_input_with_binding(binding):
    for index in range(num_layers):
        key_state = rt.OrtValue.ortvalue_from_numpy(cpu_array)
        value_state = rt.OrtValue.ortvalue_from_numpy(cpu_array)
        binding.bind_ortvalue_input(f'past_key_values.{index}.key', key_state)
        binding.bind_ortvalue_input(f'past_key_values.{index}.value', value_state)
    return binding

def reinit_input_bindings(bindings, lastOutput):
    newOutput = create_present_state_binding(bindings, lastOutput)
    binding = rebind_inputs(lastOutput, bindings)
    return binding, newOutput

def create_numpy_inputs(inputToken):
    tokenLen = len(inputToken)
    npinput_ids = np.array([inputToken], dtype=np.int64)
    npattention_mask = np.array([[1] * (tokenLen)], dtype=np.int64)
    return npinput_ids, npattention_mask

def init_ortinput(inputToken):
    flattened_past_key_values = {}
    for index in range(num_layers):
        key_state = rt.OrtValue.ortvalue_from_numpy(cpu_array)
        value_state = rt.OrtValue.ortvalue_from_numpy(cpu_array)
        flattened_past_key_values[f'past_key_values.{index}.key'] = key_state
        flattened_past_key_values[f'past_key_values.{index}.value'] = value_state
    ids, mask = create_numpy_inputs(inputToken)
    flattened_past_key_values['input_ids'] = rt.OrtValue.ortvalue_from_numpy(ids)
    flattened_past_key_values['attention_mask'] = rt.OrtValue.ortvalue_from_numpy(mask)
    return flattened_past_key_values

def init_npinput(inputToken):
    flattened_past_key_values = {}
    for index in range(num_layers):
        key_state = np.zeros((batch_size, num_heads, sequence_length, hidden_size), dtype=np.float32)
        value_state = np.zeros((batch_size, num_heads, sequence_length, hidden_size), dtype=np.float32)
        flattened_past_key_values[f'past_key_values.{index}.key'] = key_state
        flattened_past_key_values[f'past_key_values.{index}.value'] = value_state
    flattened_past_key_values['input_ids'], flattened_past_key_values['attention_mask'] = create_numpy_inputs(inputToken)
    return flattened_past_key_values

def init_bindinginput(inputToken):
    binding = sess.io_binding()
    binding = init_input_with_binding(binding)
    
    ids, mask = create_numpy_inputs(inputToken)
    binding.bind_ortvalue_input(f'attention_mask', rt.OrtValue.ortvalue_from_numpy(mask))
    binding.bind_ortvalue_input(f'input_ids',  rt.OrtValue.ortvalue_from_numpy(ids))
    return binding

# Question
# The Sun is yellow because

# Phi3
if test_phi3:
    # 450 8991 5692
    # inputToken = [32010, 29871, 13]
    inputToken = [32010, 29871, 13, 1576, 8991, 338, 13328, 1363, 29871, 32007, 13, 32001]
    # inputToken = [32010, 32010, 32010, 32010, 32010, 32010, 32010, 32010, 32010, 32010, 32010, 32010]
# lama3
if test_lama3:
    # 315 1202 7479
    inputToken = [128000, 27, 91, 882, 91, 397, 791, 8219, 374, 14071, 1606, 83739, 408, 91, 397, 27, 91, 78191, 91, 29]
    # inputToken = [315]
history_tokens = inputToken

flattened_past_key_values = init_npinput(inputToken)

# flattened_past_key_values = init_ortinput(inputToken)

# binding = init_bindinginput(inputToken)
# lastoutput = create_present_state_binding(binding, outputs)

lastTokenLen = len(inputToken)

# roption = rt.RunOptions()
# roption.add_run_config_entry("gpu_graph_id", "-1")

before = time.time()
results = sess.run(output_names, flattened_past_key_values)
# results = sess.run_with_iobinding(binding)
# results = sess.run_with_ort_values(output_names, flattened_past_key_values)
after = time.time()
print("Time cost in ms: ", (after - before) * 1000)

# print(np.argmax(results[0].numpy(), axis=-1)[-1])
print(np.argmax(results[0], axis=-1)[-1])

# print(results[0])
# print(output_names[1])
# print(results[1][0][0][0])
# print(results[1][0][0][1])
# print(results[1][0][0][2])
# # print(results[1][0][0][14])
# # print(results[1])
# print(output_names[2])
# # print(results[2])
# print(results[2][0][0][0])
# print(results[2][0][0][1])
# print(results[2][0][0][2])
# print(results[2][0][0][14])
# inputToken.append(450)

# rebind_inputs(lastOutput, binding)

def update_kvcache(inputsMap, results):
    for index in range(len(output_names)):
        if  [...]

2024-12-20 09:09 UTC, slyalin commented
How is it related to https://github.com/openvinotoolkit/openvino/pull/27648?

2025-02-05 03:16 UTC, wine99 commented
@slyalin we have relocated the transformation code from the ONNX frontend to the plugin transformation passes as detailed in https://github.com/openvinotoolkit/openvino/pull/27648. Could you please review and provide feedback? Currently, the GQA node is defined in opset15, which likely needs to be updated.

2025-02-06 13:06 UTC, mlukasze commented
hey @sgbihu
please, resolve conflicts before CI will be triggered

2025-02-06 18:05 UTC, t-jankowski commented on src/common/transformations/src/transformations/op_conversions/group_query_attention_decomposition.cpp
> +        OPENVINO_THROW("GroupQueryAttention only supports f32 and f16");
This is already validated by validate_and_infer...(). This should never happen in here.
Secondly Pass should break like that - if conditions are not met, it should skip without replace the node.

2025-02-07 05:13 UTC, wine99 commented on src/common/transformations/src/transformations/op_conversions/group_query_attention_decomposition.cpp
> +        OPENVINO_THROW("GroupQueryAttention only supports f32 and f16");
Removed and inlined this function

2025-02-07 05:39 UTC, mlukasze commented
build_jenkins

2025-02-08 01:22 UTC, wine99 commented
@t-jankowski We are adding GQA and Null to opset 15. Is this appropriate?

2025-02-10 09:15 UTC, mitruska requested changes
From my point of view, the main things to address is to clarify the correct place for GQA op (opset or dev_api) and the way of "Null" node representation for optional inputs. 
Details in the comments for the related part of the code.

@slyalin Could you please share opinion from the architecture side and as an author of the original: 
- https://github.com/openvinotoolkit/openvino/pull/27648

2025-02-10 09:15 UTC, mitruska commented on src/core/include/openvino/op/null.hpp
> +    OPENVINO_OP("Null", "opset15", op::Op);
I understand the motivation behind the "Null" Node (as GQA has several optional inputs mixed with required). Actually, this is a copy of the class used within the OV ONNX Frontend scope. Following this approach we should agreed and provide more generic meaning for Null op, not only for ONNX.

On the other hand @slyalin proposed an empty Constant to represent the "Null" Node.

```
Output<Node> GroupQueryAttentionExtension::null() {
    return v0::Constant::create(element::f32, Shape{0}, {});  // particular type and shape do not matter
}
```
@slyalin Could you please share your view on the preferred approach here?

2025-02-10 11:13 UTC, mitruska commented on src/core/src/op/group_query_attention.cpp
> +    }
The `.get_length()` will throw if called on dynamic dimension, and static dimension it's not ensured here (and in `get_head_size` func). The check for `input_shape[2].is_static()` should be added, or simply dynamic dimension division can be applied to set bounds 
with `ov::util::dim::floor_div` util from `src/core/shape_inference/include/dimension_util.hpp`

*Additional Note: Currently shape inference is usually implemented in a "shape_infer" function (like [src/core/shape_inference/include/scaled_dot_product_attention_shape_inference.hpp](https://github.com/openvinotoolkit/openvino/blob/70ec5317f43a2576ec4aef08c91671b6beacfb47/src/core/shape_inference/include/scaled_dot_product_attention_shape_inference.hpp#L12-L15)) to be reused by plugins for dynamic cases. 
But it can be considered for further refactor out of this PR scope.

2025-02-11 05:29 UTC, gkrivor reviewed
Hi, thank you for contribution! I've left a few comments from frontend perspective :)

2025-02-11 05:29 UTC, gkrivor commented on src/common/transformations/include/transformations/op_conversions/group_query_attention_decomposition.hpp
> +// Copyright (C) 2018-2024 Intel Corporation
Old copyrights in files

2025-02-11 05:29 UTC, gkrivor commented on src/frontends/onnx/frontend/src/op/com.microsoft/group_query_attention.cpp
> +    const auto onnx_op_inputs = node.get_ov_inputs();
Please, add common::defaul_op_checks, like here https://github.com/openvinotoolkit/openvino/blob/a5f7ec3b4de1451275f392c7e41da5c29f118676/src/frontends/onnx/frontend/src/op/com.microsoft/simplified_layer_normalization.cpp#L28

2025-02-11 05:29 UTC, gkrivor commented on src/frontends/onnx/frontend/src/op/com.microsoft/group_query_attention.cpp
> +        ov_op_inputs.push_back(ov::op::util::is_null(input) ? std::make_shared<v15::Null>() : input);
Usually we place defaults pre-calculation in a front-end specific code. It might be also helpful for frontend-specific optimizations in the future.

Not sure I get why can't you calculate "default values" here, instead of doing it in the transformation pipeline?

Not necessary by frontend side, but as I understand - it allows to remove op::Null in the implementation.

2025-02-11 05:29 UTC, gkrivor commented on src/frontends/onnx/frontend/src/op/com.microsoft/group_query_attention.cpp
> +    const auto rotary_interleaved = node.get_attribute_value<float>("rotary_interleaved", 0.0f);
Docs says it should be int, why it is float here?

2025-02-11 05:34 UTC, wine99 commented on src/core/include/openvino/op/group_query_attention.hpp
> +    OPENVINO_OP("GroupQueryAttention", "opset15");
We added to opset 15 due to seeing some errors when implementing this at the beginning (errors related to IR deserialization IIRC, but I do not understand the errors). But I have just tried and found that having GQA in the dev_api also works. If that is preferred, we can move GQA (and maybe Null) to dev_api.

2025-02-11 06:48 UTC, wine99 commented on src/frontends/onnx/tests/onnx_import_com_microsoft.in.cpp
> +OPENVINO_TEST(${BACKEND_NAME}, onnx_model_gqa_past_0_input_1_rotary) {
We changed this input to Null because we met some problem in NPUW. I have changed the tests to exclude this input.

2025-02-13 01:25 UTC, wine99 commented on src/frontends/onnx/frontend/src/op/com.microsoft/group_query_attention.cpp
> +    const auto rotary_interleaved = node.get_attribute_value<float>("rotary_interleaved", 0.0f);
I believe this was a mistake. Have changed now

2025-02-13 01:26 UTC, wine99 commented on src/frontends/onnx/frontend/src/op/com.microsoft/group_query_attention.cpp
> +    const auto onnx_op_inputs = node.get_ov_inputs();
Added

2025-02-13 01:29 UTC, wine99 commented on src/frontends/onnx/frontend/src/op/com.microsoft/group_query_attention.cpp
> +        ov_op_inputs.push_back(ov::op::util::is_null(input) ? std::make_shared<v15::Null>() : input);
What does pre-calculation mean? Originally we decomposed the op in the onnx frontend space. But the logic would be different for CPU/GPU and NPU so we moved it to a transformation pass that will only work for CPU and GPU.

2025-02-13 02:00 UTC, wine99 commented on src/core/src/op/group_query_attention.cpp
> +    }
Added a static check since the last dim should be known.

2025-02-13 02:35 UTC, wine99 commented on src/frontends/onnx/frontend/src/op/com.microsoft/group_query_attention.cpp
> +        ov_op_inputs.push_back(ov::op::util::is_null(input) ? std::make_shared<v15::Null>() : input);
Do you mean: we split the possibly packed Q early in the frontend so that we always push valid inputs to ov ops (and then we don't need null ops anymore in the ov space).

2025-02-13 08:25 UTC, wine99 commented on src/core/include/openvino/op/null.hpp
> +    OPENVINO_OP("Null", "opset15", op::Op);
The QKV unpacking logic is moved to frontend. Null is not needed now and removed.

2025-02-13 08:27 UTC, wine99 commented on src/frontends/onnx/frontend/src/op/com.microsoft/group_query_attention.cpp
> +        ov_op_inputs.push_back(ov::op::util::is_null(input) ? std::make_shared<v15::Null>() : input);
Done. QKV unpacking logic is now in the frontend.

2025-02-14 07:11 UTC, itikhono commented on src/common/transformations/include/transformations/op_conversions/group_query_attention_decomposition.hpp
> +    ov::OutputVector decompose(std::shared_ptr<ov::op::v15::GroupQueryAttention> node);
minor: do we need this method as public?

2025-02-19 03:15 UTC, wine99 commented on src/common/transformations/include/transformations/op_conversions/group_query_attention_decomposition.hpp
> +    ov::OutputVector decompose(std::shared_ptr<ov::op::v15::GroupQueryAttention> node);
Done. Made it private

2025-02-19 10:04 UTC, mitruska commented
The related onnx tests are failing and need to be fixed:
```
[ RUN      ] IE_CPU.onnx_model_gqa_past_0_input_1_rotary
Segmentation fault (core dumped) 
```
The Interpreter (Template plugin), tests require ref impl for ScaledDotProductAttention which is not enabled yet, so with working CPU tests, the Interpreter could be excluded eventually (here [frontends/onnx/tests/runtime/interpreter/unit_test.manifest](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/onnx/tests/runtime/interpreter/unit_test.manifest)).
```
[ RUN      ] INTERPRETER.onnx_model_gqa_past_0_input_1_rotary
Interpreter backend doesn't implement evaluate method for OP ScaledDotProductAttention
```
Please take a look ([CI logs](https://github.com/openvinotoolkit/openvino/actions/runs/13404673919/job/37455312285?pr=28163#step:18:2898)).

2025-02-20 06:56 UTC, wine99 commented
The failed CI checks are:
- onnx frontend tests on windows, but based on [CI log](https://github.com/openvinotoolkit/openvino/actions/runs/13427692095/job/37516466539?pr=28163), all tests passed
- tensorflow layer tests on ubuntu, failed at fetching openvino tarball

2025-02-24 08:52 UTC, mitruska commented
build_jenkins

2025-02-25 15:31 UTC, mitruska approved these changes
In my opinion we could merge this work, and move forward to apply any improvements as a smaller changes if needed.

2025-02-25 15:31 UTC, mitruska commented on src/core/dev_api/openvino/op/group_query_attention.hpp
> +class OPENVINO_API GroupQueryAttention : public Op {
Is there any plugin able to support this GroupQueryAttention class right now or the decomposition to ScaleDotProductAttention is always needed and applied?

2025-02-26 01:48 UTC, wine99 commented on src/common/transformations/src/transformations/op_conversions/group_query_attention_decomposition.cpp
> +    auto real_seqlens = std::make_shared<v1::Add>(seqlens_elemi64, one);
Should I make this change in this PR?

2025-02-26 09:25 UTC, mitruska commented on src/common/transformations/src/transformations/op_conversions/group_query_attention_decomposition.cpp
> +    auto real_seqlens = std::make_shared<v1::Add>(seqlens_elemi64, one);
I've already approved, so I don't force this change in this PR (but it should be applied it as a follow up).
@itikhono Do you consider it as a blocker?

2025-03-08 11:52 UTC, ilya-lavrenov commented on src/frontends/onnx/tests/runtime/interpreter/unit_test.manifest
> +# Interpreter backend doesn't implement evaluate method for OP ScaledDotProductAttention
can we decompose ScaledDotProductAttention in template plugin? so, it can be inferred then

2025-03-10 08:57 UTC, itikhono commented on src/common/transformations/src/transformations/op_conversions/group_query_attention_decomposition.cpp
> +    auto real_seqlens = std::make_shared<v1::Add>(seqlens_elemi64, one);
this is not a blocker for this PR
but it's better to apply it in the next PR

2025-03-11 05:37 UTC, wine99 commented on src/frontends/onnx/tests/runtime/interpreter/unit_test.manifest
> +# Interpreter backend doesn't implement evaluate method for OP ScaledDotProductAttention
Done.

2025-03-11 06:27 UTC, itikhono commented on src/common/transformations/src/transformations/op_conversions/group_query_attention_decomposition.cpp
> +    // TODO: add softcap support
do we have a ticket for this?

2025-03-11 06:52 UTC, itikhono commented on src/common/transformations/src/transformations/op_conversions/group_query_attention_decomposition.cpp
> +    const auto zero = v0::Constant::create(ov::element::i32, ov::Shape{}, {0});
minor:
We use i64 in some places and i32 in others. There isn't a restriction to do so but  it's better to align element types, e.g. use i64

2025-03-11 06:52 UTC, itikhono commented on src/common/transformations/include/transformations/op_conversions/group_query_attention_decomposition.hpp
> +    ov::OutputVector decompose(std::shared_ptr<ov::op::GroupQueryAttention> node);
minor:
as I can see, these functions don't use any members of GroupQueryAttentionDecomposition and can be used separately,
so it's better to move it to unnamed namespace inside group_query_attention_decomposition.cpp file or to utils if we plan to re-use it

2025-03-11 06:52 UTC, itikhono commented on src/common/transformations/src/transformations/op_conversions/group_query_attention_decomposition.cpp
> +    else if (T == ov::element::f16)
it looks unsafe, `minus_inf` might be `nullptr` after this `if` in case of another type, probably now it's impossible but it's not guaranteed that it won't be extended in the future
should we throw exception or `return false` or add some default else branch if T is not f32, f16?
usually we prefer to `return false` not to break model inference, if no replacements or model modifications were done at this moment

2025-03-11 06:53 UTC, itikhono approved these changes

2025-03-11 07:11 UTC, itikhono commented
Approved. We agreed to resolve the remaining comments in the next PR

2025-03-11 07:13 UTC, wine99 commented on src/common/transformations/src/transformations/op_conversions/group_query_attention_decomposition.cpp
> +    else if (T == ov::element::f16)
Will address this in a following PR

2025-03-11 07:47 UTC, wine99 commented
@t-jankowski  @gkrivor  Could you review again?

2025-03-11 09:03 UTC, t-jankowski approved these changes
Ok for core part

2025-03-12 06:22 UTC, gkrivor approved these changes

2025-03-12 06:46 UTC, rkazants commented
build_jenkins

2025-03-13 01:27 UTC, XinWangIntel commented
build_jenkins

2025-03-13 09:13 UTC, t-jankowski commented
build_jenkins

2025-03-13 18:06 UTC, ilya-lavrenov commented on src/common/transformations/src/transformations/common_optimizations/common_optimizations.cpp
> +    ADD_MATCHER(decomp, GroupQueryAttentionDecomposition)
why is it added to main common optimization pass?
As I remember, initially such operation was supposed for NPU only, while CPU/GPU should not support models with GQA in any form.

2025-03-14 01:26 UTC, wine99 commented
Failed jobs in build_jenkins are same as in other PRs, e.g. commit fd793e4 in PR https://github.com/openvinotoolkit/openvino/pull/29446
![image](https://github.com/user-attachments/assets/72fc636a-b7a7-4f2b-9408-b8efa3b425aa)

2025-03-14 02:50 UTC, wine99 commented
CI status: 1 failing: [ie_tests_cldnn_unit_dg2_ubuntu22_release](https://openvino-ci.toolbox.iotg.sclab.intel.com/job/private-ci/job/ie/job/ie-tests-linux-ubuntu22-cldnn_unit_dg2/5433/)

Details: 1 unit test failed:
```
[2025-03-14T01:54:32.242Z] cldnn_unit_tests_dg2-0 INFO: [2261/22863] convolution_int8_fw_gpu.quantized_convolution_u8s8f32_asymmetric_activations_per_channel_dynamic (939 ms)
[2025-03-14T01:54:32.242Z] cldnn_unit_tests_dg2-0 INFO: ERROR: ld.so: object 'libSegFault.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
[2025-03-14T01:54:32.242Z] cldnn_unit_tests_dg2-0 INFO: Running main() from src/plugins/intel_gpu/tests/unit/gtest_main_gpu.cpp
[2025-03-14T01:54:32.242Z] cldnn_unit_tests_dg2-0 INFO: Env variable cl_cache_dir: /nfs/ov-share-02/data/volatile/cache/cl_cache_linux
[2025-03-14T01:54:32.242Z] cldnn_unit_tests_dg2-0 INFO: [0;33mNote: Google Test filter = convolution_int8_fw_gpu.quantized_convolution_u8s8f32_asymmetric_activations_per_channel_dynamic
[2025-03-14T01:54:32.242Z] cldnn_unit_tests_dg2-0 INFO: [m[0;32m[==========] [mRunning 1 test from 1 test suite.
[2025-03-14T01:54:32.242Z] cldnn_unit_tests_dg2-0 INFO: [0;32m[----------] [mGlobal test environment set-up.
[2025-03-14T01:54:32.242Z] cldnn_unit_tests_dg2-0 INFO: [0;32m[ PG INFO  ] [mPostgreSQL Reporting is disabled due to missing environment settings
[2025-03-14T01:54:32.242Z] cldnn_unit_tests_dg2-0 INFO: [0;32m[----------] [m1 test from convolution_int8_fw_gpu
[2025-03-14T01:54:32.242Z] cldnn_unit_tests_dg2-0 INFO: [0;32m[ RUN      ] [mconvolution_int8_fw_gpu.quantized_convolution_u8s8f32_asymmetric_activations_per_channel_dynamic
[2025-03-14T01:54:32.243Z] cldnn_unit_tests_dg2-0 INFO: src/plugins/intel_gpu/tests/unit/test_cases/convolution_gpu_test.cpp:4746: Failure
[2025-03-14T01:54:32.243Z] cldnn_unit_tests_dg2-0 INFO: The difference between output_vec[f][y][x] and ((float)output_ptr[f * y_size * x_size + y * x_size + x]) is 80, which exceeds 1e-5f, where
[2025-03-14T01:54:32.243Z] cldnn_unit_tests_dg2-0 INFO: output_vec[f][y][x] evaluates to -36,
[2025-03-14T01:54:32.243Z] cldnn_unit_tests_dg2-0 INFO: ((float)output_ptr[f * y_size * x_size + y * x_size + x]) evaluates to 44, and
[2025-03-14T01:54:32.243Z] cldnn_unit_tests_dg2-0 INFO: 1e-5f evaluates to 9.9999997473787516e-06.
[2025-03-14T01:54:32.243Z] cldnn_unit_tests_dg2-0 INFO:  x=0 y=0 f=0
[2025-03-14T01:54:32.243Z] cldnn_unit_tests_dg2-0 INFO: [0;31m[  FAILED  ] [mconvolution_int8_fw_gpu.quantized_convolution_u8s8f32_asymmetric_activations_per_channel_dynamic (417 ms)
[2025-03-14T01:54:32.243Z] cldnn_unit_tests_dg2-0 INFO: [0;32m[----------] [m1 test from convolution_int8_fw_gpu (417 ms total)
[2025-03-14T01:54:32.243Z] cldnn_unit_tests_dg2-0 INFO: 
[2025-03-14T01:54:32.243Z] cldnn_unit_tests_dg2-0 INFO: [0;32m[----------] [mGlobal test environment tear-down
[2025-03-14T01:54:32.243Z] cldnn_unit_tests_dg2-0 INFO: [0;32m[==========] [m1 test from 1 test suite ran. (419 ms total)
[2025-03-14T01:54:32.244Z] cldnn_unit_tests_dg2-0 INFO: [0;32m[  PASSED  ] [m0 tests.
[2025-03-14T01:54:32.244Z] cldnn_unit_tests_dg2-0 INFO: [0;31m[  FAILED  ] [m1 test, listed below:
[2025-03-14T01:54:32.244Z] cldnn_unit_tests_dg2-0 INFO: [0;31m[  FAILED  ] [mconvolution_int8_fw_gpu.quantized_convolution_u8s8f32_asymmetric_activations_per_channel_dynamic
[2025-03-14T01:54:32.244Z] cldnn_unit_tests_dg2-0 INFO: 
[2025-03-14T01:54:32.244Z] cldnn_unit_tests_dg2-0 INFO:  1 FAILED TEST
[2025-03-14T01:54:32.244Z] cldnn_unit_tests_dg2-0 INFO: [2261/22863] convolution_int8_fw_gpu.quantized_convolution_u8s8f32_asymmetric_activations_per_channel_dynamic returned/aborted with exit code 1 (939 ms)
```

The failure should not be related to this PR

2025-03-17 01:48 UTC, XinWangIntel commented
build_jenkins

2025-03-17 06:34 UTC, XinWangIntel commented
build_jenkins

2025-03-17 08:17 UTC, itikhono commented
build_jenkins

2025-03-17 12:37 UTC, praasz commented on src/core/dev_api/openvino/op/group_query_attention.hpp
> +namespace op {
```suggestion
namespace ov::op::internal {
```
Put it in internal namespace or give version

2025-03-17 12:37 UTC, praasz commented on src/core/src/op/group_query_attention.cpp
> +    Dimension sequence_len = q_shape[2];
```suggestion
    const atuo& batch_size = q_shape[0];
    const auto& sequence_len = q_shape[2];
```

2025-03-17 12:37 UTC, praasz commented on src/core/src/op/group_query_attention.cpp
> +    PartialShape q_shape = get_input_partial_shape(0);
```suggestion
    const auto& q_shape = get_input_partial_shape(0);
```

2025-03-17 12:37 UTC, praasz commented on src/core/src/op/group_query_attention.cpp
> +    NODE_VALIDATION_CHECK(this, q_shape[3].is_static(), "GroupQueryAttention: head size should not be dynamic");
The q_shape cannot be dynamic and must have correct rank to access [3] and 

Why dimension [3] cannot be dynamic?

2025-03-17 12:37 UTC, praasz commented on src/core/src/op/group_query_attention.cpp
> +    m_head_size = q_shape[3].get_length();
Operation `m_head_size * m_num_heads` is well supported for Dimension class. get length is not required.

2025-03-17 12:37 UTC, praasz commented on src/core/src/op/group_query_attention.cpp
> +    if (past_sequence_len.is_static() && sequence_len.is_static()) {
Why check both has to be static? 
The `+` is supported for dynamic dimensions.

2025-03-17 12:37 UTC, praasz commented on src/core/src/op/group_query_attention.cpp
> +    auto element_type = get_input_element_type(0);
```suggestion
    const auto& element_type = get_input_element_type(0);
```

2025-03-17 12:37 UTC, praasz commented on src/core/src/op/group_query_attention.cpp
> +    Dimension past_sequence_len = get_input_partial_shape(3)[2];
```suggestion
    const auto& past_sequence_len = get_input_partial_shape(3)[2];
```

2025-03-17 12:37 UTC, praasz commented on src/core/src/op/group_query_attention.cpp
> +    return std::make_shared<GroupQueryAttention>(new_args,
Add `check_new_args_count` before make operator.

2025-03-17 12:37 UTC, praasz commented on src/frontends/onnx/frontend/src/op/com.microsoft/group_query_attention.cpp
> +namespace detail {
```suggestion
namespace ov::frontend::onnx::com_microsoft::detail {
```

2025-03-18 06:12 UTC, wine99 commented
@praasz Suggestions applied

2025-03-18 13:30 UTC, itikhono commented
build_jenkins

2025-03-19 08:14 UTC, praasz approved these changes
Ok for core part

2025-03-19 10:15 UTC, merged