[ONNX]: add support for microsoft.range operator for ONNX frontend
openvinotoolkit/openvino pull request #28202
Opened 2024-12-25 09:17 UTC by 11happy

**Overview:**
This pull request fixes #17575 .

**Dependencies:**
- No dependencies on other pull requests.

**CC:**
- @p-wysocki , @mlukasze

2024-12-28 20:19 UTC, 11happy commented
Humble Ping @mlukasze , @p-wysocki to please review this PR.
Thank you

2024-12-30 08:04 UTC, sshlyapn commented
@11happy could you please remove GPU's onednn submodule update from the changes?

2024-12-30 17:46 UTC, 11happy commented
@sshlyapn I have removed this submodule

2025-01-02 17:25 UTC, 11happy commented
@sshlyapn can you please review this

2025-01-03 05:01 UTC, p-durandin commented
build_jenkins

2025-01-04 19:22 UTC, 11happy commented
I ran clang format to resolve some of the build issues.
Thank you

2025-01-06 05:19 UTC, p-durandin commented
build_jenkins

2025-01-06 05:48 UTC, p-durandin commented
@11happy please check if oneDNN changes are required. Looks not

2025-01-07 07:03 UTC, p-durandin commented
@11happy, thanks. GPU review is not required for this PR

2025-01-13 08:23 UTC, gkrivor requested changes
Hi, could you apply a few comments, please? And as I may see - PR is mostly ready for merge.

2025-01-13 08:23 UTC, gkrivor commented on src/frontends/onnx/frontend/src/op/com.microsoft/range.cpp
> +// Copyright (C) 2018-2024 Intel Corporation
Please, use 2025 for now :) Happy new year!

2025-01-13 08:23 UTC, gkrivor commented on src/frontends/onnx/frontend/src/op/com.microsoft/range.cpp
> +    FRONT_END_GENERAL_CHECK(nodes.size() >= 2 && nodes.size() <= 3,
Please, use commom::default_op_checks procedure from "utils/common.hpp". Like here: https://github.com/openvinotoolkit/openvino/blob/0db7f8e5d603e5212bf0731e5a08147b1e269f5b/src/frontends/onnx/frontend/src/op/com.microsoft/simplified_layer_normalization.cpp#L28

2025-01-13 08:23 UTC, gkrivor commented on src/frontends/onnx/frontend/src/op/com.microsoft/range.cpp
> +    auto start = nodes.at(0);
And use nodes[0] and nodes[1] for inputs which availability was checked before.

2025-01-13 08:23 UTC, gkrivor commented on src/frontends/onnx/frontend/src/op/com.microsoft/range.cpp
> +    auto step =
https://github.com/microsoft/onnxruntime/blob/main/docs/ContribOperators.md#com.microsoft.Range

Documentation requires same input tensors for all inputs. Could you add a check for element types?

Like here: https://github.com/openvinotoolkit/openvino/blob/0db7f8e5d603e5212bf0731e5a08147b1e269f5b/src/frontends/onnx/frontend/src/op/com.microsoft/simplified_layer_normalization.cpp#L34

2025-01-13 17:06 UTC, 11happy commented on src/frontends/onnx/frontend/src/op/com.microsoft/range.cpp
> +// Copyright (C) 2018-2024 Intel Corporation
done.
Happy new year :)

2025-01-13 17:06 UTC, 11happy commented on src/frontends/onnx/frontend/src/op/com.microsoft/range.cpp
> +    FRONT_END_GENERAL_CHECK(nodes.size() >= 2 && nodes.size() <= 3,
done

2025-01-13 17:06 UTC, 11happy commented on src/frontends/onnx/frontend/src/op/com.microsoft/range.cpp
> +    auto start = nodes.at(0);
done

2025-01-13 17:08 UTC, 11happy commented on src/frontends/onnx/frontend/src/op/com.microsoft/range.cpp
> +    auto step =
I have added this , but this is causing repeated code which I think is not preferred , so should I put this in a loop or something like that?

2025-01-13 17:10 UTC, 11happy commented on src/frontends/onnx/frontend/src/op/com.microsoft/range.cpp
> +    auto step =
also I have changed step to delta to keep it consistent with documentation.
thank you

2025-01-14 05:31 UTC, gkrivor commented
build_jenkins

2025-01-14 06:05 UTC, 11happy commented
the range without delta is failing & i don't understand why.
```
FrontEnd API failed with GeneralFailure:
Errors during ONNX translation:
Check '(inputs.size() >= 3)' failed at src/frontends/onnx/frontend/src/op/range.cpp:19:
While validating ONNX node '<Node(Range): output>':
Minimum 3 inputs are required. Got: 2
" thrown in the test body.
[  FAILED  ] IE_CPU.onnx_com_microsoft_range_without_delta (1 ms)

```

2025-01-14 07:47 UTC, gkrivor commented
> the range without delta is failing & i don't understand why.
> 
> ```
> FrontEnd API failed with GeneralFailure:
> Errors during ONNX translation:
> Check '(inputs.size() >= 3)' failed at src/frontends/onnx/frontend/src/op/range.cpp:19:
> While validating ONNX node '<Node(Range): output>':
> Minimum 3 inputs are required. Got: 2
> " thrown in the test body.
> [  FAILED  ] IE_CPU.onnx_com_microsoft_range_without_delta (1 ms)
> ```
> 
> it says the check if line 19 `inputs.size()>=3` but I have already updated the checks in recent commit

You forgot to explicitly set node domain to "com.microsoft", so it was using Range from default opset instead of your implementation. Let's see how it will work now.

2025-01-14 12:12 UTC, gkrivor commented
build_jenkins

2025-01-15 12:01 UTC, gkrivor approved these changes

2025-01-15 13:52 UTC, merged