Hunyuan-3b model support kvcache and gqa fusion
openvinotoolkit/openvino pull request #28210
Opened 2024-12-26 08:19 UTC by zhaohb

### Details:
This pr enables the Hunyuan-3B model to utilize OpenVINO for inference, achieving excellent performance.

2025-01-02 04:46 UTC, ceciliapeng2011 requested changes

2025-01-02 04:46 UTC, ceciliapeng2011 commented on src/plugins/intel_gpu/src/plugin/transformations/kv_cache_fusion.cpp
> +        //    return false;
It intents to make sure the inputs and output of concat are with the same data type. Instead of deleting the check (which would lead to potential risk to inference result and hard to debug), a better check here may be, I think, to check the data type consistency of concat_past_input->get_output_element_type(0) and concat_node->get_output_element_type(0).

2025-01-03 02:45 UTC, zhaohb commented on src/plugins/intel_gpu/src/plugin/transformations/kv_cache_fusion.cpp
> +        //    return false;
had fix, thank you very much.

2025-01-06 02:54 UTC, ceciliapeng2011 approved these changes
LGTM... leave a minor comment to see if it could be removed.

2025-01-06 02:55 UTC, ceciliapeng2011 commented on src/plugins/intel_gpu/src/plugin/transformations/kv_cache_fusion.cpp
> +        // // TODO: Support conversion internally
minor: to see if we can remove this check later.

2025-01-06 02:57 UTC, ceciliapeng2011 approved these changes

2025-01-06 03:02 UTC, zhaohb commented on src/plugins/intel_gpu/src/plugin/transformations/kv_cache_fusion.cpp
> +        // // TODO: Support conversion internally
ok, thank you.

2025-01-06 14:15 UTC, Lyamin-Roman approved these changes

2025-01-07 06:06 UTC, riverlijunjie approved these changes
Look good, could you add some tests similar with Hunyuan model's case?

2025-01-07 06:55 UTC, p-durandin approved these changes

2025-01-07 08:52 UTC, merged