Disable constexpr mutex constructors for MSVC
openvinotoolkit/openvino pull request #28225
Opened 2024-12-29 12:33 UTC by p-wysocki

### Details:
 - In specific scenarios (customer script) a segfault happens when constructing `std::lock_guard<std::mutex>`
 - The issue is linked to VC 22
 - The origin of the issue lies within the environment, a mismatch between VS used to build and VS runtime
 - Disabling constexpr mutex constructors for MSVC specifically fixes the issue
 - More info: https://developercommunity.visualstudio.com/t/Crash-SEGV-in-mutex-lock/10679088#T-N10680013

### Tickets:
 - CVS-159653

2024-12-30 07:24 UTC, ilya-lavrenov requested changes
We have it globally enabled for the project https://github.com/openvinotoolkit/openvino/blob/2ef42d4b93c7a42cfac698608f16e131fa59f5aa/cmake/developer_package/compile_flags/os_flags.cmake#L458-L462

is it not enough?

2025-01-02 09:47 UTC, p-wysocki commented
I see it has been added on December 20th, while on my laptop I built master from December 19th. I didn't update branch due to long build time, I'll rebuild now and confirm the new flag also fixes CVS-159653.

2025-01-03 14:48 UTC, p-wysocki commented
Fixed in another PR. Waiting for confirmation from @olpipi before closing the ticket.

2025-01-03 14:48 UTC, closed without merging

2025-01-07 17:07 UTC, olpipi commented
This fix works but it doesn't cover all msvc version with v143 toolset according to https://cmake.org/cmake/help/latest/variable/MSVC_VERSION.html
I open a PR to fix it:
https://github.com/openvinotoolkit/openvino/pull/28300