[GNA] Added tests for negative memory layer offset and split - trivial permute - concat scenario
openvinotoolkit/openvino pull request #2989
Opened 2020-11-05 13:49 UTC by elilobanova

2020-11-06 08:47 UTC, bsochack commented on inference-engine/tests/functional/plugin/shared/src/subgraph_tests/negative_memory_layer_offset.cpp
> +        auto input = ngraph::builder::makeParams(ngPrc, { {1, 384} });
it would be great to test various sizes, 64B aligned and non-aligned.

2020-11-06 08:47 UTC, bsochack commented on inference-engine/tests/functional/plugin/shared/src/subgraph_tests/split_trivial_permute_concat.cpp
> +        auto input = ngraph::builder::makeParams(ngPrc, { {16, 1, 2, 64} });
Please try to make test more generic to test various combinations of input sizes, split and concat.

2020-11-10 11:04 UTC, bsochack approved these changes

2020-11-10 17:01 UTC, kmagiers requested changes

2020-11-10 17:01 UTC, kmagiers commented on inference-engine/tests/functional/plugin/shared/src/subgraph_tests/split_trivial_permute_concat.cpp
> +
remove unnecessary empty lines

2020-11-12 13:19 UTC, kmagiers approved these changes

2020-11-12 14:07 UTC, merged