[IE CLDNN] Add asymmetric quantization support to reference convolution imad kernel
openvinotoolkit/openvino pull request #2994
Opened 2020-11-05 18:15 UTC by jhajducz

This patch is meant to:

- add asymmetric quantization support (for both activations and weights) with and without using compensation term to fused_conv_eltwise_gpu_imad kernel

JIRA: CVS-25121

2020-11-09 09:46 UTC, lznamens requested changes

2020-11-09 09:46 UTC, lznamens commented on inference-engine/thirdparty/clDNN/kernel_selector/core/cl_kernels/fused_conv_eltwise_gpu_imad.cl
> +                        int f_addr = ((feature_location + v) / FSV + INPUT0_PAD_BEFORE_FEATURE_NUM / FSV) * INPUT0_FEATURE_PITCH * FSV  + (feature_location + v) % FSV;
Code style: too long line.

2020-11-09 09:46 UTC, lznamens commented on inference-engine/thirdparty/clDNN/kernel_selector/core/cl_kernels/fused_conv_eltwise_gpu_imad.cl
> +            w[8]= as_int(intel_sub_group_block_read((const __global uint*) &weights[weight_addr + (SIMD_SIZE<<3)]));
Please add space after w[8].

2020-11-09 09:46 UTC, lznamens commented on inference-engine/thirdparty/clDNN/kernel_selector/core/cl_kernels/fused_conv_eltwise_gpu_imad.cl
> +                            dotProdAxWZP = TO_ACCUMULATOR_TYPE(
I think that you should use a single code style for IMAD (don't split code line as you did it on the line 305).

2020-11-09 09:46 UTC, lznamens commented on inference-engine/thirdparty/clDNN/kernel_selector/core/cl_kernels/fused_conv_eltwise_gpu_imad.cl
> +                    in_addr += (INPUT0_SIZE_X + IWPAD) * 16;
Wrong alignment.

2020-11-09 09:46 UTC, lznamens commented on inference-engine/thirdparty/clDNN/kernel_selector/core/cl_kernels/fused_conv_eltwise_gpu_imad.cl
> +            for(int pf=0; pf < NUM_FILTERS; pf++) {
In other cycles you use code style looks like "pf = 0" (with spaces before and after the symbol of equality).

2020-11-09 09:46 UTC, lznamens commented on inference-engine/thirdparty/clDNN/kernel_selector/core/cl_kernels/fused_conv_eltwise_gpu_imad.cl
> +#ifdef NON_ZERO_INPUT0_PAD_BEFORE
I think you can avoid this checks and in all cases can use #undef instead of #ifdef - #undef - #endif.

2020-11-10 09:17 UTC, sshlyapn approved these changes
In general looks good to me

2020-11-10 09:17 UTC, sshlyapn commented on inference-engine/thirdparty/clDNN/kernel_selector/core/cl_kernels/fused_conv_eltwise_gpu_imad.cl
> +                            in[reg] = AS_PACKED_TYPE(conv_input[in_addr]);// read SIMD_SIZE elements wide
nit: please add space before comment

2020-11-10 09:17 UTC, sshlyapn commented on inference-engine/thirdparty/clDNN/kernel_selector/core/actual_kernels/convolution/convolution_kernel_imad.cpp
> +    else if (conv_params.quantization == QuantizationType::ASYMMETRIC_DATA) {
nit: please move `else if` to the previous line:
`    } else if (conv_params.quantization == QuantizationType::ASYMMETRIC_DATA) {`

2020-11-11 07:27 UTC, lznamens approved these changes
Thanks for fixes. Current changes look good to me.

2020-11-11 09:38 UTC, merged