Hard sigmoid ref impl
openvinotoolkit/openvino pull request #3100
Opened 2020-11-12 13:30 UTC by pszmel

Overview:
  1) Update spec 
  2) Create Hard sigmoid reference implementation
  3) Add Hard sigmoid to int_executable
  4) Create unit tests 
  5) Create onnx_model test

2020-11-13 09:33 UTC, mbencer requested changes

2020-11-13 09:33 UTC, mbencer commented on ngraph/test/runtime/interpreter/int_executable.hpp
> +        case OP_TYPEID::HardSigmoid:
I think that ref impl should be called as evaluate method in ngraph/core/src/op/hard_sigmoid

2020-11-13 09:42 UTC, mbencer approved these changes

2020-11-16 10:47 UTC, ilyachur commented on ngraph/core/reference/include/ngraph/runtime/reference/hard_sigmoid.hpp
> +            void hard_sigmoid(const T* arg, const T* alpha, const T* beta, T* out, size_t count)
Why do we need to pass `alpha` and `beta` by pointers? Looks like we can pass it by value.

2020-11-16 19:32 UTC, iefode approved these changes

2020-11-17 09:02 UTC, ilyachur approved these changes

2020-11-18 03:55 UTC, ilyachur commented
@pszmel Please rebase this PR on the latest master.

2020-11-18 12:52 UTC, merged