[DOC] ShapeInference.md update. slyalin comments
openvinotoolkit/openvino pull request #3355
Opened 2020-11-25 13:13 UTC by jane-intel

2020-11-25 16:43 UTC, aalborov requested changes

2020-11-25 16:43 UTC, aalborov commented on docs/IE_DG/ShapeInference.md
> +   It assumes batch is placed under the index 0 in the shape for all the inputs and uses `InferenceEngine::CNNNetwork::reshape` method to propagate updated shapes through the model.
```suggestion
   It assumes that the batch is placed at the 0 index in the shape for all inputs and uses the `InferenceEngine::CNNNetwork::reshape` method to propagate updated shapes through the model.
```

2020-11-25 16:43 UTC, aalborov commented on docs/IE_DG/ShapeInference.md
> +   * scalar, 1D, 3D input or input without a batch dimension
```suggestion
   * Multiple inputs with different 0 index dimension meanings
   * Input without a batch dimension
   * Scalar, 1D, or 3D input or input without a batch dimension
```

Doesn't the 3d point include the 2nd?

2020-11-25 16:43 UTC, aalborov commented on docs/IE_DG/ShapeInference.md
> +   Please use `InferenceEngine::CNNNetwork::reshape` for all the other models.
```suggestion
   The `InferenceEngine::CNNNetwork::setBatchSize` method is a high-level API method that wraps the `InferenceEngine::CNNNetwork::reshape` method call and works for trivial models from the batch placement standpoint.
   Use `InferenceEngine::CNNNetwork::reshape` for other models.
```

2020-11-25 16:43 UTC, aalborov commented on docs/IE_DG/ShapeInference.md
> +   Using `InferenceEngine::CNNNetwork::setBatchSize` method for models with a non-zero index batch placement or models with inputs without a batch dimension may lead to undefined behaviour.
```suggestion
   Using the `InferenceEngine::CNNNetwork::setBatchSize` method for models with a non-zero index batch placement or for models with inputs that do not have a batch dimension may lead to undefined behaviour.
```

2020-11-25 18:21 UTC, jane-intel commented on docs/IE_DG/ShapeInference.md
> +   * Scalar, 1D, or 3D input or input without a batch dimension
```suggestion
   * 0D, 1D, or 3D shape
```

2020-11-30 12:04 UTC, aalborov approved these changes
Just an afterthought on *zero-index dimension meanings*, please apply if it doesn't ruin the sense.

2020-11-30 12:04 UTC, aalborov commented on docs/IE_DG/ShapeInference.md
> +   * Multiple inputs with different zero index dimension meanings
```suggestion
   * Multiple inputs with different zero-index dimension meanings
```

2020-11-30 13:39 UTC, merged