[GNA] Fix import model with header version 2.1
openvinotoolkit/openvino pull request #3362
Opened 2020-11-25 15:57 UTC by admitriev-gna

2020-11-26 06:52 UTC, bsochack approved these changes
Is there any possibility to add test?

2020-11-26 11:17 UTC, aalbersk approved these changes

2020-11-26 11:20 UTC, aalbersk commented
> Is there any possibility to add test?

+1 on this one. If there'll be a possibility to have tests for all header versions, or at least the 1st one, it would be perfect

2020-11-26 12:53 UTC, aalbersk commented
Did the 2.1 header work when 2.3 was the latest one? If no, then, the [constructor for 2.1 in 2.3](https://github.com/openvinotoolkit/openvino/blob/master/inference-engine/src/gna_plugin/serial/headers/2dot3/gna_model_header.hpp#L70) is redundant and incorrect and should be removed or fixed.

2020-12-08 10:40 UTC, iefode requested changes

2020-12-08 10:40 UTC, iefode commented on inference-engine/tests/functional/plugin/shared/include/behavior/test_model_repo.hpp
> +#ifdef MODELS_PATH
Why do you add `MODELS_PATH` from deprecated_tests? We refused to use these variables in new tests

2020-12-09 09:22 UTC, admitriev-gna commented on inference-engine/tests/functional/plugin/gna/backword_compatibility.cpp
> +class BackwardCompatibilityTest : public testing::WithParamInterface<exportImportNetworkParams>,
Tests that are imported with versions 2.1 and 2.2 failing without changes.

2020-12-09 09:25 UTC, admitriev-gna commented on inference-engine/tests/functional/plugin/gna/backword_compatibility.cpp
> +        std::string inputTensorBinary = TestDataHelpers::get_data_path() + "/gna/" + nameExportModel;
I created a pull request, where I added exported models with different versions: https://github.com/openvinotoolkit/testdata/pull/3

2020-12-09 11:50 UTC, bsochack commented on inference-engine/tests/functional/plugin/gna/backword_compatibility.cpp
> +        std::string inputTensorBinary = TestDataHelpers::get_data_path() + "/gna/" + nameExportModel;
great. thanks!

2020-12-10 09:17 UTC, bsochack approved these changes

2021-01-15 16:36 UTC, dorloff commented on inference-engine/tests/functional/plugin/gna/shared_tests_instances/import_export_tests/backword_compatibility.cpp
> +// Copyright (C) 2020 Intel Corporation
backwArd compatibility. Please correct.

2021-01-18 11:13 UTC, iefode approved these changes

2021-02-19 10:05 UTC, closed without merging