Add MVN-6 support to ngraph
openvinotoolkit/openvino pull request #3464
Opened 2020-12-03 11:25 UTC by mvafin

Ticket: #30071

2020-12-04 04:47 UTC, ilyachur commented on inference-engine/tests/functional/inference_engine/ngraph_reader/mvn_tests.cpp
> +		<layer name="Const_1" type="Const" precision="FP32" id="2">
Several questions about tests:

- Could we keep tests for MVN from previous opsets?
- Why do you change the legacy IR? In legacy IR we didn't have `Const` layers and MVN layer didn't have `eps_mode` atribute.

2020-12-04 04:47 UTC, ilyachur commented on ngraph/core/include/ngraph/op/mvn.hpp
> +            enum class EpsMode
Why do we need this enum?

2020-12-04 04:47 UTC, ilyachur commented on ngraph/core/include/ngraph/op/util/attr_types.hpp
> +    class NGRAPH_API AttributeAdapter<op::MVNEpsMode>
I propose to have this `AttributeAdapter` in the same file with MVN operation.

2020-12-09 10:01 UTC, rkazants requested changes

2020-12-09 10:01 UTC, rkazants commented on ngraph/core/src/op/mvn.cpp
> +    set_output_type(0, get_input_element_type(0), get_input_partial_shape(0));
I missed some checks here: 1. `data` rank >= length(axes); 2. axes is 1d tensor. In more cases axes is a constant so we can check their values as well

2020-12-10 10:31 UTC, mvafin commented on ngraph/core/src/op/mvn.cpp
>  NGRAPH_SUPPRESS_DEPRECATED_START
It is there already

2020-12-11 12:23 UTC, ilyachur approved these changes

2020-12-11 12:23 UTC, ilyachur commented on ngraph/core/include/ngraph/op/mvn.hpp
> +                virtual std::shared_ptr<Node>
`virtual` is redundant

2020-12-14 08:22 UTC, iimironov approved these changes

2020-12-14 08:56 UTC, iefode commented
Are you going to update ngraph reference implementation?

2020-12-15 08:07 UTC, mvafin commented
> Are you going to update ngraph reference implementation?

Yes, but in different PR.

2020-12-15 16:11 UTC, lazarevevgeny approved these changes

2020-12-15 18:36 UTC, rkazants approved these changes

2020-12-15 18:36 UTC, merged