Avgpool revise
openvinotoolkit/openvino pull request #3674
Opened 2020-12-18 11:42 UTC by pszmel

1. Update the spec
2. Create unit-tests
3. Remove second constructor and add default values to the first one
4. Add type_prop tests for default values
5. Add 5D input single layer test instances
6. Update validate_and_infer_types method
7. Update infer_batched_pooling_forward and try_apply_auto_padding methods
8. Update auto_padding_spatial_dims_dynamic type_prop test for binary_conv, conv, deformable_conv, group_conv and max_pool

Changes in infer_batched_pooling_forward and try_apply_auto_padding required me to change the expected pads_begin and pads_end in 1 type_prop test for ops listed in point 8.

ticket: 37422

2020-12-22 11:45 UTC, lazarevevgeny requested changes

2020-12-28 20:12 UTC, lazarevevgeny requested changes

2020-12-28 20:12 UTC, lazarevevgeny commented on docs/ops/pooling/AvgPool_1.md
> +        <data auto_pad="same_upper" exclude-pad="true" kernel="2,2" pads_begin="0,0" pads_end="1,1" strides="2,2"/>
`exclude-pad` -> `exclude_pad`.

2020-12-28 20:12 UTC, lazarevevgeny commented on docs/ops/pooling/AvgPool_1.md
> +        <data auto_pad="explicit" exclude-pad="true" kernel="2,2" pads_begin="1,1" pads_end="1,1" strides="2,2"/>
wrong indentation

2020-12-28 20:12 UTC, lazarevevgeny commented on docs/ops/pooling/AvgPool_1.md
> +        <data auto_pad="valid" exclude-pad="true" kernel="2,2" pads_begin="1,1" pads_end="1,1" strides="2,2"/>
Wrong indentation.

2020-12-28 20:12 UTC, lazarevevgeny commented on docs/ops/pooling/AvgPool_1.md
>  <layer ... type="AvgPool" ... >
All cases are for `exclude_pad="true"`. Please, provide examples where `exclude_pad="false"`

2020-12-28 20:12 UTC, lazarevevgeny commented on docs/ops/pooling/AvgPool_1.md
> +            <dim>32</dim>
wrong dimension

2020-12-28 20:12 UTC, lazarevevgeny commented on docs/ops/pooling/AvgPool_1.md
> +  * **1**: Input shape can be either (N,C,H), (N,C,H,W) or (N,C,H,W,D). Then the corressponding output shape will be (N,C,H_out), (N,C,H_out,W_out) or (N,C,H_out,W_out,D_out)
Change "(N,C,H)" to "`[N, C, H]`" (use back tick characters "`").  The same for other dimensions.

2020-12-28 20:12 UTC, lazarevevgeny commented on docs/ops/pooling/AvgPool_1.md
> +        D_out = (H + pads_begin[2] + pads_end[2] - kernel[2] / strides[2]) + 1
Move this code to the "Detailed description section."

2020-12-28 20:12 UTC, lazarevevgeny commented on docs/ops/pooling/AvgPool_1.md
> +        H_out = (H + pads_begin[0] + pads_end[0] - kernel[0] / strides[0]) + 1
Surround formula with back tick characters "`"

2020-12-28 20:12 UTC, lazarevevgeny commented on docs/ops/pooling/AvgPool_1.md
> +  * **1**: Input shape can be either (N,C,H), (N,C,H,W) or (N,C,H,W,D). Then the corressponding output shape will be (N,C,H_out), (N,C,H_out,W_out) or (N,C,H_out,W_out,D_out)
"corressponding" -> "corresponding"

2020-12-28 20:12 UTC, lazarevevgeny commented on docs/ops/pooling/AvgPool_1.md
> +  * **1**: Input shape can be either (N,C,H), (N,C,H,W) or (N,C,H,W,D). Then the corressponding output shape will be (N,C,H_out), (N,C,H_out,W_out) or (N,C,H_out,W_out,D_out)
"shape will be" -> "shape is"

2021-01-05 10:24 UTC, mbencer approved these changes

2021-01-05 10:33 UTC, mbencer commented
Pooling from ONNX supports 1D and 2D cases. How to deal with it? Do we need new ops in new version?
@lazarevevgeny What do you think?

2021-01-12 16:00 UTC, lazarevevgeny requested changes

2021-01-12 16:09 UTC, pszmel commented on ngraph/test/type_prop/convolution.cpp
> +    ASSERT_EQ(conv->get_pads_end(), (CoordinateDiff{0, 1}));
I wrote about that in the description section

2021-01-13 13:48 UTC, lazarevevgeny approved these changes

2021-01-13 21:23 UTC, ilyachur approved these changes

2021-01-13 21:23 UTC, merged