Fixed issue with run stateful network with several infer requests on MKLDNNPlugin
openvinotoolkit/openvino pull request #3711
Opened 2020-12-23 10:39 UTC by sadolini

43825
Before changes in state API stateful networks were run only through 1 infer request. Now we can run stateful network with several infer requests for independent data for example. According tests were added.

2020-12-29 08:54 UTC, vgavrilo approved these changes

2020-12-29 09:17 UTC, alexey-varyzgin requested changes

2020-12-29 09:17 UTC, alexey-varyzgin commented on inference-engine/src/mkldnn_plugin/mkldnn_infer_request.cpp
> +                    std::memcpy(cur_state_mem_buf, data_ptr, data_size);
Could you use cpu_memcpy from common/cpu_memcpy.h

2021-01-15 07:39 UTC, alexey-varyzgin approved these changes

2021-01-15 07:41 UTC, alexey-varyzgin requested changes

2021-01-15 07:41 UTC, alexey-varyzgin commented on inference-engine/src/mkldnn_plugin/mkldnn_memory_state.h
> +        std::memcpy(this->storage->buffer(), storage->GetData(), storage->GetSize());
Could you use cpu_memcpy instead of std::memcpy

2021-01-21 07:20 UTC, alexey-varyzgin approved these changes

2021-01-21 07:32 UTC, yekruglov approved these changes

2021-01-21 12:00 UTC, dmitry-gorokhov approved these changes

2021-01-21 12:01 UTC, merged