Fixed mapping of input name
openvinotoolkit/openvino pull request #3737
Opened 2020-12-24 21:18 UTC by popovaan

Description: Fixed bug in mapping of input name which occurred when mean and scale preprocessing is added to model. 

JIRA: 28545

Code:
* [ ]  Comments
* [ ]  Code style (PEP8)
* [ ]  Transformation generates reshape-able IR
* [ ]  Transformation preserves original framework node names

Validation:
* [ ]  Unit tests
* [ ]  Framework operation tests - N/A
* [ ]  Transformation tests
* [ ]  e2e model test with an update of ./tests/e2e_oss/utils/reshape_utils.py - N/A
* [ ]  Model Optimizer IR Reader check

Documentation:
* [ ]  Supported frameworks operations list - N/A
* [ ]  Supported **public** models list - N/A
* [ ]  New operations specification - N/A
* [ ]  Guide on how to convert the **public** model - N/A
* [ ]  User guide update - N/A

2020-12-25 05:51 UTC, lazarevevgeny requested changes

2020-12-25 05:51 UTC, lazarevevgeny commented on model-optimizer/extensions/middle/AddMeanScaleValues_test.py
> +        graph_ref['fw_tensor_debug_info'] = ['data_attributes', 0]
Using this approach the `'fw_tensor_debug_info'` attribute is set for all data nodes in the graph. But it should be set to the data node of the `Parameter`. The rest data nodes should not be affected.

2020-12-25 05:51 UTC, lazarevevgeny commented on model-optimizer/extensions/middle/AddMeanScaleValues_test.py
> +                self.assertTrue(graph.node[node_name]['fw_tensor_debug_info'] == graph_ref.node[node_name]['fw_tensor_debug_info'])
This function should check that `Parameter`s data nodes have the same value for `'fw_tensor_debug_info'` attribute and that the rest of data nodes does not have it.

2020-12-25 05:51 UTC, lazarevevgeny commented on model-optimizer/extensions/middle/AddMeanScaleValues_test.py
> +def set_graph_attrs(graph, graph_ref):
The function should have just one parameter - the graph to set attrs. And it will be called twice in each test: for the `graph` and `graph_ref`.

2020-12-25 05:51 UTC, lazarevevgeny commented on model-optimizer/extensions/middle/AddMeanScaleValues_test.py
> +                                   'fw_tensor_debug_info': 'Placeholder'}),
Is the `fw_tensor_debug_info` attribute set for the data node? I think that it is set for the operation node, which is not what we want.

2020-12-25 05:51 UTC, lazarevevgeny commented on model-optimizer/extensions/middle/AddMeanScaleValues.py
> +                tmp = input_node.out_node(0)['fw_tensor_debug_info']
Please, add a comment here why we keep the `'fw_tensor_debug_info'` in the data node of the Parameter.

2020-12-27 18:45 UTC, lazarevevgeny requested changes

2020-12-27 18:45 UTC, lazarevevgeny commented on ngraph/frontend/onnx_import/src/op/softmax.cpp
> +                return std::make_shared<default_opset::Reshape>(result, data_shape, special_zero);
These changes should not belong to your review. Please, merge master branch properly.

2020-12-28 13:22 UTC, lazarevevgeny commented on model-optimizer/extensions/middle/AddMeanScaleValues_test.py
> +from mo.graph.graph import Graph, Node
Please, sort imports. And modify the code according to PEP8.

2020-12-28 13:41 UTC, lazarevevgeny approved these changes

2020-12-28 13:43 UTC, vgavrilo approved these changes

2020-12-28 14:10 UTC, rkazants commented on model-optimizer/extensions/middle/AddMeanScaleValues.py
> +                tmp = input_node.out_node(0)['fw_tensor_debug_info']
could you please rename `tmp` variable because now it sounds as artifact remained after debugging:)

2020-12-28 14:10 UTC, rkazants approved these changes
I have a comment. I suggest fixing it.

2020-12-28 19:43 UTC, merged