Base cancelation implementation
openvinotoolkit/openvino pull request #3805
Opened 2021-01-11 18:42 UTC by apankratovantonp

* Cancelation state is now part of base synchronization implementation
* Added new API for plugin developer. It is used to throw exception if inference request is canceled:
```c++
AsyncInferRequestThreadSafeInternal::CheckCanceled();
```
* Added usage example into MKLDNN Plugin

2021-01-11 22:00 UTC, apankratovantonp commented
waiting for https://github.com/openvinotoolkit/openvino/pull/3699 PR merge

2021-01-12 09:10 UTC, ilya-lavrenov commented
CC @Drizshko

2021-01-14 12:12 UTC, myshevts approved these changes

2021-01-15 14:16 UTC, myshevts requested changes

2021-01-18 07:48 UTC, myshevts requested changes

2021-01-29 16:43 UTC, myshevts commented
@apankratovantonp I suggest you close on the review remarks and merge, as we need a fix for the current cancelation impl,

2021-01-29 18:40 UTC, apankratovantonp commented
> @apankratovantonp I suggest you close on the review remarks and merge, as we need a fix for the current cancelation impl,

Was going to wait for https://github.com/openvinotoolkit/openvino/pull/4045 and add canceletion check API to base IR implementation. 

But if we need it ASAP going to merge with MKLDNN Specific API

2021-02-03 14:38 UTC, myshevts approved these changes

2021-02-03 16:31 UTC, myshevts commented
I have already reviewed/discussed and approved the adressed changes and the PR overall.
@apankratovantonp notice the conflicts with master you have to resolve first

2021-02-03 16:34 UTC, ilya-lavrenov approved these changes

2021-02-04 08:19 UTC, merged