[CPU] CumSum tensors with rank >= 6 support.
openvinotoolkit/openvino pull request #3859
Opened 2021-01-14 13:56 UTC by apertovs

issue: #41817

2021-01-14 14:07 UTC, dmitry-gorokhov commented
@mandrono please review

2021-01-15 17:01 UTC, mandrono requested changes

2021-01-15 17:05 UTC, mandrono commented
@apertovs 
could you also add changes in config creation?
69 line: ```Precision inPrecision = i == 1 ? Precision::I32 : layer->insData[i].lock()->getTensorDesc().getPrecision();```

2021-01-19 08:56 UTC, mandrono approved these changes

2021-01-19 08:56 UTC, mandrono commented on inference-engine/src/mkldnn_plugin/nodes/cum_sum.cpp
> +                Precision inPrecision = i == 1 ? Precision(Precision::I32) : layer->insData[i].lock()->getTensorDesc().getPrecision();
minor comment
not necessary explicitly call constructor for ```Precision```
https://github.com/openvinotoolkit/openvino/blob/master/inference-engine/src/mkldnn_plugin/nodes/non_max_suppression.cpp#L122

2021-01-26 13:19 UTC, dmitry-gorokhov commented on inference-engine/src/mkldnn_plugin/nodes/cum_sum.cpp
> +    void parallelItStep(std::vector<size_t>& counters, std::vector<size_t>& iterationRange) {
1. Since `iterationRange` is not changed inside the routine please make it const. The same for `parallelItInit`

2021-01-26 13:19 UTC, dmitry-gorokhov commented on inference-engine/src/mkldnn_plugin/nodes/cum_sum.cpp
> +    size_t getStartOffset(const std::vector<size_t> &forStartOffset, const std::vector<size_t>& strides) const {
It makes sense to mark the function inplace since it is called in the `iwork` loop.  Same for `parallelItStep`

2021-01-26 13:33 UTC, dmitry-gorokhov commented
@apertovs Please rebase your branch on latest master as well

2021-01-28 08:47 UTC, dmitry-gorokhov approved these changes
Please make CI green so I could merge the PR.

2021-02-02 07:45 UTC, merged