Add a target to fetch and build Intel SEAPI
openvinotoolkit/openvino pull request #3915
Opened 2021-01-19 10:37 UTC by ilyachur

2021-01-19 20:31 UTC, asomsiko requested changes

2021-01-19 20:31 UTC, asomsiko commented on openvino/conditional_compilation/CMakeLists.txt
> +        GIT_REPOSITORY https://github.com/intel/IntelSEAPI.git
Please specify a version/changeid

2021-01-20 07:10 UTC, ilyachur commented on openvino/conditional_compilation/CMakeLists.txt
> +        GIT_REPOSITORY https://github.com/intel/IntelSEAPI.git
Fixed

2021-01-26 10:15 UTC, asomsiko approved these changes

2021-01-26 10:16 UTC, merged