Move Extension tests from ieFuncTests to cpuFuncTests
openvinotoolkit/openvino pull request #3927
Opened 2021-01-19 21:33 UTC by mateusztabaka

2021-01-20 12:46 UTC, iefode requested changes

2021-01-20 12:46 UTC, iefode commented on inference-engine/tests/functional/plugin/cpu/shared_tests_instances/extension/extension.cpp
> +TEST_P(OnnxModelWithCustomAbs, Extension) {
`TEST_P` bodies should be in `plugin/shared/src/extension/extension.cpp `

2021-01-20 12:48 UTC, iefode commented
moreover, can we run extension tests for other plugins? If no, please move it to the cpu specific tests

2021-01-24 14:22 UTC, mateusztabaka commented
> moreover, can we run extension tests for other plugins? If no, please move it to the cpu specific tests

I moved those to cpu only tests.

2021-01-25 08:23 UTC, iefode commented on inference-engine/tests/functional/plugin/cpu/shared_tests_instances/extension/extension.cpp
> +// Copyright (C) 2020-2021 Intel Corporation
Why `shared_test_instances`??? I suppose to move this folder upder `functional/plugin/cpu` folder

2021-01-26 08:41 UTC, iefode commented on inference-engine/tests/functional/plugin/cpu/CMakeLists.txt
> +# Copyright (C) 2019-2021 Intel Corporation
@dmitry-gorokhov Are you OK with these changes?

2021-02-01 15:38 UTC, dmitry-gorokhov approved these changes

2021-02-02 05:02 UTC, ilyachur approved these changes

2021-02-02 08:55 UTC, iefode approved these changes

2021-02-02 08:55 UTC, merged