Add python api for CTCGreedyDecoder
openvinotoolkit/openvino pull request #3947
Opened 2021-01-20 23:14 UTC by iimironov

Ticket 43149

2021-01-27 10:49 UTC, jiwaszki requested changes

2021-01-27 10:49 UTC, jiwaszki commented on ngraph/python/src/ngraph/opset6/ops.py
> +        blank_index: Optional[int] = 0,
As far as I understand default value for `blank_index` is equal to `num_classes - 1`. Is it set to this value while processing in cpp internals? If not then I think you should change 0 to `None`, put an if statement to get length of the 3rd dimension from `data` and subtract one.

2021-01-27 10:49 UTC, jiwaszki commented on ngraph/python/src/ngraph/opset6/ops.py
> +    @param data:            The input tensor. Shape: [batch_size, seq_length, num_classes]
Optional: add 3D before tensor

2021-01-27 10:49 UTC, jiwaszki commented on ngraph/python/src/ngraph/opset6/ops.py
> +    @param sequence_length: Input tensor with sequence length. Shape: [batch_size]
Optional: add 1D before tensor

2021-01-29 12:35 UTC, jiwaszki commented on ngraph/python/src/ngraph/opset6/ops.py
> +        blank_index: Optional[int] = None,
This is fine.

2021-01-29 12:55 UTC, lazarevevgeny requested changes

2021-01-29 12:55 UTC, lazarevevgeny commented on ngraph/python/tests/test_ngraph/test_create_op.py
> +def test_ctc_greedy_decoder_seq_len(fp_dtype, int_dtype, int_ci, int_sl, merge_repeated):
Please, add tests for case when `blank_index` is `None`

2021-02-01 09:57 UTC, jiwaszki requested changes

2021-02-01 09:57 UTC, jiwaszki commented on ngraph/python/src/ngraph/opset6/ops.py
> +    }
I assume all tests for `blank_index = False` are failing due to recognizing `None` value as `dtype('O')`. You should add some check before setting inputs, please add `if blank_index is None` and assign default value of `num_classes-1` to it if true.

2021-02-02 09:06 UTC, jiwaszki requested changes

2021-02-02 09:06 UTC, jiwaszki commented on ngraph/python/tests/test_ngraph/test_create_op.py
> +        parameter_input2 = input0_shape[2] - 1
You get the idea right. However this should be implemented in _ngraph/python/src/ngraph/opset6/ops.py_ inside _ctc_greedy_decoder_seq_len_ function. Right now all we have is a test mock that does not work across nGraph module thus outside of this this test `None` value will still throw errors.

2021-02-02 10:08 UTC, jiwaszki approved these changes
Looks fine! Just wait for green checks and it is ready to merge.

2021-02-02 14:37 UTC, lazarevevgeny approved these changes

2021-02-02 17:18 UTC, pavel-esir approved these changes

2021-02-03 11:53 UTC, merged