Add Add->Clamp->Div->Mul to HSwish fusion
openvinotoolkit/openvino pull request #4027
Opened 2021-01-26 15:08 UTC by mateusztabaka

2021-01-26 16:17 UTC, GlebKazantaev requested changes

2021-01-26 16:17 UTC, GlebKazantaev commented on inference-engine/src/transformations/src/transformations/common_optimizations/hswish_fusion.cpp
> +    auto clamp = std::make_shared<ngraph::op::v0::Clamp>(add, 0.0f, 6.0f);
```suggestion
    auto clamp = std::make_shared<ngraph::opыуе4::Clamp>(add, 0.0f, 6.0f);
```

2021-01-26 16:17 UTC, GlebKazantaev commented on inference-engine/src/transformations/src/transformations/common_optimizations/hswish_fusion.cpp
> +                                  hswish);
You don't need to copy rt info for constants.
```suggestion
        ngraph::copy_runtime_info({pattern_to_output.at(add).get_node_shared_ptr(),
                                    pattern_to_output.at(clamp).get_node_shared_ptr(),
                                    pattern_to_output.at(div).get_node_shared_ptr(),
                                    pattern_to_output.at(mul).get_node_shared_ptr()
                                  },
                                  hswish);
```

2021-01-26 16:17 UTC, GlebKazantaev commented on inference-engine/tests/functional/inference_engine/transformations/hswish_fusion_test.cpp
> +        auto clamp = std::make_shared<ngraph::op::v0::Clamp>(add, 0.0f, 6.0f);
```suggestion
        auto clamp = std::make_shared<ngraph::opset4::Clamp>(add, 0.0f, 6.0f);
```

2021-01-26 19:43 UTC, GlebKazantaev approved these changes

2021-01-27 10:41 UTC, mitruska approved these changes

2021-01-27 13:48 UTC, ilyachur commented
Please resolve merge conflicts

2021-01-27 13:50 UTC, ilyachur approved these changes

2021-02-02 08:12 UTC, merged