Move Mul node before Reshape in GroupConvolutionMultiplyFusion
openvinotoolkit/openvino pull request #4031
Opened 2021-01-26 20:51 UTC by mateusztabaka

In following scenario:

                                    +-----------+
                                    |  weights  |
                                    +-----------+
                                         |
                                         v
                                    +-----------+
                                    |  Reshape  |
                       ....         +-----------+
                          \              /
                           \            /
                            v          v
                       +--------------------+
                       |  GroupConvolution  |
                       +--------------------+
                                |
                                v
                           +-----------+      +----------+
                           |  Multiply | <--- | Constant |
                           +-----------+      +----------+

if a second input (weights) to GroupConvolution is a Reshape,
we should apply Multiply node directly to weights rather than Reshape node:

                                    +-----------+
                                    |  weights  |
                                    +-----------+
                                         |
                                         v
                                    +-----------+      +----------+
                                    |  Multiply | <--- | Constant |
                                    +-----------+      +----------+
                                         |
                                         v
                                    +-----------+
                                    |  Reshape  |
                       ....         +-----------+
                          \              /
                           \            /
                            v          v
                       +--------------------+
                       |  GroupConvolution  |
                       +--------------------+
                                |
                                v

That approach has no side effects in the usual scenario when weights are constant,
but it's necessary for models with FakeQuantize since it gives possibility to perform
GroupConvolutionTransformation from LPT transformations.

2021-02-02 18:02 UTC, GlebKazantaev requested changes

2021-02-02 18:02 UTC, GlebKazantaev commented on inference-engine/src/transformations/src/transformations/common_optimizations/conv_mul_fusion.cpp
> +
I would simplify this code like this:
```cpp
auto new_weights = std::make_shared<opset4::Multiply>(m_weights, final_const);
if (are_weights_reshaped) {
    reshape->input(0).replace_source_output(new_weights);
} else {
    m_conv->input(1).replace_source_output(new_weights);
}
m_conv->set_friendly_name(m_mul->get_friendly_name());
m_mul->output(0).replace(m_conv->output(0));
copy_runtime_info({m_mul}, {m_conv, new_weights});
return true;
```

2021-02-08 11:15 UTC, GlebKazantaev approved these changes
LGTM from transformation perspective. Waiting for @eshoguli review.

2021-02-08 11:15 UTC, GlebKazantaev commented on inference-engine/src/transformations/src/transformations/common_optimizations/conv_mul_fusion.cpp
> +        const auto & G = weights_shape[0].get_length();
Please add `pattern::has_static_dims({0, 1})` to the weights pattern predicate.

2021-02-08 11:57 UTC, jane-intel commented
Don't we have such a Reshape eliminator already [here](https://github.com/openvinotoolkit/openvino/blob/master/inference-engine/src/transformations/src/transformations/common_optimizations/fq_reshape_fusion.cpp):

Introduced during: https://github.com/openvinotoolkit/openvino/pull/2388

2021-02-08 21:00 UTC, eshoguli commented on inference-engine/src/transformations/src/transformations/common_optimizations/conv_mul_fusion.cpp
> +        const auto & G = weights_shape[0].get_length();
Should we check if group count (`G`) equals to channels count and return `false` if not?

2021-02-09 06:39 UTC, eshoguli reviewed
Possible issue from LPT side: 

Issue #1. Operations on weights can be changed. LPT support predefined patterns on weights (GroupConvolution as example):

**FQ on weights**
```
 [activation]   FakeQuantize
     \          /
      \       Reshape
       \      /
    GroupConvolution
```
**New weights format**
```
              Constant
               |
              Convert  Constant
               |      /
              Subtract Constant
               |      /
              Multiply
               |
[activation]  Reshape
      \       /
    GroupConvolution
```

Note, please, there are no duplicated `Multiply` operations here. 
**Can you confirm that operations on weights will be not changed for LPT (next transformations will fuse new `Multiply` to exist `FakeQuantize` or exist `Multiply`)?**

Issue #2. In this case LPT team adds CPU & GPU regression plugin tests to check whole pipeline. I would be grateful if you could add this CPU & GPU regression test. I think it can do later but create task for that.

2021-03-11 19:33 UTC, GlebKazantaev commented on inference-engine/tests/functional/inference_engine/transformations/conv_fusion_test.cpp
> +        auto weights = opset5::Constant::create(element::f32, Shape{4, 1, 3, 3}, std::vector<float>(36, 1));
Could you please add tests where the `O` dim is greater than 1?

2021-03-11 19:33 UTC, GlebKazantaev commented
In general LGTM.

2021-03-16 04:17 UTC, ilyachur approved these changes

2021-03-16 10:11 UTC, ilyachur commented
@eshoguli Please have a look

2021-03-17 10:35 UTC, postrational approved these changes

2021-03-18 06:07 UTC, eshoguli approved these changes
Great tests for LPT GroupConvolution transformation, thanks!

2021-03-19 07:39 UTC, merged