Fuse x * HSigmoid(x) to HSwish(x)
openvinotoolkit/openvino pull request #4121
Opened 2021-02-01 14:49 UTC by mateusztabaka

2021-02-01 15:57 UTC, GlebKazantaev requested changes

2021-02-01 15:57 UTC, GlebKazantaev commented on inference-engine/src/transformations/src/transformations/common_optimizations/hswish_fusion.cpp
> +            return false;
You don't need to cast nodes, just use outputs from pattern_value_map

2021-02-01 15:57 UTC, GlebKazantaev commented on inference-engine/src/transformations/src/transformations/common_optimizations/hswish_fusion.cpp
> +#include <ngraph/opsets/opset5.hpp>
We already have opset6.

2021-02-02 05:48 UTC, ilyachur approved these changes

2021-02-02 10:36 UTC, GlebKazantaev requested changes

2021-02-02 10:36 UTC, GlebKazantaev commented on inference-engine/src/transformations/src/transformations/common_optimizations/hswish_fusion.cpp
> +        return true;
You don't need to cast nodes until you don't use any special methods from operation classes.
Also all this code can be simplified to this:
```suggestion
        const auto& pattern_to_output = m.get_pattern_value_map();
        auto hsigmoid = pattern_to_output.at(hsigmoid_pattern).get_node_shared_ptr();
        auto mul = pattern_to_output.at(mul_pattern).get_node_shared_ptr();

        auto hswish = std::make_shared<ngraph::opset6::HSwish>(pattern_to_output.at(input));
        hswish->set_friendly_name(mul->get_friendly_name());
        ngraph::copy_runtime_info({hsigmoid, mul}, hswish);
        ngraph::replace_node(mul, hswish);
        return true;
```

2021-02-02 12:06 UTC, mitruska approved these changes

2021-02-02 13:09 UTC, GlebKazantaev approved these changes

2021-02-02 19:23 UTC, merged