Created infer tool
openvinotoolkit/openvino pull request #4384
Opened 2021-02-17 12:17 UTC by omartiny

Created cli infer tool for conditional compilation based

2021-02-17 13:10 UTC, asomsiko requested changes

2021-02-17 13:10 UTC, asomsiko commented on tests/conditional_compilation/test_infer_tool.py
> +import argparse
The file name should not start with `test` - those names are reserved for test cases/suites. Please also have a separate folder for the tool

./tests/conditional_compilation/tools/infer_tool.py

2021-02-17 13:10 UTC, asomsiko commented on tests/conditional_compilation/test_infer_tool.py
> +import os
please ensure `pip3 install pylint` `pylint <file name>` report is clear

2021-02-17 13:10 UTC, asomsiko commented on tests/conditional_compilation/test_infer_tool.py
> +def python_api_infer(ir_path, device):
What is the reason for `python_api` in a function name? Should be name it `infer` or `do_infer`?

2021-02-17 13:10 UTC, asomsiko commented on tests/conditional_compilation/test_infer_tool.py
> +    parser = argparse.ArgumentParser(description='Python_api reproducer')
description needs to be rewritten.

2021-02-18 18:27 UTC, asomsiko approved these changes

2021-02-18 18:38 UTC, merged

2021-02-18 22:58 UTC, vurusovs reviewed
Please, create a separate PR with patch according to notes

2021-02-18 22:58 UTC, vurusovs commented on tests/conditional_compilation/tools/infer_tool.py
> +    net = IENetwork(model=ir_path, weights=bin_path)
please, use `ie.read_network` instead

2021-02-18 22:58 UTC, vurusovs commented on tests/conditional_compilation/tools/infer_tool.py
> +        feed_dict.update({layer: np.ones(shape=name.shape)})
please, create a separate function with input preparation. Function docstring should describe the aim that input should be reproducible from run to run

2021-02-18 22:58 UTC, vurusovs commented on tests/conditional_compilation/tools/infer_tool.py
> +    parser.add_argument('-d', dest='device', help='Target device to infer on', default="CPU")
please, make argument required with no default value

2021-02-18 22:58 UTC, vurusovs commented on tests/conditional_compilation/tools/infer_tool.py
> +    parser.add_argument('-r', dest='out_path', default=None,
please, make argument required with no default value

2021-02-18 22:58 UTC, vurusovs commented on tests/conditional_compilation/tools/infer_tool.py
> +                        help='Dumps results to the output folder')
Argument means full path to a file, not a folder. Please, fix help

2021-02-18 22:58 UTC, vurusovs commented on tests/conditional_compilation/tools/infer_tool.py
> +    bin_path = os.path.splitext(ir_path)[0] + '.bin'
unused var