update license
openvinotoolkit/openvino pull request #4407
Opened 2021-02-18 15:28 UTC by AlexeyLebedev1

### Details:
 - *item1*
 - *...*

### Tickets:
 - *ticket-id*

2021-02-18 16:34 UTC, akuporos requested changes
Please, remove the first blank lines and undo changes in inference-engine/thirdparty/mkl-dnn

2021-02-18 16:34 UTC, akuporos commented on inference-engine/ie_bridges/python/src/openvino/inference_engine/ie_api.pyx
> +
Please, remove blank lines before the license

2021-02-18 16:34 UTC, akuporos commented on inference-engine/ie_bridges/python/src/openvino/inference_engine/ie_api.pxd
> +
also, remove this blank line, please

2021-02-19 04:17 UTC, ilyachur commented
Could you fill the PR description?

2021-02-25 12:16 UTC, akuporos approved these changes
LGTM

2021-02-26 08:20 UTC, nkogteva approved these changes

2021-03-01 05:23 UTC, merged