Revert non-forward-compatible changes for PriorBox & PriorBoxClustered operations
openvinotoolkit/openvino pull request #4501
Opened 2021-02-26 07:18 UTC by achetver

### Details:
 - Revert changes for some attributes values in IR from `true`/`false` to `1`/`0` because IE 2021.2 cannot read this values.

### Tickets:
 - 49897

Code:
* [x]  Comments
* [x]  Code style (PEP8)
* [x]  Transformation generates reshape-able IR
* [x]  Transformation preserves original framework node names

Validation:
* [x]  Unit tests: N/A - No new implemented functions;
* [x]  Framework operation tests: N/A - No new enabled operations;
* [x]  Transformation tests: N/A - No new implemented transformations;
* [x]  Model Optimizer IR Reader check: Done manually.

Documentation:
* [x]  Supported frameworks operations list: N/A - No new supported operations;
* [x]  Supported **public** models list: N/A - Nothing to add;
* [x]  User guide update: N/A - Nothing to update.

2021-02-26 13:18 UTC, achetver commented
@pavel-esir @iimironov @evolosen please, review these changes.

2021-02-26 13:26 UTC, lazarevevgeny requested changes

2021-02-26 13:26 UTC, lazarevevgeny commented on docs/ops/detection/PriorBoxClustered_1.md
> +  * **Default value**: true or 1
Remove this change

2021-02-26 13:26 UTC, lazarevevgeny commented on docs/ops/detection/PriorBox_1.md
> +  * **Default value**: false or 0
remove this change

2021-02-26 13:26 UTC, lazarevevgeny commented on docs/ops/detection/PriorBox_1.md
> +  * **Default value**: false or 0
remove this change

2021-02-26 14:23 UTC, achetver commented on docs/ops/detection/PriorBoxClustered_1.md
> +  * **Default value**: true or 1
Done.

2021-02-26 14:23 UTC, achetver commented on docs/ops/detection/PriorBox_1.md
> +  * **Default value**: false or 0
Done.

2021-02-26 14:23 UTC, achetver commented on docs/ops/detection/PriorBox_1.md
> +  * **Default value**: false or 0
Done.

2021-03-01 07:10 UTC, evolosen approved these changes

2021-03-01 09:07 UTC, pavel-esir approved these changes
Looks good to me. Personally @achetver explained why these changes are needed.

2021-03-01 09:32 UTC, achetver commented
@lazarevevgeny This PR is ready for your review.

2021-03-01 10:50 UTC, lazarevevgeny approved these changes

2021-03-01 10:50 UTC, merged