Added check that new name is unique.
openvinotoolkit/openvino pull request #4516
Opened 2021-02-26 13:55 UTC by popovaan

Description: 
Added check to ResultRename transformation that new name is unique.

Ticket: 49870

Code:
* [ ]  Comments
* [ ]  Code style (PEP8)
* [ ]  Transformation generates reshape-able IR
* [ ]  Transformation preserves original framework node names

Validation:
* [ ]  Unit tests
* [ ]  Framework operation tests
* [ ]  Transformation tests
* [ ]  Model Optimizer IR Reader check

Documentation:
* [ ]  Supported frameworks operations list
* [ ]  Guide on how to convert the **public** model
* [ ]  User guide update

2021-02-26 14:52 UTC, iimironov approved these changes

2021-03-01 06:46 UTC, pavel-esir approved these changes

2021-03-01 07:13 UTC, evolosen approved these changes

2021-03-01 11:11 UTC, lazarevevgeny approved these changes

2021-03-02 08:12 UTC, lazarevevgeny requested changes

2021-03-02 08:12 UTC, lazarevevgeny commented on model-optimizer/extensions/back/ResultRename.py
> +                if tensor_names and node['name'] == tensor_names[0]:
Change to `if tensor_names and node.soft_get('name') == tensor_names[0]:`

2021-03-02 08:15 UTC, lazarevevgeny commented on model-optimizer/extensions/back/ResultRename.py
> +                    return
Do not return here. Use continue instead

2021-03-02 12:35 UTC, lazarevevgeny approved these changes

2021-03-02 14:26 UTC, merged