[IE CLDNN] Fuse reorder to permute.
openvinotoolkit/openvino pull request #4549
Opened 2021-03-02 06:12 UTC by yeonbok

### Details:
Enabled fusing [permute + reorder] to permute

### Tickets:

2021-03-02 13:20 UTC, vladimir-paramuzov requested changes

2021-03-03 01:09 UTC, yeonbok commented on inference-engine/thirdparty/clDNN/src/graph_optimizer/remove_redundant_reorders.cpp
> +                printf("found possible implementation\n");
opps thank you!

2021-03-03 02:26 UTC, yeonbok commented on inference-engine/thirdparty/clDNN/src/graph_optimizer/remove_redundant_reorders.cpp
> +                printf("found possible implementation\n");
Fixed

2021-03-03 07:30 UTC, vladimir-paramuzov approved these changes
LGTM. Will be merged after release branch creation

2021-03-06 16:18 UTC, vladimir-paramuzov commented
@yeonbok could you please rebase and restart CI?

2021-03-08 01:53 UTC, yeonbok commented
> @yeonbok could you please rebase and restart CI?

I did.

2021-03-08 19:48 UTC, merged