Power operation specification refactoring.
openvinotoolkit/openvino pull request #4566
Opened 2021-03-02 14:29 UTC by jdanieck

Power operation specification refactoring. Ticket 50101.

2021-03-04 15:12 UTC, lazarevevgeny requested changes

2021-03-04 15:12 UTC, lazarevevgeny commented on docs/ops/arithmetic/Power_1.md
>  o_{i} = {a_{i} ^ b}_{i}
incorrect formulae. `_{i}` should be after `b`

2021-03-08 07:13 UTC, lazarevevgeny approved these changes

2021-03-09 20:45 UTC, sdurawa commented
@lazarevevgeny , this PR is ready to merge.

2021-03-10 06:57 UTC, merged