Maximum operation specification refactoring.
openvinotoolkit/openvino pull request #4572
Opened 2021-03-02 15:14 UTC by jdanieck

Maximum operation specification refactoring. Ticket 50101.

2021-03-03 07:30 UTC, lazarevevgeny requested changes

2021-03-03 07:30 UTC, lazarevevgeny commented on docs/ops/arithmetic/Maximum_1.md
> +*Example 1 - no broadcsting*
typo

2021-03-03 07:30 UTC, lazarevevgeny commented on docs/ops/arithmetic/Maximum_1.md
> +As a first step input tensors *a* and *b* are broadcasted if their shapes differ. Broadcasting is performed according to `auto_broadcast` attribute specification. As a second step *maximum* operation
change `*maximum*` to `*Maximum*`

2021-03-04 14:48 UTC, lazarevevgeny approved these changes

2021-03-09 20:46 UTC, sdurawa commented
@lazarevevgeny , this PR is ready to merge.

2021-03-10 06:57 UTC, merged