Fix missing variable initializations and types
openvinotoolkit/openvino pull request #4670
Opened 2021-03-05 20:47 UTC by mletavin

### Details:
 - *Fix missing variable initializations and correct variable types*

### Tickets:
 - *50028*

2021-03-09 07:17 UTC, lznamens requested changes
layout_optimizer.cpp: 2020 -> 2021

2021-03-09 07:17 UTC, lznamens commented on inference-engine/thirdparty/clDNN/src/layout_optimizer.cpp
> +                                ( weights_layout.data_type == input_layout.data_type);
Please remove extra space.

2021-03-09 08:39 UTC, mletavin commented on inference-engine/thirdparty/clDNN/src/layout_optimizer.cpp
> +                                ( weights_layout.data_type == input_layout.data_type);
Fixed.

2021-03-16 05:27 UTC, vladimir-paramuzov approved these changes

2021-03-16 05:28 UTC, merged