[CPU] [TESTS] returned old behavior for fp32 avx2 1x1 conv with dw conv fusing
openvinotoolkit/openvino pull request #4957
Opened 2021-03-25 09:13 UTC by antonvor

PR with functionality only: https://github.com/openvinotoolkit/openvino/pull/4484

2021-03-25 09:43 UTC, maxnick approved these changes

2021-04-05 11:32 UTC, dmitry-gorokhov commented
@antonvor Is the PR ready for review?

2021-04-08 13:19 UTC, antonvor commented
> @antonvor Is the PR ready for review?

2021-04-15 07:50 UTC, dmitry-gorokhov requested changes

2021-04-15 07:50 UTC, dmitry-gorokhov commented on inference-engine/tests/functional/plugin/cpu/subgraph_tests/src/conv_dw_conv_fusing.cpp
> +        // todo: [antonvor] dw convolution without biases not supported
Lets remove than

2021-04-15 07:50 UTC, dmitry-gorokhov commented on inference-engine/tests/functional/plugin/cpu/subgraph_tests/src/conv_dw_conv_fusing.cpp
> +    auto conv2 = ngraph::builder::makeGroupConvolution(conv1, ngraph::element::f32, {3, 3}, {dwStride, dwStride}, {1, 1}, {1, 1}, {1, 1},
We also need to cover:
1) Cases with non fp32 prevision.
2) Cases when Conv and DW conv have other fusings: Eltwise/Depthwise/Sum.

2021-11-29 22:05 UTC, dmitry-gorokhov commented
@antonvor can we close this one as not actual anymore?

2021-11-30 07:48 UTC, closed without merging