[DOC] Update README for C++ samples
openvinotoolkit/openvino pull request #5019
Opened 2021-03-29 17:30 UTC by generalova-kate

### Details:
 - Update README with API info
 - Add docstrings to common functions

### Tickets:
 - 49428

2021-04-06 11:05 UTC, mryzhov commented on inference-engine/samples/classification_sample_async/main.cpp
> +        std::cout << ie.GetVersions(FLAGS_d);
Don't we need to add here std::endl?

2021-04-06 11:07 UTC, mryzhov commented on inference-engine/samples/classification_sample_async/main.cpp
> +        slog::info << "Loading network files:"
```suggestion
            slog::info << "Loading network files:" << slog::endl << FLAGS_m << slog::endl;
```

2021-04-14 08:48 UTC, mryzhov requested changes
General comment, it is better to isolate all functional changes to separate PR, they can affect CI pipeline.

2021-04-14 08:48 UTC, mryzhov commented on inference-engine/ie_bridges/c/samples/object_detection_sample_ssd/main.c
> +    if (file_num < 20) {
What does this number mean? Maybe: int max_files = 20; if (file_num < max_files); ?

2021-04-14 08:48 UTC, mryzhov commented on inference-engine/samples/classification_sample_async/main.cpp
> +                      << resultsCnt+1 << " and more than 0)\n            Maximal value " << resultsCnt << " will be used.";
missed slog::endl;?

2021-04-14 08:48 UTC, mryzhov commented on inference-engine/samples/common/utils/src/args_helper.cpp
> +    if (files.size() < 20) {
one more number, looks like it can be a global constant or #define MAX_FILES 20?

2021-04-14 12:17 UTC, antonrom23 approved these changes

2021-04-14 12:38 UTC, mryzhov approved these changes

2021-04-15 10:42 UTC, merged