Don't fuse Add to FakeQuantize if it can be fused with ConvolutionIE
openvinotoolkit/openvino pull request #5083
Opened 2021-04-02 07:23 UTC by mateusztabaka

Ticket: 49801

2021-04-06 21:19 UTC, vzinovie commented on inference-engine/src/transformations/src/transformations/common_optimizations/add_fake_quantize_fusion.cpp
> +                return node_type_info != opset5::Convolution::type_info &&
Suggest checking on MatMul node too

2021-04-06 21:21 UTC, vzinovie commented on inference-engine/src/transformations/src/transformations/common_optimizations/add_fake_quantize_fusion.cpp
> +                return node_type_info != opset5::Convolution::type_info &&
Also (on the future, maybe) ConvolutionBackpropData, GroupConvolutionBackpropData

2021-04-08 15:51 UTC, GlebKazantaev requested changes

2021-04-08 15:51 UTC, GlebKazantaev commented on inference-engine/src/transformations/src/transformations/common_optimizations/add_fake_quantize_fusion.cpp
> +        auto new_input_low = get_constant_from_source(std::make_shared<opset5::Subtract>(fq->input_value(1), add_const));
You need to check the result of `get_constant_from_source` as it returns nullptr in some cases.

2021-04-08 15:51 UTC, GlebKazantaev commented on inference-engine/src/transformations/src/transformations/common_optimizations/add_fake_quantize_fusion.cpp
> +                if (node.get_target_inputs().size() != 1)
If Constant has equal values or scalar value it can be fused into FQ in any case. @eshoguli am I right?

2021-06-07 16:02 UTC, closed without merging