[IE CLDNN] Eltwise b_fs_zyx_fsv16 optimization
openvinotoolkit/openvino pull request #5098
Opened 2021-04-04 01:03 UTC by Lyamin-Roman

2021-04-05 07:46 UTC, lznamens requested changes

2021-04-05 07:46 UTC, lznamens commented on inference-engine/thirdparty/clDNN/kernel_selector/core/actual_kernels/eltwise/eltwise_kernel_b_fs_yx_fsv16.cpp
> +                                                        ", INPUT"+std::to_string(input.index)+"_GET_INDEX(b, f_block*16, z, y, x))"));
Please use unified code style with spaces between different parts of your code line.

2021-04-05 07:46 UTC, lznamens commented on inference-engine/thirdparty/clDNN/kernel_selector/core/actual_kernels/eltwise/eltwise_kernel_b_fs_yx_fsv16.cpp
> +                                             "INPUT" + std::to_string(input.index) + "_GET_INDEX(b, f_block*16, z, y, x))";
You can simplify this via replacement of common code before if because only _GET_INDEX part is different.

2021-04-06 05:45 UTC, isanghao commented
JFYI @hyunback

2021-04-15 05:01 UTC, lznamens approved these changes
Changes look good to me and also I hope that current version has better perf on full network scope and you checked it.

2021-04-26 12:36 UTC, merged