Implementation of ArgMin ONNX + TF extractors
openvinotoolkit/openvino pull request #5126
Opened 2021-04-06 22:11 UTC by yekruglov

2021-04-13 14:08 UTC, rblaczkowski commented
Please merge current master to your branch to avoid OpenVINO ONNX CI issues.

2021-04-20 07:29 UTC, popovaan approved these changes

2021-04-20 07:51 UTC, mvafin approved these changes

2021-04-20 16:16 UTC, lazarevevgeny commented
@yekruglov , please, rebase with the latest master.

2021-04-20 17:23 UTC, lazarevevgeny requested changes

2021-04-20 17:29 UTC, lazarevevgeny requested changes

2021-04-20 17:29 UTC, lazarevevgeny commented on model-optimizer/extensions/front/tf/argmin_ext.py
> +        ArgMaxOp.update_node_stat(node, attrs)
Should be `ArgMinOp`

2021-04-20 17:29 UTC, lazarevevgeny commented on model-optimizer/extensions/front/tf/argmin_ext.py
> +            'output_type': tf_dtype_extractor(node.pb.attr['out_type'].type, np.int64)
The TF operation attribute name is `output_type` not `out_type`. The same comment for the `ArgMax` operation

2021-04-20 17:29 UTC, lazarevevgeny commented on model-optimizer/extensions/middle/ArgOpsToTopK.py
> +        topk_mode = 'max' if node['op'] == 'ArgMax' else 'min'
`node['op']` -> `node.op`

2021-04-30 13:40 UTC, iimironov approved these changes

2021-05-04 15:57 UTC, lazarevevgeny requested changes

2021-05-04 15:57 UTC, lazarevevgeny commented on model-optimizer/extensions/ops/argmax.py
> +    node.out_node().shape = out_shape
node.out_port(0).data.set_shape(out_shape)

2021-05-04 15:58 UTC, lazarevevgeny commented on model-optimizer/extensions/ops/argmax.py
Add `enabled = False`

2021-05-06 10:41 UTC, lazarevevgeny approved these changes

2021-05-06 10:41 UTC, merged