WIP: align MO pip requirements
openvinotoolkit/openvino pull request #5171
Opened 2021-04-09 13:04 UTC by ilya-naumov

### Details:
 - Set MO's pip dependency requirements to ~= and remove TF1

### Tickets:
 - internal 48358

2021-04-19 15:19 UTC, lazarevevgeny requested changes

2021-04-19 15:19 UTC, lazarevevgeny commented on model-optimizer/requirements_tf.txt
> +numpy~=1.19.5
TF 1.X requires numpy<1.19.0.

2021-04-20 13:19 UTC, lazarevevgeny commented on model-optimizer/requirements.txt
>  test-generator==0.1.1
Please, remove `test-generator=0.1.1` from all files except requirements_dev.txt. This change has been merged in the MO.

2021-04-23 10:15 UTC, lazarevevgeny commented
@achetver , please, take a look at this PR. Does MO version checker works correctly for the updated requirements?

2021-04-23 12:44 UTC, lazarevevgeny approved these changes

2021-04-26 08:25 UTC, achetver commented
@lazarevevgeny MO version checker in [PR](https://github.com/openvinotoolkit/openvino/pull/5342) works correctly with `~=` signs but I don't see support of `sys_platform == '...'` environment marker and during environment check these markers will be ignored.

2021-04-26 08:48 UTC, generalova-kate commented
@achetver could you add support sys_platform on this week?

2021-04-26 10:21 UTC, achetver commented
@generalova-kate Yes, I can. But it is necessary to use different versions of mxnet depending on platform?

2021-04-26 11:27 UTC, ilya-naumov commented
@achetver  Windows package of `mxnet 1.7.0.post2` conflicts with `numpy` and `requests` (Windows wheels isn't available for newer versions on PyPi). We use `mxnet 1.2.0` on Windows because it doesn't cause dependency conflicts on this environment and we can't use same version on Linux because it requires old `numpy`. You can find more info at the ticket.

2021-04-27 21:34 UTC, achetver commented on model-optimizer/requirements_mxnet.txt
> +mxnet~=1.2.0 ; sys_platform == 'win32'
Are whitespaces between module version and `;` necessary? If not, please remove them. Note as we use environment markers `tensorflow>=1.15.2,<2.0; python_version < "3.8"`

2021-05-06 13:21 UTC, lazarevevgeny commented
PR https://github.com/openvinotoolkit/openvino/pull/5437 has been merged. Please, merge the recent master to your branch and re-validate again.

2021-05-14 13:05 UTC, merged