WIP: Align pip requirements of benchmark tool, cross check tool, IE Python API
openvinotoolkit/openvino pull request #5199
Opened 2021-04-12 12:54 UTC by ilya-naumov

### Details:
 - Attempt to set more strict (~=) pip requirements of this components

### Tickets:
 - 48358

2021-04-26 08:04 UTC, generalova-kate approved these changes

2021-05-04 07:56 UTC, ilya-naumov commented
@azhogov Can you add `setuptools` package to the openvino-onnxruntime-lin pipeline to fix [this error](https://dev.azure.com/openvinoci/dldt/_build/results?buildId=82795&view=logs&j=6930f17f-3f5c-56d6-3bb8-6d70ad7cf7f7&t=485094ff-bc57-5a4b-e7d4-6869a68baa65&l=117)?

2021-05-13 10:26 UTC, akuporos requested changes

2021-05-13 14:36 UTC, akuporos commented on inference-engine/ie_bridges/python/requirements.txt
> -cython>=0.29.17
discussed offline

2021-05-13 14:36 UTC, akuporos approved these changes

2021-05-14 13:05 UTC, merged