[PP] adding div and sub operations
openvinotoolkit/openvino pull request #5240
Opened 2021-04-14 12:20 UTC by anton-potapov

For mean value preprocessing to function (in near future) following were added
### Details:
 - `div` operation added
 - `sub` operation added
 - unit tests

@anna-khakimova , @dmatveev FYI

2021-04-14 12:27 UTC, ilya-lavrenov commented
Why do we need this?

2021-04-15 04:16 UTC, ilyachur commented
As I know at the current moment IE plugins don't use GAPI for mean scale.

2021-04-21 09:30 UTC, anna-khakimova commented
> Why do we need this?

cc @dmatveev

2021-04-21 09:31 UTC, anna-khakimova commented
> As I know at the current moment IE plugins don't use GAPI for mean scale.

cc @dmatveev

2021-04-21 10:07 UTC, anton-potapov commented
> As I know at the current moment IE plugins don't use GAPI for mean scale.

This is correct. In order this to change, and  (GAPI) PreProcessing to support mean scale preprocessing some basic blocks is needed.  These operations are those basic blocks needed to implement the logic.

2021-04-23 08:42 UTC, anna-khakimova requested changes

2021-04-23 08:42 UTC, anna-khakimova commented on inference-engine/tests_deprecated/fluid_preproc/cpu/fluid_tests_cpu.cpp
> +                                Values(0)));
Please relax tolerance to 0.00001 value.

2021-04-23 08:42 UTC, anna-khakimova commented on inference-engine/tests_deprecated/fluid_preproc/cpu/fluid_tests_cpu.cpp
> +                                Values(0)));
Please relax tolerance to 0.00001 value.

2021-04-23 08:42 UTC, anna-khakimova commented on inference-engine/tests_deprecated/fluid_preproc/cpu/fluid_tests_cpu.cpp
> +                        Combine(//Values(CV_8U, CV_32F),
Please remove comment.

2021-04-23 08:43 UTC, anna-khakimova commented
Please rebase the PR.

2022-03-22 20:11 UTC, closed without merging