Removed transformation which removes Const->Result sub-graphs
openvinotoolkit/openvino pull request #5295
Opened 2021-04-19 08:23 UTC by lazarevevgeny

### Details:
 - Removed transformation which removes Const->Result sub-graphs

### Tickets:
 - *ticket-id*

2021-05-04 16:20 UTC, rkazants approved these changes

2021-05-04 16:22 UTC, rkazants requested changes
It also seems that we need to remove StandaloneConstEraser front transformation doesn't it?

2021-05-04 16:31 UTC, lazarevevgeny commented
> StandaloneConstEraser

Yeah! Great catch! I was sure that something additional can be removed from the MO, but I totally forget to check the front phase.

2021-05-04 18:56 UTC, rkazants approved these changes

2021-05-05 09:25 UTC, sadolini approved these changes

2021-05-05 11:24 UTC, merged