Add script to compare 2 TimeTests runs
openvinotoolkit/openvino pull request #5358
Opened 2021-04-22 16:29 UTC by vurusovs

### Tickets:
 - *-48864

2021-04-22 16:32 UTC, vurusovs commented on tests/time_tests/scripts/compare_runs.py
> +    ops = OrderedDict([
think about how to compare results including stdev

2021-04-22 16:32 UTC, vurusovs commented on tests/time_tests/scripts/compare_runs.py
> +def _parse_platform(platform):
docstring

2021-04-22 16:32 UTC, vurusovs commented on tests/time_tests/scripts/compare_runs.py
> +def _update_timetests_records(records: list):
docstring

2021-04-22 16:33 UTC, vurusovs commented on tests/time_tests/scripts/compare_runs.py
> +                log.error('Comparison for field="%s" for device="%s" failed: %s', field, device, msg)
add information about comparison status and metrics in report (HTML or any other report)

2021-04-26 08:09 UTC, asomsiko commented
data analytics should be through an internal web reporter tool. Could you clarify how the proposed tool will be used and why we need a tool additionally to the web reporter?

2021-04-26 08:09 UTC, asomsiko requested changes
it looks a duplicate to what is available in web reporter

2021-04-29 15:29 UTC, closed without merging

2021-04-29 15:29 UTC, vurusovs commented
Closed as not required for now