[nGraph] Add documentation strings
openvinotoolkit/openvino pull request #5418
Opened 2021-04-27 08:21 UTC by jiwaszki

### Details:
 - Added doc strings to nGraph classes.
 - Changed order of class registering in pybind. That allows automatic signatures generator (from pybind) to see classes in form `_pyngraph.class_name` instead of C++ notation in form of `ngraph::class_name`.
 - Added py::args to functions which suggest automatic signatures generator to replace names in signatures and allows users to specify the argument in a function call `func(argument_name = value)`.

### Tickets:
 - *51816*

2021-04-27 12:17 UTC, tomdol approved these changes

2021-04-28 09:16 UTC, ilyachur commented
@ntyukaev FYI

2021-04-28 09:17 UTC, mbencer approved these changes

2021-04-29 04:00 UTC, ilyachur approved these changes

2021-04-29 04:00 UTC, ilyachur commented
@postrational Could you have a look?

2021-04-29 07:50 UTC, postrational requested changes

2021-04-29 11:40 UTC, jiwaszki commented on ngraph/python/src/pyngraph/function.cpp
> +                    Return ordered ops used in the function.
Done.

2021-04-29 11:40 UTC, jiwaszki commented on ngraph/python/src/pyngraph/function.cpp
> +                    Create Function.
Done

2021-04-29 11:41 UTC, jiwaszki commented on ngraph/python/src/pyngraph/dimension.cpp
> +                Convert this dimension's min_dimension to integer.
Done

2021-04-29 11:41 UTC, jiwaszki commented on ngraph/python/src/pyngraph/dimension.cpp
> +                Check whether this dimension is a refinement of the argument.
Done

2021-04-29 12:18 UTC, postrational approved these changes

2021-04-29 15:12 UTC, etusien approved these changes

2021-05-05 08:15 UTC, merged