Add ShapeOfConstFolding transform
openvinotoolkit/openvino pull request #5858
Opened 2021-05-27 10:44 UTC by iimironov

Tickets: 52451

2021-05-27 11:42 UTC, jane-intel commented on model-optimizer/extensions/middle/ShapeOfConstFolding.py
> +                ('const', dict(op='Const')),
It's middle replacer. So pattern should have datas

2021-05-27 11:42 UTC, jane-intel requested changes
Transformation doesn't work

2021-05-27 11:43 UTC, jane-intel commented
Please add template description to PR

2021-05-28 17:36 UTC, jane-intel commented on model-optimizer/extensions/middle/ShapeOfConstFolding.py
> +        shape_value = shape.in_port(0).data.get_value()
the code doesn't work again. it is the shape that should become the value, not the constant value.

2021-06-03 13:11 UTC, jane-intel commented on model-optimizer/extensions/middle/ShapeOfConstFolding.py
> +        if shape.has_valid('value'):
I assume `ShapeOf` op node doesn't have value. Only data nodes have them.

2021-06-07 17:10 UTC, lazarevevgeny requested changes

2021-06-07 17:10 UTC, lazarevevgeny commented on model-optimizer/extensions/back/ShapeOfConstFolding.py
> +        print("ShapeOfConstFolding")
I think that this debug code should be removed. The same comment for line 22.

2021-06-07 17:10 UTC, lazarevevgeny commented on model-optimizer/unit_tests/extensions/back/ShapeOfConstFolding_test.py
> +from unit_tests.utils.graph import build_graph
sort imports

2021-06-07 17:24 UTC, lazarevevgeny commented on model-optimizer/extensions/back/ShapeOfConstFolding.py
> +    The transformation folding Const() -> ShapeOf() to Const()
`The transformation folding Const() -> ShapeOf() to Const()` -> `The transformation folds ShapeOf(Const) -> Const`.

2021-06-08 05:21 UTC, lazarevevgeny commented on model-optimizer/unit_tests/extensions/back/ShapeOfConstFolding_test.py
> +    def test1(self):
I don't see a test case the for following graph:

![image](https://user-images.githubusercontent.com/30651952/121127488-85953400-c832-11eb-8d0c-e2cf4d60eb62.png)

2021-06-08 05:28 UTC, lazarevevgeny requested changes

2021-06-08 05:28 UTC, lazarevevgeny commented on model-optimizer/unit_tests/extensions/back/ShapeOfConstFolding_test.py
> +                                    'new_const_shapeof_data': {'value': int64_array([1, 3, 30, 30])},
Why the graph contains new data node `new_const_shapeof_data`? The `shapeof_const_data` data node should be kept! Looks like you loose the debug information (tensor name) after running this transformation.

2021-06-08 11:47 UTC, mvafin commented on model-optimizer/unit_tests/extensions/back/ShapeOfConstFolding_test.py
> +    def test_const_with_tow_outputs(self):
Typo: tow -> two

2021-06-08 12:12 UTC, mvafin approved these changes

2021-06-08 12:13 UTC, mvafin commented on model-optimizer/unit_tests/extensions/back/ShapeOfConstFolding_test.py
> +                    'input_data': {'value': None, 'shape': int64_array([1, 3, 30, 30]), 'kind': 'data'},
nit: use helper functions for graph generation to create data nodes and connect edges.

2021-06-08 12:15 UTC, achetver approved these changes

2021-06-09 08:49 UTC, lazarevevgeny approved these changes
@jane-intel , please, review today.

2021-06-09 09:14 UTC, jane-intel approved these changes

2021-06-09 09:14 UTC, merged