Make stress and time tests build independent from gflags from samples
openvinotoolkit/openvino pull request #5883
Opened 2021-05-28 11:02 UTC by vurusovs

### Details:
 - Time tests now based on IEDevScripts instead of InferenceEngineDeveloperPackage
 - Stress tests still uses InferenceEngineDeveloperPackage because it requires gtest from IE tests

### Tickets:
 - 55465

2021-05-28 11:19 UTC, ilya-lavrenov approved these changes

2021-05-31 13:47 UTC, asomsiko requested changes
1. PR description is invalid - "independent" vs "dependent".

2. What problem this PR solves?

3. Are build steps in README.md still valid?

4. Can tests be built on installed OpenVINO?

2021-06-01 08:41 UTC, vurusovs commented on tests/time_tests/src/timetests/CMakeLists.txt
> +if (NOT TARGET IE::inference_engine)
check it works with old versions of OpenVINO installed via package

2021-06-01 09:09 UTC, vurusovs commented on tests/time_tests/src/timetests/CMakeLists.txt
> +if (NOT InferenceEngine_FOUND)
update README in the same commit

2021-06-01 09:46 UTC, vurusovs commented on tests/time_tests/src/timetests/CMakeLists.txt
> +if (NOT InferenceEngine_FOUND)
Done

2021-06-01 10:18 UTC, vurusovs commented
> 1. PR description is invalid - "independent" vs "dependent".
> 2. What problem this PR solves?
> 3. Are build steps in README.md still valid?
> 4. Can tests be built on installed OpenVINO?

1. Fixed
2. Added in description
3. Steps are updated. It still valid, but extended with new option 
4. Will be checked later

2021-06-01 19:06 UTC, vurusovs commented on tests/time_tests/src/timetests/CMakeLists.txt
> +    if (NOT InferenceEngine_FOUND)
endif

2021-06-03 23:44 UTC, vurusovs commented on tests/time_tests/src/timetests/CMakeLists.txt
> +if (NOT TARGET IE::inference_engine)
Done - it works fine

2021-06-04 06:52 UTC, ilya-lavrenov approved these changes

2021-06-04 07:01 UTC, asomsiko approved these changes

2021-06-04 07:27 UTC, merged