Revise NonZero op
openvinotoolkit/openvino pull request #5909
Opened 2021-05-31 07:26 UTC by blesniewski

### Details:
- *added visitor tests*
 - *use 🦒 RTTI macros*
 - *add boolean to type prop and sslt - [spec changed](https://github.com/openvinotoolkit/openvino/pull/5863)*

### Tickets:
 - *45836, 45837, 53956*
 - *37545*

2021-06-07 10:47 UTC, jane-intel requested changes
Please multiply all the dimensions for output computation even for the dynamic case.

2021-06-07 12:30 UTC, jdanieck commented
@jane-intel do we need LP types support in NonZero?

2021-06-07 12:43 UTC, jdanieck requested changes
I don't see NonZero SLT instantiation for CPU plugin. Please add it or prove me wrong :)

2021-06-08 10:33 UTC, blesniewski commented
> I don't see NonZero SLT instantiation for CPU plugin. Please add it or prove me wrong :)

Here you go!

2021-06-08 13:24 UTC, jdanieck approved these changes

2021-06-09 05:35 UTC, ilyachur approved these changes

2021-06-14 08:06 UTC, jdanieck commented
@tomdol maybe you'll have time to review & merge to offload @ilyachur ? Unreviewed PR's started to pile up because of the release. CC: @andrei-kochin

2021-06-15 08:03 UTC, sdurawa commented
@ilyachur , @jane-intel please review and merge this ticket.

2021-06-16 03:44 UTC, ilyachur commented
@jane-intel Do you have any other comments?

2021-06-17 10:48 UTC, jane-intel commented on ngraph/test/type_prop/non_zero.cpp
> +    EXPECT_TRUE(
please use expect equal and the correct output shape

2021-06-17 10:57 UTC, jane-intel requested changes

2021-06-17 10:57 UTC, jane-intel commented on ngraph/test/type_prop/non_zero.cpp
> +        non_zero->get_output_partial_shape(0).same_scheme(PartialShape{4, Dimension::dynamic()}));
Should it be like this?
```suggestion
    EXPECT_EQ(
        non_zero->get_output_partial_shape(0), PartialShape{4, {0, 24}}));
```

2021-06-23 11:12 UTC, jane-intel requested changes

2021-06-23 11:12 UTC, jane-intel commented on ngraph/core/src/op/non_zero.cpp
> +            begin(input_shape), end(input_shape), Dimension(0, 1), std::multiplies<Dimension>());
you've changed the behavior, please add test with dynamic input shape like 
case 1: input shape {{3, 4}, {5, 6}, {7, 8}}, expected shape {3, {105, 192}}
case 2: input shape {{3, 4}, {5, 6}, -1}, expected shape {3, -1}

2021-06-28 08:37 UTC, jdanieck commented
@jane-intel reminding about this PR. Your requested changes were resolved. We are waiting only for your LGTM.

2021-06-28 14:59 UTC, jdanieck commented
@ilyachur can we merge this PR? It's stayed in review long enough, second round of review were addressed 5 days ago.

2021-06-30 09:33 UTC, jane-intel approved these changes

2021-06-30 09:35 UTC, ilyachur approved these changes

2021-06-30 09:35 UTC, merged