Make Range operator to work with both Shape{} and Shape{1} inputs
openvinotoolkit/openvino pull request #5917
Opened 2021-05-31 09:45 UTC by mateusztabaka

2021-06-01 04:21 UTC, ilyachur commented
Could you set the milestone for this activity?
Does this PR fix some ticket?

2021-06-01 06:58 UTC, mateusztabaka commented
> Could you set the milestone for this activity?
> Does this PR fix some ticket?

There is no ticket for that.

2021-06-10 09:04 UTC, postrational approved these changes

2021-06-10 09:09 UTC, lazarevevgeny requested changes

2021-06-10 09:09 UTC, lazarevevgeny commented on ngraph/core/src/op/range.cpp
> +    NODE_VALIDATION_CHECK(this,
These changes contradicts with the spec. So they are not correct.

Also, take a look at https://github.com/openvinotoolkit/openvino/pull/6008 and https://github.com/openvinotoolkit/openvino/pull/6017 which may have fixed the root cause why the Range got a tensor of shape [1] as input.

2021-06-10 09:35 UTC, mateusztabaka commented
On latest master I'm not able to reproduce the issue. Closing.

2021-06-10 09:35 UTC, closed without merging