[BERT-NER] Document model support
openvinotoolkit/openvino pull request #6238
Opened 2021-06-18 12:00 UTC by yekruglov

Ticket: 46650

2021-06-18 12:45 UTC, vgavrilo approved these changes

2021-06-21 08:16 UTC, lazarevevgeny requested changes

2021-06-21 08:16 UTC, lazarevevgeny commented on docs/MO_DG/prepare_model/convert_model/pytorch_specific/Convert_Bert_ner.md
> +print(logits.shape)
remove

2021-06-21 08:16 UTC, lazarevevgeny commented on docs/MO_DG/prepare_model/convert_model/pytorch_specific/Convert_Bert_ner.md
> +To convert the model to ONNX* format create and run the script with the following content in the root
Please, specify the hash commit from which the model conversion works.

2021-06-22 15:31 UTC, lazarevevgeny commented
@yekruglov, please, resolve merge conflicts

2021-06-22 15:39 UTC, lazarevevgeny approved these changes

2021-06-22 16:05 UTC, merged