[BERT-NER] Document model support (to release branch)
openvinotoolkit/openvino pull request #6239
Opened 2021-06-18 12:30 UTC by yekruglov

Ticket: 46650

PR to master branch: https://github.com/openvinotoolkit/openvino/pull/6238

2021-06-18 12:45 UTC, vgavrilo approved these changes

2021-06-21 08:16 UTC, lazarevevgeny requested changes

2021-06-21 10:42 UTC, yekruglov commented on docs/MO_DG/prepare_model/convert_model/pytorch_specific/Convert_Bert_ner.md
> +python mo.py --input_model bert-ner.onnx --input "input_mask[1 128],segment_ids[1 128],input_ids[1 128]"
Not sure how it should look
Is this enough?

2021-06-21 11:43 UTC, lazarevevgeny commented on docs/MO_DG/prepare_model/convert_model/pytorch_specific/Convert_Bert_ner.md
> +python mo.py --input_model bert-ner.onnx --input "input_mask[1 128],segment_ids[1 128],input_ids[1 128]"
Good

2021-06-21 11:44 UTC, lazarevevgeny approved these changes

2021-06-21 11:53 UTC, yekruglov commented
@openvinotoolkit/openvino-docs-maintainers Can anybody review this PR, please?

2021-06-22 11:21 UTC, andrew-zaytsev requested changes

2021-06-22 11:21 UTC, andrew-zaytsev commented on docs/MO_DG/prepare_model/convert_model/pytorch_specific/Convert_Bert_ner.md
> +BERT-NER model repository. The model with config files is stored in the directory with name `out_base`.
in the directory with name `out_base` --> in the `out_base` directory.

2021-06-22 11:21 UTC, andrew-zaytsev commented on docs/MO_DG/prepare_model/convert_model/pytorch_specific/Convert_Bert_ner.md
> +To convert the model to ONNX* format create and run the script with the following content in the root
To convert the model to ONNX* format create and run the script with the following content in the root
directory of the model repository. If you download the pre-trained model, you will need
to download [`bert.py`](https://github.com/kamalkraj/BERT-NER/blob/dev/bert.py) to run the script.-->

To convert the model to the ONNX* format, create and run the script with the following content in the root
directory of the model repository. If you download the pre-trained model, you need
to download [`bert.py`](https://github.com/kamalkraj/BERT-NER/blob/dev/bert.py) to run the script.

2021-06-22 11:21 UTC, andrew-zaytsev commented on docs/MO_DG/prepare_model/convert_model/pytorch_specific/Convert_Bert_ner.md
> +The instruction was tested with repository hash commit `e5be564156f194f1becb0d82aeaf6e762d9eb9ed`.
with repository hash commit --> with the repository hash commit

2021-06-22 11:29 UTC, andrew-zaytsev approved these changes

2021-06-22 11:46 UTC, merged