[ONNX] Split importing model to two phases: decode and convert
openvinotoolkit/openvino pull request #6326
Opened 2021-06-23 14:10 UTC by mateusztabaka

Decode phase converts nodes from ONNX model to a Function with ONNXFrameworkNodes.
It's followed by convert phase, which does convert from ONNXFrameworkNodes to real ones.

Ticket: 51677

2021-06-28 14:10 UTC, postrational approved these changes

2021-06-28 14:54 UTC, mbencer approved these changes

2021-06-29 22:04 UTC, tsocha approved these changes

2021-06-30 10:15 UTC, slyalin requested changes
According to the presentation about FE, `decode`->`convert` is an advanced scenario and we shouldn't suffer from extra conversion time (and space) in case when it is not required. So if `convert` is called only, we shouldn't first run `decode` and then `convert(ngraph::Function)`, because we a passing through the graph two times and consume more memory for that intermediate representation that is built as the result of `decode` that could be significant amount in case of large models. Please make sure that we don't do that, especially because it was demonstrated in PoC that we could avoid doing that in a relatively simple way.

2021-07-12 10:13 UTC, merged