Revise sinh
openvinotoolkit/openvino pull request #6432
Opened 2021-06-29 08:58 UTC by bszmelcz

### Details:
 - refactor ngraph sinh class
 - add type_prop, backend, visitors tests
 - update spec
 - add rounding for integral type for sinh reference implementation
### Tickets:
 - 37479

2021-06-30 10:09 UTC, ggalieroc commented on docs/ops/arithmetic/Sinh_1.md
> +* **1**: An tensor of type T and arbitrary shape. **Required.**
An tensor of type T and arbitrary shape. ---> A tensor of type \*T\* and arbitrary shape

2021-06-30 10:12 UTC, ggalieroc commented on docs/ops/arithmetic/Sinh_1.md
> +* **1**: The result of element-wise sinh operation. A tensor of type T and the same shape as input.
The result of element-wise sinh operation. A tensor of type T and the same shape as input. ----> The result of element-wise \*Sinh\* operation applied to the input tensor. A tensor of type \*T\* and the same shape as the input tensor.

2021-06-30 10:13 UTC, ggalieroc commented on docs/ops/arithmetic/Sinh_1.md
>  * *T*: any numeric type.
any numeric type ----> any supported numeric type

2021-06-30 10:14 UTC, ggalieroc commented on docs/ops/arithmetic/Sinh_1.md
> +**Attributes**:
\*\*Attributes\*\*:  ---> \*\*Attributes\*\*: \*Sinh\* operation has no attributes.

2021-06-30 10:16 UTC, ggalieroc commented on docs/ops/arithmetic/Sinh_1.md
>  **Examples**
Please consider to address this comment here: https://github.com/openvinotoolkit/openvino/pull/6429#discussion_r660415923

2021-06-30 10:18 UTC, ggalieroc commented on docs/ops/arithmetic/Sinh_1.md
> +**Detailed description**: *Sinh* does the following with the input tensor *a*:
Let's keep the same style as for Cos spec.

\*\*Detailed description\*\*: \*Sinh\* performs element-wise hyperbolic sine (sinh) operation on a given input tensor, based on the following mathematical formula:

2021-06-30 10:18 UTC, ggalieroc commented on docs/ops/arithmetic/Sinh_1.md
>  **Short description**: *Sinh* performs element-wise hyperbolic sine (sinh) operation with given tensor.
with given tensor. ---> on a given input tensor

2021-06-30 10:22 UTC, ggalieroc commented on ngraph/test/backend/sinh.in.cpp
> +NGRAPH_TEST(${BACKEND_NAME}, sinh_int32)
Please replace the usage of backend and use TestCase to keep consistency of tests

2021-06-30 10:38 UTC, ggalieroc commented
Please add SLT with integer precision. You can do this by including the op in this [list](https://github.com/openvinotoolkit/openvino/blob/master/inference-engine/tests/functional/plugin/cpu/shared_tests_instances/single_layer_tests/activation.cpp#L67)

2021-06-30 10:42 UTC, ggalieroc commented
Also add checks for inputs/outputs in [evaluate ](https://github.com/openvinotoolkit/openvino/blob/master/ngraph/core/src/op/sinh.cpp#L68) method, similarly as in [here](https://github.com/openvinotoolkit/openvino/blob/master/ngraph/core/src/op/prelu.cpp#L81)

2021-06-30 10:44 UTC, ggalieroc requested changes
Please address the comments left

2021-06-30 10:59 UTC, ggalieroc commented on ngraph/core/src/op/sinh.cpp
> +NGRAPH_RTTI_DEFINITION(op::v0::Sinh, "Sinh", 0);
```suggestion
NGRAPH_RTTI_DEFINITION(op::v0::Sinh, "Sinh", 0, util::UnaryElementwiseArithmetic);
```

2021-06-30 11:42 UTC, ggalieroc commented
As for last comment, maybe you could try to clean up some [includes ](https://github.com/openvinotoolkit/openvino/blob/master/ngraph/core/src/op/sinh.cpp#L7-L8) from op class, it looks like some of them are not needed

2021-06-30 12:29 UTC, ggalieroc commented on ngraph/test/backend/sinh.in.cpp
> +    auto A = make_shared<op::Parameter>(element::i32, shape);;
nitpick: remove additional semicolon

2021-06-30 12:29 UTC, ggalieroc approved these changes

2021-06-30 12:31 UTC, ggalieroc commented
@lazarevevgeny could you please review the spec part?

2021-06-30 12:33 UTC, ggalieroc commented
Add the operator to the [list](https://github.com/openvinotoolkit/openvino/blob/master/inference-engine/tests/ie_test_utils/functional_test_utils/layer_tests_summary/utils/constants.py) of trusted ops

2021-07-01 05:04 UTC, lazarevevgeny approved these changes

2021-07-01 05:20 UTC, ilyachur approved these changes
Please fix CI

2021-07-02 10:53 UTC, jdanieck commented
@bszmelcz I've blocked this PR till we discuss why you did [changes in python api requirements](https://github.com/openvinotoolkit/openvino/pull/6432/commits/ca6130dea6b8797b55fe32a5f202bcf899f1aafc).

2021-07-02 10:56 UTC, jdanieck requested changes

2021-07-02 10:56 UTC, jdanieck commented on ngraph/python/requirements_test.txt
> +onnx==1.9.0
You shouldn't do such changes. Let's discuss online.

2021-07-02 13:23 UTC, jdanieck approved these changes
@bszmelcz looks like CI is now failing because of a merge conflict, so please resolve it and we should see green finally :)

2021-07-05 07:11 UTC, merged