Remove split-concat subgraph before pad op
openvinotoolkit/openvino pull request #6506
Opened 2021-07-02 15:31 UTC by iimironov

Ticket: 58776
Pattern Split->Concat was added before Pad op.

2021-07-07 13:35 UTC, jane-intel requested changes
Please add propagation up for Pad in the corresponding RIC dictionary

2021-07-07 13:35 UTC, jane-intel commented on model-optimizer/extensions/back/PadNormalizer.py
> +            if node.soft_get('mode') == 'constant' and not node.is_in_port_connected(3): #node.in_port(3).disconnected():
please clean up the comment

2021-07-07 13:35 UTC, jane-intel commented on model-optimizer/extensions/back/ReverseInputChannels.py
> +    def pass_rc_through_pad(node: Node, reverse_channels: Node):
nit: we can call it passthrough and if we need to add other operations here -- we could use it

2021-07-08 10:59 UTC, evolosen approved these changes

2021-07-08 11:06 UTC, mvafin approved these changes

2021-07-14 05:40 UTC, rkazants commented on model-optimizer/extensions/back/PadNormalizer.py
> +    enabled = True
Please add description for this transformation.

2021-07-14 09:04 UTC, rkazants commented on model-optimizer/extensions/back/PadNormalizer.py
> +    enabled = True
Absolutely, not clear why we need this transformation. When `Pad` operation is created in our graph, all data is in place to create this operation correctly without further need in normalization.

2021-07-14 09:05 UTC, rkazants commented on model-optimizer/extensions/back/PadNormalizer.py
> +                        .create_node()
port index is inocrrect. I think it is about the third port index for pad value.
Also it will be incorrect if this value is under ShapeOf sub-graph.

2021-07-14 09:06 UTC, rkazants commented on model-optimizer/extensions/back/PadNormalizer.py
> +                    convert_pad_value.in_port(1).connect(node.in_port(0).get_source())
I see no problem to add this value immediately once `Pad` operation is created in our graph.

2021-07-14 09:08 UTC, rkazants commented on model-optimizer/extensions/back/ReverseInputChannels.py
> +        return True
functionally not clear about why a graph `ReverseChannels->Pad` is not functionally equivalent to `Pad->ReverseChannels`

2021-07-14 09:29 UTC, rkazants commented on model-optimizer/extensions/back/ReverseInputChannels.py
> +        if node.is_in_port_connected(0):
add description as for other rc transformations

2021-07-14 09:29 UTC, rkazants commented on model-optimizer/extensions/back/ReverseInputChannels.py
> +
why it does not return:
        first - boolean value whatever we should continue propagating current ReverseChannels operation up or not
        second - list of new ReverseChannels operations that were produced while propagating reverse_channels up

2021-07-19 07:58 UTC, rkazants commented on model-optimizer/extensions/back/ReverseInputChannels.py
> +                                              ReverseChannels
It is not necessarily for `Pad` operation. Please draw a graph for arbitrary node

2021-07-19 08:15 UTC, rkazants commented on model-optimizer/extensions/back/ReverseInputChannels.py
> +        reverse_channels.in_port(0).disconnect()
also, please check that all needed input/output ports are connected using `assert`

2021-07-19 08:17 UTC, rkazants commented on model-optimizer/extensions/back/ReverseInputChannels.py
> +                 next_op
Please draw a graph for arbitrary operation node.

2021-07-19 08:23 UTC, rkazants commented on model-optimizer/extensions/back/ReverseInputChannels.py
> +            reverse_channels_copy = reverse_channels.copy_node({'axis': np.array(axis)})
I think you don't need to create a new one ReverseChannels node. Please use existing one and re-connect correspondingly.

2021-07-19 08:24 UTC, rkazants commented on model-optimizer/extensions/back/ReverseInputChannels.py
> +            port = node.in_port(0)
Please use more meaningful variable names. For example, `port -> node_input_port_0`

2021-07-19 13:21 UTC, jane-intel approved these changes

2021-07-19 17:40 UTC, rkazants approved these changes

2021-07-21 11:33 UTC, merged