[GPU] Support of new data and weight formats
openvinotoolkit/openvino pull request #6616
Opened 2021-07-13 06:51 UTC by vladimir-paramuzov

### Details:
 - Added double blocked bsvX_fsvY data tensor formats, several new weights layouts
 - Support of new layouts in several primitives: concat, lrn, pooling, quantize, reorder, resample
 - Should be merged after #6603

2021-07-26 10:30 UTC, lznamens requested changes

2021-07-26 10:30 UTC, lznamens commented on inference-engine/thirdparty/clDNN/kernel_selector/core/actual_kernels/resample/resample_kernel_opt.cpp
> +        opt_x_block_size = GetOptimalDivisor(params.output.X().v, 32);
Looks like here can be odd block sizes. Is it normal for this kernel?

2021-07-26 10:30 UTC, lznamens commented on inference-engine/thirdparty/clDNN/kernel_selector/core/cl_kernels/include/fetch_data.cl
> +                                                  uint x_pad_before, uint x_pad_after, uint alignmentB, uint alignmentF) {
nit: alignment for function's arguments

2021-09-22 11:50 UTC, sshlyapn approved these changes

2021-09-22 12:45 UTC, merged