MoveFakeQuantize
openvinotoolkit/openvino pull request #6723
Opened 2021-07-20 14:14 UTC by NikDemoShow

### Details:
 - *item1*
 - *...*

### Tickets:
 - *ticket-id*

2021-07-30 04:59 UTC, ilyachur commented
Looks like you have a lot of redundant changes in this PR.

2021-08-05 06:50 UTC, eshoguli commented on inference-engine/tests/ngraph_helpers/lpt_ngraph_functions/src/move_fake_quantize_function.cpp
> +                if (fqOnData3.empty()) {
please refactor in this way:
```cpp
std::shared_ptr<Node> parent = ...
if (!fqOnData1.empty()) {
    parent = ...
}
if (!fqOnData2.empty()) {
    parent = ...
}
if (!fqOnData3.empty()) {
    parent = ...
}
```

2021-08-05 06:51 UTC, eshoguli commented on inference-engine/tests/functional/inference_engine/lp_transformations/move_fake_quantize_for_concat_transformation.cpp
> +// Copyright (C) 2018-2021 Intel Corporation
move_fake_quantize_for_concat_transformation.cpp => move_fake_quantize_transformation.cpp

2021-08-05 06:52 UTC, eshoguli commented on inference-engine/src/low_precision_transformations/src/move_fake_quantize.cpp
> +                if (strcmp(type, "Concat") == 0) {
extend pattern matching & remove

2021-08-23 07:39 UTC, v-Golubev reviewed
Please fix comments

2021-08-23 07:39 UTC, v-Golubev commented on inference-engine/tests/functional/plugin/gpu/shared_tests_instances/low_precision_transformations/move_fake_quantize_transformation.cpp
> +       LayerTestsUtils::LayerTransformationParamsNGraphFactory::createParams().setUpdatePrecisions(false),
Could you please remove `LayerTestsUtils::LayerTransformationParamsNGraphFactory::createParams().setUpdatePrecisions(false)` ?

2021-08-23 07:39 UTC, v-Golubev commented on inference-engine/tests/functional/plugin/shared/src/low_precision_transformations/move_fake_quantize_transformation.cpp
> +
To my mind we can use default threshold in this tests. Please, remove

2021-08-24 11:13 UTC, v-Golubev approved these changes
Look good to me, thanks!

2021-09-04 21:20 UTC, eshoguli commented on inference-engine/src/low_precision_transformations/src/move_fake_quantize.cpp
> +        newFq->set_friendly_name(fq_original_name + std::to_string(i + 1));
add delimiter:
``` cpp
newFq->set_friendly_name(fq_original_name + "_" + std::to_string(i + 1));
```

2021-09-04 21:20 UTC, eshoguli commented on inference-engine/src/low_precision_transformations/src/move_fake_quantize.cpp
> +        std::shared_ptr<ngraph::Node> fqInput;
one naming conversion: `fqInput` => `fq_input`

2021-09-04 21:20 UTC, eshoguli commented on inference-engine/src/low_precision_transformations/src/move_fake_quantize.cpp
> +            as_type_ptr<opset1::FakeQuantize>(fq)->get_levels());
use `clone_with_new_inputs` here

2021-09-04 21:20 UTC, eshoguli commented on inference-engine/src/low_precision_transformations/src/move_fake_quantize.cpp
> +    auto newConcat = concat->clone_with_new_inputs(get_outputs(fqs));
don't need `get_outputs`:
``` cpp
auto newConcat = concat->clone_with_new_inputs(ngraph::OutputVector(fqs.begin(), fqs.end()));
```

2021-09-04 21:20 UTC, eshoguli commented on inference-engine/src/low_precision_transformations/src/move_fake_quantize.cpp
> +    newConcat->set_friendly_name(concat->get_friendly_name());
`NetworkHelper::copyInfo` is skipped

2021-09-04 21:20 UTC, eshoguli commented on inference-engine/tests/functional/inference_engine/lp_transformations/move_fake_quantize_transformation.cpp
> +#include <low_precision/markup_per_tensor_quantization.hpp>
please, remove not used headers in the file

2021-09-04 21:21 UTC, eshoguli commented
tests review is not completed yet

2021-09-05 10:38 UTC, eshoguli requested changes
please, fix comments

2021-09-05 10:38 UTC, eshoguli commented on inference-engine/tests/functional/inference_engine/lp_transformations/move_fake_quantize_transformation.cpp
> +        transformer.transform(actualFunction);
Use implemented transformation only:
```suggestion
        ov::pass::Manager manager;
        manager.register_pass<ngraph::pass::low_precision::MoveFakeQuantize>(params);
        manager.run_passes(actualFunction);
```

2021-09-05 10:38 UTC, eshoguli commented on inference-engine/tests/functional/inference_engine/lp_transformations/move_fake_quantize_transformation.cpp
> +    auto res = compare_functions(referenceFunction, actualFunction, true, true, false, true, false);
```suggestion
    auto res = compare_functions(referenceFunction, actualFunction, true, true, true, true, true);
```

2021-09-05 10:38 UTC, eshoguli commented on inference-engine/src/low_precision_transformations/src/move_fake_quantize.cpp
> +bool MoveFakeQuantize::transform(TransformationContext& context, ngraph::pattern::Matcher& m) {
if LPT `ConcatTransformation` doesn't handle this `Concat`, then `MoveFakeQuantizeTransformation` should not handle too. You need to make existing `Concat::canBeTransformed` static (for example: `Concat::canBeTransformedStatic`) and reuse it in the `MoveFakeQuantizeTransformation`. Don't forget negative tests cases in functional & plugin tests, please.

2021-09-12 18:26 UTC, eshoguli approved these changes
please fix minor comments in D/DQ support PR

2021-09-12 18:26 UTC, eshoguli commented on inference-engine/src/low_precision_transformations/src/move_fake_quantize.cpp
> +            fq_input = std::make_shared<ngraph::opset1::Relu>(input);
minor: `clone_wiith_new_inputs` is more preferable

2021-09-12 18:26 UTC, eshoguli commented on inference-engine/src/low_precision_transformations/src/move_fake_quantize.cpp
> +            fq_input->set_friendly_name(relu_original_name + std::to_string(i + 1));
minor: `fq_input->set_friendly_name(relu_original_name + "_" + std::to_string(i + 1));`

2021-09-15 14:15 UTC, merged