Add support opset11 for gemm normolizer
openvinotoolkit/openvino pull request #6733
Opened 2021-07-21 10:32 UTC by iimironov

Ticket: 59060

Description: 
Add support gemm with opset 11 for gemm normalizer replacer.

2021-08-02 08:06 UTC, lazarevevgeny submitted a review, later dismissed
The layer test changes are incorrect. The tests fail in pre-commit with the following error:

```
Traceback (most recent call last):
  File ".../tests/layer_tests_openvino/onnx_tests/test_gemm.py", line 240, in test_gemm_bc
    trans_b, precision, ir_version), ie_device, precision, ir_version,
TypeError: create_net() missing 1 required positional argument: 'ir_version'
```

2021-08-03 11:18 UTC, achetver approved these changes
Looks good to me.

2021-08-04 15:52 UTC, rkazants commented on model-optimizer/extensions/front/MatMul_normalizer.py
>          node.out_port(0).get_connection().set_source(bias_node.out_port(0))
could you please re-write this transformation a bit to use `find_and_replace_pattern(self, graph: Graph)` and traverse all `Gemm` nodes by `for` loop? We do so for all the single node pattern

2021-08-04 15:53 UTC, rkazants commented on model-optimizer/extensions/front/MatMul_normalizer.py
> +        if not bias_node.in_port(1).get_source():
Please use `            if bias_node.in_port(1).disconnected():
`

2021-08-04 15:58 UTC, rkazants commented on model-optimizer/extensions/front/MatMul_normalizer.py
> +            bias_const_node.out_port(0).connect(bias_node.in_port(1))
I don't think that we need it at all if `bias` is zero. If bias is zero, don't insert `Add` node at all.
Here also we have a problem with dtype, we don't know dtype of this Constant node.

2021-08-05 10:10 UTC, sadolini commented on model-optimizer/extensions/front/MatMul_normalizer.py
> +            if bias_node.in_port(1).disconnected():
I think that check node.in_port(2).disconnected() is much more clear

2021-08-09 08:47 UTC, sadolini approved these changes

2021-08-10 15:13 UTC, rkazants commented on model-optimizer/extensions/front/MatMul_normalizer.py
> +from mo.front.tf.graph_utils import create_op_with_const_inputs
please sort imports

2021-08-10 15:32 UTC, rkazants commented on model-optimizer/extensions/front/MatMul_normalizer.py
> +                bias_node_name = node.name
node.name is incorrect, also you have already retrieved this name in line 79. Please use it

2021-08-23 10:13 UTC, rkazants commented on model-optimizer/extensions/front/MatMul_normalizer.py
> +                                                       {'name': name + '/Alpha_'})
`alpha` contained `can_be_scaleshift=False` attribute? Why is it skipped now?

2021-08-23 10:39 UTC, lazarevevgeny commented on model-optimizer/extensions/front/MatMul_normalizer.py
> +                mul_alfa = create_op_with_const_inputs(graph, Mul, {1: np.array(node.alpha)},
may be `mul_alpha`?

2021-08-23 11:19 UTC, rkazants approved these changes

2021-08-23 11:24 UTC, lazarevevgeny commented on model-optimizer/extensions/front/MatMul_normalizer.py
> +                node_output_port.get_connection().set_destination(mul_alpha.in_port(0))
I think that you can use `node_output_port .get_connection().insert_node(mul_alpha)` instead of these two lines

2021-08-23 11:27 UTC, lazarevevgeny commented on model-optimizer/extensions/front/MatMul_normalizer.py
> +            if not node.in_port(2).disconnected():
Change to `if node.is_in_port_connected(2):`

2021-08-23 11:29 UTC, lazarevevgeny commented on model-optimizer/extensions/front/MatMul_normalizer.py
> +                node_name = node.name + '/WithoutBiases'
use `node_name` instead of `node.name`?

2021-08-23 11:30 UTC, lazarevevgeny commented on model-optimizer/extensions/front/MatMul_normalizer.py
> +                bias_node_name = name
Why do you need a dedicated variable `bias_node_name`? May be just write `rename_nodes([(node, node_name), (bias_node, name)])` in line 93?

2021-08-23 11:32 UTC, lazarevevgeny commented on model-optimizer/extensions/front/MatMul_normalizer.py
> +                bias_node = Add(graph, {'name': name + '/Bias_', 'can_be_scaleshift': False}).create_node()
Why do you use `_` in the end of node name? Please, remove them from everywhere in this file.

2021-08-23 11:33 UTC, lazarevevgeny commented on model-optimizer/extensions/front/MatMul_normalizer.py
> +                node_name = node.name + '/WithoutBiases'
Also, may be change the variable name to `without_biases_node_name`

2021-08-23 11:40 UTC, lazarevevgeny requested changes

2021-08-23 11:40 UTC, lazarevevgeny commented on model-optimizer/extensions/front/MatMul_normalizer.py
> +                node_output_port.get_connection().set_destination(mul_alpha.in_port(0))
Here you perform multiplication with the Gemm output. But originally the multiplication was performed with the Gemm input. Also, the spec describes that the multiplication should be applied to A input: "Compute Y = alpha * A' * B' + beta * C" . Please, fix this.

2021-08-23 15:30 UTC, lazarevevgeny commented on model-optimizer/extensions/front/MatMul_normalizer.py
> +                node_output_port.get_connection().set_destination(mul_alpha.in_port(0))
Incorrect comment. Please, disregard.

2021-08-23 15:30 UTC, lazarevevgeny approved these changes

2021-08-24 12:43 UTC, merged