Fix split-concut revers input channel
openvinotoolkit/openvino pull request #6765
Opened 2021-07-22 19:04 UTC by iimironov

Ticket: 59156

Pattern Split->Concat was added before Pad op.
As a part of optimizations ReverseChannels operation was replacing to pattern Split->Сoncat. Early if the pattern inserted before Pad layer we fused it to Pad. But it was wrong and the optimization was removed. So the root cause is that before Pad we insert  Split->Сoncat pattern and it leads to regression for some topologies.

![Screenshot (18)](https://user-images.githubusercontent.com/29801542/124589561-cc427200-de62-11eb-826e-c87da31ae9db.png)

The fix move ReverseChannels after Pad layer. It allow optimize reverse input channels propagation and avoid work around with insert Split->Сoncat subgraph.

* [x]  Comments
* [x]  Code style (PEP8)
* [x]  Transformation generates reshape-able IR N/A
* [x]  Transformation preserves original framework node names N/A: a special case, when we should rename the nodes

Validation:
* [x]  Unit tests
* [x]  Framework operation tests N/A
* [x]  Transformation tests N/A
* [x]  Model Optimizer IR Reader check N/A

Documentation:
* [x]  Supported frameworks operations list N/A: no new operations were enabled
* [x]  Guide on how to convert the **public** model N/A no new models were enabled
* [x]  User guide update N/A

2021-07-26 05:53 UTC, yekruglov approved these changes

2021-07-26 06:39 UTC, rkazants requested changes
@iimironov, please fix all typos (in title and description).

2021-07-26 08:35 UTC, rkazants commented on model-optimizer/extensions/back/ReverseInputChannels.py
> +          previous_op
please add blank line between them.

2021-07-26 08:35 UTC, rkazants commented on model-optimizer/extensions/back/ReverseInputChannels.py
>          returns boolean value whatever we should continue propagating current ReverseChannels operation down or not
please do not edit these comments.

2021-07-26 08:36 UTC, rkazants commented on model-optimizer/extensions/back/ReverseInputChannels.py
> +                                     previous_op
the same as above

2021-07-28 09:58 UTC, rkazants approved these changes

2021-07-28 12:47 UTC, merged