Install layer tests with CMake
openvinotoolkit/openvino pull request #6892
Opened 2021-08-02 18:41 UTC by alexander-shchepetov

### Tickets:
 - *60421*

2021-08-02 18:50 UTC, ilya-lavrenov commented on tests/layer_tests/CMakeLists.txt
> +install(TARGETS ${TARGET_NAME} DESTINATION tests COMPONENT tests EXCLUDE_FROM_ALL)
please, add copyright 
```
# Copyright (C) 2018-2021 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#
```

2021-08-02 18:51 UTC, ilya-lavrenov commented on tests/layer_tests/CMakeLists.txt
> +install(TARGETS ${TARGET_NAME} DESTINATION tests COMPONENT tests EXCLUDE_FROM_ALL)
BTW, `TARGET_NAME` is not defined in this file

2021-08-17 07:18 UTC, ishariko requested changes

2021-08-17 07:18 UTC, ishariko commented on tests/layer_tests/CMakeLists.txt
> +install(DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/ DESTINATION layer_tests_openvino COMPONENT tests EXCLUDE_FROM_ALL)
please replace DESTINATION folder `layer_tests_openvino` to `tests\layer_tests_openvino`

2021-08-18 14:05 UTC, ishariko approved these changes

2021-08-20 08:09 UTC, azhogov commented
CI passed: https://github.com/intel-innersource/frameworks.ai.openvino.ci.product-configs/pull/109

2021-08-20 08:09 UTC, merged