[IE CLDNN] Performance counters fix
openvinotoolkit/openvino pull request #7143
Opened 2021-08-18 12:35 UTC by Lyamin-Roman

### Tickets:
 - *CVS-51819*

2021-08-18 12:42 UTC, tsavina approved these changes

2021-08-19 06:44 UTC, sshlyapn commented on inference-engine/thirdparty/clDNN/src/program.cpp
> +        add_optimized_primitive_info(prev.id(), { node_id });
Is it correct usage of function? As I can see, the first argument is `primitive_id optimized_primitive_id` and the second one is `std::vector<primitive_id> replaced_with_ids`, so you should swap the arguments

2021-09-14 04:06 UTC, lznamens requested changes

2021-09-14 04:06 UTC, lznamens commented on inference-engine/thirdparty/clDNN/tests/test_cases/convolution_gpu_test.cpp
> +        convolution("conv", "to_int", { "weights" }, { "biases" }, { 1, 1, 1, 1 }, { 0, 0, -2, -2 }, { 1,1,1,1 }, "",
Spaces between numbers.

2021-09-14 04:06 UTC, lznamens commented on inference-engine/thirdparty/clDNN/tests/test_cases/convolution_gpu_test.cpp
> +        convolution("conv", "to_int", { "weights" }, { "biases" }, { 1, 1, 1, 1 }, { 0, 0, -2, -2 }, { 1,1,1,1 }, "",
Spaces between numbers.

2021-09-14 04:06 UTC, lznamens commented on inference-engine/thirdparty/clDNN/tests/test_cases/activation_simple_gpu_test.cpp
> +            activation("relu", "reorder", activation_func::acosh, {0.5f, 0.f}, "", padding{{0, 0, 0, 0}, 0}));
Please use unified code style as in other tests in this file and add spaces inside figure braces.

2021-09-14 04:06 UTC, lznamens commented on inference-engine/src/cldnn_engine/cldnn_graph.cpp
> +            name = name.substr(name.find(":") + 1, name.length());
Does this simple solution really cover all cases?

2021-09-15 11:15 UTC, lznamens approved these changes

2021-09-17 10:12 UTC, merged