[LPT] SubMulToMulAdd transformation: naming fix
openvinotoolkit/openvino pull request #7195
Opened 2021-08-23 07:05 UTC by v-Golubev

### Details:
 - SubtractMultiplyToMultiplyAdd: naming fix*
 - Refactoring and legacy code removed

### Issues:
 - 63030

2021-08-23 12:27 UTC, v-Golubev commented
@vzinovie, Could you please review?

2021-08-23 14:04 UTC, vzinovie requested changes
Is it possible to cover it by test?

2021-08-24 05:32 UTC, v-Golubev commented
@vzinovie, tests was added. Thank you!

2021-08-25 04:30 UTC, vzinovie approved these changes

2021-08-31 10:50 UTC, merged