Update rnnt conversion instruction with named outputs
openvinotoolkit/openvino pull request #7585
Opened 2021-09-21 17:57 UTC by eaidova

### Details:
 - *conversion script for RNNT does not contain names for output nodes, which leads to producing different nresult from run to run. It can confuse users, which does not expect changes, for avoiding confusion, I added names for outputs in exporting function*
 - *Besides that give more descriptive names for inputs*

### Tickets:
 - *65737*

2021-09-21 21:35 UTC, vurusovs approved these changes

2021-09-22 12:33 UTC, vurusovs requested changes

2021-09-22 12:33 UTC, vurusovs commented on docs/MO_DG/prepare_model/convert_model/pytorch_specific/Convert_RNNT.md
> +                  output_names=['g', 'hidden_out_1', 'hidden_out_2']
missed `,` before dynamic_axes

2021-09-22 12:33 UTC, vurusovs commented on docs/MO_DG/prepare_model/convert_model/pytorch_specific/Convert_RNNT.md
> +                  input_names=['input', 'feature_length'], output_names=['x_padded', 'x_lens']
missed `,` before dynamic_axes

2021-09-22 12:36 UTC, eaidova commented on docs/MO_DG/prepare_model/convert_model/pytorch_specific/Convert_RNNT.md
> +                  output_names=['g', 'hidden_out_1', 'hidden_out_2']
fixed, thanks

2021-09-22 12:36 UTC, eaidova commented on docs/MO_DG/prepare_model/convert_model/pytorch_specific/Convert_RNNT.md
> +                  input_names=['input', 'feature_length'], output_names=['x_padded', 'x_lens']
fixed, thanks

2021-09-22 13:46 UTC, eaidova commented on docs/MO_DG/prepare_model/convert_model/pytorch_specific/Convert_RNNT.md
> +                  dynamic_axes={'symbol': {0: 'batch'}, 'hidden_out_1': {1: 'batch'}, 'hidden_out_2': {1: 'batch'}})
```suggestion
                  dynamic_axes={'symbol': {0: 'batch'}, 'hidden_in_1': {1: 'batch'}, 'hidden_in_2': {1: 'batch'}})
```

2021-09-22 22:04 UTC, vurusovs commented
New version of instruction works with next accuracy config for rnnt:
```
evaluations:
  - name: rnnt
    module: custom_evaluators.asr_encoder_prediction_joint_evaluator.ASREvaluator
    module_config:
      network_info:
        encoder:
          inputs:
            - 'input'
          outputs:
             - 'x_padded'
        prediction:
          inputs:
            - 'symbol'
            - 'hidden_in_1'
            - 'hidden_in_2'
          outputs:
            - 'hidden_out_1'
            - 'hidden_out_2'
            - 'g'
        joint:
          inputs:
            - '0'
            - '1'
          outputs:
            - 'result'
      adapter:
        type: dumb_decoder
        alphabet: [' ', a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, '''']
      launchers:
        - framework: dlsdk
          allow_reshape_input: True
      datasets:
      - name: LibriSpeech_dev_clean_wav_max_duration_15
        reader:
          type: wav_reader
        data_source: LibriSpeech/dev-clean/
        annotation_conversion:
          converter: librispeech
          data_dir: LibriSpeech/dev-clean/
          max_duration: 15
        preprocessing:
          - type: audio_normalization
            int16mode: True
          - type: audio_to_mel_spectrogram
            splicing: 3
        metrics:
          - type: wer
```

2021-09-22 22:04 UTC, vurusovs approved these changes

2021-09-22 22:05 UTC, merged