Cecilia/paddle reader
openvinotoolkit/openvino pull request #7663
Opened 2021-09-26 03:29 UTC by ceciliapeng2011

Refactor python API read_network, and add test case for it.

1. update comment description to add paddle model support.
2. remove assumption of file directory is not allowed. in case of paddle, as well as tensorflow, a kind of scattered model representation is possible. That is, a model file as well as a group of parameter files for each of them are weights of each layer.

note: the test case has a dependency to -
https://github.com/openvinotoolkit/testdata/pull/5

2021-09-26 17:24 UTC, AlexeyLebedev1 requested changes

2021-09-26 17:24 UTC, AlexeyLebedev1 commented on inference-engine/ie_bridges/python/src/openvino/inference_engine/ie_api.pyx
> +    #  @param model: A `.xml` or `.onnx` or `.pdmodel` model file or string with IR.
```suggestion
    #  @param model: A `.xml`,  `.onnx` or `.pdmodel` model file or string with IR.
```

2021-09-27 01:16 UTC, ceciliapeng2011 commented
temporarily converted to Draft, as it has dependency PR to testdata.

2021-09-27 07:54 UTC, mvafin commented on inference-engine/ie_bridges/python/src/openvino/inference_engine/ie_api.pyx
> -            if not os.path.isfile(model):
I suggest changing this from the requirement for a path to be a file path to just checking the existence of the path with `os.path.exists()`

2021-10-12 07:26 UTC, ceciliapeng2011 commented
Dependency to testdata merged. So folks, please continue this PR review. Thanks! @mvafin @AlexeyLebedev1

2022-10-26 22:28 UTC, closed without merging