Fixed expanding ONNX function
openvinotoolkit/openvino pull request #7747
Opened 2021-09-29 17:43 UTC by mbencer

Ticket: 62895, 65805, 38726
1. Fixed expanding ONNX function:
![image](https://user-images.githubusercontent.com/11331953/136361150-498b8312-ce83-488e-8d69-1799616233af.png)

Note that an ONNX function can be inside another ONXN Function. 

2. Default `PartialShape` ctor which produces a scalar. If an input shape is not provided `PartialShape::dynamic()` should be set.

2021-10-01 08:23 UTC, t-jankowski commented on ngraph/frontend/onnx/frontend/src/core/transform.cpp
> +            // nodes expenaded from function can have another functions
Like spelling mistake  it looks.

2021-10-01 11:03 UTC, tomdol approved these changes
Just wondering - perhaps one more unit test proving the correct ordering of nodes would be useful here?

2021-10-01 11:03 UTC, tomdol commented on ngraph/frontend/onnx/frontend/src/core/transform.cpp
> +    while (origin_graph_index < graph_proto->node().size() || new_graph_index < new_graph.node().size()) {
You can consider using https://en.cppreference.com/w/cpp/algorithm/rotate to move all new added nodes to the correct position.

2021-10-01 11:41 UTC, t-jankowski requested changes

2021-10-01 11:41 UTC, t-jankowski commented on ngraph/frontend/onnx/frontend/src/core/transform.cpp
> +        }
Does it iterate twice over the graph without function ops?

2021-10-06 10:02 UTC, mbencer commented
> Just wondering - perhaps one more unit test proving the correct ordering of nodes would be useful here?

Added new tests to `openvino/ngraph/test/onnx/onnx_transformations.cpp`

2021-10-15 10:40 UTC, merged