Gkazanta/fix convert precision for nms
openvinotoolkit/openvino pull request #7778
Opened 2021-09-30 17:59 UTC by GlebKazantaev

### Description
Fix ConvertPrecision for NMS5 operation.

2021-10-01 14:48 UTC, vgavrilo requested changes

2021-10-01 14:48 UTC, vgavrilo commented on ngraph/core/src/pass/convert_precision.cpp
> +                                                                                         output_types);
Maybe this function can be rewritten using less nesting level? For example, as
```c++
bool fuse_type_to_nms5(const std::shared_ptr<ngraph::Node>& node, ngraph::element::Type to, size_t idx) {
    auto nms = ov::as_type_ptr<opset5::NonMaxSuppression>(node);
    if (!nms) {
        return false;
    }
    if ((idx == 0 || idx == 2) && (to == element::i32 || to == element::i64)) {
        nms->set_output_type(to);
        return true;
    }

    if (auto type_relaxed = std::dynamic_pointer_cast<op::TypeRelaxedBase>(node)) {
        type_relaxed->set_overridden_output_type(to, idx);
        return true;
    }

    element::TypeVector output_types;
    for (const auto& output : nms->outputs()) {
        output_types.emplace_back(output.get_element_type());
    }
    output_types[idx] = to;
    auto relaxed_op =
        std::make_shared<ngraph::op::TypeRelaxed<opset5::NonMaxSuppression>>(*nms,
                                                                             element::TypeVector{},
                                                                             output_types);
    replace_node(node, relaxed_op);
    return true;
}
```

2021-10-04 05:50 UTC, vgavrilo approved these changes

2021-10-04 08:29 UTC, jane-intel approved these changes

2021-10-04 08:52 UTC, merged