Offline transformations exposed to python with pybind11
openvinotoolkit/openvino pull request #7987
Opened 2021-10-13 16:34 UTC by tomdol

### Tickets:
 - 61868

2021-10-13 16:45 UTC, ilya-lavrenov commented
can we completely remove offline transformations from old API?
It's internal and not needed for BW compatibility

2021-10-18 14:50 UTC, tomdol commented
I've used a new `get_function` binding in this PR but it will only be available after https://github.com/openvinotoolkit/openvino/pull/8027 has been merged. Some CI failures are probably caused by this.

2021-11-02 10:50 UTC, slyubimt approved these changes

2021-11-02 11:29 UTC, akuporos approved these changes

2021-11-03 10:40 UTC, slyubimt requested changes

2021-11-03 10:40 UTC, slyubimt commented on runtime/bindings/python/src/pyopenvino/CMakeLists.txt
> +            DESTINATION ./python/${PYTHON_VERSION}/openvino
```suggestion
            DESTINATION python/${PYTHON_VERSION}/openvino
```

2021-11-03 10:40 UTC, slyubimt commented on runtime/bindings/python/src/pyopenvino/CMakeLists.txt
> +            DESTINATION ./python/${PYTHON_VERSION}
```suggestion
            DESTINATION python/${PYTHON_VERSION}
```

2021-11-03 15:17 UTC, slyubimt approved these changes

2021-11-03 17:00 UTC, merged