[CPU] Native 1D models support
openvinotoolkit/openvino pull request #8168
Opened 2021-10-22 09:47 UTC by alexey-varyzgin

### Details:
 - *1D Convolution support was added*
 - *1D Group Convolution support was added*
 - *Zero points for 1D Convolution was added*
 - *1D Pooling support was added*
 - *1D Reorders was added*

https://github.com/openvinotoolkit/oneDNN/pull/84

### Tickets:
 - *62683* 
 - *44483*
 - *38612*

2021-11-08 15:30 UTC, dmitry-gorokhov commented
@antonvor Please start the review

2021-11-10 05:28 UTC, antonvor requested changes

2021-11-10 05:28 UTC, antonvor commented on inference-engine/src/low_precision_transformations/src/weightable_layer_transformation.cpp
> +            if ((rankVal < 3) && (rankVal > 5)) {
This condition is always false
```suggestion
            if ((rankVal < 3) || (rankVal > 5)) {
```

2021-11-10 05:28 UTC, antonvor commented on inference-engine/tests/functional/plugin/cpu/single_layer_tests/convolution.cpp
> +const std::vector<SizeVector> kernels1d = { {3} };
what about `kernel == {1}`? I think we should add this case too

2021-11-10 05:28 UTC, antonvor commented on inference-engine/tests/functional/plugin/cpu/single_layer_tests/group_convolution.cpp
> +const std::vector<SizeVector> kernels1d = { {3} };
add case `kernel == 1` please

2021-11-10 14:43 UTC, alexey-varyzgin commented on inference-engine/src/low_precision_transformations/src/weightable_layer_transformation.cpp
> +            if ((rankVal < 3) && (rankVal > 5)) {
Done

2021-11-10 14:44 UTC, alexey-varyzgin commented on inference-engine/tests/functional/plugin/cpu/single_layer_tests/group_convolution.cpp
> +const std::vector<SizeVector> kernels1d = { {3} };
Done

2021-11-15 09:46 UTC, antonvor approved these changes

2021-11-18 07:43 UTC, antonvor commented
@dmitry-gorokhov could you please finally review?

2021-11-29 09:23 UTC, dmitry-gorokhov commented
@antonvor please fix remaining comment and resolve conflicts

2021-11-29 15:26 UTC, antonvor commented on inference-engine/src/mkldnn_plugin/mkldnn_graph_optimizer.cpp
> +        ptrdiff_t KH = node->getInputShapeAtPort(0).getRank() > 3 ? weightsConstantDims[weightsConstantDims.size() - 2] : 1;
fixed

2021-11-30 12:30 UTC, merged