[GNA] Update documentation for 2021.4.2
openvinotoolkit/openvino pull request #8490
Opened 2021-11-09 22:11 UTC by dorloff

### Details:
 - Updated GNA docs for 2021.4.2

### Tickets:
 - 63610,66763

2021-11-10 21:40 UTC, mdeisher requested changes

2021-11-10 21:40 UTC, mdeisher commented on docs/IE_DG/supported_plugins/GNA.md
> +In the rest of this documentation, "GNA 2.0" term will be used for GNA HW delivered with  Intel® GNA on 10th and 11th generation Intel® Core™ Processors, and "GNA 3.0" term will be used for GNA HW de
Should say:  the term "GNA 2.0" refers to Intel(R) GNA hardware delivered on 10th and 11th generation Intel(R) Core(TM) processors, and the term "GNA 3.0" will be used to refer to GNA hardware delivered on 12th generation Intel(R) Core(TM) processors.

2021-11-10 21:40 UTC, mdeisher commented on docs/IE_DG/supported_plugins/GNA.md
> +However, in most cases, networks compiled for GNA 2.0 will run as expected on GNA 3.0, although the performance may be worse compared to the case when a network is compiled specifically for the latte
I don't see the Models and Layers Limitations section in this document.  Please provide a link.

2021-11-10 21:40 UTC, mdeisher commented on docs/IE_DG/supported_plugins/GNA.md
> +You can use the `KEY_GNA_EXEC_TARGET` and `KEY_GNA_COMPILE_TARGET` options  (see the Supported Configuration Parameters section below) to check interoperability.
Please provide link to Supported Configuration Parameters section.

2021-11-10 21:40 UTC, mdeisher commented on docs/IE_DG/supported_plugins/GNA.md
> +- The maximum number of filters is 65532 for GNA 3.0 and 8192 for GNA 2.0.
You have GNA2 and GNA3 reversed here.

2021-11-10 22:57 UTC, mdeisher approved these changes

2021-11-15 13:16 UTC, andrew-zaytsev commented
Added the changes to a new #8567

2021-12-01 14:09 UTC, dorloff commented
Transferred to #8567.

2021-12-01 14:10 UTC, closed without merging