Move unit_tests from test_pkg/tools to test_pkg/tests
openvinotoolkit/openvino pull request #8548
Opened 2021-11-11 17:03 UTC by just-sparta

2021-11-12 08:14 UTC, ishariko approved these changes

2021-11-12 08:34 UTC, vurusovs requested changes

2021-11-12 08:34 UTC, vurusovs commented on model-optimizer/CMakeLists.txt
> +        DESTINATION tests/model_optimizer
should be review by MO team as well

2021-11-12 08:44 UTC, azhogov approved these changes

2021-11-12 08:50 UTC, dkrupnov approved these changes

2021-11-15 11:17 UTC, azhogov commented
CI passed: https://github.com/intel-innersource/frameworks.ai.openvino.ci.product-configs/pull/519

2021-11-15 11:18 UTC, merged