add serialize to offline_transformations
openvinotoolkit/openvino pull request #8765
Opened 2021-11-23 13:46 UTC by bszmelcz

### Details:
 - [x] expose serialize pass to offline transformations
 - [x] expose compress_model_transformation to offline transformations

### Tickets:
 - 69176 (part of)

2021-11-23 16:56 UTC, akuporos commented
Please, add tests here https://github.com/openvinotoolkit/openvino/blob/master/runtime/bindings/python/tests/test_transformations/test_offline_api.py

2021-11-23 19:14 UTC, akuporos commented on runtime/bindings/python/src/pyopenvino/core/offline_transformations.cpp
> +            manager.register_pass<ngraph::pass::Serialize>(path_to_xml, path_to_bin);
this mistake also is in https://github.com/openvinotoolkit/openvino/pull/8301
Please, use `ov::pass` instead of `ngraph::pass`

2021-11-23 19:15 UTC, akuporos commented on runtime/bindings/python/src/pyopenvino/core/offline_transformations.cpp
> +            ngraph::pass::Manager manager;
this mistake also is in #8301
Please, use ov::pass instead of ngraph::pass

2021-11-23 19:16 UTC, akuporos requested changes

2021-11-23 19:16 UTC, akuporos commented on runtime/bindings/python/src/pyopenvino/core/offline_transformations.cpp
> +            ngraph::pass::Manager manager;
this mistake also is in #8301
Please, use ov::pass instead of ngraph::pass

2021-11-25 06:57 UTC, ilya-lavrenov commented
> expose serialize pass to offline transformations

Why do we need it in offline transformations while Serialize is a part of main API now?

2021-11-25 09:05 UTC, akuporos commented
> > expose serialize pass to offline transformations
> 
> Why do we need it in offline transformations while Serialize is a part of main API now?

CC: @GlebKazantaev 

This PR was made to unblock MO asap.
We have the second PR for serialize as part of PassManager: https://github.com/openvinotoolkit/openvino/pull/8749
As I know, @GlebKazantaev wanted to discuss it with you and @ilyachur

2021-11-25 09:09 UTC, GlebKazantaev approved these changes

2021-11-25 10:01 UTC, akuporos approved these changes

2021-11-25 11:23 UTC, merged

2021-11-25 11:51 UTC, nosovmik commented on runtime/bindings/python/src/pyopenvino/core/offline_transformations.cpp
> +            manager.register_pass<ov::pass::Serialize>(path_to_xml, path_to_bin);
Original C++ API accepts 4-th argument "Version", which can be "unspecified, ir_v10, ir_v11". Can it be exposed as well to Python users? We just hit into this issue with @artyomtugaryov