Update Paddle OP support via hackathon in PRC
openvinotoolkit/openvino pull request #8810
Opened 2021-11-25 01:48 UTC by Openvino-dev-contest

### Details:

-     Paddle "not_equal" op upgrade
-     Paddle "expand" op upgrade
-     Paddle "topk" op upgrade
-     Paddle "fill_zeros_like" op upgrade
-     Paddle "gather_tree" op upgrade

### Tickets:
 - *ticket-id*

2021-11-25 03:02 UTC, ceciliapeng2011 commented
@luo-cheng2021 @liubo-intel @ilyachur @mvafin please help review. They are contributed from openvino community.

2021-11-25 07:47 UTC, ceciliapeng2011 requested changes

2021-11-25 08:11 UTC, ceciliapeng2011 requested changes

2021-11-25 08:11 UTC, ceciliapeng2011 commented on ngraph/test/frontend/paddlepaddle/test_models/gen_scripts/generate_top_k.py
> +        value, indices = fluid.layers.topk(node_x, k=k, name="top_k")
thanks for add test case for legacy topk. Can we merge it with topk_v2 into a single test file?

2021-11-25 08:11 UTC, ceciliapeng2011 commented on ngraph/frontend/paddlepaddle/src/op/top_k.cpp
> +NamedOutputs top_k(const NodeContext& node) {
Can we merge it with topk_v2? topk is a special case of topk_v2. We'd better take care of them together to reuse code.

2021-11-25 08:11 UTC, ceciliapeng2011 commented on ngraph/frontend/paddlepaddle/src/op/top_k_v2.cpp
> +        std::make_shared<ngraph::opset6::TopK>(x, k_expected_node, axis, mode, sort_type, index_element_type);
again, please use defaultopset instead of specify opset number here.

2021-12-08 01:34 UTC, ceciliapeng2011 requested changes

2021-12-08 01:34 UTC, ceciliapeng2011 commented on src/frontends/paddlepaddle/src/op/expand.cpp
> +NamedOutputs expand(const NodeContext& node) {
We can use a function to handle the common part for expand and expand_v2.

2022-01-17 05:24 UTC, ceciliapeng2011 reviewed
Why there are 163 files changed? Could you please rebase and exclude files that are not irrelated? 
Once the conversation is resolved or outdated, could you please mark it "resolved"?
@Ethan

2022-01-17 14:40 UTC, Openvino-dev-contest commented
> Why there are 163 files changed? Could you please rebase and exclude files that are not irrelated? Once the conversation is resolved or outdated, could you please mark it "resolved"? @Ethan

sorry, problem has fixed, pls review again.

2023-05-11 16:22 UTC, akladiev commented
This PR will be closed in 2 weeks in case of no activity.

2023-05-23 14:43 UTC, akladiev commented
This PR was closed because it has been stalled for 2 week with no activity.

2023-05-23 14:43 UTC, closed without merging