Resolve assertion of vsr int8 batch32
openvinotoolkit/openvino pull request #8894
Opened 2021-11-29 11:11 UTC by byungilm

+ Bugfix
+ Unexpected removal of reorder in front of narrow output conv

Signed-off-by: Min, Byungil <byungil.min@intel.com>

### Details:
 - *item1*
 - *...*

### Tickets:
 - *ticket-id*

2021-11-30 07:33 UTC, isanghao requested changes

2021-11-30 07:33 UTC, isanghao commented on inference-engine/thirdparty/clDNN/src/graph_optimizer/remove_redundant_reorders.cpp
> +                if (all_users_fuse == true && usr->get_preferred_impl_type() == impl_types::onednn) {
all_users_fuse is always true here.

2021-11-30 07:33 UTC, isanghao commented on inference-engine/thirdparty/clDNN/src/graph_optimizer/remove_redundant_reorders.cpp
> +                if (all_users_fuse == true && usr->get_preferred_impl_type() == impl_types::onednn) {
BTW, I think this needs to be placed within `can_fuse_reorder` function.

2021-11-30 16:14 UTC, vladimir-paramuzov commented on inference-engine/thirdparty/clDNN/api/cldnn/primitives/eltwise.hpp
> +    bool can_reuse_eltwise_mem(layout input_layout, layout output_layout) const {
I think program_helpers is the right place for this method

2021-12-01 05:59 UTC, isanghao approved these changes

2021-12-01 05:59 UTC, isanghao commented on inference-engine/thirdparty/clDNN/src/program_helpers.cpp
> +// check if input and output layouts are indentical to reuse memory in fused_ops of onednn
nit: `indentical` -> `identical`

2021-12-02 09:23 UTC, byungilm commented on inference-engine/thirdparty/clDNN/src/program_helpers.cpp
> +// check if input and output layouts are indentical to reuse memory in fused_ops of onednn
Fixed

2021-12-02 20:59 UTC, sshlyapn approved these changes

2021-12-07 02:08 UTC, merged