Pszmel/fix infer
openvinotoolkit/openvino pull request #9138
Opened 2021-12-09 19:16 UTC by pszmel

### Details:
 - Update outputs_to_dict to support f16 and bf16
 -  Add test to check return type of create_new_infer

2021-12-09 19:19 UTC, jiwaszki requested changes

2021-12-09 19:19 UTC, jiwaszki commented on src/bindings/python/tests/test_inference_engine/test_core.py
> +    arr.dtype
Asserts!

2021-12-09 21:54 UTC, pszmel commented on src/bindings/python/tests/test_inference_engine/test_core.py
> +    arr.dtype
Right! :D

2021-12-10 09:14 UTC, jiwaszki approved these changes

2021-12-10 09:14 UTC, jiwaszki commented on src/bindings/python/tests/test_inference_engine/test_core.py
> +    assert hasattr(arr, "nbytes")
You could provide more specific asserts.

2021-12-17 11:37 UTC, merged