Fix incorrect working UnpackPackReverseInputChannels for centernet
openvinotoolkit/openvino pull request #9201
Opened 2021-12-14 08:32 UTC by evolosen

Root cause analysis: Incorrect order in UnpackPackReverseInputChannels as result incorrect inference

Solution: change order

Ticket: CVS-73731

Code:
* [ ]  Comments
* [ ]  Code style (PEP8)
* [ ]  Transformation generates reshape-able IR
* [ ]  Transformation preserves original framework node names

Validation:
* [ ]  Unit tests
* [ ]  Framework operation tests
* [ ]  Transformation tests
* [ ]  Model Optimizer IR Reader check

Documentation:
* [ ]  Supported frameworks operations list
* [ ]  Guide on how to convert the **public** model
* [ ]  User guide update

2021-12-22 10:49 UTC, vgavrilo approved these changes

2021-12-23 08:01 UTC, pavel-esir approved these changes

2021-12-23 13:48 UTC, rkazants requested changes
please implement transformation test

2021-12-24 08:23 UTC, rkazants approved these changes

2021-12-27 12:57 UTC, merged