[IE Samples] json configuration reader and dumper for benchmark_app
openvinotoolkit/openvino pull request #9648
Opened 2022-01-13 17:16 UTC by ivikhrev

Implement config reader and dumper functions with nlohmann_json library.
### Tickets:
 - 75682

2022-01-13 19:32 UTC, vladimir-dudnik approved these changes

2022-01-14 07:26 UTC, ArtemySkrebkov-intel approved these changes
👍

2022-01-14 08:45 UTC, ivikhrev commented
@vladimir-dudnik @ArtemySkrebkov-intel I added warnings in old functions and updated readme.

2022-01-14 15:28 UTC, fzhar requested changes

2022-01-14 15:28 UTC, fzhar commented on samples/cpp/benchmark_app/README.md
> +    -load_config                Optional. Path to JSON file to load custom IE parameters. Please note, command line parameters have higher priority then parameters from configuration file.
```suggestion
    -load_config                Optional. Path to JSON file to load custom IE parameters. Please note, command line parameters have higher priority than parameters from configuration file.
```

2022-01-17 10:33 UTC, fzhar approved these changes

2022-01-18 08:22 UTC, merged