First time inference validation for dynamic shapes
openvinotoolkit/openvino pull request #9671
Opened 2022-01-14 14:19 UTC by just-sparta

### Details:
 - new options for reshape
 - new fillBlob mechanism for dynamic net

### Tickets:
 - *70150*

2022-01-19 09:05 UTC, vurusovs requested changes

2022-01-19 09:05 UTC, vurusovs commented on tests/time_tests/src/timetests_helper/main.cpp
> +  return runPipeline(FLAGS_m, FLAGS_d, FLAGS_c, FLAGS_reshape_shapes, FLAGS_data_shapes);
1. parse values before passing it to execution pipeline
2. handle exceptions during parsing the correct way - provide additional messages about what was wrong

2022-01-19 09:05 UTC, vurusovs commented on tests/lib/src/reshape_utils.cpp
> + * @brief Return vector with input tensor information provided from E2E
bad description - it should be common, not related to E2E at all

2022-01-19 09:05 UTC, vurusovs commented on tests/lib/src/common_utils.h
> +                      std::map<std::string, std::vector<size_t>>,
no name of an argument

2022-01-19 09:05 UTC, vurusovs commented on tests/lib/src/common_utils.h
> + * @brief Fill InferRequest blobs with random values or image information
extend docstring to differ from fillBlobs

2022-01-19 09:05 UTC, vurusovs commented on tests/lib/src/common_utils.h
> + * @brief Set up data shapes for model
set or get?

2022-01-19 09:05 UTC, vurusovs commented on tests/lib/src/reshape_utils.cpp
> +std::map<std::string, std::vector<size_t>> getDataShapes(const std::string& shapeString) {
parse or get?

2022-01-19 09:08 UTC, vurusovs commented on tests/time_tests/src/timetests_helper/cli.h
> +DEFINE_string(data_shapes, "", data_shapes_message);
Or need to handle the case when new model shapes may be static, so `data_shapes` isn't required

2022-01-21 13:51 UTC, vurusovs approved these changes

2022-01-21 13:51 UTC, vurusovs commented on tests/lib/src/reshape_utils.h
> +std::vector<std::string> split(const std::string& s, char delim);
not sure `split` should be available outside the `reshape_utils.cpp`, so may be removed from here

2022-01-21 13:51 UTC, vurusovs commented on tests/lib/src/reshape_utils.h
> +void fillBlobsDynamic(InferenceEngine::InferRequest inferRequest,
better to move to original `fillBlobs`, but not a blocker for merge

2022-01-24 09:44 UTC, lidiaToropova commented on tests/lib/src/reshape_utils.cpp
> +    if (isImageInfo(inputBlob) && (input_image_sizes.size() == 1)) {
Seems that 'input_image_sizes' can be empty here if tensor with image info comes first. Better to reuse 'fillBlobs' (also to avoid duplication)

2022-01-24 12:44 UTC, lidiaToropova approved these changes

2022-01-24 13:14 UTC, dkrupnov approved these changes

2022-01-24 13:19 UTC, merged