[docs] update linux/win installation guide
openvinotoolkit/openvino pull request #9720
Opened 2022-01-17 14:47 UTC by Jacob27

### Details:
 - *update linux installation guide*
 - *update windows installation guide*

### Tickets:
 - *CVS-71745*
 - *CVS-71748*

2022-01-17 16:28 UTC, Jacob27 commented
http://openvino-docs.inn.intel.com/jacek-linux-win-installation-guide-1/openvino_docs_install_guides_installing_openvino_windows.html

2022-01-21 15:00 UTC, slyubimt commented on docs/install_guides/installing-openvino-linux.md
> +## <a name="model-optimizer">Step 4 (Optional): Download additional components
Can we add here information on how to download OpenCV using a script supplied by installer? 
+ @mshabunin to provide instructions.

2022-01-21 15:04 UTC, slyubimt commented on docs/install_guides/installing-openvino-windows.md
> +## <a name="model-optimizer">Step 3 (Optional): Download additional components
Can we add here information on how to download OpenCV using a script supplied by Windows installer?

@mshabunin to provide instructions.

2022-01-28 10:03 UTC, slyubimt requested changes

2022-01-28 10:03 UTC, slyubimt commented on docs/install_guides/installing-openvino-linux.md
> +  * Red Hat* Enterprise Linux* 8.2, 64-bit
In general RHEL 8.x supported
```suggestion
  * Red Hat* Enterprise Linux* 8.x, 64-bit
```

2022-01-28 10:03 UTC, slyubimt commented on docs/install_guides/installing-openvino-linux.md
> +  * Ubuntu 20.04.0 long-term support (LTS), 64-bit
Align a format with previous line:
```suggestion
  * Ubuntu 20.04.x long-term support (LTS), 64-bit
```

2022-01-28 14:34 UTC, slyubimt approved these changes

2022-01-28 14:59 UTC, Jacob27 commented
http://openvino-docs.inn.intel.com/jacek-linux-win-installation-guide-1/openvino_docs_install_guides_installing_openvino_windows.html

2022-01-31 17:56 UTC, andrew-zaytsev requested changes

2022-01-31 18:01 UTC, andrew-zaytsev requested changes

2022-01-31 18:38 UTC, andrew-zaytsev requested changes

2022-01-31 18:38 UTC, andrew-zaytsev commented on docs/install_guides/installing-openvino-linux-header.md
> +* [Install OpenVINO™ with an Installer](installing-openvino-linux.md)
OpenVINO™ --> Intel® Distribution of OpenVINO™ toolkit

2022-01-31 18:38 UTC, andrew-zaytsev commented on docs/install_guides/installing-openvino-linux.md
>  # Install and Configure Intel® Distribution of OpenVINO™ toolkit for Linux* {#openvino_docs_install_guides_installing_openvino_linux}
Let's remove asterisks for all third-party product names (it was approved by Marketing): Windows, Linux, Ubuntu etc

2022-02-01 13:00 UTC, andrew-zaytsev approved these changes

2022-02-01 15:33 UTC, merged

2022-02-02 12:21 UTC, slyubimt commented on docs/install_guides/installing-openvino-windows-ivad-vpu.md
> +      1. Go to the `<INSTALL_DIR>\deployment_tools\inference-engine\external\hddl\drivers\SMBusDriver` directory, where `<INSTALL_DIR>` is the directory in which the Intel Distribution of OpenVINO™ t
This path is outdated