Add support api 2.0 to layer_tests
openvinotoolkit/openvino pull request #9814
Opened 2022-01-20 15:55 UTC by ishariko

### Details:
 - *item1*
 - *...*

### Tickets:
 - *ticket-id*

2022-01-24 12:42 UTC, dkrupnov requested changes

2022-01-24 12:42 UTC, dkrupnov commented on tests/layer_tests/common/tf_layer_test_class.py
> +                        # input[key] = transpose_nchw_to_nhwc(data, self.use_new_frontend)
remove

2022-01-24 12:42 UTC, dkrupnov commented on tests/layer_tests/onnx_tests/test_loop.py
>          self._test(*self.create_loop(), ie_device, precision, ir_version, temp_dir=temp_dir,
add api_2=api_2

2022-01-24 12:42 UTC, dkrupnov commented on tests/layer_tests/onnx_tests/test_loop.py
>          self._test(*self.create_loop_in_loop(), ie_device, precision, ir_version, temp_dir=temp_dir,
add api_2=api_2

2022-01-24 12:42 UTC, dkrupnov commented on tests/layer_tests/onnx_tests/test_lstm.py
> +                   temp_dir=temp_dir,
add api_2=api_2

2022-01-24 12:42 UTC, dkrupnov commented on tests/layer_tests/tensorflow_tests/test_tf_RandomUniform.py
> +            **params)
add api_2=api_2

2022-01-25 11:11 UTC, dkrupnov requested changes

2022-01-25 12:16 UTC, dkrupnov approved these changes

2022-01-25 12:26 UTC, rnugmanx commented
Is there CI results?

2022-01-25 14:18 UTC, ishariko commented
CI results: https://openvino-ci.intel.com/job/private-ci/job/customJobs/job/e2e-tests-linux/1633/
pre-commit: https://github.com/intel-innersource/frameworks.ai.openvino.ci.product-configs/pull/812

2022-01-26 09:05 UTC, just-sparta approved these changes

2022-01-26 09:12 UTC, ValentinDymchishin approved these changes

2022-01-27 08:55 UTC, ishariko commented
UPD:
CI results: https://openvino-ci.intel.com/job/private-ci/job/developer-services/job/e2e/2099/
pre-commit: https://github.com/intel-innersource/frameworks.ai.openvino.ci.product-configs/pull/812

2022-01-27 09:03 UTC, lidiaToropova approved these changes

2022-01-31 10:15 UTC, merged